### ISSUE TITLE
combo_box多屏下拉菜单错位

### ISSUE THREAD

**Issue by somicrmidaz** [zhiyiYo/PyQt-Fluent-Widgets#10]
在双屏情况下，如果将window拖到第二个屏幕，点击下拉菜单，下拉的菜单会贴在第一个屏幕的边缘，没有过来。

![](https://github.com/somicrmidaz/PicBed/blob/main/widgetbug.png?raw=true)

**Comment by zhiyiYo** [comment]
感谢反馈，请按照issue template补充完整环境信息，包括用的是哪个包

**Comment by somicrmidaz** [comment]
感谢回复

**Environment**
- OS: win10
- DPI scaling: 100%
- Python: 3.10.8 64-bit
- PyQt: PyQt5 5.15.2 / PySide 6.4.1 (I tested both)
- PyQt-Fluent-Widgets: 0.2.4 / 0.0.5

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. Just run the demo.py in examples/combo_box folder
2. Try to click the button, see the menu, or drag the window to another screen, click again and see the error.

**Expected behavior**
the menu should follow the combox button.

**Screenshots**
see the first feedback pic.

**Comment by zhiyiYo** [comment]
examples/menu/demo.py 会有此问题吗

**Comment by somicrmidaz** [comment]
有同样的问题。我测试了一下，对于 combox，问题应该是出在 combo_box.py 中 `_showComboMenu` 函数中的 `mapToGlobal` 命令上，对于双屏，这个 QPoint 横坐标可能会大于一个屏幕的横坐标，我打印了一下，移动到第二个屏幕后这个 QPoint 的 x 可以增加到 3000 以上（我屏幕分辨率1920*1080），也就是说 menu 没有跟着整个window移动，始终固定在了一个屏幕的范围内。

**Comment by zhiyiYo** [comment]
我这边没有多屏测试条件，你可以帮我测一下下面两行代码的返回值吗？
1. `qfluentwidgets/components/widgets/combo_box.py` 第 136 行 `self.mapToGlobal(QPoint(x, y))`，不知道这个映射到的全局坐标是相对第一个屏幕的还是当前屏幕的
2. `qfluentwidgets/components/widgets/menu.py` 第 557~560 行 `pos` 的横纵坐标值

**Comment by somicrmidaz** [comment]
你好，我屏幕显示方式 screen1 | screen2 （每个屏幕的分辨率1920*1080）。将程序放到 screen2 上，点击button，下拉menu显示在 screen1 的最右边。坐标测试结果如下：
```
pos: PySide6.QtCore.QPoint(1778, 497)
self.mapToGlobal(QPoint(x, y)): PySide6.QtCore.QPoint(2833, 501)
```
从结果看，映射到全局坐标是相对于 screen1 的，但可以跨屏幕，因此横坐标可以到 2833；pos值是1778，也是相对于 screen1，但应该限制在了 1920的范围内。

**Comment by zhiyiYo** [comment]
`QApplication.desktop().availableGeometry()` 的返回值是 `QRect(0, 0, 3840, 1080)` 吗？

**Comment by zhiyiYo** [comment]
我的 PySide6 分支用的是 `QApplication.screenAt(QCursor.pos()).availableGeometry()`，总感觉返回的是当前屏幕的位置，而不是全部屏幕的大小总和

**Comment by somicrmidaz** [comment]
在 PySide6中：
```
QApplication.instance().screens()[0].size():  PySide6.QtCore.QSize(1920, 1080)
QApplication.screenAt(QCursor.pos()).availableGeometry():  PySide6.QtCore.QRect(1920, 0, 1920, 1040)
```
在 PyQt5中：
```
QApplication.desktop().availableGeometry():  PyQt5.QtCore.QRect(0, 0, 1920, 1040)
```
看起来是单个屏幕的，但是之前 `mapToGlobal` 确实返回了大于 1920 的值。

**Comment by zhiyiYo** [comment]
`mapToGlobal` 应该是没问题了，应该是 `QApplication.desktop().availableGeometry()` 的问题了，我等下修改一下，感谢帮忙测试

**Comment by zhiyiYo** [comment]
@somicrmidaz 
如果把 `menu.py` 的第 557~559 行改为下述代码还会有 bug 吗
```python
rect = QApplication.screenAt(QCursor.pos()).availableGeometry()
w, h = self.width() + 5, self.height() + 5
pos.setX(max(10, min(pos.x() - self.layout().contentsMargins().left(), rect.right() - w)))
pos.setY(max(10, min(pos.y() - 4, rect.bottom() - h)))
```

**Comment by somicrmidaz** [comment]
Great！PyQt5 和 PySide6 都测试了，效果良好，没有问题。
