### ISSUE TITLE
是否有办法设置全局字体 ... ？

### ISSUE THREAD

**Issue by neavo** [zhiyiYo/PyQt-Fluent-Widgets#1000]
目前测试下来，似乎是因为内置的 *Label 控件都设置了自定义的样式，所以直接设置 app 的 font 的方式并不能生效
还有其他方式吗

```python
font = QFont()
font.setFamilies(["Consolas", "微软雅黑"])
app.setFont(font)
```

**Comment by rainzee** [comment]
推荐的方案是通过 addCustomStyleSheet 来继承并设置字体，没有办法设置 **全局** 字体

**Comment by zhiyiYo** [comment]
暂时不行，有些组件的字体是样式表控制的
