### ISSUE TITLE
[Bug]: SmoothScrollDelegate构造函数参数疑惑

### ISSUE THREAD

**Issue by mengdeer589** [zhiyiYo/PyQt-Fluent-Widgets#1001]
### What happened?

查看SmoothScrollDelegate类构造函数，有如下描述    
def __init__(self, parent: QAbstractScrollArea, useAni=False):
        """
        Parameters
        ----------
        parent: QAbstractScrollArea
            the scrolling area being delegated

        useAni: bool
            whether to use `QPropertyAnimation` to achieve smooth scrolling
        """
其中useAni默认为False，表示不使用动画，但在该类的成员函数eventFilter中，               
                if not self.useAni:
                    self.verticalSmoothScroll.wheelEvent(e)
                else:
                    self.vScrollBar.scrollValue(-e.angleDelta().y())
却是在执行，当不使用动画时，使用平滑滚动，当使用动画时，不使用平滑滚动。

### Operation System

windows7

### Python Version

python3.8.8

### PyQt/PySide Version

pyqt5.15.2

### PyQt/PySide-Fluent-Widgets Version

1.7

### How to Reproduce?

我是win7上使用pyqt5分支时，使用TableWidget展示大量数据发现滚动页面卡顿，试图优化，才发现这个问题。

### Minimum code

```python3
无
```

**Comment by zhiyiYo** [comment]
useAni 指的是是否使用 QPropertyAnimation 实现的平滑滚动，解决卡顿的方案参考官网的滚动区域文档
