### ISSUE TITLE
[建议]pro版的charts例子

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#1003]
看了pro的charts gallery，猜测可能是通过pyechats生成网页再通过webview显示。我自己也试着写了一下，有两点优化的建议：
1.可以通过设置webview背景为透明(`self.webview.page().setBackgroundColor(Qt.GlobalColor.transparent)`和配合echarts的背景透明参数`init_opts=opts.InitOpts( bg_color='transparent', is_fill_bg_color=True)`来实现只显示图表,可以正确显示fluentwindow的背景特效。
2.可以通过重写webveiw的contextMenuEvent方法，` def contextMenuEvent(self, event): event.ignore()`,来禁用webview的右键菜单。
效果图:
<img width="710" alt="image" src="https://github.com/user-attachments/assets/ef11890c-31e5-46c1-b799-77972acf448f">

**Comment by zhiyiYo** [comment]
webengine 设置透明背景之后会导致侧边栏菜单被图表遮挡
