### ISSUE TITLE
[Bug]: 官网中文文档里面API的使用演示中存在错别字

### ISSUE THREAD

**Issue by x-lancer** [zhiyiYo/PyQt-Fluent-Widgets#1008]
### What happened?

![企业微信截图_17311246928710](https://github.com/user-attachments/assets/fc55efef-3031-4357-bba2-90b406714ff8)

 官网中文文档里面API的使用演示中存在错别字

### Operation System

Windows11

### Python Version

3.11

### PyQt/PySide Version

pyside6

### PyQt/PySide-Fluent-Widgets Version

1

### How to Reproduce?

 官网中文文档里面API的使用演示中存在错别字

### Minimum code

```python3
官网中文文档里面API的使用演示中存在错别字
```

**Comment by zhiyiYo** [comment]
已修复此问题
