### ISSUE TITLE
[Bug]: macOS中，gallery的fluentwindow标题栏高度变高

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#1016]
### What happened?

直接运行gallery的源码会出现这样的标题栏高度变高的错误：
<img width="996" alt="image" src="https://github.com/user-attachments/assets/0a12ca38-b37d-41d9-bff1-f5c289b2b597">
而运行release的app因为没有用macOS的关闭按钮，是正常的。（另外，release中的mac app是无法直接运行的，需要把包里面的demo加上运行权限才行）
<img width="996" alt="image" src="https://github.com/user-attachments/assets/b946c6fb-fcd5-43ff-afce-153d447fd9f5">

### Operation System

macOS15.1.1

### Python Version

3.11.10 64bit

### PyQt/PySide Version

pyside6 6.8.0.2

### PyQt/PySide-Fluent-Widgets Version

1.7.1

### How to Reproduce?

下载gallery源码直接运行

### Minimum code

```python3
暂无
```

**Comment by zhiyiYo** [comment]
pyside6 版本太高，换成 6.7.2 即可解决
