### ISSUE TITLE
作者可以添加一个tableWidget吗

### ISSUE THREAD

**Issue by RoyRen-R** [zhiyiYo/PyQt-Fluent-Widgets#102]
**Describe the bug**

**Environment**
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.6 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):

**Code**
```python
# Minimum code to reproduce the error

```

**Expected behavior**

**Screenshots**

**Comment by RoyRen-R** [comment]
。

**Comment by StoneMoe** [comment]
与 #45 重复
