### ISSUE TITLE
[Bug]: ms_fluent_window例子的最大化 生效后窗口的界面存在问题

### ISSUE THREAD

**Issue by ZzzYanSong** [zhiyiYo/PyQt-Fluent-Widgets#1020]
### What happened?

ms_fluent_window例子的最大化 生效后窗口的界面存在问题
![image](https://github.com/user-attachments/assets/6e2ce41a-3dd8-4a40-a924-a2f060efdfc0)
非最大化时候是正常的
![image](https://github.com/user-attachments/assets/62b50b35-779d-401a-bea3-99065fc8b7da)
最大化后右侧的关闭按钮有一部分超出屏幕，窗口下方的边框也超出了屏幕

### Operation System

Windwos11

### Python Version

3.10

### PyQt/PySide Version

PyQt6

### PyQt/PySide-Fluent-Widgets Version

latest

### How to Reproduce?

运行ms_fluent_window例子 点击最大化

### Minimum code

```python3
ms_fluent_window例子
```

**Comment by zhiyiYo** [comment]
pyqt6 升级到 6.7.2 即可
