### ISSUE TITLE
[Bug]: The action truncates its shortcut at the end

### ISSUE THREAD

**Issue by deeffest** [zhiyiYo/PyQt-Fluent-Widgets#1024]
### What happened?

![img](https://github.com/user-attachments/assets/292b37e2-b6bc-4892-93a5-99857b99ce20)
The entire shortcut text, including the last character, should be fully displayed without truncation.

### Operation System

Windows10 22H2

### Python Version

3.12.3

### PyQt/PySide Version

PySide 6.8.1

### PyQt/PySide-Fluent-Widgets Version

v1.7.0

### How to Reproduce?

1. Run the minimally reproducible example below
2. Right-click on an empty space in the window
3. See the shortcuts cut off at the end

### Minimum code

```python3
from qfluentwidgets import RoundMenu, Action
from PySide6.QtWidgets import QApplication, QMainWindow

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setGeometry(100, 100, 400, 300)

    def contextMenuEvent(self, event):
        menu = RoundMenu(self)
        menu.addAction(Action("Mini-Player", shortcut="Ctrl+M"))
        menu.exec(event.globalPos())

if __name__ == "__main__":
    app = QApplication()
    window = MainWindow()
    window.show()
    app.exec()
```

**Comment by zhiyiYo** [comment]
I tested this demo with PySide6.4.2, but no truncation happened

**Comment by deeffest** [comment]
Yes, having tested this issue on Python 3.11.9 with PySide6.4.2 the problem disappeared, but isn't it better to keep up with the times? On PySide6.8.1, the problem persists.

**Comment by zhiyiYo** [comment]
This is a bug of Qt itself, I think 6.8.2 will fix this issue. You can keep watching this: 
https://bugreports.qt.io/browse/QTBUG-131946

**Comment by deeffest** [comment]
Strange, even after installing PySide6.7.3 (I checked also 6.6, same thing) the problem is still there, although the report only affects 6.8+

**Comment by rainzee** [comment]
Could you try running your application with "-platform windows:fontengine=gdi" (or with the equivalent settings in the application's Qt.conf file)? Doing this should give you the original font backend and might be a suitable work-around until the issue has been fixed.

**Comment by deeffest** [comment]
![img](https://github.com/user-attachments/assets/bbcc31fc-aabb-422d-bc65-1ed644c3b077)
Still the same problem. Can you reproduce this issue on your end?
