### ISSUE TITLE
[Bug]: windows 2.5k分辨率下缩放200%时非常模糊

### ISSUE THREAD

**Issue by wuyuesong** [zhiyiYo/PyQt-Fluent-Widgets#1025]
### What happened?

windows 2.5k分辨率下缩放200%时非常模糊

### Operation System

Windows 11   wsl

### Python Version

3.12.7

### PyQt/PySide Version

 5.15.11

### PyQt/PySide-Fluent-Widgets Version

1.7.2

### How to Reproduce?

windows 中设置2.5k分辨率，并缩放200%，然后在wsl下运行示例程序：
cd examples/gallery
python demo.py

### Minimum code

```python3
运行示例程序examples/gallery/demo.py
```

**Comment by zhiyiYo** [comment]
这个和组件库没什么关系，换成pyside6或者pyqt6会好很多
