### ISSUE TITLE
[Bug]: ComboBox无法禁用（禁止点击）部分选项

### ISSUE THREAD

**Issue by Whitolf** [zhiyiYo/PyQt-Fluent-Widgets#1026]
### What happened?

QComboBox可以通过.model().item(2).setEnabled(False) 实现禁用部分选项，但是ComboBox没有.model()方法了

### Operation System

Winfows11 

### Python Version

3.8 64bit

### PyQt/PySide Version

PySide6 6.6.2

### PyQt/PySide-Fluent-Widgets Version

1.7.2

### How to Reproduce?

self.box = ComboBox(self)
self.box.model().item(2).setEnabled(False)

### Minimum code

```python3
self.box = ComboBox(self)
self.box.model().item(2).setEnabled(False)
```

**Comment by mengdeer589** [comment]
qfluentwidgets的下拉框组件，是根据QPushButton继承改写的，而不是继承QComboBox来写的，所以方法并不完全与QComboBox一致。
对于你提到的需求，禁用部分下拉框菜单项，其实很简单，可以通过继承ComboBox，增加禁用选项的方法以及重写_showComboMenu方法来实现，下面我写了个示例代码，仅供参考。
`import sys

from PyQt5.QtCore import QPoint
from PyQt5.QtWidgets import QAction, QApplication, QLabel, QVBoxLayout, QWidget
from qfluentwidgets import ComboBox, MenuAnimationType


class ComboBoxWithEnable(ComboBox):
    def __init__(self, parent):
        super().__init__(parent)
        self.enabled_items: dict[int, bool] = {}  # 该字典用于记录哪些选项需要禁用

    def set_item_enable(self, idx: int, enable: bool) -> None:
        """添加此方法用于设置选项禁用或者启用"""
        self.enabled_items |= {idx: enable}

    def clear(self):
        """添加对禁用字典的清除"""
        super().clear()
        self.enabled_items.clear()

    def _showComboMenu(self):
        """重写下拉选项菜单，根据条件禁用部分选项"""
        if not self.items:
            return

        menu = self._createComboMenu()
        for i, item in enumerate(self.items):
            action = QAction(
                item.icon, item.text, triggered=lambda c, x=i: self._onItemClicked(x)
            )
            if i in self.enabled_items:
                action.setEnabled(self.enabled_items[i])
            menu.addAction(action)

        if menu.view.width() < self.width():
            menu.view.setMinimumWidth(self.width())
            menu.adjustSize()

        menu.setMaxVisibleItems(self.maxVisibleItems())
        menu.closedSignal.connect(self._onDropMenuClosed)
        self.dropMenu = menu

        # set the selected item
        if self.currentIndex() >= 0 and self.items:
            menu.setDefaultAction(menu.actions()[self.currentIndex()])

        # determine the animation type by choosing the maximum height of view
        x = (
            -menu.width() // 2
            + menu.layout().contentsMargins().left()
            + self.width() // 2
        )
        pd = self.mapToGlobal(QPoint(x, self.height()))
        hd = menu.view.heightForAnimation(pd, MenuAnimationType.DROP_DOWN)

        pu = self.mapToGlobal(QPoint(x, 0))
        hu = menu.view.heightForAnimation(pu, MenuAnimationType.PULL_UP)

        if hd >= hu:
            menu.view.adjustSize(pd, MenuAnimationType.DROP_DOWN)
            menu.exec(pd, aniType=MenuAnimationType.DROP_DOWN)
        else:
            menu.view.adjustSize(pu, MenuAnimationType.PULL_UP)
            menu.exec(pu, aniType=MenuAnimationType.PULL_UP)


class MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        layout = QVBoxLayout(self)

        self.label = QLabel("请选择一项", self)
        layout.addWidget(self.label)

        self.combo_box = ComboBoxWithEnable(self)

        self.combo_box.addItems(["Apple", "Banana", "Cherry"])
        self.combo_box.set_item_enable(0, False)  # 根据索引禁用第一个选项
        layout.addWidget(self.combo_box)
        self.resize(300, 100)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(app.exec_())
`

**Comment by zhiyiYo** [comment]
下个版本可以使用 `setItemEnabled` 来设置选项的可用性

**Comment by zhiyiYo** [comment]
1.7.4 已发布
