### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xqyjlj** [zhiyiYo/PyQt-Fluent-Widgets#1030]
### What happened?

Shortcut出现截断且快捷键无法响应的现象

### Operation System

win11

### Python Version

3.10.14

### PyQt/PySide Version

6.6.2

### PyQt/PySide-Fluent-Widgets Version

1.6.6

### How to Reproduce?

出现截断现象

![image](https://github.com/user-attachments/assets/83d0f26e-67a8-4ed4-a802-74f5603c4dac)

RoundMenu 快捷键无法响应

### Minimum code

```python3
examples/menu/menu/demo.py 示例即可复现
```

**Comment by xqyjlj** [comment]
目前改成如下可以解决

![image](https://github.com/user-attachments/assets/a002b953-c116-4a2e-8285-f9aeaff3e982)

![image](https://github.com/user-attachments/assets/98010190-bc57-4f91-b46a-0e4dc4c85bd6)

这种解决方式可以蹭个pr吗

**Comment by zhiyiYo** [comment]
qt 官方的 bug，你把 pyside6 降级到 6.4.2 就能解决，或者等 pyside6.8.2 的发布
