### ISSUE TITLE
运行 gallery 和 navigation 示例时发生报错

### ISSUE THREAD

**Issue by Moxiner** [zhiyiYo/PyQt-Fluent-Widgets#104]
**Describe the bug**
运行 ```gallery``` 和 ```navigation``` 示例时发生报错

**Environment**
- OS: Windows 11 专业版 22H2
- DPI scaling: 150%
- Python: 3.8.6 64-bit
- PyQt: 5.15.9 and  6.4.2
- PyQt-Fluent-Widgets:  0.6.3

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
前提概要
- 已经尝试升级为最新版 ```PyQt-Fluent-Widgets```
- 已经确保执行目录在 ```gallery``` 目录
- 已经确保运行的是 ```demo.py``` 文件
- 已经确保没有修改 ```demo.py``` 的任何代码

复现步骤
1. 打开```Vscode```
2. 打开```gallery```文件夹
3. 运行```demo.py```文件
4. 终端报错 ```QWidget: Must construct a QApplication before a QWidget```
5. 同理，满足以上条件时，复现以上步骤，在 ```navigation```  窗口也会有相同报错，并不会弹出示例窗口

这个报错并非编译器抛出 （无Traceback），貌似是QWidget的警告，但无法出现示例窗口

**Code**
```python
# Minimum code to reproduce the error
# 我并不需要提供额外的复现代码
# 复现代码为 ./gallery/demo.py
```

**Expected behavior**
运行```demo.py```是应该会弹出示例窗口

**Screenshots**
代码报错截图
[![代码报错](https://s1.ax1x.com/2023/04/10/ppb2GnI.png)](https://imgse.com/i/ppb2GnI)
各种关于Pyqt相关库的截图
[![各种关于Pyqt相关库](https://s1.ax1x.com/2023/04/10/ppb2NAf.md.png)](https://imgse.com/i/ppb2NAf)

**Last**
我知道这很可能并不是一个Bug（或许），前几个版本都还可，就升级到 ```0.6.3``` 就寄了，我作为一个菜鸡，连 ```demo.py``` 都没看懂，更不要提自己 ```debug``` 了，希望能有好心的大佬解决一下这个 ```Issuse```，谢谢！( •̀ ω •́ )✧

**Comment by zhiyiYo** [comment]
0.6.3 不是最新版本

**Comment by Moxiner** [comment]
是0.6.8嘛？我记得我升级到0.6.8试过了，也不太行，中午试一下，然后截图反馈

**Comment by Moxiner** [comment]
我尝试用 ```pip install --upgrade "PyQt-Fluent-Widgets[full]" -i https://pypi.org/simple/``` 升级 ```PyQt-Fluent-Widgets```，还是不行，下面是截图

[![pip升级库截图](https://s1.ax1x.com/2023/04/10/ppbXGW9.md.png)](https://imgse.com/i/ppbXGW9)
[![报错截图](https://s1.ax1x.com/2023/04/10/ppbjq9H.md.png)](https://imgse.com/i/ppbjq9H)

**Comment by zhiyiYo** [comment]
要不搭个虚拟环境试试

**Comment by Moxiner** [comment]
来反馈一下，确实是```PyQt5、PySide2```和```PyQt6、PySide6``` 冲突了
删除 ```PyQt6、PySide6``` 等相关库就好了。
这是删除了 ```PyQt6、PySide6``` 等相关库后的```pip list```
[![pip list](https://s1.ax1x.com/2023/04/14/ppzBjyQ.png)](https://imgse.com/i/ppzBjyQ)
运行成功的截图
[![运行成功后的截图](https://s1.ax1x.com/2023/04/14/ppzDKFx.png)](https://imgse.com/i/ppzDKFx)
