### ISSUE TITLE
gallery的demo在版本更新时会考虑打包成exe发布吗？方便试看

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#107]

**Comment by zhiyiYo** [comment]
这也太麻烦了，天天更新那还了得

**Comment by zhiyiYo** [comment]
下次也许可以搞搞

**Comment by Cheukfung** [comment]
我之前用过nuitka打包，效果还是很可以的

**Comment by Cheukfung** [comment]
你新建一个环境试试，我打包的好像是60多mb

**Comment by zhiyiYo** [comment]
有些动态链接库可以删掉

**Comment by Cheukfung** [comment]
@zhiyiYo 事实证明pyinstaller确实不够安全，支持了你的语核科技，他们的app就是pyinstaller打包的，还没用加密（虽然用了也能大概率能破解），我0基础，搜索了下用了10分钟就把源码反编译出来了。而且pyinstaller打包为单文件的时候，运行极慢。想不被反编译还是建议nuitka

**Comment by zhiyiYo** [comment]
gallery 程序应该没必要加密吧

**Comment by Cheukfung** [comment]
本来就是开源的的确没必要，只是看到那个语核的app就想到了这个issue

**Comment by zhiyiYo** [comment]
他们好像也没在源代码里面写敏感的东西，不加密也问题不大

**Comment by Cheukfung** [comment]
接口什么的都全部在里面，感觉也不太好，而且目前好像不用登陆也能用

**Comment by zhiyiYo** [comment]
刚刚和他们反馈了一下，不知道会不会改过来

**Comment by 140ai** [comment]
> > 有些动态链接库可以删掉
> 
> 7z压缩后只有20mb 我感觉已经非常小了

你好，请问使用upx压缩会不会更好，我试了一下，会报this application failed to start because no qt platform plugin could be initialized，不用upx就不会报错，你知道什么原因吗

**Comment by 140ai** [comment]
> 有些动态链接库可以删掉

请问什么样的动态链接库可以删除
