### ISSUE TITLE
圆角窗体问题

### ISSUE THREAD

**Issue by ITSweets** [zhiyiYo/PyQt-Fluent-Widgets#11]
您好。无意中看到您这个库。使用了一下。在 Windows 10 上无边框使用系统的 DWM 阴影。如果窗体想要开启圆角使用 QSS 。则会出现一个白色的一层窗体。如果使用 Qt 的 API 设置为透明背景则 DWM 阴影消失。这二者互斥。有什么解决方法么？

**Comment by zhiyiYo** [comment]
可以描述的清晰点吗，这个断句看的也太难受了。而且如果你想问的是无边框窗口的问题的话，建议在 [PyQt-Frameless-Window](https://github.com/zhiyiYo/PyQt-Frameless-Window/issues) 提 issue

**Comment by ITSweets** [comment]
在  examples/settings/demo.py 文件的第 63 行加上         self.setStyleSheet("""
            QWidget {border-radius: 20px;}
        """)  然后运行你就会看到问题了

或者你看这个文章的问题，是一样的 https://blog.csdn.net/qq_36780295/article/details/109805454

**Comment by zhiyiYo** [comment]
窗口圆角取决于操作系统，如果你想自定义圆角的话就只能把窗口弄成透明无边框，然后自己加上阴影

**Comment by zhiyiYo** [comment]
但是这样做会有很多问题

**Comment by ITSweets** [comment]
是的，这二者是冲突的。所以想来问问作者有什么解决方案。

**Comment by zhiyiYo** [comment]
没有很好的解决方案呀，二者本来就是不可调和的

**Comment by ITSweets** [comment]
好吧，我会在二者之间进行取舍。还想问一下。在 Linux 和 MacOS 下阴影是如何做到的？Linux 也是系统的 API 吗？

**Comment by zhiyiYo** [comment]
Linux 和 MacOS 不用向 Windows 一样调用系统 API 来添加阴影，就算去掉了边框还是会有阴影

**Comment by ITSweets** [comment]
所有的 Linux 发行版都是如此吗？Debian 系列的和 Red Hat 系列的。

**Comment by zhiyiYo** [comment]
Ubuntu 是这样的，好像 Arch 就不行，具体还是取决于窗口管理器吧

**Comment by ITSweets** [comment]
好的，感谢您的回复。
