### ISSUE TITLE
跑readme中的案例报错

### ISSUE THREAD

**Issue by CharlesKeeling65** [zhiyiYo/PyQt-Fluent-Widgets#113]
**Describe the bug**
跑readme中的案例报错
examples\gallery> python demo.py

------------------------------------------------------------------------------------------------------------------------
demo.py 9 <module>
from app.view.main_window import MainWindow

main_window.py 14 <module>
from .basic_input_interface import BasicInputInterface

basic_input_interface.py 4 <module>
from qfluentwidgets import (PushButton, ToolButton, PrimaryPushButton, HyperlinkButton,

ImportError:
cannot import name 'EditableComboBox' from 'qfluentwidgets'

**Environment**
- OS: Windows
- DPI scaling: 125%
- Python: 3.8.8 64-bit]
- PyQt: 6.5.0
- PyQt-Fluent-Widgets: 0.6.3

![tmpD63C](https://user-images.githubusercontent.com/94165417/231158678-06d7ecba-151b-4070-b1cc-65b69271ef23.png)

**Comment by zhiyiYo** [comment]
版本太低了，建议到 pypi 官网下载最新版

**Comment by CharlesKeeling65** [comment]
> 版本太低了，建议到 pypi 官网下载最新版

我更新之后，这个demo.py还是报错，其他的demo.py都能运行，就是gallery的这个还是不行
demo.py 9 <module>
from app.view.main_window import MainWindow

main_window.py 18 <module>
from .material_interface import MaterialInterface

material_interface.py 3 <module>
from qfluentwidgets.components.widgets.acrylic_label import AcrylicLabel

acrylic_label.py 9 <module>
from ...common.image_utils import gaussianBlur

image_utils.py 8 <module>
from scipy.ndimage.filters import gaussian_filter

__init__.py 130 <module>
from . import _distributor_init

_distributor_init.py 59 <module>
WinDLL(os.path.abspath(filename))

__init__.py 381 __init__
self._handle = _dlopen(self._name, mode)

FileNotFoundError:
Could not find module 'E:\Anaconda3\envs\spiderenvs\lib\site-packages\scipy\.libs\libbanded5x.3OIBJ6VWWPY6GDLEMSTXSIPCHHWASXGT.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.
![tmpCB60](https://user-images.githubusercontent.com/94165417/231166794-040e2be5-c0e0-4f1f-b0b6-75c9aff0a2e3.png)

**Comment by zhiyiYo** [comment]
安装虚拟环境试试？

**Comment by CharlesKeeling65** [comment]
> 建一个新的虚拟环境试试？
创了新环境，也还是不行，报错`QWidget: Must construct a QApplication before a QWidget`，而且menu/demo.py，也没法跑了，报错如下：
```
Traceback (most recent call last):
  File "F:\005_Programming\PyQt6项目\PyQt-Fluent-Widgets-PyQt6\examples\menu\demo.py", line 25, in contextMenuEvent
    menu = RoundMenu(parent=self)
  File "E:\Anaconda3\envs\pyqt_envs\lib\site-packages\qfluentwidgets\components\widgets\menu.py", line 179, in __init__
    super().__init__(parent=parent)
TypeError: QWidget(parent: typing.Optional[QWidget] = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 'parent' has unexpected type 'Demo'
```

类似的combo_box/demo.py，也是`QWidget: Must construct a QApplication before a QWidget`

**Comment by CharlesKeeling65** [comment]
> 用的 pyqt6 版本是多少？我平时测试都是用的 6.4.2

我的是6.5.0

**Comment by CharlesKeeling65** [comment]
> 

```PowerShell
Name: PyQt6
Version: 6.4.2
Summary: Python bindings for the Qt cross platform application toolkit
Home-page: https://www.riverbankcomputing.com/software/pyqt/
Author: Riverbank Computing Limited
Author-email: info@riverbankcomputing.com
License: GPL v3
Location: e:\anaconda3\envs\pyqt_envs\lib\site-packages
Requires: PyQt6-Qt6, PyQt6-sip
Required-by:
```

换成6.4.2 还是和上面的错误一样

```PowerShell
(pyqt_envs) PS F:\005_Programming\PyQt6项目\PyQt-Fluent-Widgets-PyQt6\examples\gallery> python demo.py
QWidget: Must construct a QApplication before a QWidget
```
