### ISSUE TITLE
[功能请求] 支持从 NavigationInterface 移除一个 item

### ISSUE THREAD

**Issue by StoneMoe** [zhiyiYo/PyQt-Fluent-Widgets#116]
## 关于请求
目前可以通过 `NavigationInterface.addItem()` 为左侧导航栏添加项目，是否能支持一个 `delItem()` 来移除之前添加的一个/多个item?

## 原始需求
我正在实现一个简单的项目管理软件，目前想设计成将项目列表展示在navigation的scroll区域内。
但发现没有办法delItem来在删除项目/刷新项目列表时，来更新navigation.

## 意义
个人感觉是 `delItem` 一个比较具有普适性需求的接口，于是烦请作者考虑一下是否有必要增加这个支持。

**Comment by youjunxiaji** [comment]
> ## 关于请求
> 目前可以通过 `NavigationInterface.addItem()` 为左侧导航栏添加项目，是否能支持一个 `delItem()` 来移除之前添加的一个/多个item?
> 
> ## 原始需求
> 我正在实现一个简单的项目管理软件，目前想设计成将项目列表展示在navigation的scroll区域内。 但发现没有办法delItem来在删除项目/刷新项目列表时，来更新navigation.
> 
> ## 意义
> 个人感觉是 `delItem` 一个比较具有普适性需求的接口，于是烦请作者考虑一下是否有必要增加这个支持。

你好，我想请问下左侧的导航栏是基于什么生成的呢，是toolbar吗？

**Comment by zhiyiYo** [comment]
PyQt5 分支实现了这个需求，但是我还没合并到 master

**Comment by zhiyiYo** [comment]
打算等写完时间和日期组件之后合并然后发布到 pypi

**Comment by youjunxiaji** [comment]
> 打算等写完时间和日期组件之后合并然后发布到 pypi

好的 感谢博主  期待一下

**Comment by StoneMoe** [comment]
> 你好，我想请问下左侧的导航栏是基于什么生成的呢，是toolbar吗？

@youjunxiaji 没看明白你的问题是什么意思

**Comment by StoneMoe** [comment]
@zhiyiYo 想问一下目前最优先支持的是哪个分支？目前在用PySide6。

**Comment by zhiyiYo** [comment]
优先支持pyqt5
