### ISSUE TITLE
pushButton图标错位问题

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#118]
当我在pushbutton上加入图标时，变成了这样
![image](https://user-images.githubusercontent.com/94896689/231635799-bfbbe5a6-2f48-4733-a4b0-a17683429fad.png)

**Comment by zhiyiYo** [comment]
能贴下代码吗，正确的写法应该是：
```python
PushButton('载荷优化', self, icon)
```

**Comment by youjunxiaji** [comment]
> 能贴下代码吗，正确的写法应该是：
> 
> ```python
> PushButton('载荷优化', self, icon)
> ```

当然，我可能比较懒，我用的qtdesginer直接生成的
![image](https://user-images.githubusercontent.com/94896689/231636692-26ba593a-48a6-4e66-8de5-0e3cc9d3fb84.png)
然后，我重写了你的方法，因为qtdesginer先传入的是一个parent
![image](https://user-images.githubusercontent.com/94896689/231636809-151d5695-a802-4681-a156-05b5243bb142.png)

**Comment by zhiyiYo** [comment]
可能得把 `PushButton` 的 `setIcon()` 改一下：
```python
def setIcon(self, icon: Union[QIcon, str, FluentIconBase]):
        self.setProperty('hasIcon', icon is not None)
        self.setStyle(QApplication.style())
        self._icon = icon
        self.update()
```

**Comment by youjunxiaji** [comment]
> 可能得把 `PushButton` 的 `setIcon()` 改一下：
> 
> ```python
> def setIcon(self, icon: Union[QIcon, str, FluentIconBase]):
>         self.setProperty('hasIcon', icon is not None)
>         self.setStyle(QApplication.style())
>         self._icon = icon
>         self.update()
> ```

好的感谢  可以了

**Comment by youjunxiaji** [comment]
还有一个问题，大概就是LineEdit显示不全的问题。因为之前在我使用4K的外接显示器的时候都是显示好的。所以我高度怀疑问题是出在了显示器的分辨率上面导致的放大缩小百分比所引发的一系列问题!
![image](https://user-images.githubusercontent.com/94896689/231658301-ad7ce632-bbb3-4838-8595-7529d744b241.png)
