### ISSUE TITLE
dialog/Ui_MessageBox

### ISSUE THREAD

**Issue by suterberg** [zhiyiYo/PyQt-Fluent-Widgets#122]
def __onCancelButtonClicked(self):
        self.cancelSignal.emit()
        self.reject()
信号发送和reject函数是不是要换个位置，通过信号调用其他窗口时本窗口不会关闭，会有遮挡

**Comment by zhiyiYo** [comment]
就算移动到后面应该还是会有遮挡吧？

**Comment by zhiyiYo** [comment]
应该根据 `dialog.exec()` 的返回值来决定调用什么函数

**Comment by suterberg** [comment]
> 就算移动到后面应该还是会有遮挡吧？

先reject()当前窗口会关闭，不会遮挡
