### ISSUE TITLE
Navigation展开状态时，更新导航栏内item的UI错误

### ISSUE THREAD

**Issue by StoneMoe** [zhiyiYo/PyQt-Fluent-Widgets#124]
**Describe the bug**
当Navigation为expanded状态时，此时调用`NavigationInterface.addItem()`，item仅展示`icon`而未展示`text`

**Environment**
- OS: Win11
- DPI scaling: 100%
- Python: 3.10
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: a99c7041b58ade0c678a2142f4f0d1fd49a6996e

**Screenshots**
![image](https://user-images.githubusercontent.com/5786577/232193442-bda972f9-3360-4cfc-a493-a5a602d8999a.png)

**Comment by zhiyiYo** [comment]
得调用 `item.setCompacted(True)` 才能显示

**Comment by StoneMoe** [comment]
考虑在expanded时作为默认行为吗？

**Comment by zhiyiYo** [comment]
`qfluentwidgets/components/navigation/navigation_panel.py` 的 `addWidget()` 函数中加上下述代码试试：
```python
if self.displayMode in [NavigationDisplayMode.EXPAND, NavigationDisplayMode.MENU]:
    widget.setCompacted(True)
```

**Comment by StoneMoe** [comment]
> 试下在 `qfluentwidgets/components/navigation/navigation_panel.py` 的 `addWidget()` 函数中加上：
> 
> ```python
> if self.displayMode in [NavigationDisplayMode.EXPAND, NavigationDisplayMode.MENU]:
>     widget.setCompacted(True)
> ```

添加了你提到的代码，并改为`widget.setCompacted(False)` 后，是符合直觉的预期行为了。

**Comment by zhiyiYo** [comment]
为啥改成 `widget.setCompacted(False)`

**Comment by StoneMoe** [comment]
> 为啥改成 `widget.setCompacted(False)`

因为....无论是从函数名的语义上来说，还是其逻辑来说，在panel为expanded状态时，widget就应该不是"Compacted"？

**Comment by zhiyiYo** [comment]
哦哦，我傻了

**Comment by StoneMoe** [comment]
是否考虑把这个代码正式添加到库里？

**Comment by zhiyiYo** [comment]
v0.7.0已添加此代码
