### ISSUE TITLE
There might be a typo "NavigationItemPostion"

### ISSUE THREAD

**Issue by zhang-wenjun** [zhiyiYo/PyQt-Fluent-Widgets#126]
Hi, I tried to run the demo but got this error:
`cannot import name 'NavigationItemPosition' from 'qfluentwidgets'`
I think it's because of the typo `NavigationItemPostion` (missing "i"). I correct this and run the successfully.

Nice package, btw!

**Comment by zhiyiYo** [comment]
你用的是 PyQt5 分支的代码吗？这个分支的代码还没打包发布到 pypi 上，可以先试试 master 分支的代码

**Comment by zhang-wenjun** [comment]
是的，不过改了这个也能跑hhh

**Comment by zhiyiYo** [comment]
你应该是安了包之后跑的吧？如果直接用 qfluentwidgets 文件夹里面的代码来跑应该不会报错

**Comment by zhang-wenjun** [comment]
对，是的
