### ISSUE TITLE
关于Navigtion中demo.py的bug

### ISSUE THREAD

**Issue by linyang-cq** [zhiyiYo/PyQt-Fluent-Widgets#128]
from qfluentwidgets import (NavigationInterface, NavigationItemPostion, NavigationWidget, MessageBox,
                            isDarkTheme, setTheme, Theme, setThemeColor)
上面NavigationItemPostion类的导入时，应该为NavigationItemPosition

**Comment by zhiyiYo** [comment]
你有 git pull 更新 examples 的代码吗？

**Comment by zhiyiYo** [comment]
或者说你安装的包版本太低了，试一下最新 v0.7.0

**Comment by zhiyiYo** [comment]
目前已修复此问题
