### ISSUE TITLE
examples-settings更改选项框内容后崩溃

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#13]
**Describe the bug**
更改选项框内容后程序崩溃

**Environment**
- OS: Windows11 Insider Preview 25295.1000
- DPI scaling: 100%
- Python: Python 3.11.0 64Bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.2.6

**To Reproduce**
![录制_2023_03_04_12_51_14_722](https://user-images.githubusercontent.com/101497799/222876521-59b7013d-bb3b-4573-bcca-6a4d39af2d4b.gif)
![录制_2023_03_04_12_51_50_590](https://user-images.githubusercontent.com/101497799/222876543-b321b250-d92e-4344-8702-05e40b935a23.gif)
1.更改任何一个选项框的内容
2.见错误
3.程序崩溃
4.重启程序后选项框的选项是生效的（比如变成深色模式）

**Code**
```python
Traceback (most recent call last):
  File "D:\WinDownload\examples\settings\setting_interface.py", line 260, in __showRestartTooltip
    ToastToolTip.warn(
    ^^^^^^^^^^^^^^^^^
AttributeError: type object 'ToastToolTip' has no attribute 'warn'
```

请修复此BUG

**Comment by zhiyiYo** [comment]
你下载的是最新的包吗，这个方法是我昨天才加进去的

**Comment by fsf678** [comment]
是的，使用的是PyQt-Fluent-Widgets: 0.2.6

**Comment by zhiyiYo** [comment]
现在应该是 0.2.7 了

**Comment by fsf678** [comment]
我现在尝试使用官方源下载最新版本？

**Comment by zhiyiYo** [comment]
清华源也可以，只要更新到 0.2.7 就行

**Comment by fsf678** [comment]
成功的修复 😀
