### ISSUE TITLE
Infobar没设置标题和关闭按钮时与其他情况高度不一致

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#130]
当infobar把标题设置为空，并且isClosable设置为False，infobar整体高度就会变矮，标题不为空，或者isClosable不为False的时候高度都正常的。
![image](https://user-images.githubusercontent.com/14865236/232352668-2bf53a16-4d7f-4174-9dfa-b764ec73c870.png)
![image](https://user-images.githubusercontent.com/14865236/232352688-c6d2a115-6f61-4613-9b3d-5e8355de08fb.png)
![image](https://user-images.githubusercontent.com/14865236/232352719-d8232e9c-ad15-48f3-bb9d-711ef3777d01.png)

**Comment by suterberg** [comment]
应该是布局自动压缩，把InfoIconWidget改一下就好，具体代码如下
` def __init__(self, icon: InfoBarIcon, parent=None):
        super().__init__(parent=parent)
        self.setFixedSize(36,36)
        self.icon = icon

    def paintEvent(self, e):
        painter = QPainter(self)
        painter.setRenderHints(QPainter.Antialiasing |
                               QPainter.SmoothPixmapTransform)


        #drawIcon(self.icon, painter, self.rect())

        if self.icon != InfoBarIcon.INFORMATION:
            drawIcon(self.icon, painter, QRectF(10, 10, 16, 16))
        else:
            svg = writeSvg(self.icon.path(), [0], fill=themeColor().name())
            drawSvgIcon(svg.encode(), painter, QRectF(10, 10, 16, 16))`
