### ISSUE TITLE
功能询问

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#133]
想问一下博主，目前pyside6有这个界面吗

![image](https://user-images.githubusercontent.com/94896689/232683549-7e1cebff-e2c9-45e0-b945-6e4b5e7eaa91.png)

**Comment by zhiyiYo** [comment]
应该没有吧？这个看起来是安装包程序才有的界面

**Comment by youjunxiaji** [comment]
> 如果你想做安装包可以试试 inno setup

是的我知道。我在程序里面写了个另存为功能，用的是getExistingDirectory。这个功能在新建文件夹方面不是很直观，所以我比较好奇qt存不存在这样的界面

**Comment by zhiyiYo** [comment]
可能得调用 Windows 系统 api

**Comment by youjunxiaji** [comment]
> Owner

是的 感谢
