### ISSUE TITLE
窗口左上角出现这点东西

### ISSUE THREAD

**Issue by v479038280** [zhiyiYo/PyQt-Fluent-Widgets#134]
[
![微信截图_20230419000527](https://user-images.githubusercontent.com/25096045/232837968-cb472422-48ea-4629-b92c-3644204afc2a.png)

](url)

把界面里的固定部分删除掉后左上角出现这些，不知道哪儿出的问题，程序逻辑嵌套好多，翻来翻去不知怎么去掉这东西

**Comment by suterberg** [comment]
你这不贴代码谁知道你改哪里了......

**Comment by zhiyiYo** [comment]
建议贴下最小复现代码，不然我也不知道问题出在哪

**Comment by v479038280** [comment]
> 建议贴下最小复现代码，不然我也不知道问题出在哪

用了navigation的模板改，不出现那个问题了。我改的乱七八糟的，都不知道该贴哪儿的代码。。。
这个可以设置窗口内的内容自动缩放吗

**Comment by zhiyiYo** [comment]
内容缩放指的是 dpi 缩放？

**Comment by v479038280** [comment]
> > 建议贴下最小复现代码，不然我也不知道问题出在哪
> 
> 用了navigation的模板改，不出现那个问题了。我改的乱七八糟的，都不知道该贴哪儿的代码。。。 这个可以设置窗口内的内容自动缩放吗

在不同的电脑下最大化窗口后，界面里的内容好像不能全部显示[
![屏幕截图 2023-04-20 125143](https://user-images.githubusercontent.com/25096045/233261540-10352827-82d1-46da-b439-3b90f58f8f77.jpg)
](url)

**Comment by v479038280** [comment]
> 内容缩放指的是 dpi 缩放？

我在下边贴了张图

**Comment by zhiyiYo** [comment]
你这是绝对坐标？有用流式布局吗

**Comment by v479038280** [comment]
> 你这是绝对坐标？有用流式布局吗

没有，直接在界面内添加addlayout的方式把widgits一个一个的放进去的

**Comment by zhiyiYo** [comment]
内容缩放是不可能的，不过你可以换成流式布局

**Comment by v479038280** [comment]
> 内容缩放是不可能的，不过你可以换成流式布局

流式布局效果非常棒

> 内容缩放是不可能的，不过你可以换成流式布局

流式布局可以正常显示了，不过用了流式布局，用nuitka打包后界面又不能正常显示，运行生成的exe，界面就一直卡着的状态了

**Comment by zhiyiYo** [comment]
不用流式布局会卡住吗

**Comment by zhiyiYo** [comment]
我用 pyinstaller 打包也没出现过卡界面的情况，可能是你的哪个资源文件找不见报错了？

**Comment by v479038280** [comment]
> 不用流式布局会卡住吗

不用流式布局不会卡住，我把代码里这句去掉        # self.window().showMaximized()，然后就正常了。

**Comment by zhiyiYo** [comment]
你是win7系统吗

**Comment by v479038280** [comment]
> 不用流式布局会卡住吗

不用流式布局不会卡住，我把代码里这句去掉        # self.window().showMaximized()，然后就正常了。

> 你是win7系统吗

用的Windows 10 专业版,64位，

**Comment by zhiyiYo** [comment]
试一下把无边框窗口的包升级到最新版本，如果用的是 pyqt5 就升级 pyqt5-frameless-windows

**Comment by Cheukfung** [comment]
> > 你这是绝对坐标？有用流式布局吗
> 
> 没有，直接在界面内添加addlayout的方式把widgits一个一个的放进去的，有没有什么选项可以设置内容随着窗口来x
> 
> > 
> 
> 哦，哦，我试试。流式布局的话每行显示的数目就随时变动了，有把水平移动scrollarea打开的方式没呢，这样可以滑动着把没显示的看到

你把scollarea的水平滚动打开应该可以实现你的需求

**Comment by v479038280** [comment]
> > > 你这是绝对坐标？有用流式布局吗
> > 
> > 
> > 没有，直接在界面内添加addlayout的方式把widgits一个一个的放进去的，有没有什么选项可以设置内容随着窗口来x
> > > 
> > 
> > 
> > 哦，哦，我试试。流式布局的话每行显示的数目就随时变动了，有把水平移动scrollarea打开的方式没呢，这样可以滑动着把没显示的看到
> 
> 你把scollarea的水平滚动打开应该可以实现你的需求

是的我用的太不熟，每一个换都得先看看基本的

**Comment by zhiyiYo** [comment]
nuika 编译出来的 exe 可以携带终端吗，如果有终端的话看看终端有没有报错信息

**Comment by Cheukfung** [comment]
> nuikta 编译出来的 exe 可以携带终端吗，如果有终端的话看看终端有没有报错信息

可以带。但我觉得可能是nuitka的bug，我自己用用pyside6写的程序，用了popupstackedwidget，直接运行没任何问题，打包之后，popup动画直接消失了，我猜测这个流式布局也可能是同样的原因

**Comment by zhiyiYo** [comment]
还是用 pyinstaller 吧

**Comment by Cheukfung** [comment]
目前nuitka我遇到的有两个坑，一个就是打包pyqt5如果用movetothread方式实现多线程，会失效，只能用继承Qthread重写run方法才行。另一个就是打包pyside6，popupstackedwidget动画会消失，其他的都没问题。运行速度，打包后的大小，防止反编译还是niutka好。

**Comment by zhiyiYo** [comment]
那我下次用这个打包 gallery 试试

**Comment by v479038280** [comment]
> nuikta 编译出来的 exe 可以携带终端吗，如果有终端的话看看终端有没有报错信息

我看了下终端，是我没有把qss文件复制到编译出来的文件里。。。加进去没问题了。。。

**Comment by v479038280** [comment]
galary里的一个带遮罩的对话框好像是不能正常显示的。

另这个设置页，用了FlowLayout的话，界面内容就压缩的不像样了，我用了FlowLayout就没那样，还没看出哪儿的区别。设置页是加入到了statckwidget里，能不能做个单独的只占据界面一部分的样式，在这基础上能不能有层级设置的效果。。建议啊

我用nuitka打包navigation只有不到3分钟，打包galary时间长点，没细算，顶多也就10多分钟。我跟你的编译器不一样，我用的cl。

**Comment by v479038280** [comment]
> > 目前nuitka我遇到的有两个坑，一个就是打包pyqt5如果用movetothread方式实现多线程，会失效，只能用继承Qthread重写run方法才行。另一个就是打包pyside6，popupstackedwidget动画会消失，其他的都没问题。运行速度，打包后的大小，防止反编译还是niutka好。
> 
> 我试了一下打包release中的gallery demo，大概花了40min打包完毕，删除不用的pyd和dll本体145m，zip压缩49.4m，7z压缩36.5m，zip大小对比大大发布的zip小10m吧，不知道我用的打包命令还有没有可以优化的空间？
> 
> `nuitka --standalone --windows-disable-console --enable-plugin=pyqt5 --mingw64 --show-memory --show-progress demo.py`

galary里的一个带遮罩的对话框好像是不能正常显示的。

另这个设置页，用了FlowLayout的话，界面内容就压缩的不像样了，我用了FlowLayout就没那样，还没看出哪儿的区别。设置页是加入到了statckwidget里，能不能做个单独的只占据界面一部分的样式，在这基础上能不能有层级设置的效果。。建议啊

我用nuitka打包navigation只有不到3分钟，打包galary时间长点，没细算，顶多也就10多分钟。我跟你的编译器不一样，我用的cl。

**Comment by zhiyiYo** [comment]
不能正常显示是啥情况，有报错吗

**Comment by v479038280** [comment]
[
![微信截图_20230421131154](https://user-images.githubusercontent.com/25096045/233546247-463b3141-2a64-4e15-bf38-ce941ecbeb0e.png)
](url) 把配置页self.settingInterface = Widget('Setting Interface', self)
       改为了 self.settingInterface = SettingInterface()。从galary里复制过来一个SettingInterfac.py然后setting_button消失了，左上角也不正常了

**Comment by Cheukfung** [comment]
> galary里的一个带遮罩的对话框好像是不能正常显示的。
> 
> 另这个设置页，用了FlowLayout的话，界面内容就压缩的不像样了，我用了FlowLayout就没那样，还没看出哪儿的区别。设置页是加入到了statckwidget里，能不能做个单独的只占据界面一部分的样式，在这基础上能不能有层级设置的效果。。建议啊
> 
> 我用nuitka打包navigation只有不到3分钟，打包galary时间长点，没细算，顶多也就10多分钟。我跟你的编译器不一样，我用的cl。

重复打包会有缓存的，第二次打包速度会快很多
