### ISSUE TITLE
功能询问

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#136]
我很想知道一下这个功能是怎么实现的，还望博主赐教一下
![image](https://user-images.githubusercontent.com/94896689/232992682-de65268d-7e35-4971-b609-bbdcebb97a47.png)

**Comment by youjunxiaji** [comment]
> 

就是点击`三`，就能展开的那种

**Comment by zhiyiYo** [comment]
把点击信号连接到了 navigationpanel.expand 函数上然后调用了每一个菜单项的 setCompacted 函数
