### ISSUE TITLE
请问Release中的打包使用的是什么工具？

### ISSUE THREAD

**Issue by somicrmidaz** [zhiyiYo/PyQt-Fluent-Widgets#137]
如题，觉得release中的打包方式很好，请问使用什么工具打包的？

**Comment by zhiyiYo** [comment]
使用 pyinstaller 打包的，需要把 pyinstaller 安装到虚拟环境里面，然后激活虚拟环境，使用下述命令打包：
```sh
pyinstaller -w -i app/resource/images/logo.png demo.py
```

**Comment by zhiyiYo** [comment]
不过我还删了一些冗余的 dll

**Comment by Cheukfung** [comment]
我测试了下，release是用pyinstaller打包的，启动速度明显比nuitka慢很多，nuitka基本上是秒开的，作者可以试试

**Comment by zhiyiYo** [comment]
用的是哪个版本的 nuikta

**Comment by Cheukfung** [comment]
1.5.4

**Comment by lintheyoung** [comment]
我也测试了下使用nuitka打包，nuitka --onefile --windows-disable-console --plugin-enable=qt-plugins --plugin-enable=pkg_resources demo.py，运行正常

**Comment by zhiyiYo** [comment]
Win7 有测试过吗？打包要花多久呀

**Comment by Cheukfung** [comment]
> 编译出来的代码在 Win7 可以跑吗？之前看到一个说要 Visual C++ 运行时环境的

可以跑，应该不需要运行时的

**Comment by Cheukfung** [comment]
> Win7 有测试过吗？打包要花多久呀

nuitka打包是把代码转为c再编译的，因为包含第三方库编译的比较慢，特别是numpy这种，但是第二次之后编译有缓存，会快很多，没有亚克力的版本编译也更快。
