### ISSUE TITLE
添加导航控件

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#14]
![image](https://user-images.githubusercontent.com/101497799/222901839-4f08627e-d7b0-4045-ac5c-a56fb6b0fe9a.png)
![image](https://user-images.githubusercontent.com/101497799/222902017-0facaac2-f456-47d0-928f-82975967b5e1.png)

能添加这种侧边选项卡和可以与空间高度一致的标题栏吗？

**Comment by zhiyiYo** [comment]
下次有空搞搞吧
