### ISSUE TITLE
请问多语言本地化改动后如何生效

### ISSUE THREAD

**Issue by josStorer** [zhiyiYo/PyQt-Fluent-Widgets#142]
例如我在改动了 gallery_zh.ts 之后, 直接调用 lrelease 生成qm, 但是启动后仍然是原来的文本

可能是一个qt使用的基础问题, 抱歉我不太熟悉

**Comment by zhiyiYo** [comment]
需要重新编译 app/resource/resource.qrc 为 app/common/resource.py

**Comment by josStorer** [comment]
好的，谢谢
