### ISSUE TITLE
是否有多媒体控件例如视频播放器

### ISSUE THREAD

**Issue by OdinLin** [zhiyiYo/PyQt-Fluent-Widgets#143]
没有在例子里面看到播放器相关的 是否可以增加呢

**Comment by zhiyiYo** [comment]
下次可以加上

**Comment by zhiyiYo** [comment]
我记得 qt 支持的格式很少，之前写了一个 Groove 音乐播放器，解码器得用户自己安装，比如 lav-filters

**Comment by zhiyiYo** [comment]
Linux 上面需要安装 GStreamer，经常会出问题

**Comment by monkeycc** [comment]
建议增加 +1

**Comment by monkeycc** [comment]
也可以读取摄像头 @zhiyiYo

**Comment by kend777** [comment]
视频的话可以用cv2.VideoCapture读帧，再加个多线程切换QPixmap的图片

**Comment by zhiyiYo** [comment]
pyqt5 分支已添加多媒体组件

**Comment by HATTER-LONG** [comment]
这个多媒体组件，这里是个笔误还是什么原因么，stop 是调用的 pause 🤔 https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/1b423425cd1c12d947cf7661fd74c48870b03604/qfluentwidgets/multimedia/video_widget.py#L75

**Comment by zhiyiYo** [comment]
> 这个多媒体组件，这里是个笔误还是什么原因么，stop 是调用的 pause 🤔 https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/1b423425cd1c12d947cf7661fd74c48870b03604/qfluentwidgets/multimedia/video_widget.py#L75

确实是写错了
