### ISSUE TITLE
TableView

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#145]

**Comment by comddy** [comment]
同求一个TableView的FlutenUI组件

**Comment by zhiyiYo** [comment]
WinUI3 的设计稿里面没有这个组件，暂时还不知道要怎么做

**Comment by zhiyiYo** [comment]
如果大家在使用 Fluent Design 风格的软件的时候有碰到表格组件或许可以分享到这里参考一下

**Comment by somicrmidaz** [comment]
![image](https://user-images.githubusercontent.com/119293761/234784783-47c22774-7be5-464c-a132-b5c20e2f928d.png)
我虽然不太清楚 Fluent Design 风格是啥，但用这个软件感觉界面挺舒服的，供参考。

**Comment by zhiyiYo** [comment]
目前的实现效果
![image](https://user-images.githubusercontent.com/65096819/234841024-55a23734-e110-4aa6-a991-84740e5008f1.png)

**Comment by zhiyiYo** [comment]
是不是要在 `QTableView` 样式表里面加上 `selection-background-color: transparent;`

**Comment by zhiyiYo** [comment]
试过了吗

**Comment by zhiyiYo** [comment]
感谢

**Comment by zhiyiYo** [comment]
可能是因为委托没画出来，要不打印一下看看有没有被选中

**Comment by zhiyiYo** [comment]
我这边改下

**Comment by zhiyiYo** [comment]
@qianye216 
PyQt5 分支加了多选功能了，可以试试不？

**Comment by zhiyiYo** [comment]
可能得处理一下 `selectionChanged` 信号

**Comment by huangluming** [comment]
> 目前的实现效果 ![image](https://user-images.githubusercontent.com/65096819/234841024-55a23734-e110-4aa6-a991-84740e5008f1.png) ![image](https://user-images.githubusercontent.com/65096819/234841165-29ab37a0-bce0-4c13-8f42-a18ab0847a42.png)

挺好看的 求更新~

**Comment by zhiyiYo** [comment]
这个组件有些问题，还在改

**Comment by zhiyiYo** [comment]
@qianye216 
现在应该改过来了

**Comment by zhiyiYo** [comment]
@qianye216 
应该是 `mouseReleaseEvent` 内部逻辑顺序有问题，目前已修复

**Comment by zhiyiYo** [comment]
@qianye216 
已修复此问题

**Comment by zhiyiYo** [comment]
已经修复这些问题了

**Comment by CheshireCC** [comment]
> @zhiyiYo 另外发现一个问题，如果手动调整行高的话，进入编辑模式时，输入框没有自适应高度 ![image](https://user-images.githubusercontent.com/8281775/236720821-f917a7c7-8dc6-4957-8261-1e08de2b0508.png)

请教一下，你这个表格进入编辑之后，是如何让编辑框保持原本的内容？我设置了自定义 Delegates 之后，还是不行啊
