### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#146]

**Comment by adityash4rma** [comment]
## Here is a suggestion for a cool looking progress bar

![](https://graph.org/file/96d54511ab7375af56bd4.png)

### Source
> https://github.com/rdbende/Sun-Valley-ttk-theme-svg/blob/main/DOCUMENTATION.pdf

**Comment by zhiyiYo** [comment]
Microsoft has provided the design draft
https://www.figma.com/community/file/1159947337437047524/Windows-UI-3

**Comment by zhiyiYo** [comment]
设计稿和 WinUI3 gallery 里面的组件不一样
