### ISSUE TITLE
希望添加导航控件

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#15]
目前我的做法是用listwidget配合stackedwidget，首先在qlistwidget设置好图标和文字，然后给定一个宽度，比如200px，然后切换的时候，把这个宽度设置为50px，就有类似缩回去的动画；这时候宽度只够显示图标，把滚动条隐藏，就有视频中的效果，但是这个做法比较奇葩，希望作者有更好的实现方法。

https://user-images.githubusercontent.com/14865236/223174484-239ac919-fa23-4a67-ace1-f7b279e19a29.mp4

**Comment by zhiyiYo** [comment]
等周末有空再试试看吧，我觉得你的方法能用就可以了

**Comment by fsf678** [comment]
球球辣，快加导航和图标

**Comment by zhiyiYo** [comment]
别急，晚上就推上去

**Comment by fsf678** [comment]
右上角消息框能搞一些控件在里面吗？我想添加图片、滑块在里面作为一个比较小的音乐播放模块内置在我的应用中？

**Comment by zhiyiYo** [comment]
这个你可能得自己写了

**Comment by zhiyiYo** [comment]
@Cheukfung 
你是怎么让导航部件右边的 `QStackedWidget` 填满整个界面的，重写主界面 `resizeEvent` 来调整大小吗？用 `QHBoxLayout` 的话会有一大片的空白🤔
![image](https://user-images.githubusercontent.com/65096819/224729380-e6795e74-916b-4077-81b5-a049cb4e2e2e.png)

**Comment by Cheukfung** [comment]
@zhiyiYo 用QHBoxLayout，包含 左边的listwidget和右边的stackedwidget，然后把 QHBoxLayout 的 layoutStretch 设置为 0,1，也就是满足listwidget的宽度下，让stackedwidget撑满整个layout容器

**Comment by zhiyiYo** [comment]
我是这么写的，但是并不起作用
```python
self.hBoxLayout.setSpacing(0)
self.hBoxLayout.setContentsMargins(0, self.titleBar.height(), 0, 0)
self.hBoxLayout.addWidget(self.navigationInterface, 0, Qt.AlignLeft)
self.hBoxLayout.addWidget(self.stackWidget, 1, Qt.AlignLeft)

self.navigationInterface.setFixedWidth(48)
```

**Comment by Cheukfung** [comment]
试试 self.hBoxLayout..setStretch(0,1)

**Comment by zhiyiYo** [comment]
解决了，改成下述代码就 ok 了，chatgpt 确实牛逼
```python
 self.hBoxLayout.setSpacing(0)
self.hBoxLayout.setContentsMargins(0, self.titleBar.height(), 0, 0)
self.hBoxLayout.addWidget(self.navigationInterface)
self.hBoxLayout.addWidget(self.stackWidget)
self.hBoxLayout.setStretchFactor(self.stackWidget, 1)
```

**Comment by Cheukfung** [comment]
就是把stretch设置为1就可以了

**Comment by zhiyiYo** [comment]
@Cheukfung @fsf678 
我把最新代码提交上去了，运行 `examples/navigation/demo.py` 可以看到效果

**Comment by Cheukfung** [comment]
是不是没推到pypi呀

**Comment by zhiyiYo** [comment]
还没，你们可以先看下有没有问题吗，如果ok的话我就推上去

**Comment by Cheukfung** [comment]
我运行了demo，没问题的

**Comment by Cheukfung** [comment]
还有一个希望留个接口，实时切换dark mode

**Comment by zhiyiYo** [comment]
正在搞

**Comment by Ephemeralwanning** [comment]
> 正在搞

太好了大大，这下不用别人的主题了

**Comment by zhiyiYo** [comment]
已将新版本的包发布到 pypi 了
