### ISSUE TITLE
treeview 如果使用QFileSystemModel模型，标题文字不是微软雅黑

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#155]
treeview 如果使用QFileSystemModel模型，标题文字不是微软雅黑，而且背景色和treeview本身背景色不一样，
![QQ截图20230429230642](https://user-images.githubusercontent.com/104692238/235309750-e17f5b35-74fa-4f34-88e7-f0fb90f83ed1.png)

**Comment by zhiyiYo** [comment]
设计稿里面没有对表头样式进行说明，所以我也没在样式表里面改它的样式

**Comment by zhiyiYo** [comment]
或许可以按照表格视图的表头样式表进行设置

**Comment by zhiyiYo** [comment]
可以改，但是还是觉得表头的样式不够好看

**Comment by zhiyiYo** [comment]
暂时保持现状吧，主要是树状组件一般只会用一列，这时候直接把表头隐藏掉就 Ok 了
