### ISSUE TITLE
No module named 'qframelesswindow'

### ISSUE THREAD

**Issue by huiyangou** [zhiyiYo/PyQt-Fluent-Widgets#156]
一直缺少这个文件

![image](https://user-images.githubusercontent.com/44021436/235322149-2cfb8b63-43d2-4e3a-a97c-a7d660550e8e.png)

**Comment by Cheukfung** [comment]
pyqt-fluent-widgets依赖pyqt5-frameless-window，你安装一下就行了

**Comment by zhiyiYo** [comment]
建议仔细阅读 readme 或者中文文档

**Comment by huiyangou** [comment]
已经解决了，把安装的包copy到venv中就好了....

**Comment by huiyangou** [comment]
最新的代码在gallery例子中，

会报QWidget: Must construct a QApplication before a QWidget，各位大佬能给点建议吗

**Comment by zhiyiYo** [comment]
环境乱了，肯定和pyside或者pyqt6一起用了才会这样

**Comment by zhiyiYo** [comment]
建议问问题之前先搜索一下issue历史
