### ISSUE TITLE
合并messagebox与dialog

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#157]
~~这两个貌似是一样的?~~
- 建议把原版qmessagebox中warning information question整合一下
- 然后建议添加单独的参数来指定win10风格或是win11的

**Comment by zhiyiYo** [comment]
这两个不一样吧，一个是无边框对话框，一个是带遮罩的对话框

**Comment by zhiyiYo** [comment]
Win10 风格的那个对话框可能之后会被我移除掉

**Comment by zhiyiYo** [comment]
如果想要 warning、info、question 功能或许可以换成 `InfoBar`，因为对话框的设计稿里面好像没有这些功能
