### ISSUE TITLE
add badges

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#158]
考虑添加一下徽章控件吗，应该比较简单的。
这个是官方设计稿：
![image](https://user-images.githubusercontent.com/14865236/235361361-7c58ef05-6d8f-4fc5-9edf-2d166b761178.png)
这个是我简单实现的
![image](https://user-images.githubusercontent.com/14865236/235361471-d7012a38-1f3a-48eb-b275-152899493236.png)
![image](https://user-images.githubusercontent.com/14865236/235361833-99028171-ed74-400a-aa79-4e219aebb3b9.png)

**Comment by zhiyiYo** [comment]
之后有空可以加上，目前在写拆分按钮和动画图标

**Comment by Cheukfung** [comment]
好的，感谢，我的水平就不提这些控件的pr了，等你有空再写

**Comment by adityash4rma** [comment]
> Okay, thanks, I won’t mention the pr of these controls at my level, I’ll write them when you have time

@Cheukfung do you mind telling how did you made the widgets by yourself?

**Comment by Cheukfung** [comment]
@adityash4rma This is a simple implementation, I used a QLabel and the LineEditButton from QFluentWidgets as the close button.

```python
from PyQt5.QtCore import pyqtSignal, Qt, QRectF
from PyQt5.QtGui import QPainter
from PyQt5.QtWidgets import QLabel, QHBoxLayout
from qfluentwidgets import FluentIcon as FIF, drawIcon, isDarkTheme
from qfluentwidgets import LineEditButton


class CloseableLabel(QLabel):
    close_button_clicked = pyqtSignal(str)

    def __init__(self, text="", parent=None):
        super().__init__(text, parent)
        self.hb_layout = QHBoxLayout(self)
        self.hb_layout.setSpacing(3)
        self.hb_layout.setContentsMargins(0, 0, 0, 0)
        self.hb_layout.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.close_button = MyCloseButton(FIF.CLOSE, self)
        self.close_button.setFixedSize(20, 20)
        self.hb_layout.addWidget(self.close_button, 0, Qt.AlignRight)
        self.text_width = self.fontMetrics().width(text)
        self.setFixedWidth(self.text_width + 30)
        self.text_height = self.fontMetrics().height()
        self.setFixedHeight(self.text_height + 10)
        self.close_button.clicked.connect(lambda: self.close_button_clicked.emit(self.text()))


class MyCloseButton(LineEditButton):

    # Rewrite the paintEvent method in order to change the color of the close icon.
    def paintEvent(self, e):
        super().paintEvent(e)
        painter = QPainter(self)
        painter.setRenderHints(QPainter.Antialiasing |
                               QPainter.SmoothPixmapTransform)

        iw, ih = self.iconSize().width(), self.iconSize().height()
        w, h = self.width(), self.height()
        rect = QRectF((w - iw) / 2, (h - ih) / 2, iw, ih)

        if self.isPressed:
            painter.setOpacity(0.7)

        if isDarkTheme():
            drawIcon(self._icon, painter, rect, fill='#FF99A4')
        else:
            drawIcon(self._icon, painter, rect, fill='#C42B1C')
```

```css
 CloseableLabel{
        border: 1px solid #C42B1C;
        color: #C42B1C;
        padding-left:6px;
        background-color: #FDE7E9;
        border-radius: 10px;
 }
```

**Comment by adityash4rma** [comment]
> @adityash4rma This is a simple implementation, I used a QLabel and the LineEditButton from QFluentWidgets as the close button.
> 
> ```python
> from PyQt5.QtCore import pyqtSignal, Qt, QRectF
> from PyQt5.QtGui import QPainter
> from PyQt5.QtWidgets import QLabel, QHBoxLayout
> from qfluentwidgets import FluentIcon as FIF, drawIcon, isDarkTheme
> from qfluentwidgets import LineEditButton
> 
> 
> class CloseableLabel(QLabel):
>     close_button_clicked = pyqtSignal(str)
> 
>     def __init__(self, text="", parent=None):
>         super().__init__(text, parent)
>         self.hb_layout = QHBoxLayout(self)
>         self.hb_layout.setSpacing(3)
>         self.hb_layout.setContentsMargins(0, 0, 0, 0)
>         self.hb_layout.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
>         self.close_button = MyCloseButton(FIF.CLOSE, self)
>         self.close_button.setFixedSize(20, 20)
>         self.hb_layout.addWidget(self.close_button, 0, Qt.AlignRight)
>         self.text_width = self.fontMetrics().width(text)
>         self.setFixedWidth(self.text_width + 30)
>         self.text_height = self.fontMetrics().height()
>         self.setFixedHeight(self.text_height + 10)
>         self.close_button.clicked.connect(lambda: self.close_button_clicked.emit(self.text()))
> 
> 
> class MyCloseButton(LineEditButton):
> 
>     # Rewrite the paintEvent method in order to change the color of the close icon.
>     def paintEvent(self, e):
>         super().paintEvent(e)
>         painter = QPainter(self)
>         painter.setRenderHints(QPainter.Antialiasing |
>                                QPainter.SmoothPixmapTransform)
> 
>         iw, ih = self.iconSize().width(), self.iconSize().height()
>         w, h = self.width(), self.height()
>         rect = QRectF((w - iw) / 2, (h - ih) / 2, iw, ih)
> 
>         if self.isPressed:
>             painter.setOpacity(0.7)
> 
>         if isDarkTheme():
>             drawIcon(self._icon, painter, rect, fill='#FF99A4')
>         else:
>             drawIcon(self._icon, painter, rect, fill='#C42B1C')
> ```
> 
> ```css
>  CloseableLabel{
>         border: 1px solid #C42B1C;
>         color: #C42B1C;
>         padding-left:6px;
>         background-color: #FDE7E9;
>         border-radius: 10px;
>  }
> ```

@Cheukfung Thank You Very much for the explanation 😊!

**Comment by zhiyiYo** [comment]
这个徽章好像和 WinUI3 gallery 里面的 `InfoBadge` 不一样
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/69c578f5-117c-468a-8838-3355c44b8660)

**Comment by Cheukfung** [comment]
> 这个徽章好像和 WinUI3 gallery 里面的 `InfoBadge` 不一样 ![image](https://user-images.githubusercontent.com/65096819/239687735-69c578f5-117c-468a-8838-3355c44b8660.png)

好像有两种，我上面那种在badges and links的项目里面
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/6b0222f0-c95e-4684-b096-44c13ae91548)

**Comment by zhiyiYo** [comment]
这个应该不是库里面的组件？看起来只在 figma 里面起标识作用

**Comment by Cheukfung** [comment]
> 

好像是的，我装了winui3 gallery也找不到这个组件。这个组件在web应比较常用，估计只是用来做标识的。
另外新添加的info badge可能是因为字体还是其他原因，没有垂直居中。
<img width="274" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/275fbb1f-215a-4721-9ace-7a980261c6e0">

**Comment by Cheukfung** [comment]
官方的好像也不居中，不知道是不是4k屏的原因
<img width="624" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/633cf0a5-44d8-491b-9534-bf894ce7b019">

**Comment by zhiyiYo** [comment]
我这也没完全居中，但是 #315 中给的图是有居中的，估计是字体的原因
