### ISSUE TITLE
TextEdit不能粘贴图片

### ISSUE THREAD

**Issue by CofWMil** [zhiyiYo/PyQt-Fluent-Widgets#161]
TextEdit粘贴图片会变成图片的本地路径

**Comment by zhiyiYo** [comment]
QTextEdit 粘贴图片能直接显示吗？我应该只改了样式，没动其他功能

**Comment by CofWMil** [comment]
> QTextEdit 粘贴图片能直接显示吗？我应该只改了样式，没动其他功能

我试了一下pyside2确实不能直接粘贴图片
