### ISSUE TITLE
建议对app字体进行全局设置`PreferNoHinting`以去除在Windows上文字的锯齿（4K屏幕锯齿明显）

### ISSUE THREAD

**Issue by kevintsq** [zhiyiYo/PyQt-Fluent-Widgets#162]
现在需要手动设置
```python
font = app.font()
font.setHintingPreference(QFont.HintingPreference.PreferNoHinting)
app.setFont(font)
```
可否直接全局设置？

**Comment by zhiyiYo** [comment]
这个可能得用户手动设置

**Comment by kevintsq** [comment]
似乎是这样……那也可以在demo里默认都加上
另外，`PyQt-Frameless-Window`也存在一样的问题

**Comment by zhiyiYo** [comment]
@kevintsq 
能截张图演示一下前后对比吗？我的笔记本加了这个标志位还是会有点锯齿

**Comment by kevintsq** [comment]
添加前：
![image](https://user-images.githubusercontent.com/62129747/235639105-024e8ec8-634e-4bfe-9da9-b01692836483.png)
添加后：
![image](https://user-images.githubusercontent.com/62129747/235639251-89dbed65-7091-4fc2-8b53-1d779ca48706.png)

**Comment by zhiyiYo** [comment]
感谢，我等下再试试

**Comment by zhiyiYo** [comment]
发现确实可以反锯齿，应该是因为我刚才没有 `app.setFont()` 所以不起作用

**Comment by zhiyiYo** [comment]
加了之后字体变粗了，看着有点奇怪
![image](https://user-images.githubusercontent.com/65096819/235821360-24978c80-9fd6-405c-83a9-7ba6bb04faac.png)

**Comment by kevintsq** [comment]
但加上后在4K屏幕上似乎才是正常的效果……从你图上看加上后锯齿也少了
