### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 1661021512** [zhiyiYo/PyQt-Fluent-Widgets#163]
运行时pyside6下的demo.py出现以下问题

qt.core.plugin.loader: In D:/anaconda/Library/plugins/platforms/qdirect2d.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In D:/anaconda/Library/plugins/platforms/qminimal.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In D:/anaconda/Library/plugins/platforms/qoffscreen.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In D:/anaconda/Library/plugins/platforms/qwebgl.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In D:/anaconda/Library/plugins/platforms/qwindows.dll:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by zhiyiYo** [comment]
换成虚拟环境试试？

**Comment by 1661021512** [comment]
已解决，在代码前加入
import PySide6
dirname = os.path.dirname(PySide6.__file__)
plugin_path = os.path.join(dirname, 'plugins', 'platforms')
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE" 
即可，虽然仍然有报错，但是界面加载成功

**Comment by zhiyiYo** [comment]
可能是 opencv 的锅
