### ISSUE TITLE
【求助】 请问icon_interface的搜索功能是怎么实现的

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#164]
能说一下大致思路嘛，谢谢

**Comment by zhiyiYo** [comment]
看下 `examples/gallery/app/view/icon_interface.py` 的 `IconCardView.search()` 函数，用的数据结构是 `Trie`

**Comment by zhiyiYo** [comment]
Qt 应该有自带的表格搜索功能吧
