### ISSUE TITLE
A Bug of Navigation-Demo

### ISSUE THREAD

**Issue by CLimber-Rong** [zhiyiYo/PyQt-Fluent-Widgets#168]
**Describe the bug**
In the absence of any changes, run the demo of the navigation, but report an error

**Environment**
- OS: Windows10
- Python: Python 3.9.7
- PyQt: 5.14
- PyQt-Fluent-Widgets: 0.8.4

**To Reproduce**
1. CD PyQt-Fluent-Widgets\examples\navigation
2. python demo.py
3. TypeError: addItem() got an unexpected keyword argument 'tooltip'

![image](https://user-images.githubusercontent.com/101919236/235884034-7e666b53-19f6-45f0-afb8-43414b775494.png)

**Comment by zhiyiYo** [comment]
我这边无法复现此问题，是不是你的包版本没升级到 0.8.4
