### ISSUE TITLE
Add Command Bar

### ISSUE THREAD

**Issue by adityash4rma** [zhiyiYo/PyQt-Fluent-Widgets#170]
## Please try to add a command bar

---
### Here is a GIF from official WINUI 3 docs:
![](https://learn.microsoft.com/en-us/windows/apps/design/controls/images/command-bar-minimal.gif)

image:
![image](https://user-images.githubusercontent.com/102592458/235940242-55a38c76-c055-4f99-b6eb-38dbde3aa629.png)

---

### Placement
![image](https://user-images.githubusercontent.com/102592458/235940726-de4b4fa7-8ee9-4ae6-86f2-36174a812049.png)

**Comment by zhiyiYo** [comment]
这要求也太多了吧

**Comment by adityash4rma** [comment]
is it possible btw ?
