### ISSUE TITLE
表格的列的字没有跟随主题

### ISSUE THREAD

**Issue by DancingSnow0517** [zhiyiYo/PyQt-Fluent-Widgets#172]
**Describe the bug**

**Environment**
- OS: Windows11
- DPI scaling: 125%
- Python: 3.10.7 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.8.2

**Expected behavior**
表格的列的字没有跟随主题，手动触发一次setTheme才变成白的字

**Screenshots**
![image](https://user-images.githubusercontent.com/60736156/236172197-5f946389-4375-4127-9397-e98be0cecc75.png)

**Comment by zhiyiYo** [comment]
gallery里面应该是有跟随主题吧

**Comment by zhiyiYo** [comment]
同时建议升级到0.8.4

**Comment by DancingSnow0517** [comment]
> gallery里面应该是有跟随主题吧

gallery里面是有跟随的，但是不知道我这里就不生效了

**Comment by zhiyiYo** [comment]
贴一下最小复现代码吧

**Comment by DancingSnow0517** [comment]
没能成功用最小代码复现，相关代码在这里https://github.com/DancingSnow0517/StarRail-gacha/blob/master/src/star_rail_gacha/app/pages/history_page.py

**Comment by zhiyiYo** [comment]
下述函数没有在初始化的时候调用的样子，而且也没必要把主题变化信号连接到这个槽函数上，因为  `StyleSheet.HISTORY_PAGE.apply(self)` 之后 `qfluentwidgets` 会自动帮你更换主题
```python
def set_theme(self):
        StyleSheet.HISTORY_PAGE.apply(self)
```
