### ISSUE TITLE
PySide6 下，Navigation 少于四个的情况下会导致程序图标显示不正常

### ISSUE THREAD

**Issue by MaiXiaoMeng** [zhiyiYo/PyQt-Fluent-Widgets#173]
**Describe the bug**
PySide6 下，Navigation 少于四个的情况下会导致程序图标显示不正常

**Environment**
- OS: Microsoft Windows 11 企业版
- DPI scaling: 125%
- Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
- PySide6 : 6.5.0
- PySide6-Fluent-Widgets: 0.8.4

**To Reproduce**
1.  用 git 下载  [PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)，然后切换到 PySide6 分支
2.  打开 ”examples\navigation\demo.py“ ，注释掉 103 行，然后运行

**Screenshots**
![微信截图_20230505105435.png](https://s2.loli.net/2023/05/05/uDOV65WXYPJy8io.png)

**Comment by zhiyiYo** [comment]
取消注释的话就不会把子界面加到 qstackwidget 里面了，也就不会被隐藏，才会出现这个问题
