### ISSUE TITLE
Messagebox in qfluentwidgets error

### ISSUE THREAD

**Issue by Adsicmes** [zhiyiYo/PyQt-Fluent-Widgets#174]
in the offical demo (fluent gallery) of version v0.8.4

when i click the avatar, here's a Error
```shell
D:\Code\pythonEnvs\Conda\OMDownloader\python.exe D:\Code\python\PyQt-Fluent-Widgets\examples\gallery\demo.py 
Traceback (most recent call last):
  File "D:\Code\python\PyQt-Fluent-Widgets\examples\gallery\app\view\main_window.py", line 199, in showMessageBox
    w = MessageBox(
  File "D:\Code\python\PyQt-Fluent-Widgets\qfluentwidgets\components\dialog_box\dialog.py", line 134, in __init__
    super().__init__(parent=parent)
  File "D:\Code\python\PyQt-Fluent-Widgets\qfluentwidgets\components\dialog_box\mask_dialog_base.py", line 14, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by Cheukfung** [comment]
新建一个虚拟环境试试，这个应该是环境问题

**Comment by Adsicmes** [comment]
以后每次更新都要重新搞环境？

**Comment by Cheukfung** [comment]
正常不需要的，这个错误应该是环境乱了导致的，你直接conda新建一个环境应该就没有这个问题

**Comment by zhiyiYo** [comment]
在一个环境里面同时下载 PyQt-Fluent-Widgets、PyQt6-Fluent-Widgets、PySide2-Fluent-Widgets、PySide6-Fluent-Widgets 会有包名冲突问题

**Comment by zhiyiYo** [comment]
如果不想新建虚拟环境的话只要把安装过的各种 PyQt-Fluent-Widgets 都卸载掉，重装一种 PyQt-Fluent-Widgets 就可以了

**Comment by Adsicmes** [comment]
> 在一个环境里面同时下载 PyQt-Fluent-Widgets、PyQt6-Fluent-Widgets、PySide2-Fluent-Widgets、PySide6-Fluent-Widgets 会有包名冲突问题

我只下了PySide6-Fluent-Widgets   看演示实例的时候我也切分支到了pyside6那边  应该是不会有包名冲突问题的

**Comment by Cheukfung** [comment]
你新建一个环境试试先 如果新建了还是不行就把python版本贴一下

**Comment by zhiyiYo** [comment]
或者换成 python3.8 试试

**Comment by zhiyiYo** [comment]
之前也有人提过的这问题，可以看下 https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/103

**Comment by Adsicmes** [comment]
python3.10

`conda create`之后仅运行了`pip install "PySide6-Fluent-Widgets[full]" -i https://pypi.org/simple/`和`pip install pyside6`

仍然有这个问题

**Comment by zhiyiYo** [comment]
看下那个 issue，可能是 pyside 版本过高导致的，换成 6.4.2 试试

**Comment by Adsicmes** [comment]
好  我不是非得用这个组件   只是出了bug而且没找到相应的办法来反馈一下

**Comment by zhiyiYo** [comment]
可以先在 issue 页面搜索一下，一般都会有人踩过相应的坑
