### ISSUE TITLE
ComboBox在Item较多时，下拉列表显示长度过长

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#179]
**Describe the bug**
`ComboBox`在 Item 较多时，下拉列表显示长度过长，或许可以适当缩短一点，而且本身也自带滚动浏览效果，再加个滚动条提示用户下面还有内容应该效果更好。此外，我看了下win11本身的下拉框，似乎win11的下拉列表在长度超出屏幕底部时，也并不会自动上移下拉列表(最近想把`EditableComboBox`做成可键入搜索Item，这样长度太长自动上移会阻挡原控件没办法实时预览效果)

**Environment**
- OS: Windows11
- DPI scaling: 100%
- Python: 3.9.16 64-bit
- PyQt: 5.15.7
- PyQt-Fluent-Widgets: 0.8.4

**Code**
```python
  from PyQt5.QtCore import Qt
  from PyQt5.QtWidgets import QApplication, QHBoxLayout, QWidget
  from qfluentwidgets import ComboBox

  QApplication.setHighDpiScaleFactorRoundingPolicy(
      Qt.HighDpiScaleFactorRoundingPolicy.PassThrough
  )
  QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
  QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

  properties = [str(i) for i in range(50)]
  app = QApplication([])
  viewer = QWidget()
  layout = QHBoxLayout()
  combobox = ComboBox()
  combobox.addItems(properties)
  layout.addWidget(combobox)
  viewer.setLayout(layout)
  viewer.show()
  app.exec_()
```

**Screenshots**
过长自动上移导致位置偏离：
![1](https://user-images.githubusercontent.com/62167519/236596791-35310bac-609d-47e7-b71b-d1679d96c7e7.gif)

Win11 的下拉框效果：
![image](https://user-images.githubusercontent.com/62167519/236598082-33c791a1-992d-43be-98f0-148754e5d5fa.png)

**Comment by zhiyiYo** [comment]
之前还没写滚动条，滚动条被隐藏了，现在可以加回去了

**Comment by zhiyiYo** [comment]
最新版本已经解决了这个问题
