### ISSUE TITLE
关于LineEdit和TextEdit在不可编辑时的样式问题

### ISSUE THREAD

**Issue by Aye10032** [zhiyiYo/PyQt-Fluent-Widgets#180]
目前，当这类组件的setReadOnly设置为Tru时，区分不是很明显，只能通过是否有光标来显示，若鼠标点击仍然会发生样式变化（即下方出现阴影）
是否考虑修改一下，当文本框为只读时选中后样式不发生变化？又或者当只读时将背景稍微变暗？

**Comment by zhiyiYo** [comment]
感谢反馈，现在就改

**Comment by zhiyiYo** [comment]
有点诡异，改不了 `LineEdit[readOnly="true"]:focus` 的样式，只能 `lineEdit.setFocusPolicy(Qt.NoFocus)` 来曲线救国了
