### ISSUE TITLE
[BUG] 无法用鼠标拖动TableWidget右侧的滚动条 

### ISSUE THREAD

**Issue by AuroraZiling** [zhiyiYo/PyQt-Fluent-Widgets#181]
**Describe the bug**
无法用鼠标拖动滚动条
![d1](https://user-images.githubusercontent.com/69903523/236653985-3c34b729-8082-4856-9d85-dac4b3c171cf.gif)

**Environment**
- OS: Windows 11 21H2
- Python: 3.10
- PyQt: 6
- PyQt-Fluent-Widgets: 0.8.4

**To Reproduce**
在gallery中的表格控件

**Expected behavior**
如果频繁拖动+鼠标滚轮滚动，会触发崩溃
```
TypeError: unable to convert a Python 'float' object to a C++ 'int' instance
```

**Comment by zhiyiYo** [comment]
哪一行报的这个错呀

**Comment by AuroraZiling** [comment]
![image](https://user-images.githubusercontent.com/69903523/236654168-44ff4c06-5423-4ac2-915b-41cf607b0807.png)
没看出来

**Comment by zhiyiYo** [comment]
要不换成 pyside6 试试有没有提示第几行报错，我的 python3.8 无法复现这个问题

**Comment by AuroraZiling** [comment]
换成pyside6就没问题了

**Comment by zhiyiYo** [comment]
还是 pyqt5 稳定

**Comment by AuroraZiling** [comment]
目前换成pyside6解决问题
