### ISSUE TITLE
Custom Dialog and Frameless Window

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#186]
please add custom dialog. to build a specific form etc. 
which takes QFrame or Widgets (LineEdit, Spinbox, comboBox etc)
SomeThing Like This 
![image](https://user-images.githubusercontent.com/101139501/236882366-b398ec59-81d6-4f0d-9bfd-6d9b240e54b6.png)

**Comment by ImmiProgramer** [comment]
for the demonstrate

**Comment by zhiyiYo** [comment]
dulplicated with #93. Please search for historical issues before submitting a new issue.
