### ISSUE TITLE
Mac下MessageBox对话框窗口的取消和确定按钮间距为0

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#19]
**Describe the bug**
Mac下MessageBox对话框窗口的取消和确定按钮间距为0
**Environment**
- OS: MAC
- Python: 3.9.6
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: 0.3.1

使用messagebox，弹出的窗口取消按钮和确定按钮中间的间距为0
![image](https://user-images.githubusercontent.com/8281775/225485791-1a588297-9f8d-44eb-894c-904d64643d36.png)

如果是使用messageDialog,则正常
![image](https://user-images.githubusercontent.com/8281775/225485956-3dee8c20-f327-43ba-885f-278a527b7eb8.png)

**Comment by zhiyiYo** [comment]
两个对话框 content 不一样，下面那个对话框改成 `If you delete the ""Music".` 之后按钮间距会是 0 吗？

**Comment by qianye216** [comment]
> 两个对话框 content 不一样，下面那个对话框改成 `If you delete the ""Music".` 之后按钮间距会是 0 吗？

是的，不管内容多长间距都是0
![image](https://user-images.githubusercontent.com/8281775/225486993-8d0a0ac0-46fa-40a0-81c1-86e982a786d2.png)

**Comment by zhiyiYo** [comment]
这就奇怪了，两个对话框继承的是同一个 `Ui_MessageBox` 类

**Comment by zhiyiYo** [comment]
@qianye216 
`qfluentwidgets/components/dialog_box/dialog.py` 的第 69 行到第 72 行改成下述代码可以 work 吗：
```python
self.buttonLayout.setSpacing(0)
self.buttonLayout.setContentsMargins(24, 24, 24, 24)
self.buttonLayout.addWidget(self.yesButton, 1, Qt.AlignVCenter)
self.buttonLayout.addSpacing(12)
self.buttonLayout.addWidget(self.cancelButton, 1, Qt.AlignVCenter)
```

**Comment by qianye216** [comment]
> @qianye216 `qfluentwidgets/components/dialog_box/dialog.py` 的第 69 行到第 72 行改成下述代码可以 work 吗：
> 
> ```python
> self.buttonLayout.setSpacing(0)
> self.buttonLayout.setContentsMargins(24, 24, 24, 24)
> self.buttonLayout.addWidget(self.yesButton, 1, Qt.AlignVCenter)
> self.buttonLayout.addSpacing(12)
> self.buttonLayout.addWidget(self.cancelButton, 1, Qt.AlignVCenter)
> ```

间距还是0

**Comment by zhiyiYo** [comment]
@qianye216 
有找到解决方案吗？

**Comment by qianye216** [comment]
> @qianye216 有找到解决方案吗？

没有

> ```python
> self.buttonLayout.setSpacing(0)
> self.buttonLayout.setContentsMargins(24, 24, 24, 24)
> self.buttonLayout.addWidget(self.yesButton, 1, Qt.AlignVCenter)
> self.buttonLayout.addSpacing(12)
> self.buttonLayout.addWidget(self.cancelButton, 1, Qt.AlignVCenter)
> ```

在dialog.py代码中初始化ui后重新设置间距大于12才可以看到间距，等于12就不行了
![image](https://user-images.githubusercontent.com/8281775/225568188-ae7435ca-40e7-45d3-ad05-9814fcb5cfca.png)
![image](https://user-images.githubusercontent.com/8281775/225568253-665bf8be-cb58-454c-9d5f-acc9c7660197.png)

**Comment by qianye216** [comment]
`self.buttonLayout.setSpacing(20)
        self.buttonLayout.setContentsMargins(24, 24, 24, 24)
        self.buttonLayout.addWidget(self.yesButton, 1, Qt.AlignVCenter)
        self.buttonLayout.addWidget(self.cancelButton, 1, Qt.AlignVCenter)`
这里代码设置间距大于12也可以生效

**Comment by zhiyiYo** [comment]
13 可以不

**Comment by zhiyiYo** [comment]
会不会是字体导致的，要不把按钮的字体换成系统自带的试试

**Comment by qianye216** [comment]
> 会不会是字体导致的，要不把按钮的字体换成系统自带的试试

应该不是字体原因，设置13的话间距实际上看到的效果就只有1px的间距了

**Comment by zhiyiYo** [comment]
如果把 `MessageBox` 改成下述代码效果如何：
```python
class MessageBox(MaskDialogBase, Ui_MessageBox):
    """ Message box """

    def __init__(self, title: str, content: str, parent=None):
        super().__init__(parent=parent)
        self._setUpUi(title, content, self.widget)

        self.setShadowEffect(60, (0, 10), QColor(0, 0, 0, 50))
        self.setMaskColor(QColor(0, 0, 0, 76))

        self.widget.setFixedSize(
            max(self.contentLabel.width(), self.titleLabel.width())+48,
            self.contentLabel.y() + self.contentLabel.height() + 105
        )

        # self._hBoxLayout.removeWidget(self.widget)
        # self._hBoxLayout.addWidget(self.widget, 1, Qt.AlignCenter)

    def eventFilter(self, obj, e: QEvent):
        if obj is self.window():
            if e.type() == QEvent.Resize:
                self._adjustText()

        return super().eventFilter(obj, e)
```

**Comment by qianye216** [comment]
> 如果把 `MessageBox` 改成下述代码效果如何：
> 
> ```python
> class MessageBox(MaskDialogBase, Ui_MessageBox):
>     """ Message box """
> 
>     def __init__(self, title: str, content: str, parent=None):
>         super().__init__(parent=parent)
>         self._setUpUi(title, content, self.widget)
> 
>         self.setShadowEffect(60, (0, 10), QColor(0, 0, 0, 50))
>         self.setMaskColor(QColor(0, 0, 0, 76))
> 
>         self.widget.setFixedSize(
>             max(self.contentLabel.width(), self.titleLabel.width())+48,
>             self.contentLabel.y() + self.contentLabel.height() + 105
>         )
> 
>         # self._hBoxLayout.removeWidget(self.widget)
>         # self._hBoxLayout.addWidget(self.widget, 1, Qt.AlignCenter)
> 
>     def eventFilter(self, obj, e: QEvent):
>         if obj is self.window():
>             if e.type() == QEvent.Resize:
>                 self._adjustText()
> 
>         return super().eventFilter(obj, e)
> ```

还是一样

**Comment by zhiyiYo** [comment]
看来只能对mocOS的间距进行特殊处理了。其他对话框有这个问题吗？比如颜色对话框

**Comment by qianye216** [comment]
> 看来只能对macOS的间距进行特殊处理了。其他对话框有这个问题吗？比如颜色对话框
其他对话框都正常

**Comment by zhiyiYo** [comment]
也许可以从颜色对话框突破一下

**Comment by zhiyiYo** [comment]
在MessageBox的构造函数中添加
`self.setAttribute(Qt.WA_LayoutUsesWidgetRect)`试试

**Comment by zhiyiYo** [comment]
@qianye216

**Comment by qianye216** [comment]
> 

还是不行

**Comment by zhiyiYo** [comment]
改成这样也不行吗：
```python
class MessageBox(MaskDialogBase, Ui_MessageBox):
    """ Message box """

    yesSignal = pyqtSignal()
    cancelSignal = pyqtSignal()

    def __init__(self, title: str, content: str, parent=None):
        super().__init__(parent=parent)
        self.setAttribute(Qt.WA_LayoutUsesWidgetRect)
        self._setUpUi(title, content, self.widget)

        self.setShadowEffect(60, (0, 10), QColor(0, 0, 0, 50))
        self.setMaskColor(QColor(0, 0, 0, 76))
        self._hBoxLayout.removeWidget(self.widget)
        self._hBoxLayout.addWidget(self.widget, 1, Qt.AlignCenter)

        self.widget.setFixedSize(
            max(self.contentLabel.width(), self.titleLabel.width())+48,
            self.contentLabel.y() + self.contentLabel.height() + 105
        )
```

**Comment by qianye216** [comment]
> 

是的，间距还是0

**Comment by zhiyiYo** [comment]
累了累了

**Comment by zhiyiYo** [comment]
还是直接把 macOS 下的间距改成 24 吧

**Comment by qianye216** [comment]
> 还是直接把 macOS 下的间距改成 24 吧

没其他解决方法的话就只能这样了，不过改成24的话另外一个带标题栏的消息对话框的按钮间距就显得大了点

**Comment by zhiyiYo** [comment]
可以在 `MessageBox` 的构造函数里面加这行代码

**Comment by qianye216** [comment]
> 可以在 `MessageBox` 的构造函数里面加这行代码

可以，判断如果是Mac系统就设置间距为24

**Comment by zhiyiYo** [comment]
对

**Comment by zhiyiYo** [comment]
@qianye216 
改成下述代码应该就没问题了吧：
```python
class MessageBox(MaskDialogBase, Ui_MessageBox):
    """ Message box """

    yesSignal = pyqtSignal()
    cancelSignal = pyqtSignal()

    def __init__(self, title: str, content: str, parent=None):
        super().__init__(parent=parent)
        self._setUpUi(title, content, self.widget)

        # fixes https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/19
        if sys.platform == 'darwin':
            self.buttonLayout.setSpacing(24)

        self.setShadowEffect(60, (0, 10), QColor(0, 0, 0, 50))
        self.setMaskColor(QColor(0, 0, 0, 76))
        self._hBoxLayout.removeWidget(self.widget)
        self._hBoxLayout.addWidget(self.widget, 1, Qt.AlignCenter)

        self.widget.setFixedSize(
            max(self.contentLabel.width(), self.titleLabel.width())+48,
            self.contentLabel.y() + self.contentLabel.height() + 105
        )
```

**Comment by qianye216** [comment]
> ```python
> if sys.platform == 'darwin':
>             self.buttonLayout.setSpacing(24)
> ```

没问题，记得导入sys模块就行

**Comment by zhiyiYo** [comment]
感谢

**Comment by Cheukfung** [comment]
我来辣我来辣，setSpacing(24)这个方法不通用，我的主界面是qtdesigner做的，间距完全正常，如果setSpacing(24)了，就会出现距离超宽了。
这是个明确的bug，过12年了还不修复，服了。
解决方法：为每个button都setAttribute(Qt.WA_LayoutUsesWidgetRect)即可。
但是qt designer做的界面为什么没有这个bug，我还没找到原因。。。只能说mac下的qt真奇葩。

**Comment by zhiyiYo** [comment]
@qianye216 
按照他这样改可以 work 吗？

**Comment by qianye216** [comment]
> setAttribute(Qt.WA_LayoutUsesWidgetRect)

牛的，给每个按钮添加这个属性就可以了，不过这种也需要判断Mac系统才添加这个属性吧，直接在Ui_MessageBox中添加就行了

**Comment by zhiyiYo** [comment]
对 Windows 没有影响的
