### ISSUE TITLE
Add LineEdit with icon

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#192]
Add LineEdit with icon like windows 11 task manager search or like this:
![image](https://user-images.githubusercontent.com/101139501/236888526-6553778b-9ee8-4d48-a1a3-a304891cf693.png)
![image](https://user-images.githubusercontent.com/101139501/236888630-90cfa0d9-8dc8-4adb-9c78-74ac9a16f97a.png)

**Comment by zhiyiYo** [comment]
you can insert the LineEditButton to LineEdit.hBoxLayout. But you should adjust the text margins to prevent occlusion.
