### ISSUE TITLE
QtDesigner 插件由于虚拟环境引发的 BUG 及我自己的解决方案

### ISSUE THREAD

**Issue by CheshireCC** [zhiyiYo/PyQt-Fluent-Widgets#196]
QtDesigner 插件使用时出现的问题及解决方法：

​		在最新版的 **pyqt-fluent-widgets**（以下简称 **PFW** ）中，`Dev` 大佬为我们带来了可以直接在 *QtDesigner* 中使用 **PFW** 控件的 *designer plugins* ，但是由于初代版本还不太稳定，存在一些由虚拟环境引发的 *bug*。这里有一些可能有用的解决方案。

1.  **conda** 创建虚拟环境，但运行脚本之后无事发生，无法打开 **designer.exe** 程序
        解决方案：检查各级文件夹目录是否含有“特殊字符”以及空格。

2. **conda**环境运行脚本之后 打开 **designer.exe** 但是并没有 **PFW** 控件（还是原版的 **designer.exe** ）
        解决方案：需要将 代码仓库中提供的 `tools` 和 `plugins` 两个文件夹放在同级别目录下，一般来说这两个文件夹应当位于项目根目录下，与项目主脚本同级目录。

3. 非 **conda** 虚拟环境（包括 `venv`、`virtualenv`、`Pipenv `等方式创建的虚拟环境） 
        无法启动 **designer.exe** ，同 1。
        启动 **designer.exe** 但为原版 ：
                （1）首先同 2 ，检查文件目录；
                （2）如果不行，那么是因为这几种方法创建的 `python `虚拟环境依赖于系统中特定的 `python.exe` ，非完全隔离环境。该种虚拟环境中的 `Scripts\python.exe` 顾名思义，也只是一个运行真正 `python.exe` 程序的工具脚本；
                        比如： 我使用位于 `D:\python39\python.exe` 的 `python` 软件 创建了 `./venv` 这个虚拟环境，那么实际上会运行 的 `python.exe` 程序依然是 `D:\python39\python.exe` 。该运行对象保存于 `./vnev/pyvenv.cfg` 文件中的 `home = D:\python39` 字段中。
解决办法：将 `D:\python39\` 目录下的 **python.exe**、**python.dll**、**python39.dll**、**pythonw.exe**、**vcruntime.dll**（如果有的话）这几个文件全部拷贝到 `./venv` 。然后修改 `./vnev/pyvenv.cfg -> home=.\venv`，自测能解决问题。这里的文件路径换成你自己创建虚拟环境时依赖的 **基础解释器** 和创建完之后的虚拟环境所在的路径。

**Comment by zhiyiYo** [comment]
感谢分享

**Comment by CheshireCC** [comment]
pycharm 测试结果为：pyqt5 丢失，请卸载pyqt5之后重新安装，或者先移动文件更改 home 字段之后再装软件包
                                     提示 no python：xxxxxxxx ，请在 home 字段使用绝对路径

**Comment by ningwana** [comment]
已经有一个ui窗口，已经详细看过帮助文档，想通过提升控件的方式去用组件，但是Qt Desinger老是提示 

抱歉无法截图，请问这是为啥。

eg:
基类名称：QPushButton
提升的类名称：PushButton
头文件：qfluentwidget

弹出错误窗口提示：
类 xxxx 已经存在。


@zhiyiYo

**Comment by tom9672** [comment]
```
(venv) C:\Users\Administrator\test\tools>python -V
Python 3.9.13

(venv) C:\Users\Administrator\test\tools>pip list
Package                Version
---------------------- ----------
click                  8.1.3
colorama               0.4.6
colorthief             0.2.1
darkdetect             0.8.0
numpy                  1.24.3
Pillow                 9.5.0
pip                    22.0.4
PyQt-Fluent-Widgets    0.8.7
PyQt5                  5.15.9
PyQt5-Frameless-Window 0.2.7
pyqt5-plugins          5.15.9.2.3
PyQt5-Qt5              5.15.2
PyQt5-sip              12.12.1
pyqt5-tools            5.15.9.3.3
python-dotenv          1.0.0
pywin32                306
qt5-applications       5.15.2.2.3
qt5-tools              5.15.2.1.3
scipy                  1.10.1
setuptools             58.1.0
```

plugins和tools都存在，打不开。删掉plugins，能打开但没新组件。
这是什么情况，怎么解决？

**Comment by zhiyiYo** [comment]
最新版本应该是 0.8.8 了吧

**Comment by zhiyiYo** [comment]
最好把代码放在英文路径下，参见 #215

**Comment by hanyuelanya** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/5726bdc3-36f8-4244-ad61-cff56014b89f)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/936b0def-9869-4461-b2bc-3540b678bdc8)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/5381e859-f1de-42ff-9d1d-dd9c7764e8ef)
用的miniconda，包和代码都是最新的，同级目录，环境没有中文，打开qtdesigner还是原样，在plugins/base_input.py里加上try catch后，运行后没有在本地生成日志文件

**Comment by Calvariaa** [comment]
`Arch Linux`, `Python 3.8.16`, `Virtualenv`, `PyQt-Fluent-Widgets 0.9.0`

遇到了使用`python ./tools/designer.py`启动之后没有加载plugins的问题，注释掉 https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/8be9751324da5c12c7ae36dc7bbab9d9997b810e/tools/designer.py#L61 之后一切正常

**Comment by zhiyiYo** [comment]
@hanyuelanya 
可以 pip show 看下版本号吗

**Comment by hanyuelanya** [comment]
> @hanyuelanya 可以 pip show 看下版本号吗

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/339ca6ba-ff77-4089-a49d-c1c11fb1ed18)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/432dfd91-2d34-4436-8104-4daf8e9e3cfd)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/7f9cd718-2407-4e41-b124-88590657f3f0)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/7b76683b-16bd-4aea-a6d5-7f10e5e877c5)

**Comment by zhiyiYo** [comment]
Qt Designer --> 帮助 --> 关于插件 能看到 pyqt5.dll 吗

**Comment by hanyuelanya** [comment]
> Qt Designer --> 帮助 --> 关于插件 能看到 pyqt5.dll 吗

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78330408/0869d844-2403-4869-aed0-4ac89ba2c547)
kan
我发现conda创建的虚拟环境可以利用外部的python包，是不是没有完全隔离

**Comment by zhiyiYo** [comment]
重新建一个吧，pyqt版本用 5.15.9

**Comment by CheshireCC** [comment]
> > QtDesigner 插件使用时出现的问题及解决方法：
> > ​ 在最新版的 **pyqt-fluent-widgets**（以下简称 **PFW** ）中，`Dev` 大佬为我们带来了可以直接在 _QtDesigner_ 中使用 **PFW** 控件的 _designer plugins_ ，但是由于初代版本还不太稳定，存在一些由虚拟环境引发的 _bug_。这里有一些可能有用的解决方案。
> > ```
> > 1. **conda** 创建虚拟环境，但运行脚本之后无事发生，无法打开 **designer.exe** 程序
> >    解决方案：检查各级文件夹目录是否含有“特殊字符”以及空格。
> > 
> > 2. **conda**环境运行脚本之后 打开 **designer.exe** 但是并没有 **PFW** 控件（还是原版的 **designer.exe** ）
> >    解决方案：需要将 代码仓库中提供的 `tools` 和 `plugins` 两个文件夹放在同级别目录下，一般来说这两个文件夹应当位于项目根目录下，与项目主脚本同级目录。
> > 
> > 3. 非 **conda** 虚拟环境（包括 `venv`、`virtualenv`、`Pipenv `等方式创建的虚拟环境）
> >    无法启动 **designer.exe** ，同 1。
> >    启动 **designer.exe** 但为原版 ：
> >    （1）首先同 2 ，检查文件目录；
> >    （2）如果不行，那么是因为这几种方法创建的 `python `虚拟环境依赖于系统中特定的 `python.exe` ，非完全隔离环境。该种虚拟环境中的 `Scripts\python.exe` 顾名思义，也只是一个运行真正 `python.exe` 程序的工具脚本；
> >    比如： 我使用位于 `D:\python39\python.exe` 的 `python` 软件 创建了 `./venv` 这个虚拟环境，那么实际上会运行 的 `python.exe` 程序依然是 `D:\python39\python.exe` 。该运行对象保存于 `./vnev/pyvenv.cfg` 文件中的 `home = D:\python39` 字段中。
> >    解决办法：将 `D:\python39\` 目录下的 **python.exe**、**python.dll**、**python39.dll**、**pythonw.exe**、**vcruntime.dll**（如果有的话）这几个文件全部拷贝到 `./venv` 。然后修改 `./vnev/pyvenv.cfg -> home=.\venv`，自测能解决问题。这里的文件路径换成你自己创建虚拟环境时依赖的 **基础解释器** 和创建完之后的虚拟环境所在的路径。
> > ```
> 
> 这个venv的环境问题，我找到了解决办法，具体请看 #224
更直接的解决方案是，移动文件并修改Home字段之后激活虚拟环境，然后卸载掉相关的包（主要就是pyqt5和tools），重新安装，应该就行了。路径哪里不填绝对路径的话多数时候会报错。

**Comment by v479038280** [comment]
> `Arch Linux`, `Python 3.8.16`, `Virtualenv`, `PyQt-Fluent-Widgets 0.9.0`
> 
> 遇到了使用`python ./tools/designer.py`启动之后没有加载plugins的问题，注释掉
> 
> https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/8be9751324da5c12c7ae36dc7bbab9d9997b810e/tools/designer.py#L61
> 
> 之后一切正常

试了上边说的几种方式，最后是这个有效了

**Comment by DreamOfStars** [comment]
> Python 3.10 不行的话可以试下 3.8，最好把代码放在英文路径下，参见 #215，#224
> 
> 如果启动之后看不到 PyQt-Fluent-Widgets 的组件，可以在 basic_input_plugin.py 的 import 处加上 try except，把报错信息保存到 txt 文件中：
> 
> ```python
> import traceback
> try:
>     from qfluentwidgets import (PrimaryPushButton, SplitPushButton, DropDownPushButton,
>                                 ToolButton, SplitToolButton, DropDownToolButton, FluentIcon, ToggleButton,
>                                 SwitchButton, RadioButton, CheckBox, HyperlinkButton, Slider, ComboBox, IconWidget,
>                                 EditableComboBox, PixmapLabel, PushButton)
> 
>     from plugin_base import PluginBase
>     from task_menu_factory import EditTextTaskMenuFactory
> except:
>     with open('error.txt', 'w', encoding='utf-8') as f:
>         f.write(traceback.format_exc())
> ```

我使用的是 pyenv 的 Python 3.11.1。打开 designer 后看不到组件。
按照这个方法，得到的报错信息如下：
```python
Traceback (most recent call last):
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\plugins\basic_input_plugin.py", line 6, in <module>
    from qfluentwidgets import (
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\__init__.py", line 17, in <module>
    from .components import *
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\components\__init__.py", line 1, in <module>
    from .dialog_box import *
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\components\dialog_box\__init__.py", line 1, in <module>
    from .color_dialog import ColorDialog
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\components\dialog_box\color_dialog.py", line 7, in <module>
    from ...common.style_sheet import FluentStyleSheet, isDarkTheme
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\common\__init__.py", line 1, in <module>
    from .config import *
  File "C:\Users\Dreamy\Downloads\PyQt-Fluent-Widgets-PyQt6\qfluentwidgets\common\config.py", line 6, in <module>
    import darkdetect
  File "C:\Users\Dreamy\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\darkdetect\__init__.py", line 36, in <module>
    from ._windows_detect import *
  File "C:\Users\Dreamy\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\darkdetect\_windows_detect.py", line 3, in <module>
    import ctypes
  File "C:\Users\Dreamy\.pyenv\pyenv-win\versions\3.11.1\Lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

但是我在 Python 里面 `import ctypes` 一切正常，有什么解决方法吗？

**Comment by CheshireCC** [comment]
> 
https://pypi.org/project/pyqt6-tools/

你好像在用pyqt6，pyqt6-tools 貌似只支持到 python 3.9 ，不知道是不是这样的原因

**Comment by DreamOfStars** [comment]
使用了3.7和3.9版本的Python，安装完PyQt6相关包之后，运行脚本无法打开designer.exe程序了。而3.11可以。

暂时不知道怎么解决，还是用回PyQt5了，一切正常。

**Comment by Orionxty** [comment]
改中文路径后确实就有了!!

**Comment by q447552640** [comment]
![屏幕截图 2023-06-22 024532](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/3325417/e22df2dc-ec83-48d9-a850-8f4a50f80013)
最新版pyqt6分支，你们有这个问题吗

**Comment by zhiyiYo** [comment]
pyqt6 也不行的话就用 pyqt5 的 QtDesigner 生成 ui 文件，然后 pyqt6 uic 来编译

**Comment by zhiyiYo** [comment]
开发新组件库的时候发现 PySide6 Designer 插件启动不了 QtDesigner 的原因是枚举类命名空间问题，应该在枚举成员前加上枚举类名

**Comment by TcDhlPro** [comment]
> QtDesigner 插件使用时出现的问题及解决方法：
> 
> ​ 在最新版的 **pyqt-fluent-widgets**（以下简称 **PFW** ）中，`Dev` 大佬为我们带来了可以直接在 _QtDesigner_ 中使用 **PFW** 控件的 _designer plugins_ ，但是由于初代版本还不太稳定，存在一些由虚拟环境引发的 _bug_。这里有一些可能有用的解决方案。
> 
> 1. **conda** 创建虚拟环境，但运行脚本之后无事发生，无法打开 **designer.exe** 程序
>    解决方案：检查各级文件夹目录是否含有“特殊字符”以及空格。
> 2. **conda**环境运行脚本之后 打开 **designer.exe** 但是并没有 **PFW** 控件（还是原版的 **designer.exe** ）
>    解决方案：需要将 代码仓库中提供的 `tools` 和 `plugins` 两个文件夹放在同级别目录下，一般来说这两个文件夹应当位于项目根目录下，与项目主脚本同级目录。
> 3. 非 **conda** 虚拟环境（包括 `venv`、`virtualenv`、`Pipenv `等方式创建的虚拟环境）
>    无法启动 **designer.exe** ，同 1。
>    启动 **designer.exe** 但为原版 ：
>    （1）首先同 2 ，检查文件目录；
>    （2）如果不行，那么是因为这几种方法创建的 `python `虚拟环境依赖于系统中特定的 `python.exe` ，非完全隔离环境。该种虚拟环境中的 `Scripts\python.exe` 顾名思义，也只是一个运行真正 `python.exe` 程序的工具脚本；
>    比如： 我使用位于 `D:\python39\python.exe` 的 `python` 软件 创建了 `./venv` 这个虚拟环境，那么实际上会运行 的 `python.exe` 程序依然是 `D:\python39\python.exe` 。该运行对象保存于 `./vnev/pyvenv.cfg` 文件中的 `home = D:\python39` 字段中。
>    解决办法：将 `D:\python39\` 目录下的 **python.exe**、**python.dll**、**python39.dll**、**pythonw.exe**、**vcruntime.dll**（如果有的话）这几个文件全部拷贝到 `./venv` 。然后修改 `./vnev/pyvenv.cfg -> home=.\venv`，自测能解决问题。这里的文件路径换成你自己创建虚拟环境时依赖的 **基础解释器** 和创建完之后的虚拟环境所在的路径。

此方法实测无效

**Comment by QianyeYang** [comment]
> 开发新组件库的时候发现 PySide6 Designer 插件启动不了 QtDesigner 的原因是枚举类名问题，应该在枚举成员前加上枚举类名

你好我也遇到了Pyside6无法启动插件的问题，请问可以详细解释一下嘛？

**Comment by zhiyiYo** [comment]
还是不太行，目前还在想办法。如果你用的是 qfluentwidgets 的话可以考虑用 PyQt-Fluent-Widgets 来生成 ui 文件然后 pyside6-uic 编译代码 @QianyeYang

**Comment by RequestSharp** [comment]
Not everyone can speak Chinese maybe?!

**Comment by zhiyiYo** [comment]
> Not everyone can speak Chinese maybe?!

谷歌翻译一下不是很快吗？

**Comment by zhiyiYo** [comment]
谷歌翻译不准确就换成 ChatGPT 吧，二者都比我翻译的好

**Comment by RequestSharp** [comment]
> 谷歌翻译不准确就换成 ChatGPT 吧，二者都比我翻译的好

yea does kinda of a better idea

**Comment by RequestSharp** [comment]
It seems like the issue is related to using the PyQt-Fluent-Widgets library in QtDesigner and encountering various problems, especially in virtual environments. The issue has multiple comments suggesting solutions and workarounds. Based on the provided information, here's a summary of the potential fixes mentioned in the comments:

Check Folder Names: Ensure that there are no special characters or spaces in the directory paths of your project, especially when using a conda virtual environment. This might cause issues when trying to run designer.exe.

Directory Structure: Make sure that the tools and plugins folders from the PyQt-Fluent-Widgets code repository are placed in the same directory level as your project's main script. These folders should ideally be located in the project's root directory.

Virtual Environment: If you are using a virtual environment created using methods like venv, virtualenv, or Pipenv, you might encounter issues running designer.exe. You can try copying specific files (e.g., python.exe, python.dll, etc.) from the base interpreter directory (e.g., D:\python39\) to your virtual environment directory (./venv) to resolve this.

Python Interpreter Dependencies: In some cases, virtual environments created using methods like venv might still depend on the system's specific Python interpreter. You can try modifying the pyvenv.cfg file in your virtual environment to point to your virtual environment's interpreter location.

Specific PyQt Version: Depending on the version of PyQt and Python you are using, you might encounter compatibility issues. It's suggested to use specific versions of PyQt (e.g., PyQt5 or PyQt6) and Python (e.g., Python 3.8 or Python 3.9) that are known to work with PyQt-Fluent-Widgets.

Language Paths: If you are using non-English characters in your paths, changing them to English characters might help resolve some issues.

Path Manipulation: In some cases, modifying the path environment variable by commenting out certain lines of code (e.g., env.insert('PATH', PATH)) might help resolve the issue.

QtDesigner Plugin Naming: When developing new components, if you encounter issues with PySide6 Designer plugins not starting in QtDesigner, it might be related to enumeration class names. Ensure that enumeration members are preceded by the enumeration class name.

Generate UI Files: If you're facing issues with the PyQt-Fluent-Widgets library, you can consider generating UI files using PyQt-Fluent-Widgets and then using pyside6-uic to compile the code.

It's important to carefully review and try these solutions based on your specific setup and requirements. Additionally, since the issue is ongoing and has multiple comments, you might want to follow any updates or new solutions posted in the original issue thread.

**Comment by annpeter** [comment]
> 感谢分享，Windows 建议直接使用发行页面提供的 FluentDesigner

能不能在发布的时候提供一个mac版本的FluentDesigner呢？

**Comment by Xianmo6924** [comment]
好像最新版的不用虚拟环境也可以（23/10/22）
我使用了Python3.9.13运行PyQt5版的就没问题

**Comment by zhiyiYo** [comment]
今天在 mac 上成功打开了带插件的 PySide6 Designer，分享一下操作流程：
1. 将虚拟环境下 `/lib/python3.11/site-packages/PySide6/scripts/pyside_tool.py` 的第 160 行环境变量改成虚拟环境中 python 动态链接库的地址，比如在我电脑上是：
    ```python
    os.environ['DYLD_INSERT_LIBRARIES'] = "/Users/shokokawaii/miniconda3/envs/FluentStudio/lib/libpython3.11.dylib"
    ```
2. 启动 designer：
   ```python
    python tools/designer.py
   ```

**Comment by xylewis** [comment]
> `Arch Linux`, `Python 3.8.16`, `Virtualenv`, `PyQt-Fluent-Widgets 0.9.0`
> 
> 遇到了使用`python ./tools/designer.py`启动之后没有加载plugins的问题，注释掉
> 
> https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/8be9751324da5c12c7ae36dc7bbab9d9997b810e/tools/designer.py#L61
> 
> 之后一切正常

是的 他工作了 这太不可思议了

**Comment by NamelessDev0000** [comment]
> `Arch Linux`, `Python 3.8.16`, `Virtualenv`, `PyQt-Fluent-Widgets 0.9.0`
> 
> 遇到了使用`python ./tools/designer.py`启动之后没有加载plugins的问题，注释掉
> 
> https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/8be9751324da5c12c7ae36dc7bbab9d9997b810e/tools/designer.py#L61
> 之后一切正常

这是什么原理？好奇怪啊...

**Comment by NamelessDev0000** [comment]
对于 wayland 用户，如果没有弹出 designer 窗口，请尝试修改 `designer.py` 中这段代码，切换到 xwayland 上运行：

```python
# set up environment variables
os.environ["QT_QPA_PLATFORM"] = "xcb"
env = QProcessEnvironment.systemEnvironment()
PATH = f"{os.path.dirname(PyQt5.__file__)};{sys.prefix};{env.value('PATH', '')}"
```
