### ISSUE TITLE
dialog.qss没指定cancelButton的字体颜色导致颜色被覆盖

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#20]
dialog.qss只写了QPushButton#yesButton的样式，#cancelButton没指定，默认用的QPushButton，但是我程序本身的qss也有定义了QPushButton，导致覆盖了cancelButton的样式

**Comment by zhiyiYo** [comment]
你是给 Dialog 加了按钮？

**Comment by zhiyiYo** [comment]
发个图康康，如果这里被你的qss覆盖了，其他部件应该也会出问题啊，你是不是改了一些东西

**Comment by Cheukfung** [comment]
以demo为例子，demo.qss加一段，`QPushButton {
   color:red;
}`，cancelbutton的字体也会被覆盖。
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/14865236/225594968-cba6a22c-1a8a-47ed-ad09-6a5193b05716.png">

**Comment by zhiyiYo** [comment]
测试了一下发现很多组件都有这个问题，得集体改改了

**Comment by zhiyiYo** [comment]
目前已修复该问题

**Comment by zhiyiYo** [comment]
这个问题你有什么想法吗，除了直接改spacing外：
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/19

**Comment by Cheukfung** [comment]
感谢修复。
另外那个问题应该是Mac的bug导致的，我用的qtdesigner做的主ui，没有出现bug。我猜测是因为qtdesigner默认加了setAttribute(Qt.WA_LayoutUsesWidgetRect);
具体请看https://stackoverflow.com/questions/3978889/why-is-qhboxlayout-causing-widgets-to-overlap
如果把dialog代码的spacing设置为0，就会出现和这个链接一样的控件重叠bug，只存在于Mac

**Comment by zhiyiYo** [comment]
感谢
