### ISSUE TITLE
QtDesigner插件无法在PyQt-Fluent-Widgets的PyQt6版上使用

### ISSUE THREAD

**Issue by Aero80wd** [zhiyiYo/PyQt-Fluent-Widgets#205]
报错:
G:\PyQt-Fluent-Widgets-master\tools\designer.py:44: UserWarning: Can't find avaliable pyqt6.dll, which may cause PyQt-Fluent-Widgets not being visible in QtDesigner.
  warnings.warn(f"Can't find avaliable {dll_name}, which may cause PyQt-Fluent-Widgets not being visible in QtDesigner.")
C:\Users\li_ji\AppData\Local\Programs\Python\Python311\Lib\site-packages\qt5_applications\Qt\bin\designer.exe

**Comment by zhiyiYo** [comment]
你这是pyqt5还是pyqt6？为啥报错信息里两个都有？

**Comment by zhiyiYo** [comment]
请重开一个 issue，需要补充完整 issue 模板里面的环境信息
