### ISSUE TITLE
Can you provide us with the .ui files for the examples?

### ISSUE THREAD

**Issue by sc0ned** [zhiyiYo/PyQt-Fluent-Widgets#207]
Would it be possible to include the .ui files for some of the examples so we can see how they were made in qt designer? would be helpful for building upon the existing demos.

Thanks and love the project! its already saved me a bunch of time <3

**Comment by zhiyiYo** [comment]
The `examples/login` folder has provided a `.ui` file. The code for other examples is very simple and does not require `.ui` files.
