### ISSUE TITLE
按照b站视频完全照做但是启动后的页面是原版的designer页面

### ISSUE THREAD

**Issue by bianliuyang** [zhiyiYo/PyQt-Fluent-Widgets#209]
**Describe the bug**
用conda环境+命令行启动tools中的designer.py，还是原来的设计师页面，没有扩展的插件

**Environment**
- OS: windows10
- Python: 3.8
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: 0.2.1

已经将plugins和tools放在了同级目录：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/62277627/5c022b78-d99c-4088-8ded-3ca92b70e709)
终端启动：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/62277627/7d42b859-2ff2-4f22-804a-df7c7e7bf443)
但是出现的界面还是原来的：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/62277627/b2094328-862d-4cdd-8797-5ca90978e7fb)

**Comment by zhiyiYo** [comment]
pyqt-fluent-widgets 版本太低了，现在是 0.8.8
