### ISSUE TITLE
Mac下Dialog消息提示框未禁用窗口调整大小

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#21]
**Describe the bug**
Mac下Dialog消息提示框未禁用窗口调整大小
**Environment**
- OS: MAC
- Python: 3.9.6
- PyQt:  5.15.2
- PyQt-Fluent-Widgets: 0.3.1

使用带标题栏的消息对话框，弹出后可以随意调整窗口尺寸大小，看代码有self.setResizeEnabled(False)，但是不生效
![2023-03-17 09 04 18](https://user-images.githubusercontent.com/8281775/225786701-14cdc78e-0517-433f-ae92-be428d277611.gif)

**Comment by zhiyiYo** [comment]
macOS下这个函数不起作用，可能得用 `self.setFixedSize(self.size())`

**Comment by qianye216** [comment]
> macOS下这个函数不起作用，可能得用 `self.setFixedSize(self.size())`

可以了
