### ISSUE TITLE
qt-designer不显示控件

### ISSUE THREAD

**Issue by Fgaoxing** [zhiyiYo/PyQt-Fluent-Widgets#215]
环境：都是最新的，py3.8，用的Conda，qt-designer不显示PyQt-Fluent-Widgets控件，和原版没区别

**Comment by zhiyiYo** [comment]
在 basic_input_plugin.py 的 import 处加上 try except，把报错信息保存到 txt 文件中：
```python
import traceback
try:
    from qfluentwidgets import (PrimaryPushButton, SplitPushButton, DropDownPushButton,
                                ToolButton, SplitToolButton, DropDownToolButton, FluentIcon, ToggleButton,
                                SwitchButton, RadioButton, CheckBox, HyperlinkButton, Slider, ComboBox, IconWidget,
                                EditableComboBox, PixmapLabel, PushButton)

    from plugin_base import PluginBase
    from task_menu_factory import EditTextTaskMenuFactory
except:
    with open('test.txt', 'w', encoding='utf-8') as f:
        f.write(traceback.format_exc())
```

**Comment by Fgaoxing** [comment]
报错如下
```python
Traceback (most recent call last):
  File "D:\用户\SmartSchoolSystem\plugins\basic_input_plugin.py", line 5, in <module>
    from qfluentwidgets import (PrimaryPushButton, SplitPushButton, DropDownPushButton,
ImportError: cannot import name 'SplitPushButton' from 'qfluentwidgets' (C:\Users\Yoga\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyqt_fluent_widgets-0.5.2-py3.11.egg\qfluentwidgets\__init__.py)
```

**Comment by zhiyiYo** [comment]
估计版本太低了

**Comment by Fgaoxing** [comment]
但是不知道为啥，我用了conda的环境，但是用的还是本机的Python

**Comment by zhiyiYo** [comment]
需要先激活虚拟环境

**Comment by Fgaoxing** [comment]
激活了
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/92655031/88262661-51fd-42f1-8998-8471d35a294c)
重新安装之后不报错了，但是还是没有

**Comment by Fgaoxing** [comment]
@zhiyiYo

**Comment by zhiyiYo** [comment]
更新一下 plugin 的代码

**Comment by Fgaoxing** [comment]
我是直接拉取的，就是最新的了

**Comment by Fgaoxing** [comment]
@zhiyiYo

**Comment by zhiyiYo** [comment]
昨天再整吧，太晚了，先睡了

**Comment by Fgaoxing** [comment]
@zhiyiYo 有空吗

**Comment by zhiyiYo** [comment]
QtDesigner 帮助 --> 关于插件里面有 pyqt5.dll 吗

**Comment by Fgaoxing** [comment]
有



在 2023-05-20 11:40:13，"一级棒卡哇伊的硝子酱" ***@***.***> 写道：

QtDesigner 帮助 --> 关于插件里面有 pyqt5.dll 吗

**Comment by Fgaoxing** [comment]
@

**Comment by zhiyiYo** [comment]
要不把路径换成中文的试试吧

**Comment by Fgaoxing** [comment]
一会的

**Comment by Fgaoxing** [comment]
终于好了 @zhiyiYo

**Comment by zhiyiYo** [comment]
是中文路径的锅吗

**Comment by Fgaoxing** [comment]
应该是，反正放到C:/目录就好了



在 2023-05-20 15:59:31，"一级棒卡哇伊的硝子酱" ***@***.***> 写道：

是中文路径的锅吗

**Comment by sc0ned** [comment]
> Add try except to the import of basic_input_plugin.py, and save the error message to a txt file:
> 
> ```python
> import traceback
> try:
>     from qfluentwidgets import (PrimaryPushButton, SplitPushButton, DropDownPushButton,
>                                 ToolButton, SplitToolButton, DropDownToolButton, FluentIcon, ToggleButton,
>                                 SwitchButton, RadioButton, CheckBox, HyperlinkButton, Slider, ComboBox, IconWidget,
>                                 EditableComboBox, PixmapLabel, PushButton)
> 
>     from plugin_base import PluginBase
>     from task_menu_factory import EditTextTaskMenuFactory
> except:
>     with open('test.txt', 'w', encoding='utf-8') as f:
>         f.write(traceback.format_exc())
> ```

hey @zhiyiYo so I'm getting a similar issue and was wondering if you knew the solution. when I run this traceback, I get the following missing import error: `ModuleNotFoundError: No module named 'darkdetect'` - obviously I've tried pip installing that package but it said it was already installed.

here's my pip list output:
```
(venv) C:\Users\sconed\PycharmProjects\qt_widget_examples\tools>pip list
Package                Version
---------------------- ----------
click                  8.1.3
colorama               0.4.6
colorthief             0.2.1
darkdetect             0.8.0
numpy                  1.24.3
Pillow                 9.5.0
pip                    21.1.3
PyQt-Fluent-Widgets    0.9.0
PyQt5                  5.15.9
PyQt5-Frameless-Window 0.2.7
pyqt5-plugins          5.15.9.2.3
PyQt5-Qt5              5.15.2
PyQt5-sip              12.12.1
pyqt5-tools            5.15.9.3.3
python-dotenv          1.0.0
pywin32                306
qt5-applications       5.15.2.2.3
qt5-tools              5.15.2.1.3
scipy                  1.10.1
setuptools             56.0.0
```

Using the latest PyQt-Fluent-Widgets source, python 3.9 - let me know if you need any more info!
