### ISSUE TITLE
FramelessWindow的TitleBar在最大化模式下，关闭按钮右侧16个像素的宽度渲染不出来

### ISSUE THREAD

**Issue by ADTrigger** [zhiyiYo/PyQt-Fluent-Widgets#216]
**Environment**
- OS: Win11
- DPI scaling: 100%
- Python: 3.9.13
- PyQt: PyQt6
- PyQt-Fluent-Widgets: 0.9.0

在使用FramelessWindow的默认TitleBar时，最大化窗口后，关闭按钮会有一半渲染不出来
我试过直接调用showMaximized方法，结果和点击TitleBar的最大化按钮一样，关闭按钮会有部分渲染不出来

* 正常状态下的TitleBar和三个功能按钮：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/53900809/0adf0899-5e82-4f73-ad13-ab1bf6548d3e)

* 窗口最大化时的三个功能按钮：可以看出来 CloseButton 少了一截（这绝对不是我截图截少了一部分）
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/53900809/c04b4d47-05fa-4784-bfad-e9d918fd5584)

我在(1900, 100)放了个宽度为 10 像素的红色Widget，在窗口最大化模式下能看到这个部件，所以应该是CloseButton的渲染在窗口最大化模式下有点问题

**Comment by zhiyiYo** [comment]
pyqt6 版本太高了，换成 6.4.2 试试

**Comment by ADTrigger** [comment]
哇dalao回复这么快！明天我就试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月20日 22:34 |
| 收件人 | ***@***.***> |
| 抄送至 | Chengzhi ***@***.***>***@***.***> |
| 主题 | Re: [zhiyiYo/PyQt-Fluent-Widgets] FramelessWindow的TitleBar在最大化模式下，关闭按钮右侧16个像素的宽度渲染不出来 (Issue #216) |

pyqt6 版本太高了，换成 6.4.2 试试
