### ISSUE TITLE
OpacityAniStackedWidget

### ISSUE THREAD

**Issue by doublexbepa** [zhiyiYo/PyQt-Fluent-Widgets#217]
**Describe the bug**
使用OpacityAniStackedWidget的时候，当连续切换的两个页面都有内容时候，会出现图标重叠的情况

**Environment**
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.6 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):

**Code**
```python
# Minimum code to reproduce the error

```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
环境信息没有、截图也没有、复现代码也没有，咋整？
