### ISSUE TITLE
How to use custom containers in qt designer?

### ISSUE THREAD

**Issue by sc0ned** [zhiyiYo/PyQt-Fluent-Widgets#218]
How exactly are we supposed to use the container widgets (framelessmainwindow, scrollarea, etc.) in qt designer? Whenever I try to use one, it doesn't let me place any widgets on top of it and I'm unable to set its layout (see image to see what I mean). I've tried placing it in QWidget, QFrame, etc. and its always the same

thanks!
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/77380633/285ef279-fecc-495a-a15f-4b49a7813ae0)

**Comment by zhiyiYo** [comment]
I will fix the issue with the container plugin in the future

**Comment by sc0ned** [comment]
> I will fix the issue with the container plugin in the future

That would be very useful to help understand how things work under-the-hood, thank you brother!

**Comment by zhiyiYo** [comment]
`FramelessWindow` and `FramelessMainWindow` are not available in Qt Designer.
