### ISSUE TITLE
侧边栏位置

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#22]
![image](https://user-images.githubusercontent.com/101497799/226073758-14a39663-9917-4cd2-8134-7d234e47d47e.png)
怎么实现侧边栏像这样、位置不处于标题栏的下方？

**Comment by zhiyiYo** [comment]
你把标题栏图标和title往右边平移就好了

**Comment by fsf678** [comment]
具体说说awa

**Comment by zhiyiYo** [comment]
感谢写了一个 demo，运行 `examples/navigation2/demo.py` 就能看到效果，但是你得手动下载源代码了，因为我还没把最新代码打包上传到 pypi
