### ISSUE TITLE
designer.exe路径中有空格时，tools\designer.py无法启动designer

### ISSUE THREAD

**Issue by JAEChase** [zhiyiYo/PyQt-Fluent-Widgets#220]
**BUG描述**
如果pyqt5-tools安装的路径包含空格，tools\designer.py无法启动designer。

**环境**
- OS: Windows11
- Python: e.g. 3.9.12 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.9.0

**复现步骤**
1.创建一个带空格的虚拟环境`virtualenv "test venv"`
2.虚拟环境安装pyqt5、pyqt5-tools
3.启动tools\designer.py脚本

**预期表现**
能够正常启动designer.exe

**实际表现**
无法启动designer.exe

**Comment by zhiyiYo** [comment]
在没有空格的路径创建不就Ok了？

**Comment by JAEChase** [comment]
刚开始使用的时候没有使用虚拟环境，所有的python包安装在了D:\Program Files\目录下，后来查了下是路径有空格导致的，想提交个PR改一下来着，所以创建了这个issue。
