### ISSUE TITLE
PyQt5 designer Fluent插件的问题，即便按照置顶配置了依旧是原来的

### ISSUE THREAD

**Issue by Trainerchan** [zhiyiYo/PyQt-Fluent-Widgets#224]
这个是我当前的项目根目录文件列表：
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88485587/31d8c375-3f30-4b34-9768-2e6048823914)

venv里面的pyvenv.cfg文件里面也修改了，只是不能直接写./venv，必须写绝对路径，如下：
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88485587/bf8bb9ab-4cbd-4edd-9fb3-7bff76e96c95)

并且我也按照置顶所讲，将python.exe等复制粘贴到venv下面，如下：
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88485587/38559a95-dbd5-4c90-a02d-5d142c7bce47)

这样子后，cmd里面运行 python .\tools\designer.py，打开之后还是原来的，这是为什么，哪里的问题吗？

**Comment by zhiyiYo** [comment]
有报错日志吗

**Comment by zhiyiYo** [comment]
按照 #215 也没有日志吗

**Comment by Trainerchan** [comment]
> 按照 #215 也没有日志吗

![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88485587/8c889d25-01ae-4030-becf-5d1db13092fc)

这个是报错，然后我去环境里面看了看，有安装这个包：

![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88485587/21abd93b-94a7-4cd4-a5a0-53e38d6896a9)

**Comment by zhiyiYo** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/215#issuecomment-1556082697

**Comment by CheshireCC** [comment]
更直接的解决方案是，移动文件并修改Home字段之后激活虚拟环境，然后卸载掉相关的包（主要就是pyqt5和tools），重新安装，应该就行了。路径哪里不填绝对路径的话多数时候会报错。

**Comment by WJJ1031338633** [comment]
> python ./tools/designer.py

意思是不用虚拟环境了》？

**Comment by Trainerchan** [comment]
> 

本身这个插件就是为了开发UI，所以直接安装在主环境也无伤大雅，也就安装一次，之后就是重复性的使用，或者直接搞个GUI脚本，使用就双击打开这样子，所以虚拟环境不要也罢，直接拉下来github代码，然后主环境安装对应包，之后运行即可正常使用

**Comment by WJJ1031338633** [comment]
> > 
> 
> 本身这个插件就是为了开发UI，所以直接安装在主环境也无伤大雅，也就安装一次，之后就是重复性的使用，或者直接搞个GUI脚本，使用就双击打开这样子，所以虚拟环境不要也罢，直接拉下来github代码，然后主环境安装对应包，之后运行即可正常使用

我就是因为没用虚拟环境，打开还是原版designer的。。你是怎么做到的

**Comment by WJJ1031338633** [comment]
> 

有设置什么环境变量吗？我电脑本身就装了designer

**Comment by zhiyiYo** [comment]
脚本里面设置了临时的环境变量，最好还是用虚拟环境吧，不然出了问题谁也帮不了你

**Comment by WJJ1031338633** [comment]
`Could not find platform independent libraries <prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '.\venv\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = 'E:\git\PyQt-Fluent-Widgets\Lib'
  sys._base_executable = 'E:\\git\\PyQt-Fluent-Widgets\\venv\\python.exe'   
  sys.base_prefix = 'E:\\git\\PyQt-Fluent-Widgets'
  sys.base_exec_prefix = 'E:\\git\\PyQt-Fluent-Widgets'
  sys.platlibdir = 'DLLs'
  sys.executable = 'E:\\git\\PyQt-Fluent-Widgets\\venv\\Scripts\\python.exe'
  sys.prefix = 'E:\\git\\PyQt-Fluent-Widgets'
  sys.exec_prefix = 'E:\\git\\PyQt-Fluent-Widgets'
  sys.path = [
    'E:\\git\\PyQt-Fluent-Widgets\\venv\\python311.zip',
    'E:\\git\\PyQt-Fluent-Widgets',
    'E:\\git\\PyQt-Fluent-Widgets\\Lib',
    '.\\venv',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding   
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004a08 (most recent call first):
  <no Python frame>`

切换了home路径之后 连 python命令都出错了，求解

**Comment by WJJ1031338633** [comment]
请问

> 和这个问题一样，[#215 (comment)](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/215#issuecomment-1556082697) 我没用过 venv，不清楚这是怎么回事

请问这组card组件有加入到designer插件中吗?
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54835553/33e93b83-c3af-4ad1-a117-398cb0d4f2ed)
