### ISSUE TITLE
 重新下载后    app.installTranslator(translator) TypeError: installTranslator(messageFile: QTranslator): argument 1 has unexpected type 'FluentTranslator'

### ISSUE THREAD

**Issue by boshuaiYu** [zhiyiYo/PyQt-Fluent-Widgets#225]
作者大大您好! 我最近想添加浏览器模块，于是下载了pyqtwebengine ，命令是pip pyqt5 pyqtwebengine 下载完之后可以运行的代码不成功，于是我重新删除，又下载了一遍，再跑变成了上述描述报错，实在不知道怎么解决啦

OS：Win11
python: 3.10
PyQt: 5.15.9
PyQt-Fluent-Widgets: 

error:
app.installTranslator(translator) TypeError: installTranslator(messageFile: QTranslator): argument 1 has unexpected type 'FluentTranslator'

代码如下：
```python
import os
import sys

from PyQt5.QtCore import Qt, QTranslator
from PyQt5.QtWidgets import QApplication
from qfluentwidgets import FluentTranslator

from MyUI.examples.common.config import cfg
from MyUI.examples.view.main_window import MainWindow

if cfg.get(cfg.dpiScale) == "Auto":
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
else:
    os.environ["QT_ENABLE_HIGHDPI_SCALING"] = "0"
    os.environ["QT_SCALE_FACTOR"] = str(cfg.get(cfg.dpiScale))

QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

app = QApplication(sys.argv)
app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)

locale = cfg.get(cfg.language).value
translator = FluentTranslator(locale)
galleryTranslator = QTranslator()
galleryTranslator.load(locale, "gallery", ".", ":/gallery/i18n")

app.installTranslator(translator)
app.installTranslator(galleryTranslator)

w = MainWindow()
w.show()
app.exec()
```
是您的gallery的demo文件

**Describe the bug**

**Environment**
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.6 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):

**Code**
```python
# Minimum code to reproduce the error

```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
麻烦填一下 PyQt-Fluent-Widgets 版本号

**Comment by zhiyiYo** [comment]
> 应该是0.9.0，我刚刚下载的

检查一下吧，镜像不一定是最新的

**Comment by boshuaiYu** [comment]
是PyQt6 0.9.0

**Comment by boshuaiYu** [comment]
我把pip uninstall PyQt6-Fluent-Widgets后下载的PyQt-Fluent-Widgets，这样应该不会冲突吧

**Comment by zhiyiYo** [comment]
这样也行

**Comment by boshuaiYu** [comment]
大大您帮我看一下，那个新的问题呗QWidget: Must construct a QApplication before a QWidget 
之前的写了好几天了，今天下载那个突然就运行不了 心态炸裂

**Comment by zhiyiYo** [comment]
就是环境乱了才会这样呀，不能同时下载多个 PFW 包。实在不行的话就用虚拟环境吧
