### ISSUE TITLE
LineEdit及相关控件当设置了setReadOnly(True)时右键菜单显示不对

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#227]
若给LineEdit及其他输入框控件设置了`setReadOnly(True)`属性时，输入框应该只读，不能修改和编辑才对
但是现在如果复制内容，可以通过在输入框右键菜单粘贴方式修改输入框内容，也可以选中输入框部分内容进行剪切、撤回、粘贴操作

预期结果：
只读属性的输入框
1. 未选中输入框的内容时，右键菜单应该只显示复制和全选菜单，且复制菜单置灰
2. 选中输入框内容时，若选中全部内容，则右键菜单只显示复制和全选菜单，全选菜单置灰，若选中部分内容，则右键菜单只显示复制菜单和全选菜单，均不置灰
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/872e1fa0-65cc-4436-94d2-c780a73261ef)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/a1a78443-d721-4a0c-ae2a-cdf0472b89c1)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/891604b3-ff89-4381-bb6d-90a67e005a71)

**Comment by zhiyiYo** [comment]
下个版本改改。
