### ISSUE TITLE
python /tools/designer.py 不能在wayland窗口协议下运行

### ISSUE THREAD

**Issue by cxsunflower** [zhiyiYo/PyQt-Fluent-Widgets#229]
**描述**
python /tools/designer.py 不能在wayland窗口协议下运行

**环境**
- OS: Arch Linux x86_64
- DPI scaling: 200%
- Python: 3.11.3 64-bit
- PyQt: 6.*
- PyQt-Fluent-Widgets: 0.9.1

**复现和暂时解决方法**
tools/designer.py 需要添加
```python
if os.environ.get('XDG_SESSION_TYPE') == 'wayland':
    env.insert('QT_QPA_PLATFORM','xcb')
```
设置qt运行环境x11才能运行qt-designer

**Comment by cxsunflower** [comment]
通过注释 
```python
# env.insert('PATH', PATH) 
```
解决不能加载组件问题

**Comment by zhiyiYo** [comment]
注释掉这一行试试：
env.insert('PATH', PATH)

**Comment by cxsunflower** [comment]
> 注解掉这一步考试：
> 
> ```python
> env.insert('PATH', PATH) 
> ```

注释掉这行解决了没有显示相关组件的问题，但是在linux wayland环境下不能通过designer.py启动qtdesigner，需要强制设置环境变量QT_QPA_PLATFORM="xcb"

按道理qtdesigner应该能使用系统库依赖开启wayland支持
https://wiki.archlinuxcn.org/wiki/Wayland

**Comment by zhiyiYo** [comment]
手动加一个环境变量也问题不大
