### ISSUE TITLE
请多多添加ICON

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#23]
ICON太少了，根本不够用！！

**Comment by zhiyiYo** [comment]
图标太多了，怎么可能添加的完😕

**Comment by zhiyiYo** [comment]
想要图标的话我可以提供几个字体文件，然后你可以用 metro studio 或者[百度字体编辑器](https://kekee000.github.io/fonteditor/)导出为 svg 格式

**Comment by zhiyiYo** [comment]
[FluentIcons.zip](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/files/11008522/FluentIcons.zip)
