### ISSUE TITLE
将pivot与stackwidget合并成tabwidget

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#232]
请求添加tabwidget，方便直接提升旧应用

**Comment by zhiyiYo** [comment]
TabWidget 的样式实现不了，之后有时间再看看要不要写

**Comment by abcdesteve** [comment]
> TabWidget 的样式实现不了，之后有时间再看看要不要写

pivot中已经实现了呀，就是希望把pivot和stackwidget合并成tabwidget
因为已有的应用不方便更改

另外现在的pivot还没有动画，也不能用鼠标滚轮滚动
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72078508/8401d688-4f7e-4288-88f5-8ee77e22363f)

**Comment by zhiyiYo** [comment]
还有另一种风格的标签页，文件资源管理器就是这种风格

**Comment by abcdesteve** [comment]
> 还有另一种风格的标签页，文件资源管理器就是这种风格

那个是可以关闭并且拖动顺序的tab吧？
感觉这两个不太一样，还是根据是否可以关闭的这个参数来切换两种风格吧
