### ISSUE TITLE
将默认主题色（不是主题）默认设置为跟随系统

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#236]
就像`Theme.AUTO`一样，添加`ThemeColor.AUTO`来跟随系统主题色
另外`setTheme()`传入的参数可以变为`str('dark')`而不是`Theme.DARK`吗，这样方便传参

**Comment by zhiyiYo** [comment]
dark、light 可能拼写错误，还要考虑大小写问题，枚举类无此问题

**Comment by zhiyiYo** [comment]
linux 没有主题色的说法，无法跨平台使用
