### ISSUE TITLE
General help with updating PivotItems

### ISSUE THREAD

**Issue by sc0ned** [zhiyiYo/PyQt-Fluent-Widgets#238]
Hey again @zhiyiYo, I know this is more of a general pyqt question but I was wondering if you or someone else reading this could help me understand this process better.

Using PivotItems as an example, how could I change the default appearance of an element like the rectangular bar under the PivotItem text so that the change isn't reverted whenever I update the qtfluentwidgets package? 

Would I need to make my own Pivot.py that inherits the original classes (with the modification to the text bar included) and use that version of Pivot in my program, or is there a way that I can "update" only that text bar in my existing code where i create the Pivot widget? I was thinking it might involve using update() to update the PivotItems "paintEvent" method but I'm not sure how exactly how to access each PivotItem to do the update.

Hopefully that makes sense and can be translated easily to your native language - let me know if I need to clear anything up.

Appreciate the help/advice in advance!

**Comment by zhiyiYo** [comment]
You should inherits the original classes

**Comment by zhiyiYo** [comment]
You should inherits the original classes

**Comment by zhiyiYo** [comment]
You should inherit the original classes
