### ISSUE TITLE
CalendarPicker组件当拖曳日期后日期显示重复并错乱

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#241]
【Bug】点击日历控件按钮弹出日历组件窗口，当鼠标点击随便一个日期然后按住鼠标往下移动一点点，出现加号图标时松开鼠标，日期显示重复并错乱。
【建议】另外日历默认是周一在最前面的，不知能否支持原生日历组件的`setFirstDayOfWeek`方法
![2023-05-29 16 32 09](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/bf8f5e6c-6d91-4098-beaf-f4927da9c261)

**Comment by zhiyiYo** [comment]
这个组件太复杂了，改不动了
