### ISSUE TITLE
IndeterminateProgressBar手动使用start方法开启进度动画，而非在showEvent中开启

### ISSUE THREAD

**Issue by JAEChase** [zhiyiYo/PyQt-Fluent-Widgets#244]
主要原因有以下两点：

1.实际使用过程中，进度条并非一显示就要滚动，而是应该在执行某些具体的动作后才显示。

2.如果调用pause方法暂停了动画，窗口最小化，然后又显示窗口时，进度条会继续滚动，不符合预期。

另外，如果一个动作执行完成，期望进度条能够停止滚动，并且长/短进度显示都应当归零，目前的pause方法只能停止滚动，尚无接口归零进度显示，因此还需要新增一个stop完成前述动作。

**Comment by zhiyiYo** [comment]
完成动作正常操作是把进度条隐藏了吧？没必要归零
