### ISSUE TITLE
TableWidget当不点击选中行，直接右键菜单操作时无法弹出右键菜单

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#246]
目前的TableWidget如果设置了自定义的右键菜单，当表格有多行时：
如果不单击选中一行，鼠标直接在某一行上面右键菜单，无法弹出右键菜单，必须先选中该行再右键才能弹出右键菜单

预期结果：
当直接鼠标右键时也能触发选中当前行的操作，这样就能弹出右键菜单，目前原生的tablewidget是支持直接弹出右键菜单的（直接右键菜单会选中对应的行）
![2023-05-31 11 14 54](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/409343ca-d9dc-4633-9701-3e8751ca0bbc)

**Comment by ImmiProgramer** [comment]
How to add icon like that picture

**Comment by zhiyiYo** [comment]
测试了 Apple Music 的表格组件右击后是没有变成选中状态的

**Comment by zhiyiYo** [comment]
可以手动调用 `updateSelectedRows()` 来更新选中的行
