### ISSUE TITLE
功能诉求

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#248]
我使用了NavigationInterface和stackedWidget设计了一个主界面，
但我发现在我addSubInterface并启动时，其原先的widget的界面尺寸会被忽略掉，
所以有没有办法在我调出其他widget时，主界面尺寸可以自动扩展成被通讯的widget尺寸大小
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/69e9fd64-9397-48f6-8f89-0d66faf38782)

**Comment by zhiyiYo** [comment]
stackedwidget加到布局里面之后子界面的大小就会和他保持一致

**Comment by youjunxiaji** [comment]
那这个问题无法解决吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 之一 ***@***.***&gt;
发送时间: 2023年5月31日 23:52
收件人: zhiyiYo/PyQt-Fluent-Widgets ***@***.***&gt;
抄送: 鼬君夏纪 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zhiyiYo/PyQt-Fluent-Widgets] 功能诉求 (Issue #248)





 
stackedwidget加到布局里面之后子界面的大小就会和他保持一致

**Comment by zhiyiYo** [comment]
子界面本来就应该填满除了导航栏以外的空间吧🧐

**Comment by youjunxiaji** [comment]
是的是的 &nbsp;我本来想的是通过获取子界面size的，然后再切换界面的时候resize一下主界面，但是不知道为啥失败了☹️



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 之一 ***@***.***&gt;
发送时间: 2023年6月1日 00:13
收件人: zhiyiYo/PyQt-Fluent-Widgets ***@***.***&gt;
抄送: 鼬君夏纪 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zhiyiYo/PyQt-Fluent-Widgets] 功能诉求 (Issue #248)





 
子界面本来就应该填满除了导航栏以外的空间吧🧐
