### ISSUE TITLE
Ubuntu下没能显示fluent组件

### ISSUE THREAD

**Issue by hairenjun** [zhiyiYo/PyQt-Fluent-Widgets#249]
**Describe the bug**

使用designer.py打开designer后没有fluent的组件
**Environment**
- OS: [Ubuntu 20.04 LTS]
- Python: [3.10.11]
- PyQt: [5.15.9]
- PyQt-Fluent-Widgets: [0.9.2]
- pyqt5-plugins: [5.15.9.2.3]
- qt5-tools: [5.15.9.3.3] 
-pyqt5-frameless-window: [0.2.7]

**To Reproduce**
使用conda创建虚拟环境
在clone的仓库里pip install -r requirements.txt 
然后安装pyqt-fluent-widgets：pip install pyqt-fluent-widgets 
最后在仓库里python -u ./tools/designer.py
出来了个原始的designer

我看过了 #196 和#215 #224
和#224一样，插入了try...except代码也不产生错误日志，但也不出现fluent控件
也试过注释PATH的方法(#196)，仍然不起作用
![Screenshot from 2023-05-31 21-34-09](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/34180832/5d30312b-cac2-4379-8bb1-a88fc354336d)

**Comment by hairenjun** [comment]
![Screenshot from 2023-05-31 21-42-13](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/34180832/105e7bd7-3213-4379-b41e-7fe9ca8b4e4c)
这也是个怪问题

**Comment by hairenjun** [comment]
> 你可以看下他的designer.py代码，只是添加了一个全局环境变量， 实际上你可以再你的bashrc或者zshrc中添加一行 `export PYQTDESIGNERPATH="/home/lk/PyQt-Fluent-Widgets/plugins"` 然后在任意路径用命令行执行 `pyqt5-tools designer` 这样designer会有fluent 组件 

成功的解决了上述QT plugins报错的问题，遗憾的是他还是没能出fluent的组件
![Screenshot from 2023-06-02 00-10-32](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/34180832/1c87057d-4137-4e8b-bf84-c89168214113)

Python3.8是第一个尝试的，因为[B站视频](https://www.bilibili.com/video/BV1ms4y137EU/?spm_id_from=333.788&vd_source=e46a52a0924828db081b70296577bf04)用的3.8

**Comment by zkvii** [comment]
> > 你可以看下他的designer.py代码，只是添加了一个全局环境变量， 实际上你可以再你的bashrc或者zshrc中添加一行 `export PYQTDESIGNERPATH="/home/lk/PyQt-Fluent-Widgets/plugins"` 然后在任意路径用命令行执行 `pyqt5-tools designer` 这样designer会有fluent 组件
> 
> 成功的解决了上述QT plugins报错的问题，遗憾的是他还是没能出fluent的组件 ![Screenshot from 2023-06-02 00-10-32](https://user-images.githubusercontent.com/34180832/242643500-1c87057d-4137-4e8b-bf84-c89168214113.png)
> 
> Python3.8是第一个尝试的，因为[B站视频](https://www.bilibili.com/video/BV1ms4y137EU/?spm_id_from=333.788&vd_source=e46a52a0924828db081b70296577bf04)用的3.8

[这个是我简单的录制的，用的是python3.8.6 pyqt5 你看看你的包是不是冲突了，你创建一个全新环境看看](https://www.bilibili.com/video/BV1rh4y1s7hq/?share_source=copy_web&vd_source=79bbba3c829827987ae43085df86b0b2)

**Comment by 2c2048d2** [comment]
> 你可以看下他的designer.py代码，只是添加了一个全局环境变量， 实际上你可以再你的bashrc或者zshrc中添加一行 `export PYQTDESIGNERPATH="/home/lk/PyQt-Fluent-Widgets/plugins"` 然后在任意路径用命令行执行 `pyqt5-tools designer` 这样designer会有fluent 组件 ![image](https://private-user-images.githubusercontent.com/113273091/242592331-d77bdcc9-ca8a-49f8-947c-7ec22a56c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDYyOTIsIm5iZiI6MTcwNjUwNTk5MiwicGF0aCI6Ii8xMTMyNzMwOTEvMjQyNTkyMzMxLWQ3N2JkY2M5LWNhOGEtNDlmOC05NDdjLTdlYzIyYTU2YzcwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwNTI2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDE1ODFjYjVmMjVkYzlkMDA0NmY5MmVhNjU1ZTM3NDUxMGVjNmRjNmNjYjYwNzNiZDIxOGNjNGM4YjdmNTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0KKs2_dN17thJKVmQjsCnHjz0IBt2qyKObP5N29mjjM)

十分感谢，我看了很久issue，只有你这个方法生效了
这是我的fetch
<img width="751" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93045538/28259e1d-65c6-4548-b294-b2f79e2f4ca6">

下面是我自己写的几个启动方式
<img width="946" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93045538/43a0ab06-612e-4e55-b937-5e224a38e2fa">
<img width="951" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93045538/76e0d38f-fd02-4686-838b-1f3b3cb7105d">
希望能帮到大家
