### ISSUE TITLE
python ./tools/designer.py ?

### ISSUE THREAD

**Issue by kyoko9000** [zhiyiYo/PyQt-Fluent-Widgets#250]
after install 
pip install PyQt-Fluent-Widgets
pip install pyqt5-tools

and i use command:
python ./tools/designer.py

i got this error: [Errno 2] No such file or directory
how can i fix that?
i use python 3.9.13
pycharm newest version
window 10 64bit

**Comment by zhiyiYo** [comment]
文档里面说的很清楚，需要下载仓库代码
