### ISSUE TITLE
关于默认qss的问题

### ISSUE THREAD

**Issue by Changgeng-Wei** [zhiyiYo/PyQt-Fluent-Widgets#257]
请问默认加载的.qss文件在哪个路径？找了好久没找到， 看了源码，似乎是f":/qfluentwidgets/qss/{theme.value.lower()}/{self.value}.qss"，但这个找了好久没找到，不知道是不是我路径的问题，或者有其它的方法可以修改加载的默认路径也行~
另外，在官方的document中，修改主题的方法，也似乎只能修改除qfluentwidgets提供的类之外的其它样式~

**Comment by zhiyiYo** [comment]
样式表被编译到资源文件里面了，所以路径是 :/qfluentwidgets 打头，建议谷歌一下 Qt 资源系统

**Comment by zhiyiYo** [comment]
没看懂最后一句话想要表达什么

**Comment by Changgeng-Wei** [comment]
多谢多谢
