### ISSUE TITLE
关于TreeView中的字体问题

### ISSUE THREAD

**Issue by Changgeng-Wei** [zhiyiYo/PyQt-Fluent-Widgets#258]
大佬，我在用TreeWidget的时候，在添加QTreeWidgetItem时，无法使用setFont修改项目的字体大小，如果使用QTreeWidget是可以的，请问是不是要用其他操作？

**Comment by zhiyiYo** [comment]
需要重写 `TreeItemDelegate` 的 `initStyleOption`，写法看下源代码和 `examples/table_view/demo.py`
