### ISSUE TITLE
建议Dialog加个最小宽度

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#26]
如果文字提示太短，会导致消息框太小，很难看，建议加个最小宽度比如25%父窗口大小，看起来顺眼很多
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/14865236/226121859-9f79ccca-7e24-46d2-bcfe-1a2d4d63d6ba.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/14865236/226121884-edac7339-6231-47f6-ab80-7e0315afb97c.png">

**Comment by qianye216** [comment]
@zhiyiYo 另外补充一个建议，能否title属性可缺省为空，因为有的时候就想给个消息对话框一句话提醒用户，不想再编个标题，如果标题为空的话再调整下宽高样式就比较好了

**Comment by zhiyiYo** [comment]
> @zhiyiYo 另外补充一个建议，能否title属性可缺省为空，因为有的时候就想给个消息对话框一句话提醒用户，不想再编个标题，如果标题为空的话再调整下宽高样式就比较好了

你可以手动调用 `titleLable.hide()`

**Comment by zhiyiYo** [comment]
已完成最小宽度的设置
