### ISSUE TITLE
关于PySide6,因为qt官方版本是pyside6,我试了试pyside6使用designer，这里把ubuntu的坑填一填

### ISSUE THREAD

**Issue by zkvii** [zhiyiYo/PyQt-Fluent-Widgets#260]
**Describe the bug**
pyside ubuntu wsl2 designer 组件显示

**Environment**
- OS: wsl2 22.04
- DPI scaling: [e.g. 125%]
- Python: latest[3.11.3]
- PyQt: pyside6.4
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**To Reproduce**

[`视频链接上传到了b站`](https://www.bilibili.com/video/BV1c8411Z7XD/?share_source=copy_web&vd_source=79bbba3c829827987ae43085df86b0b2)

**Comment by zhiyiYo** [comment]
用了 pyside6 插件的 qtdesigner 在 Windows 上经常启动不了，所以这些插件已经没有维护了，平时合并代码的时候都是直接接受传入
