### ISSUE TITLE
Acrylic Menu

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#261]
Add Transparency & Blur to RoundedMenu

**Comment by ImmiProgramer** [comment]
Please

**Comment by zhiyiYo** [comment]
1.2.1 will add acrylic menu
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/b5e78823-1055-4987-b2ba-24c9ea65ebaa)

**Comment by immiProgrammer** [comment]
> 1.2.1 will add acrylic menu
> 
> ![33YOG@ PY4FRU15ZW134AER](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/42bbfa22-94db-47c3-bb70-83646ecdcb2a)
> 

Thanks

**Comment by immiProgrammer** [comment]
Also add Acrylic Card
