### ISSUE TITLE
QML support.

### ISSUE THREAD

**Issue by LightCannon** [zhiyiYo/PyQt-Fluent-Widgets#27]
Hello. Thanks for this project.

Is there a way to use it for QML?
I would like to write fluent style ui but I'm using QML not Qt widgets. 
Thanks.

**Comment by Wip-Sama** [comment]
I guess this is still a no

**Comment by zhiyiYo** [comment]
> I guess this is still a no

Maintaining four branches for free is already exhausting, let alone QML and PyQt are completely different
