### ISSUE TITLE
InfoBar有时出现错误堆栈错误

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#273]
直接使用Vscode运行程序，有时看到终端报以下错误，主程序未崩溃闪退
看错误提示应该是infobar的原因：

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/info_bar.py", line 417, in eventFilter
    return super().eventFilter(obj, e)
RuntimeError: wrapped C/C++ object of type TopInfoBarManager has been deleted
```

**Comment by zhiyiYo** [comment]
应该是因为 `InfoBar` 对象被销毁了，而 `InfoBarManager` 没有及时移除对象导致的。讲道理 `InfoBar.closeEvent()` 里面会发出一个信号让 `InfoBarManager` 移除自己，不知道为什么这个信号没有发出去

**Comment by Cheukfung** [comment]
退出软件的时候偶尔也会触发这个问题，不过不影响正常运行

**Comment by Xisenqvq** [comment]
我也有偶尔遇见过，在pyside6上尤为严重，几乎100%复现且偶尔会出现infobar错位，已经开始怀疑是自己的问题了

**Comment by YiChen1997** [comment]
PyQt6通过Pycharm运行examples/info_bar/demo.py，点击任意一个button都会报异常退出的错：“Process finished with exit code -1073741571 (0xC00000FD)“，请问大佬这是什么原因呢 @zhiyiYo

**Comment by zhiyiYo** [comment]
> PyQt6通过Pycharm运行examples/info_bar/demo.py，点击任意一个button都会报异常退出的错：“Process finished with exit code -1073741571 (0xC00000FD)“，请问大佬这是什么原因呢 @zhiyiYo 

估计是环境乱了，建个新的环境试试

**Comment by zhiyiYo** [comment]
> 我也有偶尔遇见过，在pyside6上尤为严重，几乎100%复现且偶尔会出现infobar错位，已经开始怀疑是自己的问题了

我的 pyside6 不会这样，用的 6.4.2

**Comment by LxHTT** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/98154001/1878777d-63a8-49d4-9c7a-352867e46bd7)

**Comment by rainzee** [comment]
> 我也有偶尔遇见过，在pyside6上尤为严重，几乎100%复现且偶尔会出现infobar错位，已经开始怀疑是自己的问题了

可以提供一下最小复现代码吗？

**Comment by LimeBow-Studios** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/273#issuecomment-1681679234
> ![image](https://user-images.githubusercontent.com/98154001/261216004-1878777d-63a8-49d4-9c7a-352867e46bd7.png)

这个错误提示咋做的，没这思路

**Comment by LxHTT** [comment]
> [#273 (comment)](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/273#issuecomment-1681679234)
> 
> > ![image](https://user-images.githubusercontent.com/98154001/261216004-1878777d-63a8-49d4-9c7a-352867e46bd7.png)
> 
> 这个错误提示咋做的，没这思路

接管sys.excepthook，自己处理。
参考https://github.com/MCSLTeam/MCSL2/blob/10f367beaecb52c903022b72cfb7f28cdbf253d7/MCSL2Lib/windowInterface.py#L352C9-L352C24

**Comment by rainzee** [comment]
主要无法稳定复现，所以也不好修
