### ISSUE TITLE
FramelessMainWindow 无论拖动什么组件到窗口内都被禁止了

### ISSUE THREAD

**Issue by WJJ1031338633** [zhiyiYo/PyQt-Fluent-Widgets#278]
发现创建 FramelessMainWindow 后无论拖动什么组件到窗口内都被禁止了

**Comment by WJJ1031338633** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54835553/1ada9095-45f2-4451-bdc6-e76e082e881f

**Comment by zhiyiYo** [comment]
无边框的插件有点问题，还是不要用了
