### ISSUE TITLE
大佬能否添加一个支持toast提示组件

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#28]
目前的消息提醒都是消息对话框的形式，能否添加一个toast提示的组件，不用用户二次确认，直接提醒，1到2秒后自动消失

例如参考下面：
https://element-plus.gitee.io/zh-CN/component/message.html#%E4%B8%8D%E5%90%8C%E7%8A%B6%E6%80%81
![image](https://user-images.githubusercontent.com/8281775/226148361-431a1c59-afbd-477d-a64c-36a28a42ba3a.png)

**Comment by zhiyiYo** [comment]
winui3里面有这个组件吗

**Comment by qianye216** [comment]
> winui3里面有这个组件吗
不太清楚，如果没有的话感觉应该可以按winui3的整体风格设计一个类似风格的也行

**Comment by Cheukfung** [comment]
state_tool_tip.py里面的ToastToolTip换个样式和位置，不就是Toast了吗

**Comment by qianye216** [comment]
> state_tool_tip.py里面的ToastToolTip换个样式和位置，不就是Toast了吗

差不多，toast最好能支持普通的信息提示、成功、错误、警告不同的类型的样式，然后能默认1到2秒左右自动消失就好了，这样更通用，很多交互操作只需要给个简单的提示给用户就行了，不用再去点击确定或者取消

**Comment by zhiyiYo** [comment]
`ToastToolTip` 其实是 Win10 风格的，之后有时间再加个 Win11 的吧

**Comment by qianye216** [comment]
> `ToastToolTip` 其实是 Win10 风格的，之后有时间再加个 Win11 的吧

好的，期待……

**Comment by zhiyiYo** [comment]
看了一下 WinUI3 的文档，他们把这组件叫做 `InfoBar`
https://learn.microsoft.com/en-us/windows/apps/design/controls/infobar

**Comment by qianye216** [comment]
> 看了一下 WinUI3 的文档，他们把这组件叫做 `InfoBar` https://learn.microsoft.com/en-us/windows/apps/design/controls/infobar

恩恩，因为平时用手机比较多，手机端一般叫这个toast

**Comment by zhiyiYo** [comment]
已添加 `InfoBar`，你可以运行 gallery 界面或者 `examples/info_bar/demo.py` 来查看效果

**Comment by zhiyiYo** [comment]
可能是字体导致的

**Comment by zhiyiYo** [comment]
居中是指软件的正中间吗？

**Comment by zhiyiYo** [comment]
能录个屏吗，我康康效果长啥样

**Comment by Cheukfung** [comment]
起飞，下个就是table组件了

**Comment by zhiyiYo** [comment]
table太难了，先整点简单的 SpinBox 和进度条
