### ISSUE TITLE
关于TitleBar

### ISSUE THREAD

**Issue by Changgeng-Wei** [zhiyiYo/PyQt-Fluent-Widgets#287]
大佬，我要自定义标题栏，加个按钮，然后在测试用官方的StandardTitleBar时，出现奔溃，调试原因，提醒WindowsFramelessWindow的resizeEvent()方法中，有widget已经被删除，但是仍然被使用
class TestStickButton(FramelessWindow):
    def __init__(self):
        super(TestStickButton, self).__init__()
        self.titleBar = StandardTitleBar(parent=self)
        self.setTitleBar(self.titleBar)

**Comment by zhiyiYo** [comment]
代码写的有问题：不需要再次赋值`self.titleBar = StandardTitleBar(parent=self)`，把这一行去掉就行，换成 `self.setTitleBar(StandardTitleBar(self))`
