### ISSUE TITLE
关于setLayout()的问题

### ISSUE THREAD

**Issue by rainzee** [zhiyiYo/PyQt-Fluent-Widgets#289]
在 https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/PySide6/examples/navigation2/demo.py 中，初始化布局，但是却没有显示调用 setLayout() 去应用此布局，想请问一下为什么不需要显式调用该方法也能成功应用布局？

**Comment by zhiyiYo** [comment]
构造函数指定父级就行了

**Comment by rainzee** [comment]
> 构造函数指定父级就行了

self.hBoxLayout = QHBoxLayout(self)
所以这样就等于自动应用了布局对吗，因为传入了self

**Comment by rainzee** [comment]
> 是的

感谢您的回复
