### ISSUE TITLE
建议导航组件宽度可以自定义

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#29]
现在默认的宽度有点太宽了，比Windows设置界面的还要宽，能否加个参数可以定义宽度的
![截图_20230320102620](https://user-images.githubusercontent.com/14865236/226232887-a9ebcaf0-d307-4f89-b258-5143763b12c2.png)

**Comment by zhiyiYo** [comment]
照片和媒体播放器都是这个宽度

**Comment by zhiyiYo** [comment]
目前已添加方法 `NavigationInterface.setExpandWidth()` 来控制伸展宽度
