### ISSUE TITLE
spinbox设置accelerated无效

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#293]
**Describe the bug**
如标题，设置后仍然无法长按加快速度

**Environment**
- OS: win11
- DPI scaling: [e.g. 125%]
- Python: 3.10 x86_64 miniconda3
- pyside6
- PyQt-Fluent-Widgets: 0.9.5

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):

**Code**
```python
# Minimum code to reproduce the error
self.spin_ram.setAccelerated(True)
```

**Expected behavior**
设置后长按可以提升数值改变的速度

**Screenshots**

**Comment by zhiyiYo** [comment]
可能得给 SpinBox 里面的按钮设置 `autoRepeat` 标志

**Comment by abcdesteve** [comment]
我测试了不提升的时候是可以直接用的

**Comment by zhiyiYo** [comment]
已修复此问题
