### ISSUE TITLE
加入FontComboBox控件

### ISSUE THREAD

**Issue by JasonMo1** [zhiyiYo/PyQt-Fluent-Widgets#294]
正如[#214 ](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/214)中@zhiyiYo给出的示例代码，将Font Family作为 item的确可以显示出字体的列表，但无法获取字体的文件位置。
我尝试创建了一个用于枚举字体名称的函数：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/111677135/14ebb17a-ec75-4c5b-b180-1e1eced05d74)
但这个函数是无法正常工作的。原因是在C:/Windows/Fonts中存储的字体与在Font Family中获取的字体名并不完全一致。C:/Windows/Fonts中的部分字体文件：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/111677135/4c57041e-22af-4f29-83db-467d7815781e)
这对我的开发工作带来了较多困难，且目前网上并没有相关解决方案故希望开发者们开发此控件。谢谢！

**Comment by zhiyiYo** [comment]
chatgpt 的回答：
如果你想获取系统中已安装的字体路径，可以使用 `QFontDatabase` 类的 `applicationFontFamilies` 静态方法获取系统中已安装的字体名称列表，然后使用 `QFontDatabase` 类的 `fontPath` 静态方法获取字体的文件路径。示例代码如下：

```python
from PyQt5.QtGui import QFontDatabase

# 获取系统中已安装的字体名称列表
font_families = QFontDatabase.applicationFontFamilies()

# 遍历字体名称列表，获取每个字体的文件路径
for font_family in font_families:
    font_info = QFontDatabase().font(font_family, '', 12)
    font_path = QFontDatabase().fontPath(font_info)
    print('{}: {}'.format(font_family, font_path))
```

这里使用了 `QFontDatabase` 类的 `font` 方法获取指定字体名称、样式和大小的 `QFont` 对象，然后再使用 `fontPath` 方法获取字体文件的路径。

注意：`fontPath` 方法可能返回多个路径，因为一个字体文件可能位于多个目录中。在这种情况下，可以选择其中一个路径即可。
