### ISSUE TITLE
Mac下label标签中文字体未默认支持加粗样式

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#298]
Mac运行最新添加的Label组件demo，如果Label文本内容包含中文的话无法显示粗体样式
建议字体集增加“`PingFang SC`”以便支持mac下中文字体的粗体样式
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/71a46327-cf4b-4cfd-934a-e61be00e6022)
以下是添加了`PingFang SC`的效果图
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/ee7c9339-9f97-448d-a212-aa053ad78e09)

**Comment by zhiyiYo** [comment]
感谢反馈，已修复此问题
