### ISSUE TITLE
switchbox禁用后仍然可以切换开关

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#299]
**Describe the bug**

**Environment**
- OS: win11
- DPI scaling: [e.g. 125%]
- Python: 3.10 x86_64 anaconda
- pyside6
- Pyside6-Fluent-Widgets: 0.9.6

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):

**Code**
```python
# Minimum code to reproduce the error
SwitchBox().setEnabled(False)
```

**Expected behavior**
禁用后显示为灰色，单击切换时会有一瞬间闪出主题色，然后变灰，并且状态还变化了

**Screenshots**

**Comment by zhiyiYo** [comment]
没有这个组件

**Comment by zhiyiYo** [comment]
SwitchButton 确实存在此问题，目前已修复
