### ISSUE TITLE
更新PySide6版本

### ISSUE THREAD

**Issue by rainzee** [zhiyiYo/PyQt-Fluent-Widgets#301]
PySide6在持续迭代pyi，能否更新PySide6库版本

**Comment by rainzee** [comment]
实际上Pyside6的迭代和维护非常积极 https://wiki.qt.io/Qt_for_Python_Development_Notes 他们现在在改善诸如内存泄漏问题，启动时间优化等等。我自己尝试在更新的版本上使用，并没有发现什么大问题。

**Comment by zhiyiYo** [comment]
pyqt-fluent-widgets 在高版本的pyside6下最大化有问题
