### ISSUE TITLE
SwitchButton Handle is Misaligned

### ISSUE THREAD

**Issue by rllysleepy** [zhiyiYo/PyQt-Fluent-Widgets#302]
**Describe the bug**
The switch button is misaligned when switching from off to on. 
In the off state, the button handle is 9px from top and bottom.
In the on state, the button handle has shrunk, and is now 9px from top but 12px from bottom.

**Environment**
- OS: Win 11
- DPI scaling: 200%
- Python: 3.11
- PyQt: PyQt6

**To Reproduce**
Gallery file shows this behaviour.

**Expected behavior**
Should be aligned--button handle shouldn't shrink in size.

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94653795/e325904d-8726-499e-a7b1-e9a223b321fe)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94653795/2b041f38-8086-481e-8e02-78ae4c302697)

**Comment by zhiyiYo** [comment]
无法复现此问题
