### ISSUE TITLE
加入QWebEngineView后，窗体不能用鼠标通过边框调整大小

### ISSUE THREAD

**Issue by henry989-hub** [zhiyiYo/PyQt-Fluent-Widgets#303]
**Describe the bug**
加入QWebEngineView后，会破坏窗体的外观（例如四个角从圆弧变成了直角），窗体不能用鼠标通过边框调整大小。

**Environment**
环境信息
- OS:Windwos11
- DPI scaling: 100%
- Python: 3.8.16 [64-bit]
- PySide6: 6.4.3
- PySide6-Fluent-Widgets: 0.9.6

**To Reproduce**
1. 只要添加QWebEngineView，就会出现描述中的问题，注释掉后问题消失。
![1687662636685](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/85954370/f48080a8-4b2e-4343-8720-ff4686cb0031)

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
        frame = QWebEngineView(self)
        # url = QUrl("http://www.baidu.com/")
        # frame.setUrl(url)
        self.addExampleCard(
            title=self.tr('A WebView'),
            widget=frame,
            sourcePath='https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/PySide6/examples/web_view/demo.py'
        )

```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
pyside确实有这个问题，如果不商用的话换成 pyqt5 就能解决

**Comment by henry989-hub** [comment]
非常感谢您的确认，那我换个环境算了。
本来还觉得奇怪，后来在样例里面加这一行就出现这个问题了。
|
|
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年6月25日 11:46 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhiyiYo/PyQt-Fluent-Widgets] 加入QWebEngineView后，窗体不能用鼠标通过边框调整大小 (Issue #303) |

pyside确实有这个问题，如果不商用的话换成 pyqt5 就能解决
