### ISSUE TITLE
Mac下TeachingTip若设置了图片，当文本内容比较少时出现显示错位的情况

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#305]
新增的TeachingTip很实用，但是如果添加了图片在内容文本比较少的情况下可能无法导致显示错位
可能需要根据图片缩放显示设置content区域的最小宽度
重现代码：demo中将content内容删除一些即可出现
<img width="600" alt="115截图20230626082350" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/3fa2640d-51c1-42ec-bb1f-2bfcf689af9a">

**Comment by zhiyiYo** [comment]
感谢反馈，忘记设置最小宽度了，暂时可以在 content 里面补空格来调整宽度

**Comment by zhiyiYo** [comment]
@qianye216 
现在还有这个问题吗

**Comment by zhiyiYo** [comment]
ok
