### ISSUE TITLE
PySide6 Titlebar 位置偏移

### ISSUE THREAD

**Issue by rainzee** [zhiyiYo/PyQt-Fluent-Widgets#307]
在全屏窗口的时候，`Titlebat`的`CloseButton`在窗口的位置发生少许偏移，如下图：
普通状态下一切正常
![normal](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/ba2fb5f1-cc3e-4f5f-8b4c-aa7646e4f9c1)
期望的全屏效果
![hope](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/6624dd2c-2e96-4621-a486-33a4d88026c7)
实际的全屏效果
![full](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/a295b153-0bd8-418d-b5f0-4732f4c55a29)

可以看到在实际全屏下，关闭按钮的位置有点向右溢出窗口，这个问题出现在所有使用了`Titlebat`的组件上

**Comment by zhiyiYo** [comment]
pyside 版本太高了，换成 6.4.2 就能解决
