### ISSUE TITLE
PyQt6运行"examples/teaching_tip/demo.py"时"TeachingTipView.addWidget"以及”TeachingTip.make“报错

### ISSUE THREAD

**Issue by YiChen1997** [zhiyiYo/PyQt-Fluent-Widgets#309]
**Describe the bug**
**问题描述**
PyQt6运行"examples/teaching_tip/demo.py"时"TeachingTipView.addWidget"以及”TeachingTip.make“报错

**Environment**
环境信息
- OS: Windows10
- Python: 3.9.15 64-bit
- PyQt: 6.5.1
- PyQt-Fluent-Widgets:  0.9.9
- IDE: PyCharm 2023.1.3 (Professional Edition)

**To Reproduce**
1. Go to 'examples/teaching_tip/demo.py'
2. Run function "main"
3. Scroll down to 'line 68 and 87'
4. teaching_tip的原本的import方式`from qfluentwidgets import (TeachingTipView)`会引发”Cannot find reference 'TeachingTipView' in '__init__.py' 错误，故将import方式**修改为**`from qfluentwidgets.components.widgets.teaching_tip import TeachingTipView`
5. See error
Bottom按钮对应的teaching_tip能正常显示，而top按钮和custom按钮对应的teaching_tip不显示
"AttributeError: 'TeachingTipView' object has no attribute 'addWidget'"
"AttributeError: type object 'TeachingTip' has no attribute 'make'"

**Screenshots**
![test](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/30857339/431535f0-252a-4f4a-a738-2939f2f07eb9)

错误信息：
![Snipaste_2023-06-28_00-17-20](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/30857339/37d31647-be2c-4b77-89ea-fff8abbd6bc4)

**Comment by zhiyiYo** [comment]
版本太低了，现在已经是0.9.10

**Comment by YiChen1997** [comment]
感谢🌹，已解决
