### ISSUE TITLE
Mac下对话框相关组件如果是英文语言状态则对话框的取消按钮和确定按钮高度不一致

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#311]
运行Gallery程序，当设置语言为英文时，点击示例程序中的Dialog、MessageBox、ColorDialog弹出对话框
其中cancelButton和yesButton的高度不一致，在中文语言下正常
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/047398d2-0c22-46f4-8b1f-8d609e350c8c)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/9e34dec9-4fd2-412c-ba3d-069bba2b693c)

**Comment by Cheukfung** [comment]
无法复现。环境：
python3.8.13 
pyqt5.15.9 
fluent-widget:0.10.0
macOS13.4

无论是gallery还是dialog的demo，都是正常的，你看看你有没有加了自己的样式。
<img width="1039" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/570defc5-ccb7-454b-9b4c-f8eb7f8b75dc">
<img width="824" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/31795017-fdca-49a9-b3e3-263d6c8172e9">

**Comment by zhiyiYo** [comment]
Ok

**Comment by zhiyiYo** [comment]
@qianye216 之前日期选择器没有居中对齐是不是也是因为字体的原因呀

**Comment by zhiyiYo** [comment]
🤔

**Comment by zhiyiYo** [comment]
话说 `CommandBar` 在 Mac 下会有问题吗

**Comment by zhiyiYo** [comment]
感谢
