### ISSUE TITLE
TeachingTip在点击按钮多次后重复创建建议优化

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#313]
TeachingTip的demo文件运行后点击按钮，如果重复点击按钮，会弹出多个
能否在TeachingTip未关闭的情况下且内容不变的情况下不重复创建
对比flyout组件点击弹出后再点击组件以外区域就会关闭组件，看看交互是否保持一致比较好
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/9bec6df3-4d62-4f57-b4df-9018a96cb7ef)

**Comment by zhiyiYo** [comment]
其实可以把 TeachingTip 作为一个成员变量存起来，下次点击的时候判断成员是不是 None

**Comment by zhiyiYo** [comment]
官方就是这么搞的，所以没有和flyout保持一致。不过可以手动把窗口标志改成popup

**Comment by zhiyiYo** [comment]
v0.10.1 中添加了 `PopupTeachingTip`，窗口标志和 `Flyout` 一样，点击其他位置可以直接隐藏
