### ISSUE TITLE
InfoBadge类型和位置建议优化

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#315]
新添加的InfoBadge目前主要是显示文本或者数字内容
而且好像显示的位置无法自定义显示，如果在按钮上显示，显示在左上角了，按钮上一般是右上角比较常见？
看官方的定义有圆点、图标、数字类型，并且在不同的组件显示的位置不同，如在导航栏展开状态以及收起状态等
相关参考：https://learn.microsoft.com/zh-cn/windows/apps/design/controls/info-badge
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/d94cabe8-7d3b-4965-8dad-4295528c4f7a)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/1b87c88e-c52d-4439-ba52-e01d22b575a3)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/c41260e4-6d62-49cb-a31f-dc6693f7f976)

**Comment by zhiyiYo** [comment]
下个版本可以加上这个功能

**Comment by zhiyiYo** [comment]
最新的 commit 加了这个功能，不知道在 Mac 端效果咋样？

**Comment by zhiyiYo** [comment]
试下 window 示例

**Comment by zhiyiYo** [comment]
可以帮忙看下 `SplashScreen` 和 `PillButton` 在 Mac 下是否显示正常吗？明天放假回家了，打算发布一下 1.0.0 版本

**Comment by Cheukfung** [comment]
@zhiyiYo  splash screen没问题
<img width="996" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/2b232ad5-d6b1-44b0-9e8a-de2685180dfd">
pillbutton的demo有点奇怪，会显示两个窗口
<img width="973" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/1e0f989d-b1b5-464a-bd4f-9b95bc6101f8">

**Comment by zhiyiYo** [comment]
感谢
