### ISSUE TITLE
右键菜单Action无法设置为不可用

### ISSUE THREAD

**Issue by candyfermi** [zhiyiYo/PyQt-Fluent-Widgets#316]
**Describe the bug**
如题，RoundMenu中的Action无法通过setEnabled(false)来设为不可用状态

**Environment**
环境信息
- OS: Windows10
- DPI scaling: 125%
- Python: 3.11
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: 0.10.1

**To Reproduce**
创建一个RoundMenu并将对Action调用setEnabled(false)即可发现

**Code**
最小复现代码
```python
#使用RoundMenu时会出错
        menu = RoundMenu(parent=self)

        resizeAction = Action(FluentIcon.ZOOM, self.tr("调整至合适大小"))
        resizeAction.setEnabled(False)

        menu.addAction(resizeAction)

        menu.exec(e.globalPos(), aniType=MenuAnimationType.DROP_DOWN)

#使用QMenu时显示正常
        menu = QMenu(parent=self)

        resizeAction = QAction(self.tr("调整至合适大小"))
        resizeAction.setEnabled(False)

        menu.addAction(resizeAction)

        menu.exec(e.globalPos())

```

**Comment by candyfermi** [comment]
这是预期行为(QMenu)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72252880/04842fa8-dd73-4087-a113-eda4c1c8c509)
这是bug(RoundMenu)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72252880/6c1efaa2-cc88-45ad-acce-03775ebc1d26)

**Comment by zhiyiYo** [comment]
可以把禁用动作这一行代码移动到添加动作的后面，不过禁用的样式也有点问题，下个版本会修复此问题

**Comment by candyfermi** [comment]
我看了下应该和代码顺序关系不大，虽然视觉效果上可以点击但并未触发事件，应该仅仅是样式的问题

**Comment by zhiyiYo** [comment]
移动到后面之后图标会变浅，而且菜单项也是不可点击的
![后](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/e3340ad4-f207-48c7-8c3a-ce2b35e08298)

**Comment by zhiyiYo** [comment]
已修复此问题
