### ISSUE TITLE
可能忘了做或者可能出错的地方

### ISSUE THREAD

**Issue by Adsicmes** [zhiyiYo/PyQt-Fluent-Widgets#318]
# 刚刚翻win ui3 翻到的，来看看是不是作者您忘了(

*一切都是为了该组件库能够更好，并无冒犯之意*

---

## 这是我看Win Ui3的启动画面，在现有的窗口模板类中是否可以尽早添加

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/047480d2-0d3e-47a6-9891-fbef6c9a6b8c)

---

## 针对部分控件比如各种下拉框 单选多选框 普通按钮的hyperlink

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/1fcb7fe0-8e27-45f1-be4d-0bcc684cf441)

#### 类似这种 activated下的控件应该是具有hyperlink的边的

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/e69672f8-ebf5-49b2-8df7-a2ff408addb6)

---

## Pill Button是不是忘了做

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/a7e84940-45e0-4587-88a8-749a65967330)

---

## 像这种switch button 是否应该应用针对点到点的motion而不是相对平滑的motion

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/f7bbff70-68bc-44af-a21e-2d6db8437c05)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/223459eb-fc5b-43a9-bb16-3c5a52314214)

---

## TitleBar还未实现 ，是不是忘了

design参考 https://learn.microsoft.com/zh-cn/windows/apps/design/basics/titlebar-design

至少在figma中，titlebar的样式多种多样，可以做一套模板titlebar类出来
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/d8e55c2a-b113-4244-bd2c-b1c4f6c65c66)

对了，在deactived下，窗口标题应产生颜色变化(怕您忘了)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/46bab6e4-8563-4fe0-b23f-faabcb3f9fed)

---

## Win Ui 3下的navigation里的back按钮是不是应该在titlebar里

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/17c18349-0fd3-4b92-b9cc-d7c6e8c3d211)

---

## 关于 navigation

如下图，若back按钮在不在titlebar行，应该在navigation内，那么应该对navigation应用一个深度(阴影)亦或者与titlebar混合
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/c8cba0a5-183b-4392-8c33-ed9a40d8ddf7)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/05f4cdf3-6c26-4e7c-b4f1-4a40890e0f7c)

您的gallery示例仍然存在问题
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/57f308c2-8d76-4c7b-ae59-2a3ca7d50549)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/f6cfd280-113f-437e-b84c-23da7a59bdd1)

但在我使用FluentWindow类实现后并无问题
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/10c9f778-0a27-4b1d-930c-c89bdae86152)

---

## Dialog之类的对话框窗口titlebar中icon应是可选项

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/73bed56f-f883-4756-a242-74058eccf0ef)

---

## 关于SearchLineEdit

这应该是应用比较广泛的一个控件，应该可以考虑实现
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/1a112085-639d-4703-a7c6-ef1cb462e341)

---

## 关于以下样式的Number Box

可以选择实现(
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/1f71ceb2-d53f-45f8-8956-4f94443e16ab)

---

## 浮动组件大概是应整体支持应用material
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/029ab59c-370e-46cb-854f-d9d345ccf472)

---

## 关于之前说的motion

诸如这种的，会产生颜色变化的部件，他们应该有一个变化曲线
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/79645438/1030899b-c96c-4315-8738-b8e600f706d6)

**Comment by zhiyiYo** [comment]
titlebar完全可以继承无边框窗口的titlebar来自定义，变种太多，无法一一实现

**Comment by zhiyiYo** [comment]
亚克力效果无法用于小部件上，因为无法知道底部窗口长什么样子

**Comment by zhiyiYo** [comment]
目前看来还没实现的其实就只有pillbutton和splashscreen，其他像focus效果和阴影也可有可无的

**Comment by zhiyiYo** [comment]
最新代码已添加 `SplashScreen` 和 `PillButton`

**Comment by nuthx** [comment]
草熟悉的图标，是osu大佬

**Comment by Adsicmes** [comment]
草，有osu大爹
