### ISSUE TITLE
右键菜单默认的快捷键建议增加适配Mac系统对应快捷键显示

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#319]
首先庆祝1.0.0正式版终于发布了，想要的组件基本都有了，大佬辛苦了🎉
另外发现一个小小的瑕疵，新增的菜单快捷键功能在全局文本编辑的右键菜单中默认是显示的Win下的快捷键
建议判断系统，如果是Mac系统则显示Mac下对应的快捷键
如 Win下的`CTRL+X`，对应Mac下的`⌘ X`
<img width="400" alt="115截图20230703080107" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/6271998a-bcdf-4c29-82ed-9cf1a636d3a2">
<img width="415" alt="115截图20230703080246" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/c1ddb945-72c7-498b-a5fe-4d8b24b577d5">

**Comment by zhiyiYo** [comment]
把 `qfluentwidgets/widgets/menu.py` 的第152行改成 `action.shortcut().toString(QKeySequence.NativeText)` 可以吗

**Comment by zhiyiYo** [comment]
实在不行的话只能先 split 再插入空格了

**Comment by zhiyiYo** [comment]
@qianye216 qt 自带的菜单快捷键也会有空格分隔吗

**Comment by zhiyiYo** [comment]
把示例里面的roundmenu换成qmenu应该就ok了？

**Comment by zhiyiYo** [comment]
那就没办法了

**Comment by zhiyiYo** [comment]
只能手动插入了，但是不确定有没有那种超过一个字符的键

**Comment by zhiyiYo** [comment]
对于 F1 这种快捷键没办法直接插入空格
