### ISSUE TITLE
有多级子菜单时，RoundMenu无法正常关闭所有菜单

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#32]
**Describe the bug**
有多级子菜单时，RoundMenu点击最后一一级的菜单的action时，无法正常关闭所有菜单

**Environment**
- OS: Windows11
- DPI scaling: 100%
- Python: 3.9.0
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: 0.2.8

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. 创建三级菜单
2. 点击三级菜单的QAction

**Code**
非复现代码，我在修改了RounMenu的_closeParentMenu为递归close后恢复正常
```python
    def _closeParentMenu(self):
        menu = self
        while menu.parentMenu:
            parent = menu.parentMenu
            menu.close()
            menu = parent
        menu.close()
```

**Expected behavior**
正常关闭所有菜单

**Screenshots**
![bug](https://user-images.githubusercontent.com/62167519/226622474-9b4a95b5-56c9-4645-8512-825bdce00f3f.gif)

**Comment by zhiyiYo** [comment]
感谢反馈，目前已经修复该问题了

**Comment by Cheukfung** [comment]
好奇怪，国内的pypi镜像从0.3.3就不同步了，是啥原因呢 https://pypi.tuna.tsinghua.edu.cn/simple/pyqt-fluent-widgets/

**Comment by zhiyiYo** [comment]
其他镜像有同步吗

**Comment by Cheukfung** [comment]
https://mirrors.bfsu.edu.cn/pypi/web/simple/pyqt-fluent-widgets/
https://pypi.doubanio.com/simple/pyqt-fluent-widgets/
https://mirrors.aliyun.com/pypi/simple/pyqt-fluent-widgets/
估计是同步延迟。。国内的镜像，只有阿里云更新到0.3.4了，其他的都在0.3.3，我下午用阿里云镜像更新还只是0.3.3

**Comment by zhiyiYo** [comment]
之前同步挺快的，五分钟就行了
