### ISSUE TITLE
macOS下同时出现了两套关闭按钮

### ISSUE THREAD

**Issue by nuthx** [zhiyiYo/PyQt-Fluent-Widgets#320]
<img width="1243" alt="QQ20230703-110632@2x" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/29234438/55f42abf-8a59-431b-93f5-7441d675d9b6">

如上图所示，最大化/最小化/关闭同时出现了macOS和Windows下的样式

第一次用的时候版本好像是0.92左右，那时候是没问题的。后来升级一次到了0.98还是0.99，就发现了这个问题，1.0同样存在

环境如下：macOS 13.4，PySide6 6.4.3，pyQt6 6.5.0

时间有点久，但最近好像没有升级过操作系统或者软件版本

**Comment by zhiyiYo** [comment]
@Cheukfung 你那边会这样吗？好像昨晚的截图上没有出现mac标题栏的样子

**Comment by Cheukfung** [comment]
@zhiyiYo 我的是pyqt5测试正常，晚上我试试pyside6和pyqt6

**Comment by zhiyiYo** [comment]
> @zhiyiYo 我的是pyqt5测试正常，晚上我试试pyside6和pyqt6

感谢

**Comment by Cheukfung** [comment]
@zhiyiYo 测试了一下pyqt6环境的，这个bug是上次我在frameless Window提到的issue引起的（zhiyiYo/PyQt-Frameless-Window/issues/35）。
由于新版的gallery示例的window不再直接继承Frameless window，而是FluentWindow->FluentWindowBase。FluentWindowBase中重写了paintEvnet，但是忘记执行```super().paintEvent(e)```了，最终导致__hideSystemTitleBar无法执行。pyside6应该也是同样的原因

**Comment by zhiyiYo** [comment]
pyqt5 分支已解决此问题

**Comment by zhiyiYo** [comment]
v1.0.1 修复了这个问题
