### ISSUE TITLE
点击全屏闪退

### ISSUE THREAD

**Issue by xiaowine** [zhiyiYo/PyQt-Fluent-Widgets#322]
**Describe the bug**
问题的简要描述。

**Environment**
环境信息
- OS: Windows 11 22H2
- DPI scaling: 100%
- Python:  3.11.4
- PyQt: 6.4.2
- PyQt-Fluent-Widgets: 1.0.0

**To Reproduce**
- 运行examples/gallery/demo.py,点击最大化，卡顿一下后直接关闭窗口，ide也没有任何报错

**Code**
最小复现代码
```python
# Minimum code to reproduce the error




```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
换成 python3.8 试试?
