### ISSUE TITLE
1.0.0版本的gallery demo在MacOS下系统原生控制按钮与框架的控制按钮同时存在

### ISSUE THREAD

**Issue by LittleNyima** [zhiyiYo/PyQt-Fluent-Widgets#323]
**Describe the bug**
问题的简要描述。

如题，1.0.0版本的gallery demo在MacOS下系统原生控制按钮与框架的控制按钮同时存在，在之前的版本里没有这个现象。这个应该不是框架的错误导致的，而是不知道出于什么原因，重载系统标题栏的代码在这个版本里被去掉了，所以系统的原生控制按钮也保留了下来。具体情况参见截图。

**Environment**
环境信息
- OS: MacOS 13.4.1
- DPI scaling: 100%
- Python: Python 3.8.13 [Clang 12.0.0 ] :: Anaconda, Inc. on darwin
- PySide6: 6.4.3
- PySide6-Fluent-Widgets: 1.0.0

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)

直接运行 `examples/gallery/demo.py`

**Code**
最小复现代码

```python
import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication
from qfluentwidgets import FluentWindow


class MainWindow(FluentWindow):

    def __init__(self):
        super().__init__()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)

    w = MainWindow()
    w.show()

    app.exec()
```

**Expected behavior**

应该没有左上角的控制按钮

**Screenshots**

![screenshot-0](https://i2.mjj.rip/2023/07/03/85964cea73b1f3de4e4151a73bc0ed9b.png)

![screenshot-1](https://i2.mjj.rip/2023/07/03/1a253aa3993b6771d668a66e5a6e0633.png)

**Comment by zhiyiYo** [comment]
和另一个issue重复了

**Comment by zhiyiYo** [comment]
v1.0.1 已修复此问题
