### ISSUE TITLE
Command Bar button size

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#324]
Command Bar Button Size is not automatically changed when set different properties in .setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

TransparentDropDownPushButton (Menu Button)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/e3e79257-1ac9-4138-9210-25323e122c26)

**Comment by ImmiProgramer** [comment]
create a toolButton for DropDownMenu like other ToolButtons

**Comment by zhiyiYo** [comment]
you should adjust the height of custom widget before adding it to command bar

**Comment by zhiyiYo** [comment]
Maybe I need to adjust the vertical alignment of custom widgets
