### ISSUE TITLE
Navigation Push execute function when click on it

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#325]
Function is Not Run when press button on dropdown arrow (that not show in simple Navigation-Push-Button)

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/be2c3577-d0d6-4235-9ad2-8d46bf59859c)

**Comment by zhiyiYo** [comment]
PyQt5 branch has fixed this issue
