### ISSUE TITLE
combox的筛选功能

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#329]
我想知道博主的combox有之前原先的editable功能吗（通过输入的方式筛选combox下拉框的内容）

**Comment by youjunxiaji** [comment]
就是带不全功能的输入框和combox的结合体

**Comment by zhiyiYo** [comment]
看下 examples/combo_box/demo.py，里面有补全的例子

**Comment by youjunxiaji** [comment]
> 看下 examples/combo_box/demo.py，里面有补全的例子

好像并没有
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/1d7b60db-7b5f-4551-86be-c2ae03f56c03)

**Comment by zhiyiYo** [comment]
取消掉 QCompleter 的注释

**Comment by youjunxiaji** [comment]
> 取消掉 QCompleter 的注释

ok
感谢 解决了
