### ISSUE TITLE
Bug in PopUpAniStackedWidget

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#330]
When changing the current index and finishing the animation, the widget does not correctly align in its designated position. It appears to have a top margin. However, when resizing the window, the widget adjusts to the correct position

before
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/b413f0b0-1193-47b2-acb6-10ddfdb5b3c1)

after
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/0d77e057-83df-4b3a-b373-5ecf6e100cea)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/e768d365-4835-4147-a561-af93c53566e6)

# This is My Code:

```
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton, QLabel, QStackedWidget
from qfluentwidgets import PopUpAniStackedWidget
class StackedWidgetExample(QWidget):
    def __init__(self):
        super().__init__()

        self.stacked_widget = PopUpAniStackedWidget(self)

        self.button1 = QPushButton("Page 1", self)
        self.button1.clicked.connect(self.show_page2)
        self.stacked_widget.addWidget(self.button1)

        self.label = QLabel("Page 2", self)
        self.stacked_widget.addWidget(self.label)

        self.button2 = QPushButton("Page 2", self)
        self.button2.clicked.connect(self.show_page1)
        self.stacked_widget.addWidget(self.button2)

        layout = QVBoxLayout()
        layout.addWidget(self.stacked_widget)
        self.setLayout(layout)

    def show_page1(self):
        self.stacked_widget.setCurrentIndex(0)

    def show_page2(self):
        self.stacked_widget.setCurrentIndex(2)

app = QApplication([])
window = StackedWidgetExample()
window.show()
app.exec_()
```

**Comment by ImmiProgramer** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/db7444b8-009c-43dd-a053-c90273c3b40a


https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/68c595ae-9db5-4a96-843a-9fb71e5a1660

**Comment by zhiyiYo** [comment]
There are two solutions:
1. don't use layout. Rewrite resizeEvent to control the size of stackedwidget.
2. wrap the stackedwidget like fluentwindow.

**Comment by ImmiProgramer** [comment]
I am a beginner plz tell me more details

**Comment by zhiyiYo** [comment]
Check `qfluentwidgets/window/stacked_widget.py` by yourself, I'm not a chatgpt.

**Comment by ImmiProgramer** [comment]
ok Thanks
