### ISSUE TITLE
Pyside6版本错误

### ISSUE THREAD

**Issue by Shapaper** [zhiyiYo/PyQt-Fluent-Widgets#331]
在一个新的环境中安装Pyside6-Fluent-Widgets，pyside6自动安装的版本为6.4.3而不是6.4.2。
经测试，最大化bug6.4.3中会出现。

**Comment by Shapaper** [comment]
顺便问一下，这个界面会未响应无法操作放大缩小按钮是正常的吗？
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/9cbe66b8-a7a2-48c4-92a0-c67813cb1858)

**Comment by zhiyiYo** [comment]
卸掉6.4.3重装6.4.2试试

**Comment by zhiyiYo** [comment]
SplashScreen  显示期间主线程在创建其他窗口，无法交互是正常的

**Comment by Shapaper** [comment]
不是，我的意思是是不是您的依赖写错了

**Comment by zhiyiYo** [comment]
应该是写错了，需要改成 PySide6<=6.4.2
