### ISSUE TITLE
Add New icon like *:

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#334]
Add New icon like this:
[Check it](https://learn.microsoft.com/zh-cn/windows/apps/design/controls/info-badge#:~:text=There%20are%20three%20info%20badge%20styles%20to%20choose%20from%20%2D%20dot%2C%20icon%2C%20and%20number%2C%20as%20shown%20below)

[image](https://learn.microsoft.com/zh-cn/windows/apps/design/controls/images/infobadge/infobadge-types.png)

_Originally posted by @ImmiProgramer in https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/326#issuecomment-1626888171_

**Comment by zhiyiYo** [comment]
V1.0.0 had added this icon. You can search it in the iconibterface of gallery.
