### ISSUE TITLE
关于窗体亚克力和云母效果

### ISSUE THREAD

**Issue by Shapaper** [zhiyiYo/PyQt-Fluent-Widgets#336]
在您的另一个库中，是允许窗口开启亚克力或云母效果的，但是fluent似乎没有打开的api欸（也许我没看见）
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/aa3c266d-8a2b-4f65-83bc-fb57db6c0c34)
比如这个gallery，能不能使这些区域背景设置为透明，再开启云母效果实现
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/381d7d84-fc46-45f6-a4f9-9b4f1221611d)
再比如groove播放器中，左边是允许使用亚克力的。
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/8d886fbe-f7de-43d9-8c3a-0aab3eca4d08)

**Comment by zhiyiYo** [comment]
重写一下 paintEvent 就行，然后用 windowEffect 开启，具体写法看下无边框库的 demo

**Comment by Shapaper** [comment]
知道了
话说Pyside6下，最大化窗口时，右侧滚动条很难点到欸
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/eebf0be4-9063-4222-aa17-a12bf1d56809)
鼠标放上去没有响应

**Comment by zhiyiYo** [comment]
目前无法将拖拽区域移动到窗口外部，所以会导致边缘响应效果不佳

**Comment by Shapaper** [comment]
哦

**Comment by Shapaper** [comment]
方便指出下是哪个paintEvent吗，找了半天确认不了（）
