### ISSUE TITLE
Enhancement: wordwrap in ComboBox

### ISSUE THREAD

**Issue by infizer91** [zhiyiYo/PyQt-Fluent-Widgets#338]
Hi! Amazing framework 👍 

Can you add wordwrap option in ComboBox widget for longline items and set width for items? If open app in fullscreen, part of items will be outside the screen

![wordwrap](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/22096378/5758639e-f612-44d8-8b10-c186badfe118)    
![wordwrap2](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/22096378/e0a507b8-a28a-4a06-927d-edb61cc31bad)

**Comment by zhiyiYo** [comment]
I think displaying long text in `ComboBox` is a bad idea, maybe you can use abbreviations to shorten the length of text.

**Comment by infizer91** [comment]
unfortunately, in some cases it is not possible to shorten the length of a string using abbreviations. this is one of my cases. can you embed QListView and QStringListModel into the widget? this will help solve the problem
