### ISSUE TITLE
TreeWidget交错行显示颜色错误

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#340]
**Describe the bug**
如图
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72078508/59f32b95-f556-4d95-9047-055e2b035e98)

当开启暗黑主题时TreeWidget交错行的白色显示异常
ListWidget与TableWidget无此问题

**Environment**
环境信息
- OS: win11
- DPI scaling: [e.g. 125%]
- Python: 3.10 miniconda
- pyside6:6.4.3
- PySide6-Fluent-Widgets: 1.0.1

**Comment by zhiyiYo** [comment]
headeritem 的样式没去改，需要自己按照需求定制

**Comment by zhiyiYo** [comment]
设计稿里面没给出交错样式，所以暂时不支持交错行

**Comment by abcdesteve** [comment]
是不是可以考虑一下参照ListWidget那样，毕竟能用总比不能用强，不需要考虑树状层级，只要奇偶错开就行

**Comment by abcdesteve** [comment]
现在白色完全看不见

**Comment by zhiyiYo** [comment]
可以选择不开启
