### ISSUE TITLE
125%DPI下菜单控件中部分图标显示不全

### ISSUE THREAD

**Issue by hopeful0** [zhiyiYo/PyQt-Fluent-Widgets#341]
**Describe the bug**
在125%DPI（120）的情况下，菜单RoundMenu中的部分图标会有被遮挡的情况
如Feedback图标，以及名字中带FOLDER的所有图标
这些图标在100%DPI（96）和150%DPI（144）显示正常

**Environment**
环境信息
- OS: Windows11/Manjaro
- DPI scaling: 125%
- Python: 3.10 in Windows/3.11.3 in Manjaro
- PyQt:  5.15.9
- PyQt-Fluent-Widgets: 1.0.1

**Code**
example/menu/demo.py

**Screenshots**
略微修改的example/menu/demo.py
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/13890191/adcd8bd7-7b2e-4fab-a36b-3730549765f3)

**Comment by zhiyiYo** [comment]
已修复此问题
