### ISSUE TITLE
progress_ring编译报错

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#342]
**Describe the bug**
progress_ring的代码报编译错误，drawArc函数只接受int的输入，但self.startAngle和self._spanAngle是浮点类型：
```python
Traceback (most recent call last):
  File "D:\Enviroment\miniconda3\envs\mikan\lib\site-packages\qfluentwidgets\components\widgets\progress_ring.py", line 190, in paintEvent
    painter.drawArc(rc, (startAngle % 360)*16, -self.spanAngle*16)
TypeError: arguments did not match any overloaded call:
  drawArc(self, rect: QRectF, a: int, alen: int): argument 2 has unexpected type 'float'
  drawArc(self, r: QRect, a: int, alen: int): argument 1 has unexpected type 'QRectF'
  drawArc(self, x: int, y: int, w: int, h: int, a: int, alen: int): argument 1 has unexpected type 'QRectF
```
报错对应的库中代码为：
```python
        # draw bar
        pen.setColor(themeColor())
        painter.setPen(pen)

        startAngle = -self.startAngle + 180
        painter.drawArc(rc, (startAngle % 360)*16, -self.spanAngle*16)
```
测试把`(startAngle % 360)*16`, `-self.spanAngle*16`均类型转换为`int`的话可以解决问题

**Environment**
环境信息
- OS:  Windows11
- DPI scaling: [e.g. 100%]
- Python: 3.10.12 64-bit
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: 1.0.1

**To Reproduce**
在上述环境编译运行`example/progress_ring/demo.py`

**Comment by zhiyiYo** [comment]
把第 122-138 行代码改成下面这样还会报错吗：
```python
@pyqtProperty(int)
    def startAngle(self):
        return self._startAngle

    @startAngle.setter
    def startAngle(self, angle: int):
        self._startAngle = angle
        self.update()

    @pyqtProperty(int)
    def spanAngle(self):
        return self._spanAngle

    @spanAngle.setter
    def spanAngle(self, angle: int):
        self._spanAngle = angle
        self.update()
```

**Comment by TwooSix** [comment]
> 把第 122-138 行代码改成下面这样还会报错吗：
> 
> ```python
>     @pyqtProperty(int)
>     def startAngle(self):
>         return self._startAngle
> 
>     @startAngle.setter
>     def startAngle(self, angle: int):
>         self._startAngle = angle
>         self.update()
> 
>     @pyqtProperty(int)
>     def spanAngle(self):
>         return self._spanAngle
> 
>     @spanAngle.setter
>     def spanAngle(self, angle: int):
>         self._spanAngle = angle
>         self.update()
> ```

定义成int后不会报错

**Comment by zhiyiYo** [comment]
感谢
