### ISSUE TITLE
有一个很奇怪的bug，不知道是不是因为我没写好

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#343]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/8d43d74a-21a9-4ce4-bd60-ea70a532b001)
问题如图，就是不能自动回归正常尺寸了（打开侧边栏后关闭，尺寸会变大）

**Comment by youjunxiaji** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/e1678b8a-a76c-4002-8390-c7cc1a407fa1)
当我侧边栏就留一个的时候就不会出现这个bug，留2个及以上的时候机会出现这个bug

**Comment by zhiyiYo** [comment]
不知道你现在代码中布局咋写的，建议试下 `FluentWindow` 类，`examples/clock` 演示了如何与 qtdesigner 一起使用

**Comment by youjunxiaji** [comment]
> 不知道你现在代码中布局咋写的，建议试下 `FluentWindow` 类，`examples/clock` 演示了如何与 qtdesigner 一起使用

我知道问题出在哪里了，有一个之前项目移植的，是qmainwindow的被我用作widget接进去了，导致出现了这个bug
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/0e2ca4d4-7650-42a4-b0f1-5aec1407c2ae)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/cf103496-495e-4c45-a8dd-c6aa3aee03f0)
