### ISSUE TITLE
请求兼容pyside6.5以上

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#345]
在使用nuitka打包py程序时要求使用新版pyside6，否则会导致无法使用

**Comment by zhiyiYo** [comment]
6.4.3及以上的 pyside6 无边框窗口最大化之后会超出屏幕，如果不用无边框窗口完全可以高版本 pyside6

**Comment by abcdesteve** [comment]
6.5.1.1会导致可编辑的combobox无法选择项目

**Comment by Shapaper** [comment]
> 在使用nuitka打包py程序时要求使用新版pyside6，否则会导致无法使用

.\venv\Scripts\nuitka --standalone --windows-disable-console --mingw64 --nofollow-imports --show-memory --show-progress --output-dir=.\autobuild .\main.py

**Comment by Shapaper** [comment]
6.4.2可用

**Comment by zhiyiYo** [comment]
虽然我没用过 nuitka，但是之前有用户和我说 6.4.2 也可以打包

**Comment by abcdesteve** [comment]
> 虽然我没用过 nuitka，但是之前有用户和我说 6.4.2 也可以打包

6.4.2不支持使用slot

**Comment by abcdesteve** [comment]
> 虽然我没用过 nuitka，但是之前有用户和我说 6.4.2 也可以打包

现在最主要的问题是combo box无法选择项目

**Comment by abcdesteve** [comment]
> 虽然我没用过 nuitka，但是之前有用户和我说 6.4.2 也可以打包

刚刚测试了一下，FramelessMainWindow在nuitka打包后用不了，已经向nuitka反馈了https://github.com/Nuitka/Nuitka/issues/2331

**Comment by Shapaper** [comment]
可以用啊

**Comment by Shapaper** [comment]
无论是frameless单独的还是这个fluent，都可以打包啊

**Comment by Shapaper** [comment]
甚至连云母和亚克力效果都可以打开并打包

**Comment by Shapaper** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/8f05797b-4ecf-4ad4-8171-5ca67cd022dd)
这是我打包后的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/5ee506f0-6e78-43c6-8fcb-2b960045b76d)

**Comment by Shapaper** [comment]
需要手动吧虚拟环境里面装的库的pyside6的plugin文件夹拖到打包后的pyside6文件夹内，不然运行不了

**Comment by Shapaper** [comment]
如果还不行，在main.py开头加入
```
import sys,os
import PySide6
'''
添加环境变量
'''
dirname = os.path.dirname(PySide6.__file__)
plugin_path = os.path.join(dirname, 'plugins', 'platforms')
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = plugin_path
```

**Comment by Shapaper** [comment]
用pyside6.4.2，不要用nuitka的插件打包，就用上面发的命令就行

**Comment by abcdesteve** [comment]
> ![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/8f05797b-4ecf-4ad4-8171-5ca67cd022dd)
> 这是我打包后的
> ![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/5ee506f0-6e78-43c6-8fcb-2b960045b76d)
> 
> 

我需要单文件打包喔

**Comment by Shapaper** [comment]
你改下我上面的命令，应该也行的

**Comment by Shapaper** [comment]
你改下我上面的命令，应该也行的

**Comment by abcdesteve** [comment]
> 甚至连云母和亚克力效果都可以打开并打包

另外问一下，云母是mica吗
怎么启用？

**Comment by Shapaper** [comment]
az

**Comment by Shapaper** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/08ae8e00-c4a0-49e1-bd02-5255c13042de)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/c5caade0-4651-46b9-9af2-7422d411d8b2)
frameless改成这个↑
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/88654772/580e1118-94dd-454f-8532-aa8fafaf0296)
再加这一行开启

**Comment by abcdesteve** [comment]
> 你改下我上面的命令，应该也行的

刚刚试了，不管启不启用pyside6都不行，已经添加环境变量，并复制了plugins，用的是pyside6.4.3，一运行就闪退

**Comment by AlphaLiu** [comment]
可以强制更新到PySide6.5.2的，nuitka打包后我还没发现framelesswindow有什么问题...

**Comment by abcdesteve** [comment]
> > obox无法选择项目
> 
> 刚刚发现了，使用Pyside6.5.2确实会有这个问题

你试过哪个版本可以？对nuitka有版本要求吗？

**Comment by abcdesteve** [comment]
> 可以强制更新到PySide6.5.2的，nuitka打包后我还没发现framelesswindow有什么问题...

我现在打包出来根本没有窗口
