### ISSUE TITLE
ComboBox无法添加activated()信号

### ISSUE THREAD

**Issue by Jim2742514076** [zhiyiYo/PyQt-Fluent-Widgets#347]
Traceback (most recent call last):
  File "E:\pyqt\Rainoff_predict\run.py", line 271, in <module>
    main()
  File "E:\pyqt\Rainoff_predict\run.py", line 266, in main
    window = Mainapp()
  File "E:\pyqt\Rainoff_predict\run.py", line 66, in __init__
    self.handlebutton()
  File "E:\pyqt\Rainoff_predict\run.py", line 135, in handlebutton
    self.ComboBox_2.activated.connect(self.test2)
AttributeError: 'ComboBox' object has no attribute 'activated'

**Comment by Jim2742514076** [comment]
highlighted信号也无法添加，currentIndexChanged信号可以添加但是无法正常运行

**Comment by zhiyiYo** [comment]
> highlighted信号也无法添加，currentIndexChanged信号可以添加但是无法正常运行

为啥无法正常运行，有最小代码吗

**Comment by Jim2742514076** [comment]
from PyQt5.QtGui import *
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import sys

ui, _ = loadUiType('test001.ui')

class Mainapp(QMainWindow, ui):

    signals = pyqtSignal()
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self) # 构造界面
        self.ComboBox.addItems(["a","b","c"])
        self.ComboBox.activated.connect(self.test1)

    def test1(self):
        self.LineEdit.setText(self.ComboBox.text())


def main():
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon("./icons/应用图标.ico"))
    window = Mainapp()
    window.show()
    app.exec_()


if __name__ == '__main__':
    main()


Traceback (most recent call last):
  File "E:\pyqt\Rainoff_predict\001.py", line 35, in <module>
    main()
  File "E:\pyqt\Rainoff_predict\001.py", line 29, in main
    window = Mainapp()
  File "E:\pyqt\Rainoff_predict\001.py", line 19, in __init__
    self.ComboBox.activated.connect(self.test1)
AttributeError: 'ComboBox' object has no attribute 'activated'

**Comment by Jim2742514076** [comment]
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test001.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LineEdit = LineEdit(self.centralwidget)
        self.LineEdit.setGeometry(QtCore.QRect(520, 210, 128, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.ComboBox = ComboBox(self.centralwidget)
        self.ComboBox.setGeometry(QtCore.QRect(180, 220, 76, 32))
        self.ComboBox.setObjectName("ComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from qfluentwidgets import ComboBox, LineEdit



================================================
# -*-coding = utf-8 -*-
# @Time : 2023/7/12 11:47

from PyQt5.QtGui import *
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from test001 import Ui_MainWindow
import sys


class Mainapp(QMainWindow, Ui_MainWindow):

    signals = pyqtSignal()
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self) # 构造界面
        self.ComboBox.addItems(["a","b","c"])
        self.ComboBox.activated.connect(self.test1)

    def test1(self):
        self.LineEdit.setText(self.ComboBox.text())


def main():
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon("./icons/应用图标.ico"))
    window = Mainapp()
    window.show()
    app.exec_()


if __name__ == '__main__':
    main()



=============================================
Traceback (most recent call last):
  File "E:\pyqt\Rainoff_predict\001.py", line 34, in <module>
    main()
  File "E:\pyqt\Rainoff_predict\001.py", line 28, in main
    window = Mainapp()
  File "E:\pyqt\Rainoff_predict\001.py", line 19, in __init__
    self.ComboBox.activated.connect(self.test1)
AttributeError: 'ComboBox' object has no attribute 'activated'

**Comment by Jim2742514076** [comment]
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LineEdit = LineEdit(self.centralwidget)
        self.LineEdit.setGeometry(QtCore.QRect(520, 210, 128, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.ComboBox = ComboBox(self.centralwidget)
        self.ComboBox.setGeometry(QtCore.QRect(180, 220, 76, 32))
        self.ComboBox.setObjectName("ComboBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from qfluentwidgets import ComboBox, LineEdit


===============================================================
from PyQt5.QtGui import *
from PyQt5.uic import loadUiType
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from test001 import Ui_MainWindow
import sys


class Mainapp(QMainWindow, Ui_MainWindow):

    signals = pyqtSignal()
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self) # 构造界面
        self.ComboBox.addItems(["a","b","c"])
        self.ComboBox.activated.connect(self.test1)

    def test1(self):
        self.LineEdit.setText(self.ComboBox.text())


def main():
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon("./icons/应用图标.ico"))
    window = Mainapp()
    window.show()
    app.exec_()


if __name__ == '__main__':
    main()


=======================================================
Traceback (most recent call last):
  File "E:\pyqt\Rainoff_predict\001.py", line 34, in <module>
    main()
  File "E:\pyqt\Rainoff_predict\001.py", line 28, in main
    window = Mainapp()
  File "E:\pyqt\Rainoff_predict\001.py", line 19, in __init__
    self.ComboBox.activated.connect(self.test1)
AttributeError: 'ComboBox' object has no attribute 'activated'

**Comment by Jim2742514076** [comment]
我也不知道为什么，不过替换成designer自带的combo box组件可以添加这些信号

**Comment by zhiyiYo** [comment]
`ComboBox` 是 `QPushButton`  和菜单组合而成的，建议用 `提升为..` 而不是插件，然后信号用 `currentIndexChanged` 或者 `currentTextChanged`

**Comment by Jim2742514076** [comment]
谢谢大佬
