### ISSUE TITLE
designer.py打开后没有反应

### ISSUE THREAD

**Issue by Aero80wd** [zhiyiYo/PyQt-Fluent-Widgets#348]
**Describe the bug**
designer.py打开后没有反应

**Environment**
环境信息
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.11.4 64-bit]
- PyQt: [e.g. 6.4.2]
- PyQt-Fluent-Widgets: [e.g 1.0.2]

**Code**
最小复现代码
```shell
python tools\designer.py

```

**Expected behavior**

**Screenshots**

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/98873438/a76e5a37-a4fb-460f-b969-7eb94bfea197)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/98873438/f0134909-e468-44cc-b254-89fa7b6b4e68)

**Comment by zhiyiYo** [comment]
看置顶 Issue
