### ISSUE TITLE
SegmentedWidget在deisgner插入后转py文件后不显示

### ISSUE THREAD

**Issue by ShionCox** [zhiyiYo/PyQt-Fluent-Widgets#349]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/139309562/9f48e776-0caa-41ee-8027-ccb7ef421835)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/139309562/d7524720-1502-4527-a44f-a8b84943df4f)
保存后UI转py就不见了
pyqt5的

**Comment by zhiyiYo** [comment]
需要手动调用 `addItem()` 来添加导航项
