### ISSUE TITLE
ComboBox在Item较多时，下拉列表太长，是否考虑添加 setMaxVisibleItems 函数

### ISSUE THREAD

**Issue by keymou** [zhiyiYo/PyQt-Fluent-Widgets#353]
**Describe the bug**
ComboBox在 Item 较多时，下拉列表显示长度过长，作者是否考虑添加类似 QComboBox 的 setMaxVisibleItems 功能，设置最大的可见项目数.

**Environment**
环境信息
- OS: [e.g. Windows 7]
- DPI scaling: [100%]
- Python: [3.8.6 64-bit]
- PyQt: [5.15.2]
- PyQt-Fluent-Widgets: [1.0.2]

**Comment by zhiyiYo** [comment]
之后可以加上

**Comment by ImmiProgramer** [comment]
i user this code in qfluentwidgets/components/widgets/combo_box.py/ComboBoxBase/_showComboMenu()
```

    def _showComboMenu(self):
        if not self.items:
            return

        menu = ComboBoxMenu(self)
        
        # immi
        if self.__fixedHeight:
            menu.__setFixedHeight(self.__fixedHeight)
```
and use below code in qfluentwidgets/components/widgets/combo_box.py/ComboBoxMenu

```
# create new function by immi
    def __setFixedHeight(self, h:int):
        self.view.set_fixedHeight(h)
```

# The OutPut is:
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/3a05bc3b-5812-48fb-a762-5a85cbe61ab2

**Comment by ImmiProgramer** [comment]
you can user item_size*nItems fix that issue
default item size is this in ComboBoxMenu class
self.setItemHeight(33)

**Comment by zhiyiYo** [comment]
已添加此功能
