### ISSUE TITLE
List/Table控件右键点击不更新选中行

### ISSUE THREAD

**Issue by hopeful0** [zhiyiYo/PyQt-Fluent-Widgets#356]
**Describe the bug**
List控件中的行在右键点击时，会触发`currentItemChanged`和`itemSelectionChanged`等信号，然而控件并不会更新选中行，实际上是由于`ListBase`类中的`mouseReleaseEvent`排除了右键点击的事件

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/38c0935749699751f7cf3ec70fd2c0846676da94/qfluentwidgets/components/widgets/list_view.py#L73

在Table控件中存在同样的问题

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/38c0935749699751f7cf3ec70fd2c0846676da94/qfluentwidgets/components/widgets/table_view.py#L198

由于`KeyPressEvent`中会更新选择行，这还导致了以下行为：
选中行A的状态下，右键点击行B，选中行未更新（但信号被触发，且Table控件中行B的header会被加粗表示选中），在该窗口按下任何按键，选中行更新到行B。

这是在尝试截图Table控件中header与行内容显示不一致时发现的，所以导致不方便提供截图（因为截图需要按键，然后截到的图就是正常的了）

**Environment**
环境信息
- OS: Manjaro
- DPI scaling: 125%
- Python:3.11。3
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 1.0.1

**Expected behavior**
显示状态与信号保持一致;与原生QListWidget/QTableWidget保持相似的行为

**Comment by zhiyiYo** [comment]
我记得有提供一个方法来强制更新选中行

**Comment by hopeful0** [comment]
`updateSelectRows`应该是能够强制更新的，但是在`mouseRelease`事件中排除了右键很奇怪，不知道是出于什么考虑？显式调用是可以解决问题的，但开发者通常不容易意识到这个问题，可能会产生困惑

**Comment by zhiyiYo** [comment]
这个组件的样式和交互行为参考自 Apple Music 的表格组件，它里面就是这样的。但是有些人可能希望右键后刷新选中状态，所以留着这个接口出来

**Comment by hopeful0** [comment]
这种右键后不更新，但按任意键会导致选中行变化的交互行为也很奇怪啊。归根到底是底层选中行跟显示选中行不一致导致的问题，那么有没有可能覆盖掉底层选中行变化的逻辑和信号等呢？

**Comment by ImmiProgramer** [comment]
i face a new issue
try this code

1. select a item
2. press Ctrl+Up/Down arrow key
3. notice its behaviour
```

# coding: utf-8
import sys

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QListWidgetItem, QListWidget, QWidget, QHBoxLayout, QAbstractItemView

from qfluentwidgets import ListWidget


class Demo(QWidget):

    def __init__(self):
        super().__init__()
        
        self.hBoxLayout = QHBoxLayout(self)
        self.listWidget = ListWidget(self)
        self.listWidget.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)

        stands = [
            '白金之星', '绿色法皇', "天堂制造", "绯红之王",
            '银色战车', '疯狂钻石', "壮烈成仁", "败者食尘",
            "黑蚊子多"
        ]
        for stand in stands:
            item = QListWidgetItem(stand)
            self.listWidget.addItem(item)

        self.setStyleSheet("Demo{background: rgb(249, 249, 249)} ")
        self.hBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.hBoxLayout.addWidget(self.listWidget)
        self.resize(300, 200)


if __name__ == "__main__":
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Demo()
    w.show()
    app.exec()


```

**Comment by zhiyiYo** [comment]
最新 pyqt5 分支解决了这个问题，调用 `tableView.setSelectRightClickedRow(True/False)` 可以更改交互逻辑
