### ISSUE TITLE
MSFluentWindow子页面点击按钮后如何快速切换侧边栏的其他页面

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#357]
大佬您好，目前我写了一个继承MSFluentWindow的窗口，添加了几个子页面：
当我点击第一个子页面的按钮时，弹出MessageBox，点击确定按钮后想自动切换到第二个子页面，但是目前发现比较麻烦，可能我的方法不对，如果没问题的话不知道能否优化下
目前我的方法如下：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/3a4fef85-cf12-4df2-9773-a50470f83e9b)
不知道有没有更简便的方法，如setCurrentItem方法能同时选中侧边栏以及自动切换对应页面

**Comment by zhiyiYo** [comment]
> 不知道有没有更简便的方法，如 setCurrentItem 方法能同时选中侧边栏以及自动切换对应页面

这个不太好搞，因为无法知道用户传入的 `onClick` 具体是做什么的

**Comment by zhiyiYo** [comment]
`navigationInterface.widget('XXX').clicked.emit(True)` 可以模拟点击效果，之后可以考虑加个 `click()` 接口

**Comment by zhiyiYo** [comment]
不好说，有的可能没有子界面，只是想让 item 处于选中状态
