### ISSUE TITLE
如何动态创建或更新InfoBadge

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#359]
大佬你好，我现在有个需求是点击按钮后能动态创建、更新、移除InfoBadge，但是发现没有效果，只有界面初始化的时候才会显示
不知道有没有办法支持
复现代码：
直接运行InfoBadge的demo文件，给ToolButton的点击信号连接到槽函数进行更新InfoBadge，发现没有效果
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/d3c30307-4131-41e3-bdcf-6ff6df105860)

**Comment by zhiyiYo** [comment]
`InfoBadge.success()` 会返回徽章实例，调用 `setNum` 或者 `setText` 就能更新文本

**Comment by zhiyiYo** [comment]
不能在槽函数里面创建吗？

**Comment by zhiyiYo** [comment]
需要在 `InfoBadge.make()` 的最后加上 `show()` 函数吗

**Comment by zhiyiYo** [comment]
这样也行

**Comment by zhiyiYo** [comment]
有最小代码吗，最好是单文件

**Comment by zhiyiYo** [comment]
可能是因为我加了事件过滤器导致的，在 InfoBadge 的第372行：
```python
def eventFilter(self, obj, e: QEvent):
        if obj is self.target:
            # 这两行注释掉试试
            if e.type() == QEvent.Hide:
                self.badge.hide()
            if e.type() in [QEvent.Resize, QEvent.Move]:
                self.badge.move(self.position())

        return super().eventFilter(obj, e)
```

**Comment by zhiyiYo** [comment]
好像注释了也不起作用，有点诡异😕

**Comment by zhiyiYo** [comment]
@qianye216 
把过滤器中的那两行注释掉之后，把 `showInfoBadge()` 的 parent 改成 `self.button1.parent()` 就能解决问题
