### ISSUE TITLE
PYQT5萌新，不懂就问qwq

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#36]
给窗口设置背景的时候遇到了这种情况
![image](https://user-images.githubusercontent.com/101497799/227706547-4e43fddb-5682-485f-95c7-3aba617ce654.png)
这样实现的
` self.homeInterface.setObjectName("home")  
self.homeInterface.setStyleSheet(#home{border-image:url(resource/bg/1.png);}")  `
如何让侧边选项卡也加上背景图片？怎样在侧边选项卡中使用acrylic_label？

**Comment by zhiyiYo** [comment]
你可以设置主界面的背景图片，然后把 navigationInterface 以及其他子界面背景调成透明的

**Comment by fsf678** [comment]
大佬具体说说awa

**Comment by fsf678** [comment]
大佬细说行吗，本人纯纯小萌新一枚

**Comment by zhiyiYo** [comment]
暂时没时间写示例，我还在写其他的组件

**Comment by fsf678** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOK
