### ISSUE TITLE
setTheme not applying colors.

### ISSUE THREAD

**Issue by Whitesun123** [zhiyiYo/PyQt-Fluent-Widgets#362]
**Describe the bug**
setTheme(Theme.DARK) not being applied to the FramlessWindow on Windows, but works normally on my Macbook.

**Environment**
- OS: Windows 11
- DPI scaling: 100%
- Python: 3.11.4
- PyQt: 6.5.1
- PyQt-Fluent-Widgets: 1.0.2

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)

**Code**
```python
class App(FramelessWindow):
    def __init__(self):
        super().__init__()
        setTheme(Theme.DARK)
        self.resize(400, 600)
        pixmap = QIcon("titleVG.png")
        pixmap = pixmap.pixmap(200, 200)
        imageLabel = QLabel()
        imageLabel.setPixmap(pixmap)
        imageLabel.setAlignment(Qt.AlignmentFlag.AlignHCenter)
        self.layout = QVBoxLayout(self)
        self.layout.addSpacing(20)
        self.layout.addWidget(imageLabel)
```

**Expected behavior**

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/41925432/a59af9a9-9d46-4ef9-973a-124901aae34d)

**Comment by ImmiProgramer** [comment]
Try setTheme() before calling App() class in _main_

**Comment by Whitesun123** [comment]
> Try setTheme() before calling App() class in _main_

I tried putting setTheme() between every line with no luck.

**Comment by zhiyiYo** [comment]
FramelessWindow is not a component of qfluentwidgets, and setTheme has no effect on it
