### ISSUE TITLE
conda 创建虚拟环境，但运行脚本之后无事发生，无法打开 designer.exe 程序，已确认各级文件夹目录没有含有“特殊字符”以及空格

### ISSUE THREAD

**Issue by exgbit** [zhiyiYo/PyQt-Fluent-Widgets#363]
**Describe the bug**
conda 创建虚拟环境，但运行脚本之后无事发生，无法打开 designer.exe 程序
解决方案：检查各级文件夹目录是否含有“特殊字符”以及空格。 -- 无法解决该问题

**Environment**
环境信息
Windows11
Python 3.11
PyQt6 6.3.1
PyQt6-Qt6 6.3.1
PyQt6-Fluent-Widgets[full]

**To Reproduce**
conda create -n pyq python=3.11
conda activate pyq
pip install PyQt6==6.3.1
pip install PyQt6-Qt6==6.3.1
pip install pyqt6-plugins==6.3.1.2.3
pip install "PyQt6-Fluent-Widgets[full]" -i https://pypi.org/simple/

以下是我的运行代码和全部的路径，是没有空格和特殊字符的
(pyq) D:\PyQt6\tools>python designer.py
Copy D:\anaconda3\envs\pyq\Lib\site-packages\pyqt6_plugins\Qt\plugins\designer\pyqt6.dll to D:\anaconda3\envs\pyq\Lib\site-packages\qt6_applications\Qt\plugins\designer\pyqt6.dll.

(pyq) D:\PyQt6\tools>python designer.py

**Comment by exgbit** [comment]
尝试重新创建虚拟环境，用了3.9、3.10都做了尝试，一样问题

**Comment by exgbit** [comment]
又尝试了3.10下面，安装最新版本，还是不能打开[designer.exe 程序
#363
pip install PyQt6==6.5.1
pip install pyqt6-plugins
pip install "PyQt6-Fluent-Widgets[full]" -i https://pypi.org/simple/

**Comment by exgbit** [comment]
又尝试了3.10下面
pip install PyQt6==6.3.1
pip install pyqt6-plugins==6.3.1.2.3

在不安装PyQt6-Fluent-Widgets[full]时，是可以打开designer.exe 程序的
pip install "PyQt6-Fluent-Widgets[full]" -i https://pypi.org/simple/

**Comment by exgbit** [comment]
<img width="566" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/11531273/958f243e-2b4f-4630-bbcf-49c6587cb7cd">
D:\PyQt6目录结构

**Comment by exgbit** [comment]
python 3.9
git clone https://github.com/zhiyiYo/PyQt-Fluent-Widgets.git
pip install PyQt5
pip install pyqt5-plugins
pip install "PyQt-Fluent-Widgets[full]" -i https://pypi.org/simple/

改用3.9+PyQT5，可以正常打开

**Comment by zhiyiYo** [comment]
pyqt5 和 pyqt6 效果一样，最后可以换成 pyuic6 编译 ui 文件
