### ISSUE TITLE
关于MSFluentWindow的侧边栏按钮问题

### ISSUE THREAD

**Issue by PHalfStudio** [zhiyiYo/PyQt-Fluent-Widgets#364]
大佬你好，本人有一些小问题想要请求指教。
如图所示，我的代码是这样的：
<img width="668" alt="Snipaste_2023-07-17_13-57-16" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/134825435/b1d7b1f6-8c49-49ee-a088-4b6363110182">
但是执行的时候界面是这样的：
<img width="397" alt="Snipaste_2023-07-17_13-57-54" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/134825435/04d5a90d-7947-4d1e-87ab-f3ac6dace149">
侧边并没有我添加的第三个子项。
不知道是不是我的使用方法不对，还是程序本身的问题，我更倾向于前者，因为我自身的Python特别是pyqt的水平很烂。
本人刚学习PyQt5，看了一圈API文档也没找到解决方案，请指教，谢谢。

**Comment by PHalfStudio** [comment]
> @PHalfStudio 检查下第三个页面的代码是否有问题
@qianye216 
大佬好，如果像这样尝试把第二个页面的代码注释掉，第三个界面也会正常显示，代码如下：
<img width="659" alt="Snipaste_2023-07-17_19-28-30" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/134825435/47388748-c238-40e4-9f17-da319fc5044b">

这是界面效果：
<img width="394" alt="Snipaste_2023-07-17_19-28-43" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/134825435/7ab64ee2-0064-40d4-bac1-3fa3ab0995bf">
现在问题就是无论如何侧边栏都无法显示第三个内容，我很是困扰

**Comment by zhiyiYo** [comment]
可能是对象名重复了

**Comment by PHalfStudio** [comment]
> 可能是对象名重复了

感谢大佬，确实是我的问题，显示界面正常了
