### ISSUE TITLE
add abstract RoundMenu for custom widgets

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#365]
like this:

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/ac045617-3aa6-41d5-acb7-0c918b8b7881

**Comment by ImmiProgramer** [comment]
I also face that issue

**Comment by zhiyiYo** [comment]
you can use flyout

**Comment by ImmiProgramer** [comment]
> you can use flyout. Check the example/flyout to learn how to customize flyout.

Ok
