### ISSUE TITLE
FluentWindow类的addSubInterface函数调用异常

### ISSUE THREAD

**Issue by Jim2742514076** [zhiyiYo/PyQt-Fluent-Widgets#367]
大佬您好：
我在使用FluentWindow类的addSubInterface函数调用异常的情况

**Environment**
环境信息
- OS:  Windows10
- Python:  3.9   64-bit
- PyQt: 5.15.2
- PyQt-Fluent-Widgets:  1.0.2

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
调用addSubInterface无法示例中的效果，单次只能加载一个页面

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/84441591/5c0991f8-c1de-45f0-8d45-e6f20319b2f0)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/84441591/fa027f57-3d79-4045-b1d0-108c765b8e84)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/84441591/e8f7a5e0-61ab-46aa-ae5f-c0935328d082)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/84441591/0ecbe502-2c9c-4a46-a467-649cd25c4e10)

**Code**
最小复现代码
```python
class Window(SplitFluentWindow):
    def __init__(self):
        super(SplitFluentWindow,self).__init__()
        self.create_sub()
        self.initNavigation()
    def create_sub(self):
        # create sub interface
        self.waterinf = Form_waterinf()
        self.predict = Form_predict()
        self.dispatch = Form_dispatch()
        self.decision = Form_decision()
    def initNavigation(self):
        self.addSubInterface(self.waterinf, MyFluentIcon.Waterinf, '水情分析')
        self.addSubInterface(self.predict, MyFluentIcon.Predict,"来水预报")
        self.addSubInterface(self.dispatch,MyFluentIcon.Dispatch,"水量调度")
        self.addSubInterface(self.decision, MyFluentIcon.Decision,"方案决策")

```

**Expected behavior**
希望能够实现导航栏标签的正常加载，麻烦大佬有时间帮忙看看，谢谢大佬

**Comment by zhiyiYo** [comment]
类似于 #364， 检查一下 objectName 有没有重复
