### ISSUE TITLE
button DropDownButtonBase类adjust只能调节变大

### ISSUE THREAD

**Issue by Liruochen1207** [zhiyiYo/PyQt-Fluent-Widgets#369]
在button demo中 对于同一个RoundMenu对象，DropDownPushButton与DropDownToolButton本身有一个自动调节大小的功能，
但我发现小的按钮的宽度本身很小，一开始点击展开menu框的宽度也是贴切按钮宽度的。
这时候去点击大号按钮，也会自动调整为大号宽度的menu。

但是，再回去展开小button就会发现展示框被宽度放大成了刚刚最大号的。

![屏幕截图 2023-07-18 180344](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/bd943463-a08d-461a-94b8-b4b1344ed13a)
原本尺寸

![屏幕截图 2023-07-18 180410](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/fe20c8d3-668c-4e31-8088-a78d2a138020)
d
点击大号按钮

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/0b0deeb3-9669-4b46-80e4-2ef4e0ef989e)
小按钮尺寸被放大

在某些情景该bug可能会造成使用体验不佳，比如说：需要每个按钮的下拉框大小完全贴合并且不去重复创建相同属性的RoundMenu对象 。

对此我给出了我的应对方案

![屏幕截图 2023-07-18 175921](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/83fbf402-8291-4907-94c7-6bb232b2a4d1)
上图是原本的 DropDownButtonBase类的 _showMenu方法。
我将调整大小的if判断删去，就能解决该bug

![屏幕截图 2023-07-18 180216](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/8a8a8ec7-f714-48f6-9ce5-93fc2f8d7683)
上图为修改后

虽然解决了，但是总觉得并没有彻底解决。原因是我不太了解原先的写的判断语句
if menu.view.width() < self.width():
到底是为了什么情景才添加上去的，显而易见直接删除会导致此情景失效

**Comment by zhiyiYo** [comment]
菜单宽度不能小于按钮，不然看起来很奇怪

**Comment by Liruochen1207** [comment]
> 菜单宽度不能小于按钮，不然看起来很奇怪

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/d2c40866-e707-4a3a-ab27-127396ecd9e9)
我这边修改后并不影响呢

**Comment by Liruochen1207** [comment]
我收回刚刚那句话，点击长框后，短框会出显示bug
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/53438791-8fa3-4733-a7c2-ca81745adbae)

**Comment by Liruochen1207** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/18d82291-68bf-40ab-a849-880d53e6526f)
这样写就不会有显示bug了

**Comment by Liruochen1207** [comment]
添加了一个menu.view.adjustSize()

**Comment by Liruochen1207** [comment]
虽然不明显了，但是还是有细微的误差，不知道是哪里造成的。我再研究研究

**Comment by Liruochen1207** [comment]
SplitWidgetBase我也做了相似修改，误差消失了
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74223784/bcee5062-a3e2-493e-874e-ae92077f837a)

**Comment by zhiyiYo** [comment]
感谢帮忙打的补丁，最近忙着另一个组件库，暂时抽不出时间维护这个项目，之后会集中处理的

**Comment by Liruochen1207** [comment]
加油，罗马不是一天建成的，所以不着急

**Comment by zhiyiYo** [comment]
已修复此问题
