### ISSUE TITLE
mac下lineEdit有额外的focus框

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#37]
大佬牛逼，button lineedit等各个组件都添加了，早知道我就不对着winui3的设计稿自己写qss了。。。
这个bug我好早前就遇到过了，mac下有个特性，会给编辑框强行加个focus框，需要添加
`QLineEdit.setAttribute(QtCore.Qt.WA_MacShowFocusRect, 0)`
才可以消除。你还在写其他组件，我就不提pr了

<img width="536" alt="iShot_2023-03-25_22 10 16" src="https://user-images.githubusercontent.com/14865236/227722615-47826bc7-4f0a-4ffc-9224-0a6cd1e94dbd.png">
<img width="536" alt="iShot_2023-03-25_22 10 50" src="https://user-images.githubusercontent.com/14865236/227722623-f147e570-b806-4f1d-a839-417018c7caee.png">

**Comment by zhiyiYo** [comment]
感谢反馈，我这里自己加吧

**Comment by Cheukfung** [comment]
lineEdit都有了，textEdit也加一下呗😊

**Comment by zhiyiYo** [comment]
lineEdit 的底部边框样式还是有点问题，我用 paintEvent 也画不出 Win11 上面的效果，你有什么想法吗

**Comment by Cheukfung** [comment]
确实，lineEdit有焦点的时候，下边框应该是2px，如果qss设置2px的下边框，圆角的地方会很奇怪。
我之前试过在button实现这样的套娃。。
就是带有背景颜色（这个颜色就是下边框的颜色）的QFrame，给QFrame一个QHBoxlayout，包含一个lineEdit，layout的下边距是1px（未点击的，这时候就是深灰色1px）。获取输入焦点时，Qframe的layout的下边距设置为2px，把linEdit两个下圆角取消，QFrame颜色改变为focus的颜色，这样效果就差不多了
<img width="594" alt="image" src="https://user-images.githubusercontent.com/14865236/227724185-5c822f57-6ae8-4240-a0a2-76532643e45c.png">

**Comment by zhiyiYo** [comment]
但是这样做的话还得对 QFrame 的子类加上 QLineEdit 的方法，有点麻烦

**Comment by Cheukfung** [comment]
补一张图，感觉这样很奇葩。。子类要重写方法
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/14865236/227724446-eb53919f-6018-4e79-9146-811b881299c6.png">

**Comment by Cheukfung** [comment]
> 但是这样做的话还得对 QFrame 的子类加上 QLineEdit 的方法，有点麻烦

是的。。我后面放弃了，直接用了1px的下边框算了

**Comment by zhiyiYo** [comment]
也许可以在 QLineEdit 里面加布局

**Comment by Cheukfung** [comment]
你可以试试，我的能力止步于此了。。

**Comment by Cheukfung** [comment]
你可以试试，我的能力止步于此了。。

**Comment by Ephemeralwanning** [comment]
想问问楼主，大大给的控件应该只能手撸布局才能用吧，楼主也是手写的吗

**Comment by zhiyiYo** [comment]
是手写的布局，QtDesigner 我不会用

**Comment by Ephemeralwanning** [comment]
> 是手写的布局，QtDesigner 我不会用

只会用一点点qt designer，手写对我来说有点困难，努力学习中ing...

**Comment by zhiyiYo** [comment]
多写写就熟练了

**Comment by Cheukfung** [comment]
@Ephemeralwanning  可以在qtdesigner用的，比如lineEdit，你在qtdesigner正常添加LineEdit控件，然后右键，把它提升为 LineEdit （作者写的组建名），头文件就写 qfluentwidgets .这样你的ui文件生成py文件的时候，会自动import这个组件

**Comment by Ephemeralwanning** [comment]
> @Ephemeralwanning 可以在qtdesigner用的，比如lineEdit，你在qtdesigner正常添加LineEdit控件，然后右键，把它提升为 LineEdit （作者写的组建名），头文件就写 qfluentwidgets .这样你的ui文件生成py文件的时候，会自动import这个组件

原来还能这样使用，感谢回复，改天研究一下

**Comment by zhiyiYo** [comment]
@Cheukfung @Ephemeralwanning 
我刚刚写了一个 gallery 界面，可以帮我测试一下吗，代码放在了 `examples/gallery` 文件夹下

**Comment by Ephemeralwanning** [comment]
大大现在更新太频繁了，刚刚被坤坤的歌吓坏了，我等他发布新版本后再研究吧

**Comment by zhiyiYo** [comment]
新包已经发布了

**Comment by Ephemeralwanning** [comment]
> @Cheukfung @Ephemeralwanning 我刚刚写了一个 gallery 界面，可以帮我测试一下吗，代码放在了 `examples/gallery` 文件夹下

需要测试什么吗 我只知道能正确运行

貌似带有动画的流式布局只有第一次切换有动画，继续切换导航栏就没动画效果了

**Comment by zhiyiYo** [comment]
只要能正确运行就ok了

**Comment by Cheukfung** [comment]
很强，测试了下各个组件都没问题

**Comment by zhiyiYo** [comment]
@Cheukfung 
刚才用 `QPainterPath` 画了底部边框，看起来和 WinUI3 的效果差不多
![image](https://user-images.githubusercontent.com/65096819/229327697-7e08e614-e751-46c9-8b5c-b082b093d74a.png)

**Comment by Cheukfung** [comment]
很强，可以说一样了

**Comment by Cheukfung** [comment]
总觉得lineEdit的focus下边框太粗了，截图一看发现有3个像素，是因为抗锯齿的原因吗？
![image](https://user-images.githubusercontent.com/14865236/230242257-1087c7ea-451a-48b0-9280-ab76c14a399f.png)
![image](https://user-images.githubusercontent.com/14865236/230242496-5ebdd721-1011-4d4d-99da-1447e6ab5e41.png)

**Comment by zhiyiYo** [comment]
2px 有点难看，还是会有一部分圆弧露出来

**Comment by zhiyiYo** [comment]
@Cheukfung 
目前 qss 里面的圆角半径为6px，但是我看 figma 里面才 3px，实际用ps量出来应该是4px

**Comment by Cheukfung** [comment]
3px的是边框内圆角吧
