### ISSUE TITLE
[help wanted]子页面怎么利用左上角的返回键进行返回？

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#371]
fluentwindow里的route似乎只能针对左侧导航栏内的主页面进行返回，如果一些子级页面也想展示在主体窗口上，并利用左上角的返回按钮进行返回的话，应该怎么写比较好？看了一下FluentWindow和Router的代码感觉摸不着头脑，想来问一下。

**Comment by zhiyiYo** [comment]
`examples/gallery/app/view/navigation_view_interface.py` 里面展示了添加二级子界面的方法，核心代码都和 `qrouter` 有关
