### ISSUE TITLE
建议给HyperlinkButton增加setIcon方法

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#372]
目前HyperlinkButton无法设置图标，有时候确实需要显示图标，希望大佬考虑下
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/296aa058-3c88-43ca-aa45-dff001d51238)

**Comment by zhiyiYo** [comment]
下一个版本可以加上
