### ISSUE TITLE
Dialog.setTitleBarVisible会导致窗口不是圆角

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#374]
**Describe the bug**
问题的简要描述。
当设置为True时，窗口正常显示为圆角，但圆角曲率明显比MessageBox偏小
当设置为False时，则完全为直角

**Environment**
环境信息
- OS: win11 x86_64
- DPI scaling: [e.g. 125%]
- Python: 3.10
- PyQt-Fluent-Widgets: 1.0.1

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
Dialog.setTitleBarVisible(False)

```

**Screenshots**

**Comment by zhiyiYo** [comment]
我这里还是圆角，无边框对话框的圆角大小取决于操作系统，`MessageBox` 的圆角是 qss 设置的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/d2677f09-b487-4c6e-8cb3-df3ebd326252)

**Comment by tom9672** [comment]
MessageBox 我是圆角，主窗口我这边显示直角。
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54530491/1db65a0d-9b8e-48a5-8143-c4951e19b8af)
