### ISSUE TITLE
ComboBox如何在选择项目的时候调用函数

### ISSUE THREAD

**Issue by mstouk57g** [zhiyiYo/PyQt-Fluent-Widgets#375]
你好大佬，我是一个pyqt小白
ComboBox似乎没法像Qcombobox一样用activated信号
我看到您的示例上`self.comboBox.currentTextChanged.connect(print)`使选择的过程中输出选择的项目
那么我怎么做才能做到将这个选项的text传到另一个字符串呢?

**Comment by zhiyiYo** [comment]
把print换成自己的槽函数就行了

**Comment by mstouk57g** [comment]
那大佬，这是什么错误
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65524880/ac649d0e-6b0a-4902-bfda-5e7bd4cb197a)
`       self.comboBox = ComboBox(self)
        items = ["请选择版本","1.19.4"]
        self.comboBox.addItems(items)
        self.comboBox.setCurrentIndex(0)
        self.comboBox.currentTextChanged.connect(sp)
        #self.comboBox.move(200, 200)
        self.hBoxLayout.addWidget(self.comboBox) 

        def sp(value):
            print(value) #仅调试
            return value`

**Comment by zhiyiYo** [comment]
改成 `self.sp`

**Comment by zhiyiYo** [comment]
建立掌握一些 pyqt 基础只是后再来用这个库
