### ISSUE TITLE
menu icons messed up in 125DPI

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#377]
**Describe the bug**
问题的简要描述。

**Environment**
环境信息
- OS: [e.g. Windows11]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.11.0 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.1.0]

**Expected behavior**
menu icons messed up

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/9d6ab094-6fa0-4536-bed7-cd70d28d8434)

**Comment by zhiyiYo** [comment]
dulplicated with #341
