### ISSUE TITLE
运行时切换主题Label中文字颜色不切换

### ISSUE THREAD

**Issue by ruixiaotian** [zhiyiYo/PyQt-Fluent-Widgets#378]
设置了一个按钮，点击时会切换主题（白色和黑色的切换），使用过程中发现了这个问题，我不知道如何解决，麻烦大大帮我看下

使用的是StrongBodyLabel,换了TitleLabel和SubtitleLabel也会不能解决,以下是切换功能的槽函数

```python
@staticmethod
def switchThemes():
    setTheme(Theme.LIGHT) if isDarkTheme() else setTheme(Theme.DARK)
```

默认是白色主题,切换后这几个StrongBodyLabel颜色依旧是黑色,这几个卡片都是使用CardWidget实现的
![image](https://github.com/zhiyiYo/PyQt-Frameless-Window/assets/78299308/e08808b9-2316-4bc4-83c3-933882b37cf0)

**Comment by ruixiaotian** [comment]
没有设置其他样式，谢谢解答！

**Comment by HainanWinter-l** [comment]
> 实在解决不了的话就在父级样式表里面设置一下标签颜色，写法见文档 https://pyqt-fluent-widgets.readthedocs.io/en/latest/theme.html
您好，请问能否给出一个实例代码参考一下呢
