### ISSUE TITLE
CalendarPicker doesn't supported scroll wheel to scroll months (like windows 11 Calendar in taskbar)

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#383]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/5e2dfdda-a1fd-4ecb-92c4-87bee0c31838

#And also add animation when click on year button

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/40cb22c8-f227-49e6-804d-9282091737b5)
watch the video again to see animation

**Comment by zhiyiYo** [comment]
写不出来
