### ISSUE TITLE
TreeView控件如何在选择Item的时候调用函数

### ISSUE THREAD

**Issue by mstouk57g** [zhiyiYo/PyQt-Fluent-Widgets#386]
不懂就问：TreeView控件如何在选择Item的时候调用函数，并且把选择的行数传递到所调用函数的参数里
文档上没有找到相关的

**Comment by keymou** [comment]
> 不懂就问：TreeView控件如何在选择Item的时候调用函数，并且把选择的行数传递到所调用函数的参数里 文档上没有找到相关的

可以通过`itemClicked`来传入所选择的Item
简单示例：
```
self.treeWidget = TreeWidget()
self.treeWidget.itemClicked.connect(self.show_detail)

def show_detail(self, item):
    pass
```

**Comment by zhiyiYo** [comment]
这些和组件库没有关系的问题请右转 Chatgpt 或者谷歌
