### ISSUE TITLE
关于这套插件打包成可执行程序

### ISSUE THREAD

**Issue by TcDhlPro** [zhiyiYo/PyQt-Fluent-Widgets#389]
**Describe the bug**
**打包是打包成了, 运行也没问题, 插件也显示
问题在于, 不知道是作者的插件还是其他地方, 肯定会指向本机python环境中的PyQt5这个目录
我想解决是, 在什么地方修改指向本机Python环境的?, 能解决这个, 就应该可以把这套插件独立出来**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/100897011/caf0cc9d-3ae9-41da-8cc9-65243539cc1a)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/100897011/25c7ed52-b9cb-4054-b7b8-deee3c623e7f)

**Environment**
环境信息
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 100%]
- Python: [e.g. 3.10.10 64-bit]
- PyQt5: [e.g. 5.15.9]
- PyQt-Fluent-Widgets: [e.g 1.0.2]
- PyQt5-Frameless-Window 0.2.8
- pyqt5-plugins          5.15.9.2.3
- PyQt5-Qt5              5.15.2
- PyQt5-sip              12.12.2
- pyqt5-tools            5.15.9.3.3
- qt5-applications       5.15.2.2.3
- qt5-tools              5.15.2.1.3

**Code**
为了打包, 修改了`designer.py`文件
```python
# coding: utf-8
#from distutils.sysconfig import get_python_lib
import os
import sys
import shutil
import warnings

from pathlib import Path

#import PyQt5
from PyQt5.QtCore import QProcessEnvironment, QProcess
from Extend_Plugins.plugins.basic_input_plugin import BasicInputPlugin


def get_designer_path():
    """ get the path of qt designer """
    #site_packages = get_python_lib()

    #if sys.platform == "win32":
    #    designer_name = "designer.exe"
    #elif sys.platform == "darwin":
    #    designer_name = "designer.app"
    #else:
    #    designer_name = "designer"
    designer_name = "designer.exe"

    #path = Path(f"{site_packages}/qt5_applications/Qt/bin/{designer_name}")
    #path = f"{Path(__file__).parent}/qt5_applications/Qt/bin/{designer_name}"
    path = Path(__file__).parent.joinpath("qt5_applications", "Qt", "bin", designer_name)
    print(path)
    if not path.exists():
        raise Exception(
            "Can't find available QtDesigner for current environment. You can try `pip install pyqt5-tools` to solve this problem.")

    # check pyqt5 dll
    if sys.platform == "win32":
        dll_name = "pyqt5.dll"
    elif sys.platform == "darwin":
        dll_name = "libpyqt5.dylib"
    else:
        dll_name = "libpyqt5.so"

    #dll_path = Path(f"{site_packages}/qt5_applications/Qt/plugins/designer/{dll_name}")
    dll_path = Path(__file__).parent.joinpath("qt5_applications", "Qt", "plugins", "designer", dll_name)
    print(dll_path)
    if dll_path.exists():
        return str(path)

    #plugin_dll_path = Path(f"{site_packages}/pyqt5_plugins/Qt/plugins/designer/{dll_name}")
    plugin_dll_path = Path(__file__).parent.joinpath("pyqt5_plugins", "Qt", "plugins", "designer", dll_name)
    print('Copy',plugin_dll_path)
    if not plugin_dll_path.exists():
        warnings.warn(f"Can't find avaliable {dll_name}, which may cause PyQt-Fluent-Widgets not being visible in QtDesigner.")
        return str(path)

    # copy pyqt5 dll
    dll_path.parent.mkdir(exist_ok=True, parents=True)
    shutil.copy(plugin_dll_path, dll_path)
    print(f'Copy {plugin_dll_path} to {dll_path}.')

    return str(path)


tools_dir = Path(__file__).absolute().parent#当前脚本所在目录
project_dir = tools_dir.parent#返回当前脚本所在目录的上一级

# set up environment variables
env = QProcessEnvironment.systemEnvironment()
#PATH = f"{os.path.dirname(PyQt5.__file__)};{sys.prefix};{env.value('PATH', '')}"
Path_PyQt5 = Path(__file__).parent.joinpath("Extend_Python310","Lib","site-packages","PyQt5")
Path_Python = Path(__file__).parent.joinpath("Extend_Python310")
PATH = f"{Path_PyQt5};{Path_Python}"#需要第一,第二个参数
print(PATH)
#print(os.path.dirname(PyQt5.__file__))
#print(sys.prefix)


env.insert('PATH', PATH)
env.insert('PYQTDESIGNERPATH', str(tools_dir / 'Extend_Plugins/plugins'))
env.insert('PYTHONPATH', str(project_dir))

#print(f"PATH: {env.value('PATH')}")
#print(f"PYQTDESIGNERPATH: {env.value('PYQTDESIGNERPATH')}")
#print(f"PYTHONPATH: {env.value('PYTHONPATH')}")

#@检查是否是MacOS系统
if sys.platform == "darwin":
    env.insert('DYLD_LIBRARY_PATH', get_python_lib() + "/../..")

# launch QtDesigner
designer = QProcess()
designer.setProcessEnvironment(env)

designer.start(get_designer_path(), [])
designer.waitForFinished(-1)
sys.exit(designer.exitCode())
```

**Comment by zhiyiYo** [comment]
打包后的结果可以分享一下不

**Comment by TcDhlPro** [comment]
> 

可以, 压缩包有点大, 我想想咋个发给你

**Comment by TcDhlPro** [comment]
> 打包后的结果可以分享一下不，我在本机测试康康

下载地址: https://wormhole.app/vOz14#EnWaGzaE0PxWkPXMFHlvVA

**Comment by zhiyiYo** [comment]
文件被删了，或许可以放在阿里云盘上？

**Comment by TcDhlPro** [comment]
> 文件被删了，或许可以放在阿里云盘上？

https://www.aliyundrive.com/t/gNmUJGkLWnMRxxm0BJVg

**Comment by zhiyiYo** [comment]
感觉你的 project_dir 有点问题

**Comment by zhiyiYo** [comment]
`env.insert('PYTHONPATH', str(project_dir))` 的作用是指出 `qfluentwidgets` 所在目录，如果打包的时候是和 designer.py 一起打包了，可能应该改成 `str(tool_dir)`

**Comment by TcDhlPro** [comment]
> `env.insert('PYTHONPATH', str(project_dir))` 的作用是指出 `qfluentwidgets` 所在目录，如果打包的时候是和 designer.py 一起打包了，可能应该改成 `str(tool_dir)`

我要等空的时候再好好试一试

**Comment by WJJ1031338633** [comment]
同问打包问题：


虚拟环境：
Package                Version
---------------------- -------
colorthief             0.2.1
darkdetect             0.8.0
et-xmlfile             1.1.0
markdown2              2.4.10
numpy                  1.25.2
openpyxl               3.1.2
pandas                 2.0.3
Pillow                 10.0.0
pip                    23.2.1
PyQt-Fluent-Widgets    1.0.4
PyQt5                  5.15.9
PyQt5-Frameless-Window 0.2.9
PyQt5-Qt5              5.15.2
PyQt5-sip              12.12.2
python-dateutil        2.8.2
pytz                   2023.3
pywin32                306
scipy                  1.11.1
setuptools             68.0.0
six                    1.16.0
tzdata                 2023.3
wheel                  0.40.0

运行结果：
仍然找不到'qfluentwidgets'，问题是我调试时候都是正常的。
打包时也在虚拟环境下打包的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54835553/c53200bc-5843-48c0-8499-f4c41aa0f18d)

**Comment by zhiyiYo** [comment]
目前我使用 python3.11 成功打包了含有插件的 QtDesigner

**Comment by zhiyiYo** [comment]
可在发行页面下载 FluentDesigner压缩包，运行designer/designer.exe即可
