### ISSUE TITLE
navigation头像组件的建议

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#39]
demo里面的AvatarWidget的构造函数建议加个文字和图像的参数，改成如果没有传入头像，就把传入的字符串首字画到头像框里面，比如这样
![image](https://user-images.githubusercontent.com/14865236/227824818-9b2a7b0a-5811-40e5-8318-7029f8381177.png)

**Comment by zhiyiYo** [comment]
可以提个 PR 吗
