### ISSUE TITLE
TextWrap换行BUG

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#390]
**Describe the bug**
使用TextWrap对以下文本换行时，在末尾链接处反复生成了过多的换行符
原文本：
`
『ドラえもん』は、藤子・F・不二雄の漫画作品『ドラえもん』を原作とするテレビアニメである。\r\n『ドラえもん』のテレビアニメには以下の3作品が存在する。\r\n1973年に日本テレビ系列局で放送されたシリーズ\r\n1979年から2005年3月まで放送されたシリーズ\r\n2005年4月より放送中のシリーズ\r\nこれらを区別する呼称は公式には発表されていない[1]。一方、アニメ誌では2005年4月より放送中のシリーズを『ドラえもん（新・第2期）』としている。ウィキペディアではそれにならい、1973年に放送されたシリーズを第1作、1979年より放送されているシリーズをまとめて第2作とする。また第2作において、1979年から2005年3月まで放送されたシリーズを第1期、2005年4月より放送中のシリーズを第2期とする。\r\nvia http://ja.wikipedia.org/wiki/%E3%83%89%E3%83%A9%E3%81%88%E3%82%82%E3%82%93_(2005%E5%B9%B4%E3%81%AE%E3%83%86%E3%83%AC%E3%83%93%E3%82%A2%E3%83%8B%E3%83%A1)
`
换行后文本：
`
『ドラえもん』は、藤子・F・不二雄の漫画作品『ドラえもん』を原作とするテレビアニメである。\r\n『ドラえもん』のテレビアニメには以下の3作品が存在する。\r\n1973年に日本テレビ系列局で放送されたシリーズ\r\n1979年から2005年3月まで放送されたシリーズ\r\n2005年4月より放送中のシリーズ\r\nこれらを区別する呼称は公式には発表されていない[1]。一方、アニメ誌では2005年4月より放送中の\nシリーズを『ドラえもん（新・第2期）』としている。ウィキペディアではそれにならい、1973年に\n放送されたシリーズを第1作、1979年より放送されているシリーズをまとめて第2作とする。また第2\n作において、1979年から2005年3月まで放送されたシリーズを第1期、2005年4月より放送中のシリー\nズを第2期とする。\r\nvia\nhttp://ja.wikipedia.org/wiki/%E3%83%89%E3%83%A9%E3%81%88%E3%82%82%E3%82%93_(2005%E5%B9%B4%\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nE3%81%AE%E3%83%86%E3%83%AC%E3%83%93%E3%82%A2%E3%83%8B%E3%83%A1)
`

**Environment**
环境信息
- PyQt-Fluent-Widgets: 1.0.1

**Code**
最小复现代码
```python
from qfluentwidgets import TextWrap
print(TextWrap.wrap("『ドラえもん』は、藤子・F・不二雄の漫画作品『ドラえもん』を原作とするテレビアニメである。\r\n『ドラえもん』のテレビアニメには以下の3作品が存在する。\r\n1973年に日本テレビ系列局で放送されたシリーズ\r\n1979年から2005年3月まで放送されたシリーズ\r\n2005年4月より放送中のシリーズ\r\nこれらを区別する呼称は公式には発表されていない[1]。一方、アニメ誌では2005年4月より放送中のシリーズを『ドラえもん（新・第2期）』としている。ウィキペディアではそれにならい、1973年に放送されたシリーズを第1作、1979年より放送されているシリーズをまとめて第2作とする。また第2作において、1979年から2005年3月まで放送されたシリーズを第1期、2005年4月より放送中のシリーズを第2期とする。\r\nvia http://ja.wikipedia.org/wiki/%E3%83%89%E3%83%A9%E3%81%88%E3%82%82%E3%82%93_(2005%E5%B9%B4%E3%81%AE%E3%83%86%E3%83%AC%E3%83%93%E3%82%A2%E3%83%8B%E3%83%A1)", 90, False)[0])
```

**Comment by zhiyiYo** [comment]
url 需要使用 `urllib.parse.unquote` 进行解码
