### ISSUE TITLE
EditableComboBox ClearButton bug

### ISSUE THREAD

**Issue by CheshireCC** [zhiyiYo/PyQt-Fluent-Widgets#392]
在启用了 EditableComboBox  组件的 ClearButton 之后，如果点击 ClearButton  ，不仅文本框里的内容被清空，下拉列表也不再显示了，此时单击下拉按钮，无条目显示，但是如果设置过 Completer 那么检索仍然生效。

环境信息
- OS:  Windows11]
- Python: [3.8.17 64-bit Conda]
- PySide6 6.4.3

复现问题

![issue](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/36411617/5e4d21ad-4224-4072-86e6-9cbbfa810ed6)

修复这个问题也很容易

```
# self.combox_language 是 EditableComboBox  的实例对象
self.combox_language.clearButton.clicked.disconnect(self.combox_language.clear)
self.combox_language.clearButton.clicked.connect(lambda : self.combox_language.setText(""))
```

也就是说将控件的 `click` 信号与 `clear() ` 函数的链接断开，自己重设该信号的 `Slot`，
我认为该控件的 `clear` 方法应当重写

根据目前源代码，该控件的 `clear` 方法是继承自父类，`LineEdit` 的 `clear` 方法，
但是 `LineEdit` 的 `clear` 方法为什么会将 `comboBox` 的条目清空呢？
这是一个 bug 吗？
期待修复

**Comment by zhiyiYo** [comment]
应该是 `ComboBoxBase.clear()`  覆盖了 `LineEdit.clear()` 导致的
