### ISSUE TITLE
[gallery_interface.py]这个模块的具体作用是什么

### ISSUE THREAD

**Issue by cxjnevergiveup** [zhiyiYo/PyQt-Fluent-Widgets#393]
[gallery_interface.py](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/PyQt5/examples/gallery/app/view/gallery_interface.py)

请问view中的各个导航的子界面的布局都看到了，这个gallery_interface.py是起到什么作用？好像导航栏没有这一项
 谢谢~

**Comment by zhiyiYo** [comment]
基类界面，提供了工具栏和添加示例卡片的方法
