### ISSUE TITLE
TableWidget使用setCellWidget添加多个LineEdit，之后鼠标在多个LineEdit移动时，可编辑状态会自动切换，如何取消？

### ISSUE THREAD

**Issue by xiyangz** [zhiyiYo/PyQt-Fluent-Widgets#395]

**Comment by xiyangz** [comment]
是table_view.qss中包含QTableView indicator hover导致，删除就没问题了

**Comment by xiyangz** [comment]
将 self.setMouseTracking(True)注释并且table_view.qss中关于hover相关的删除，就没有出现这个问题了，但这样解决有点奇怪。

**Comment by ImmiProgramer** [comment]
give me minimum code
and try customStyledItemdeleget (more details in tableView example)
