### ISSUE TITLE
在Infobar弹出时关闭主窗口，自定义隐藏窗口的closeEvent失效变成关闭程序

### ISSUE THREAD

**Issue by Ianzb** [zhiyiYo/PyQt-Fluent-Widgets#397]
python3.11.4+PyQt5最新版本
如何复现：
在仓库example里面的info_bar，给主窗口加一个
def closeEvent(self, QCloseEvent):
    QCloseEvent.ignore()
    self.hide()
之后运行程序，点任意按钮，等一小会，在infobar消失之前点关闭按钮，发现程序没有隐藏而是终止运行。等待弹窗消失后再点关闭按钮，窗口隐藏，程序没有退出
![屏幕截图 2023-07-30 202254](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101161232/0a7a6d74-95f1-4ca0-8bab-365f66409faa)

**Comment by zhiyiYo** [comment]
没有报错信息，怀疑是事件过滤器的问题，#273
