### ISSUE TITLE
当按钮文本太长时，文本前会有空白部分

### ISSUE THREAD

**Issue by 1604042736** [zhiyiYo/PyQt-Fluent-Widgets#398]
![Snipaste_2023-07-31_08-38-56](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/61647477/eb270eb6-0afa-43c5-a8bd-af22b4ec1edc)
![Snipaste_2023-07-31_08-39-11](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/61647477/01729c0b-c6cb-412a-bd35-8e28eef2293b)
用的是TransparentTogglePushButton
QPushButton则不会出现这种状况

**Comment by zhiyiYo** [comment]
看起来像是设置了空图标才会这样
