### ISSUE TITLE
ComBox下拉框的几个bug，望修复

### ISSUE THREAD

**Issue by sys98** [zhiyiYo/PyQt-Fluent-Widgets#399]
Describe the bug
**1、ComboBox在初始化添加元素时，无法默认显示列表第一个元素**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/fb3c2038-8383-451a-a99d-be4d0304948d)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/1b74b869-e7ca-4095-b00e-145414492c6f)

2、ComboBox在setCurrentIndex无法触发currentTextChanged信号，currentIndexChanged也一样。
如下图，图二为初始化设置下拉项后   控制台无输出，图三为下列选择后控制台的输出
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/98d2cd69-6e6f-452d-8018-c3469d375eca)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/e132168a-79da-44ff-b26f-8078f4730530)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/53f5a78b-2ae1-4d1b-8f02-f4c6b3b91cc3)

Environment
环境信息

OS: [e.g. Windows 7]
DPI scaling: [100%]
Python: [3.8.6 64-bit]
PyQt: [5.15.2]
PyQt-Fluent-Widgets: [1.0.2]

**Comment by zhiyiYo** [comment]
需要把 `self.comboBox.currentTextChanged.connect(print)` 放在 `setCurrentIndex` 前面才行

**Comment by zhiyiYo** [comment]
第一个问题已修复

**Comment by sys98** [comment]
> 需要把 放在 前面才行`self.comboBox.currentTextChanged.connect(print)``setCurrentIndex`

这个问题似乎没有修复，把connect放在前面也是一样在默认的情况下不会有触发

**Comment by sys98** [comment]
> 第一个问题已修复

第一个问题似乎在最新版还是不行

> > 需要把 放在 前面才行`` self.comboBox.currentTextChanged.connect(print)``setCurrentIndex ``
> 
> 这个问题似乎没有修复，把connect放在前面也是一样在默认的情况下不会有触发

不过这里我对比的是官方的QComboBox，官方这个下拉框控件在建立信号连接后，最开始的addItems也可以触发槽函数

**Comment by liwind** [comment]
第二个问题还是没有修复，setCurrentIndex无法触发currentIndexChanged信号
