### ISSUE TITLE
是否能增加这个效果

### ISSUE THREAD

**Issue by xianyongjian080402** [zhiyiYo/PyQt-Fluent-Widgets#4]
（看视频）

https://user-images.githubusercontent.com/70191815/212612262-aa29ed4f-618a-4b79-95e3-e50ea9c60098.mov

就是……我也想实现一个这样的背景特效

**Comment by xianyongjian080402** [comment]
![Filmage 2023-01-16_143647](https://user-images.githubusercontent.com/70191815/212614390-b8f7a99c-6e38-4fc0-a136-d8e27decd6f9.gif)

**Comment by zhiyiYo** [comment]
应该可以用opencv透视变换实现，关于透视变换可以参见我之前的博客 [《如何在pyqt中通过OpenCV实现对窗口的透视变换》](https://www.cnblogs.com/zhiyiYo/p/14644253.html)

**Comment by zhiyiYo** [comment]
以后和本仓库没关系的问题还是发邮件给我吧

**Comment by xianyongjian080402** [comment]
okk,好的，感谢
