### ISSUE TITLE
邊框不是圓角

### ISSUE THREAD

**Issue by tom9672** [zhiyiYo/PyQt-Fluent-Widgets#400]
在Ubuntu20.04中測試發現，普通窗口是圓角的，但是gallery這種無邊框窗口是尖角的，這是Frameless的問題嗎？有什麽辦法讓無邊框的窗口也能呈現圓角邊框的效果。

PySide2-Fluent-Widgets        1.0.2
PySide2-Frameless-Window   0.1.2

**Comment by zhiyiYo** [comment]
做不到，ubuntu 无边框后只能变成尖角
