### ISSUE TITLE
Errors installing PySide6-Fluent-Widgets module

### ISSUE THREAD

**Issue by kasoob** [zhiyiYo/PyQt-Fluent-Widgets#405]
I am unable to install the full version of the module.

I was using pip install "PySide6-Fluent-Widgets[full]" -i https://pypi.org/simple/

And everything was going fine until I encountered the following error: 
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\User\\AppData\\Local\\Temp\\pip-uninstall-135_p8cu\\msvcp140_1.dll'

I have tried to look everywhere online but I cannot figure out how to solve this. And I ran this using Admin perms.

Here is the full installation progress:

Looking in indexes: https://pypi.org/simple/
Collecting PySide6-Fluent-Widgets[full]
  Obtaining dependency information for PySide6-Fluent-Widgets[full] from https://files.pythonhosted.org/packages/6c/6b/73ab6206ac05cad2029d5ad2f36b7d2e7c692fcc6c9982e579eb7b4a856b/PySide6_Fluent_Widgets-1.0.2-py3-none-any.whl.metadata
  Downloading PySide6_Fluent_Widgets-1.0.2-py3-none-any.whl.metadata (4.5 kB)
Collecting PySide6<6.5.0 (from PySide6-Fluent-Widgets[full])
  Downloading PySide6-6.4.3-cp37-abi3-win_amd64.whl (7.2 kB)
Collecting PySideSix-Frameless-Window (from PySide6-Fluent-Widgets[full])
  Obtaining dependency information for PySideSix-Frameless-Window from https://files.pythonhosted.org/packages/ef/e8/db8c1672e3117ef21c43dae19a612f8404561ddab3d4bf1805c21e5449bc/PySideSix_Frameless_Window-0.1.2-py3-none-any.whl.metadata
  Downloading PySideSix_Frameless_Window-0.1.2-py3-none-any.whl.metadata (5.6 kB)
Collecting darkdetect (from PySide6-Fluent-Widgets[full])
  Downloading darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Requirement already satisfied: scipy in c:\user\appdata\local\programs\python\python311\lib\site-packages (from PySide6-Fluent-Widgets[full]) (1.10.1)
Requirement already satisfied: pillow in c:\user\appdata\local\programs\python\python311\lib\site-packages (from PySide6-Fluent-Widgets[full]) (9.5.0)
Collecting colorthief (from PySide6-Fluent-Widgets[full])
  Downloading colorthief-0.2.1-py2.py3-none-any.whl (6.1 kB)
Collecting shiboken6==6.4.3 (from PySide6<6.5.0->PySide6-Fluent-Widgets[full])
  Downloading shiboken6-6.4.3-cp37-abi3-win_amd64.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 5.1 MB/s eta 0:00:00
Collecting PySide6-Essentials==6.4.3 (from PySide6<6.5.0->PySide6-Fluent-Widgets[full])
  Downloading PySide6_Essentials-6.4.3-cp37-abi3-win_amd64.whl (78.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 MB 4.4 MB/s eta 0:00:00
Collecting PySide6-Addons==6.4.3 (from PySide6<6.5.0->PySide6-Fluent-Widgets[full])
  Downloading PySide6_Addons-6.4.3-cp37-abi3-win_amd64.whl (106.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 MB 3.6 MB/s eta 0:00:00        
Requirement already satisfied: pywin32 in c:\user\appdata\local\programs\python\python311\lib\site-packages (from PySideSix-Frameless-Window->PySide6-Fluent-Widgets[full]) (306)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in c:\user\appdata\local\programs\python\python311\lib\site-packages (from scipy->PySide6-Fluent-Widgets[full]) (1.24.3)
Downloading PySide6_Fluent_Widgets-1.0.2-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 6.9 MB/s eta 0:00:00
Downloading PySideSix_Frameless_Window-0.1.2-py3-none-any.whl (26 kB)
Installing collected packages: shiboken6, PySideSix-Frameless-Window, darkdetect, colorthief, PySide6-Essentials, PySide6-Addons, PySide6, PySide6-Fluent-Widgets
  Attempting uninstall: shiboken6
    Found existing installation: shiboken6 6.5.2
    Uninstalling shiboken6-6.5.2:
      Successfully uninstalled shiboken6-6.5.2
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\User\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\~hiboken6\\msvcp140.dll'
Consider using the `--user` option or check the permissions.

**Comment by ImmiProgramer** [comment]
Maybe u don't have msvcp140.dll
Plz download it and place that directory

**Comment by zhiyiYo** [comment]
Try open terminal as admin
