### ISSUE TITLE
无法在PySide6的designer中显示Fluent-Widgets组件

### ISSUE THREAD

**Issue by hjw0301** [zhiyiYo/PyQt-Fluent-Widgets#409]
我没有用虚拟环境,Plugins和tools在同级目录,使用的是PySide6,运行tools/designer.
没有报错,但是无法在designer看到Fluent-Widgets组件.
关闭designer,报错Error: ERROR: ld.so: object 'libpython3.8.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
不能显示Fluent-Widgets组件和这个报错有没有关系?
有没有使用PySide6的大哥,可以在designer中显示Fluent-Widgets组件的,能不能指点下是怎么配置的?

**Comment by zhiyiYo** [comment]
看下文档或者搜索历史 issue 就那么难吗，都写的很清楚了 pyside6 插件有问题
