### ISSUE TITLE
RoundMenu在父组件隐藏后子菜单不能正常隐藏

### ISSUE THREAD

**Issue by TwooSix** [zhiyiYo/PyQt-Fluent-Widgets#41]
多次右键两个RoundMenu的时候，子菜单有可能异常显示。
猜测是父菜单隐藏前鼠标滑动到了子菜单上，子菜单打开，父菜单隐藏，但子菜单却没有跟着父菜单隐藏。
![动画2](https://user-images.githubusercontent.com/62167519/227876383-03897fb3-a6ad-4112-aa85-49a98c504e31.gif)

**Comment by zhiyiYo** [comment]
原图是三级菜单吗

**Comment by TwooSix** [comment]
> 原图是三级菜单吗

异常显示的是二级菜单，预处理菜单下的都是Ation，但实际三级菜单也会异常显示。
对了，图中两张图片对应的是两个不同的menu实例。但这似乎没有影响，我后续测试的时候在同一个实例下也能复现bug。
复现方法是：右键打开一级菜单，鼠标滑过子菜单，在它播放弹出动画但未完全打开的时候快速的到其他地方右键再次打开一级菜单。
在两个不同实例的时候更容易复现bug。

**Comment by zhiyiYo** [comment]
菜单实例的生命周期和窗口一样长吗？如果只在 `contextMenuEvent` 里面创建菜单还会有这个问题吗

**Comment by zhiyiYo** [comment]
`QMenu` 不会有这个问题的，因为我是用 `QListWidget` 模拟的菜单，所以会有一些细节问题，脑壳疼
