### ISSUE TITLE
InfoBadge无法依附到pivotItem的指定位置

### ISSUE THREAD

**Issue by AlphaLiu** [zhiyiYo/PyQt-Fluent-Widgets#410]
**Describe the bug**
使用InfoBadge，设定taget为一个pivot item, position为TOP_RIGHT， 但实际运行时，infoBadge并不在这个pivot item的右上角。
不确定是我使用的方法不正确还是bug。请帮忙看看，谢谢。

**Environment**
环境信息
- OS: Windows 11
- DPI scaling: 100%
- Python: 3.10
- PySide6: 6.4.2
- PyQt-Fluent-Widgets:  1.0.2/1.0.3

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
1. 在examples\pivot\demo.py的 __init__ 方法最后面添加复现代码后运行demo

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
# examples\pivot\demo.py __init__
# add info badge to pivot item
        widget = self.pivot.widget('songInterface')
        InfoBadge.error(
            1, self, target=widget, position=InfoBadgePosition.TOP_RIGHT
        )
```

**Expected behavior**
infobadge应该在正确的位置

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/880467/5ab6201b-6177-4d08-9623-581d9b69513f)

**Comment by zhiyiYo** [comment]
`InfoBadge` 的 `parent` 应该是 `Pivot`
