### ISSUE TITLE
Mac下新的系统托盘图标点击无法显示菜单

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#411]
更新了最新的1.0.4版本，运行系统托盘demo，在Mac顶部菜单栏可以看到托盘图标，但是点击或者右键菜单均无法显示菜单
使用PyQt自带的系统托盘可以正常显示菜单
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/cacb3e9c-ec59-43d0-a0d8-2c45880be63d)

**Comment by zhiyiYo** [comment]
在 `SystemTrayMenu` 的 `showEvent` 里面打印一下 `self.pos()` 看看？

**Comment by zhiyiYo** [comment]
还以为是超出了屏幕，所以看不到

**Comment by zhiyiYo** [comment]
应该打印 `menuActions()`

**Comment by zhiyiYo** [comment]
那应该不是 action 的问题

**Comment by zhiyiYo** [comment]
话说 pyside6 启动 QtDesigner 的时候会有报错信息吗

**Comment by zhiyiYo** [comment]
好吧

**Comment by zhiyiYo** [comment]
昨晚朋友帮忙测试了 Mac 的这个问题，发现是由于 `RoundMenu` 在 `addAction()` 里面没有调用 `super().addAction()` 导致的

**Comment by zhiyiYo** [comment]
但是直接加上 `super().addAction()` 会导致圆角菜单上出现额外的菜单项

**Comment by zhiyiYo** [comment]
现在能看见托盘菜单吗

**Comment by zhiyiYo** [comment]
不一样，感觉变成默认菜单了

**Comment by zhiyiYo** [comment]
测试了 Ubuntu 也是默认菜单样式，可能只有 Windows 可以自定义
