### ISSUE TITLE
添加 TabWidget

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#412]
计划在下个版本中添加 TabWidget，样式参考：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/084b28a1-66fd-4d57-8c14-b7ebdf5caea7)

**Comment by ImmiProgramer** [comment]
thanks

**Comment by zhiyiYo** [comment]
这个组件还没写完，之后还会完善

**Comment by keymou** [comment]
nice

**Comment by JingyuanBai** [comment]
求问各位大佬，作者的源码demo我下载了，请问我怎么能实现在切换不同的tabBar下面显示不同的navigationBar和stackWidget？也就是随着tabBar的切换下面的内容也随着切换，谢谢！

**Comment by zhiyiYo** [comment]
@JingyuanBai 看下最新的 demo

**Comment by zhiyiYo** [comment]
@qianye216 拖拽功能在 Mac 上会有问题吗

**Comment by zhiyiYo** [comment]
还会有重叠吗？我在 Windows 下面复现不了这个问题

**Comment by zhiyiYo** [comment]
如果把 TabBar 放在别的组件的水平布局里面会重叠吗

**Comment by zhiyiYo** [comment]
是在 TabItem 上面加吗

**Comment by zhiyiYo** [comment]
okk

**Comment by zhiyiYo** [comment]
目前实现的效果如下：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/2f0f8a37-b740-4314-b633-45164c399624)

**Comment by zhiyiYo** [comment]
那把那行代码注释掉呢

**Comment by zhiyiYo** [comment]
启用亚克力效果也会报错吗

**Comment by zhiyiYo** [comment]
看来只能在 Win11 开了

**Comment by zhiyiYo** [comment]
@qianye216 现在运行 gallery 的 demo 会报错吗？

**Comment by JingyuanBai** [comment]
> @qianye216 现在运行 gallery 的 demo 会报错吗？

我的会闪退，win10

**Comment by zhiyiYo** [comment]
@JingyuanBai 有报错信息吗

**Comment by zhiyiYo** [comment]
> 正常运行，没有报错

感谢

**Comment by JingyuanBai** [comment]
> @JingyuanBai 有报错信息吗

没有报错信息，直接退出去了

**Comment by zhiyiYo** [comment]
@JingyuanBai 你用的是 python 3.11 吗

**Comment by JingyuanBai** [comment]
> @JingyuanBai 你用的是 python 3.11 吗

3.8.8

**Comment by zhiyiYo** [comment]
把 `FluentWindowBase` 的 `self.setMicaEffectEnabled(True)` 注释掉试试？

**Comment by JingyuanBai** [comment]
> 把 `FluentWindowBase` 的 `self.setMicaEffectEnabled(True)` 注释掉试试？

卡在初始化界面很长时间，鼠标转圈，然后退掉，无报错信息

**Comment by zhiyiYo** [comment]
之前的代码会这样吗？Win10 应该不会执行设置 Mica 特效的代码

**Comment by JingyuanBai** [comment]
> 之前的代码会这样吗？Win10 应该不会执行设置 Mica 特效的代码

之前不会，我过去一直用的是更新系统拖盘之前的代码

**Comment by zhiyiYo** [comment]
@JingyuanBai 切换到这个 Commit 试试 `添加滑动条动画 ([#422](vscode-file://vscode-app/d:/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html))`

**Comment by zhiyiYo** [comment]
估计是你导入的包是 pip install 的，而不是源代码里面的模块

**Comment by zhiyiYo** [comment]
如果想要使用最新的源代码来运行 demo，需要把 gallery 文件夹下的文件拖到项目根目录下

**Comment by JingyuanBai** [comment]
> 如果想要使用最新的源代码来运行 demo，需要把 gallery 文件夹下的文件拖到项目根目录下

我运行tab_view下的demo是没问题的

**Comment by zhiyiYo** [comment]
可以录个屏演示一下吗？

**Comment by JingyuanBai** [comment]
> 可以录个屏演示一下吗？


https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/102663151/6e9203aa-d810-4f86-ab68-e8a2b1dbb1bd

**Comment by zhiyiYo** [comment]
@JingyuanBai 现在还能运行 tab_view 的 demo 吗？以及 window ~ window3

**Comment by zhiyiYo** [comment]
@JingyuanBai 试下我打包的 exe 会闪退吗 https://wwff.lanzoum.com/ijvOS14wkyeb

**Comment by JingyuanBai** [comment]
> @JingyuanBai 现在还能运行 tab_view 的 demo 吗？以及 window ~ window3

可以运行

**Comment by JingyuanBai** [comment]
> @JingyuanBai 打包的 exe 会闪退吗 https://wwff.lanzoum.com/ijvOS14wkyeb

不会闪退

**Comment by zhiyiYo** [comment]
怀疑是你环境问题，试试虚拟环境

**Comment by JingyuanBai** [comment]
> 怀疑是你环境问题，试试虚拟环境
当前就是虚拟环境

**Comment by zhiyiYo** [comment]
那为啥代码运行不起来🧐
