### ISSUE TITLE
TableWidget在外部代码中不能更改字体大小

### ISSUE THREAD

**Issue by agentUD** [zhiyiYo/PyQt-Fluent-Widgets#413]
删除了
QHeaderView::section {
    background-color: transparent;
    color: black;
    padding-left: 5px;
    padding-right: 5px;
    border: 1px solid rgba(0, 0, 0, 19);
    font: 13px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
}
中设置字体的部分。用的PyQt5。
但在外部代码中还是不能更改表头和单元格字体的大小，如果换成原生的tableWeidget就可以更改。
还要麻烦您指教！

**Comment by zhiyiYo** [comment]
单元格的字体应该是可以改的吧？我记得前景色也可以

**Comment by zhiyiYo** [comment]
如果你改了qss，还需要重新编译为resource.py才能起作用

**Comment by agentUD** [comment]
> 单元格的字体应该是可以改的吧？我记得前景色也可以

单元格字体试了也不能改，代码应该是没问题的，作用于原生的控件没问题。这样不能改字体，导致字体很小，看起来比较难受

**Comment by agentUD** [comment]
> 如果你改了qss，还需要重新编译为resource.py才能起作用

怎么重新编译？我不太懂，能指教一下吗

**Comment by agentUD** [comment]
> 如果你改了qss，还需要重新编译为resource.py才能起作用

我把ui文件转成python文件进行调用了，python文件中的qss更新了，但是出来的界面没有生效，这是什么情况？

**Comment by ImmiProgramer** [comment]
> > If you change qss, you need to recompile to resource.py to work
> 
> I converted the ui file into a python file and called it. The qss in the python file was updated, but the interface did not take effect. What is the situation?

try:
override setStyleSheet() of a TableWidget and when call setStyleSheet form FluentStyleSheet it take stylesheet as a string then modify the style sheet and apply into tableWidget
stylesheet.replace("font: 13px 'Segoe UI ', 'Microsoft YaHei', 'PingFang SC';", "font: 20px 'Segoe UI ', 'Microsoft YaHei', 'PingFang SC';")

**Comment by zhiyiYo** [comment]
这不是设置的好好的吗？
```python
# coding: utf-8
import sys

from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QApplication, QTableWidgetItem, QWidget, QHBoxLayout

from qfluentwidgets import TableWidget, getFont


class Demo(QWidget):

    def __init__(self):
        super().__init__()
        self.hBoxLayout = QHBoxLayout(self)
        self.tableView = TableWidget(self)

        self.tableView.setWordWrap(False)
        self.tableView.setRowCount(6)
        self.tableView.setColumnCount(5)
        songInfos = [
            ['かばん', 'aiko', 'かばん', '2004', '5:04'],
            ['爱你', '王心凌', '爱你', '2004', '3:39'],
            ['星のない世界', 'aiko', '星のない世界/横顔', '2007', '5:30'],
            ['横顔', 'aiko', '星のない世界/横顔', '2007', '5:06'],
            ['秘密', 'aiko', '秘密', '2008', '6:27'],
            ['シアワセ', 'aiko', '秘密', '2008', '5:25'],
        ]
        songInfos += songInfos
        for i, songInfo in enumerate(songInfos):
            for j in range(5):
                item = QTableWidgetItem(songInfo[j])
                item.setFont(QFont('SongTi'))
                item.setForeground(Qt.red)
                self.tableView.setItem(i, j, item)

        self.tableView.verticalHeader().hide()
        self.tableView.setHorizontalHeaderLabels(
            ['Title', 'Artist', 'Album', 'Year', 'Duration'])
        self.tableView.resizeColumnsToContents()

        self.setStyleSheet("Demo{background: rgb(249, 249, 249)} ")
        self.hBoxLayout.setContentsMargins(0, 0, 0, 0)
        self.hBoxLayout.addWidget(self.tableView)
        self.resize(635, 700)


if __name__ == "__main__":
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Demo()
    w.show()
    app.exec()
```

**Comment by agentUD** [comment]
> 这不是设置的好好的吗？
> 
> ```python
> # coding: utf-8
> import sys
> 
> from PyQt5.QtCore import Qt
> from PyQt5.QtGui import QFont
> from PyQt5.QtWidgets import QApplication, QTableWidgetItem, QWidget, QHBoxLayout
> 
> from qfluentwidgets import TableWidget, getFont
> 
> 
> class Demo(QWidget):
> 
>     def __init__(self):
>         super().__init__()
>         self.hBoxLayout = QHBoxLayout(self)
>         self.tableView = TableWidget(self)
> 
>         self.tableView.setWordWrap(False)
>         self.tableView.setRowCount(6)
>         self.tableView.setColumnCount(5)
>         songInfos = [
>             ['かばん', 'aiko', 'かばん', '2004', '5:04'],
>             ['爱你', '王心凌', '爱你', '2004', '3:39'],
>             ['星のない世界', 'aiko', '星のない世界/横顔', '2007', '5:30'],
>             ['横顔', 'aiko', '星のない世界/横顔', '2007', '5:06'],
>             ['秘密', 'aiko', '秘密', '2008', '6:27'],
>             ['シアワセ', 'aiko', '秘密', '2008', '5:25'],
>         ]
>         songInfos += songInfos
>         for i, songInfo in enumerate(songInfos):
>             for j in range(5):
>                 item = QTableWidgetItem(songInfo[j])
>                 item.setFont(QFont('SongTi'))
>                 item.setForeground(Qt.red)
>                 self.tableView.setItem(i, j, item)
> 
>         self.tableView.verticalHeader().hide()
>         self.tableView.setHorizontalHeaderLabels(
>             ['Title', 'Artist', 'Album', 'Year', 'Duration'])
>         self.tableView.resizeColumnsToContents()
> 
>         self.setStyleSheet("Demo{background: rgb(249, 249, 249)} ")
>         self.hBoxLayout.setContentsMargins(0, 0, 0, 0)
>         self.hBoxLayout.addWidget(self.tableView)
>         self.resize(635, 700)
> 
> 
> if __name__ == "__main__":
>     # enable dpi scale
>     QApplication.setHighDpiScaleFactorRoundingPolicy(
>         Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
>     QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
>     QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
> 
>     app = QApplication(sys.argv)
>     w = Demo()
>     w.show()
>     app.exec()
> ```

感谢回复！用TableView是可以的，但TableWidget在外部不能设置字体大小。我的问题已经解决，感谢您的指导！
