### ISSUE TITLE
使用Designer 设计文档，转成py后，1. 按钮、下拉框、文本框等控件字体变小 2. 使用showMaximized无法最大化

### ISSUE THREAD

**Issue by TheCoderChen** [zhiyiYo/PyQt-Fluent-Widgets#417]
**Describe the bug**
使用Designer 设计文档，转成py后，1. 按钮、下拉框、文本框等控件字体变小 2. 使用showMaximized无法最大化
在designer 中预览的大小正常，但转化成py后显示异常

**Environment**
环境信息
- OS: Windows10
- DPI scaling: 200%
- Python: 3.8.10 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 1.0.4

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
1. 设计Designer 文件，预览如图所示：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/76744114/6f45e850-a76c-461e-92b3-49da7d2888c6)
2. 生成PY文件
3. 运行代码，实际如图所示：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/76744114/87e2091f-c001-44eb-92b5-b1cbc904be90)

**Code**
最小复现代码
```python
# Minimum code to reproduce the error

class XX_Mainwindow(QMainWindow):
    def __init__(self):
        super(XX_Mainwindow, self).__init__()
        self.ui = ui_mainwindow.Ui_MainWindow()
        self.ui.setupUi(self)
        self.initUi()


if __name__ == '__main__':
    app = QApplication(sys.argv)
    # 高分屏适配
    QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    test_window = XX_Mainwindow()
    test_window.showMaximized()
    sys.excepthook = except_hook
    app.exit(app.exec_())

```

**Expected behavior**
显示正常大小，正常最大化

**Screenshots**
上文中已截图

**Comment by zhiyiYo** [comment]
高分屏适配的代码要放在创建 app 前面
