### ISSUE TITLE
如何让侧边栏永久呈现悬浮样式呢

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#419]
如题，我想做到无论界面大小怎么变化，都永远是悬浮样式
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/f8c1896e-f93b-4690-b5f7-7344ca1fad86)

**Comment by zhiyiYo** [comment]
怎么感觉你想要的是展开样式而不是菜单样式

**Comment by zhiyiYo** [comment]
`setCollapsible(False)` 可以禁用自动折叠

**Comment by youjunxiaji** [comment]
> `setCollapsible(False)` 可以禁用自动折叠

我都设置过了，那样子感觉很别扭 
我重写了你的部分功能，包括鼠标进入时自动展开，离开时自动关闭；
在切换不同widget的时候界面尺寸可以跟着变化而不会被强制拉宽或者是缩小（但是这部分功能碰到了一个小问题，尺寸没有按照我想要的实际去变换）

**Comment by youjunxiaji** [comment]
> > `setCollapsible(False)` 可以禁用自动折叠
> 
> 我都设置过了，那样子感觉很别扭 我重写了你的部分功能，包括鼠标进入时自动展开，离开时自动关闭； 在切换不同widget的时候界面尺寸可以跟着变化而不会被强制拉宽或者是缩小（但是这部分功能碰到了一个小问题，尺寸没有按照我想要的实际去变换）

我觉得导致出现这个问题的原因就是因为侧边栏展示方式的变换

**Comment by youjunxiaji** [comment]
> `setCollapsible(False)` 可以禁用自动折叠

设置为False时如下图
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/269bd193-81ae-47a7-9a30-e5dc87a224ee)

**Comment by zhiyiYo** [comment]
你可能得改下 `NavigationPanel` 的 eventFilter 部分
