### ISSUE TITLE
关于程序介绍

### ISSUE THREAD

**Issue by TcDhlPro** [zhiyiYo/PyQt-Fluent-Widgets#42]
能不能整一版中文的"README.md"和"help document"

**Comment by zhiyiYo** [comment]
README 里面也没几个单词，感觉汉化的意义不大，谷歌浏览器的翻译开起来就 ok 了。在线帮助文档之后有时间会汉化的

**Comment by zhiyiYo** [comment]
中文文档参见：https://pyqt-fluent-widgets.readthedocs.io/zh_CN/latest/

**Comment by TcDhlPro** [comment]
> 中文文档参见：https://pyqt-fluent-widgets.readthedocs.io/zh_CN/latest/

好的谢谢
