### ISSUE TITLE
Combox 下拉框不支持自动向上扩展

### ISSUE THREAD

**Issue by liuqiang1111** [zhiyiYo/PyQt-Fluent-Widgets#423]
**Describe the bug**
问题的简要描述。

**Environment**
环境信息
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.6 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.2.1]

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)

**Code**
最小复现代码
```python
# Minimum code to reproduce the error

```

**Expected behavior**

**Screenshots**

**Comment by zhiyiYo** [comment]
高度足够小会上拉

**Comment by zhiyiYo** [comment]
有点小 bug，之前的上拉不起作用了

**Comment by zhiyiYo** [comment]
v1.1.1已修复此问题

**Comment by liuqiang1111** [comment]
大佬 效率

**Comment by liuqiang1111** [comment]
@zhiyiYo 这个问我今天更新后，我在单个widget中可以向上扩展，但是我把widget加入到TabWidget中，则上拉失效了。
<img width="295" alt="1691642432059" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52993562/51a654bc-1729-46f4-b4d9-8ecda22bd42d">
<img width="124" alt="1691642480653" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52993562/544f2ab6-4c04-4f36-beea-7556090a3f81">

**Comment by liuqiang1111** [comment]
不好意思，我自己的原因，修改好了
