### ISSUE TITLE
FluentWindow侧边栏动态添加item时建议能动态自适应显示item

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#427]
当启动窗口后，再动态添加侧边栏item时发现item的高度被挤扁了，实际上下方有足够的空间可以完全容纳添加的item
如果我最大化窗口后再还原就能显示正常了
<img width="900" alt="115截图20230810153614" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/1db19d60-01dc-4293-81f4-dfc6e4dca87e">
<img width="900" alt="115截图20230810153628" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/a139f810-99da-4130-99bd-edf33d7013ca">

**Comment by zhiyiYo** [comment]
动态添加的 Item 位置建议设置为 `NavigationItemPosition.SCROLL`

**Comment by zhiyiYo** [comment]
这个不太好搞，动态添加放在顶部或者底部会导致窗口高度不断增大
