### ISSUE TITLE
自定义图标错位(2)

### ISSUE THREAD

**Issue by fsf678** [zhiyiYo/PyQt-Fluent-Widgets#43]
应该是[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)的问题，我在https://fluenticons.co/?ref=microns.io、https://www.iconfont.cn/ 下载的许多图标都在错位（我使用的所有图标向有偏移），不知道是否与viewBox（viewBox="0 0 16 16" ）相关？

像这样↓
![image](https://user-images.githubusercontent.com/101497799/227930818-ece98943-68dd-46b5-8377-3a56bd411f6a.png)

**Comment by fsf678** [comment]
`<svg width="24" height="24" fill="none" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M14.998 5a7 7 0 0 1 .24 13.996l-.24.004H9.002a7 7 0 0 1-.24-13.996L9.001 5h5.996Zm0 1.5H9.002a5.5 5.5 0 0 0-.221 10.996l.221.004h5.996a5.5 5.5 0 0 0 .221-10.996l-.221-.004ZM8 9a.75.75 0 0 1 .75.75v1.498h1.5a.75.75 0 0 1 0 1.5h-1.5v1.502a.75.75 0 0 1-1.5 0v-1.502h-1.5a.75.75 0 1 1 0-1.5h1.5V9.75A.75.75 0 0 1 8 9Zm6.75 3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Zm2-3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Z" fill="#ffffff"/></svg>`原来的错位更狠，我修改了 viewBox( viewBox="0 0 24 24"  to  viewBox="0 0 16 16"  )

**Comment by zhiyiYo** [comment]
应该是你的 viewbox 改的有问题，得改的和 height 和 width 一样大
```xml
<svg width="24" height="24" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <path
        d="M14.998 5a7 7 0 0 1 .24 13.996l-.24.004H9.002a7 7 0 0 1-.24-13.996L9.001 5h5.996Zm0 1.5H9.002a5.5 5.5 0 0 0-.221 10.996l.221.004h5.996a5.5 5.5 0 0 0 .221-10.996l-.221-.004ZM8 9a.75.75 0 0 1 .75.75v1.498h1.5a.75.75 0 0 1 0 1.5h-1.5v1.502a.75.75 0 0 1-1.5 0v-1.502h-1.5a.75.75 0 1 1 0-1.5h1.5V9.75A.75.75 0 0 1 8 9Zm6.75 3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Zm2-3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Z"
        fill="#ffffff"/>
</svg>
```

**Comment by fsf678** [comment]
可是，我在浏览器中打开并不错位

**Comment by fsf678** [comment]
如果这种问题对你来说很智障，我很抱歉，我是不了解SVG和PYQT5:(

**Comment by zhiyiYo** [comment]
你把图标导出为 16px 的试试

**Comment by zhiyiYo** [comment]
@fsf678 
如果不想重新导出图标的话可以改一下 transform 属性和图标大小：
```python
<svg width="16" height="16" fill="none" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
    <path
        d="M14.998 5a7 7 0 0 1 .24 13.996l-.24.004H9.002a7 7 0 0 1-.24-13.996L9.001 5h5.996Zm0 1.5H9.002a5.5 5.5 0 0 0-.221 10.996l.221.004h5.996a5.5 5.5 0 0 0 .221-10.996l-.221-.004ZM8 9a.75.75 0 0 1 .75.75v1.498h1.5a.75.75 0 0 1 0 1.5h-1.5v1.502a.75.75 0 0 1-1.5 0v-1.502h-1.5a.75.75 0 1 1 0-1.5h1.5V9.75A.75.75 0 0 1 8 9Zm6.75 3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Zm2-3.5a1.25 1.25 0 1 1 0 2.5 1.25 1.25 0 0 1 0-2.5Z"
        fill="#ffffff" transform="scale(0.75, 0.75) translate(-1.5, -1.5)"/>
</svg>
```
