### ISSUE TITLE
PySide6-Fluent-Widgets中的小问题

### ISSUE THREAD

**Issue by Franknah** [zhiyiYo/PyQt-Fluent-Widgets#430]
**问题描述**
     在PySide6-Fluent-Widgets的tab_view演示文件运行时出错，发现问题在第149行
如图：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/82433111-d8e8-4107-8ccc-fd4ab32e0a33)
修改为：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/cee8f9d6-8a68-4350-a594-dc1f36253265)
后运行正常。
看其他示例文件是正常的，应该是疏忽没改吧

**Comment by zhiyiYo** [comment]
感谢反馈，目前已修复此问题
