### ISSUE TITLE
slider无法发出信号

### ISSUE THREAD

**Issue by Franknah** [zhiyiYo/PyQt-Fluent-Widgets#432]
**问题**
PySide6-FW（版本为1.1.1）下的Slider组件无法发出sliderMoved，sliderPressed等一系列信号

**最小复现代码**
版本：1.1.1
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/3eee6367-9f10-4cde-aacc-08d6ee2147ee)
效果：
![屏幕录制 2023-08-11 111032](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/fbcd31f5-a2ea-4868-9195-65bd71db4f47)
把Slider换成QSlider，再次运行：
![屏幕录制 2023-08-11 111701](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/3efe7cd2-c48d-479f-bf73-1cdab372994a)
再下载回1.0.4：
![屏幕录制 2023-08-11 113151](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/4aedad0d-8da3-4a27-bfb8-f79a54793e15)

**Comment by zhiyiYo** [comment]
目前已修复此问题

**Comment by Franknah** [comment]
看了一下，还是不行：
![3vsts-4708m](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/43a405b1-d599-4878-ae60-4847a5976d82)

**Comment by Franknah** [comment]
好吧
