### ISSUE TITLE
Bug when automatically switch from light mode to dark mode

### ISSUE THREAD

**Issue by jamalsa** [zhiyiYo/PyQt-Fluent-Widgets#437]
**Describe the bug**
I add a mechanism to automatically switch window theme when system theme changed using [darkdetect](https://github.com/albertosottile/darkdetect) and QThread. When system changed from dark theme to light theme, the application theme changed correctly. But when system changed from light theme to dark theme, the application theme is still light and text and icon is invisible.

**Environment**
- OS: Windows11
- DPI scaling: 125%
- Python: 3.11.2 64-bit
- PyQt: 6.4.2
- PyQt-Fluent-Widgets: 1.1.3

**To Reproduce**

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/146671/58f14dc9-facb-4b9e-9812-f0a26f0eddb3

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/146671/41f972a1-bf6d-4e4f-ade0-a7310af9f9cf

**Code**
https://github.com/jamalsa/darkmode-bug

**Expected behavior**
Can automatically switch from light theme to dark theme

**Comment by Franknah** [comment]
看了你的代码，你没有禁用云母效果，应该是它导致出现错误，我也同样遇到这个问题，我的解决方法是在你的代码加上`self.setMicaEffectEnabled(True)`：
 Reading your code, i noticed that you did not disable the mica effect, which should have caused an error. I also encountered this problem, and my solution is to add `self.setMicaEffectEnabled (True) `to your code` :
```
    def callback(self, mode: str):
        print('Callback with mode: ', mode)
        if mode == "Light":
            setTheme(Theme.LIGHT)
        else:
            setTheme(Theme.DARK)
```
加上`self.setMicaEffectEnabled(True)`变成：
after adding `self.setMicaEffectEnabled(True)`
```
    def callback(self, mode: str):
        print('Callback with mode: ', mode)
        self.setMicaEffectEnabled(True)
        if mode == "Light":
            setTheme(Theme.LIGHT)
        else:
            setTheme(Theme.DARK)
```
应该可以解决
perhaps it works
(机翻+人修)

**Comment by Franknah** [comment]
或者可以把`self.setMicaEffectEnabled(True)`替换成`self.windowEffect.setMicaEffect(self.winId(),isDarkTheme())`

**Comment by zhiyiYo** [comment]
```python
def toggleTheme(self):
        theme = Theme.LIGHT if isDarkTheme() else Theme.DARK
        cfg.set(cfg.themeMode, theme)

        if self.isMicaEffectEnabled():
            self.windowEffect.setMicaEffect(self.winId(), isDarkTheme())
```

**Comment by zhiyiYo** [comment]
也许应该在 FluentWindowBase 中处理主题切换的情况

**Comment by zhiyiYo** [comment]
v1.1.5 will provide `qfluentwidgets.toggleTheme()` to toggle the theme of app.
