### ISSUE TITLE
I need your help

### ISSUE THREAD

**Issue by ImmiProgramer** [zhiyiYo/PyQt-Fluent-Widgets#438]
You are a very experienced person, so kindly let me know which one is better between PyQt and PySide. Whose performance is better?

I am already aware of the licensing differences between PyQt and PySide.

I have done a lot of research, but I haven't found any correct answer. Therefore, please let me know.

And Why u choose pyqt5 for "Groove"
https://github.com/zhiyiYo/Groove

**Comment by ImmiProgramer** [comment]
And Why u choose pyqt5 for "Groove"
https://github.com/zhiyiYo/Groove

**Comment by ImmiProgramer** [comment]
I am currently working with Pyqt5

**Comment by LimeBow-Studios** [comment]
# Which one is better between PyQt and PySide?
That's a good question, and I think from my understanding it should explain this pretty well. I'm Chinese, so if you can only read English, I guess I'll need to use a translator.

## My Answer
Both PyQt and PySide are Python bindings for the Qt framework, which allows you to create cross-platform desktop applications with a native look and feel. Both libraries provide similar functionalities and have their own advantages and disadvantages. Here are some points to consider:

1. **Licensing**: PyQt is available under the GNU General Public License (GPL) or a commercial license, while PySide is available under the LGPL. This means that if you plan to use PyQt for commercial purposes, you will need to purchase a commercial license.

2. **Compatibility**: PyQt is compatible with both Python 2 and Python 3, while PySide has separate versions for Python 2 (PySide) and Python 3 (PySide2). This makes PyQt a better choice if you need to support both Python versions.

3. **Documentation** and Community: PyQt has been around for a longer time and has a more extensive documentation and a larger community. This means that you may find more resources and support for PyQt compared to PySide.

4. **Development** and Maintenance: PyQt is developed and maintained by Riverbank Computing, while PySide is developed and maintained by The Qt Company. PyQt tends to have more frequent updates and bug fixes, but PySide has been catching up in recent years.

**Ultimately, the choice between PyQt and PySide depends on your specific requirements and preferences. If licensing and Python version compatibility are important to you, PyQt may be a better choice. However, if you prefer a more permissive license and want to use the latest version of Qt, PySide2 could be a good option. It's recommended to try out both libraries and see which one fits your needs better.**
(For the summarization part I used the AI summarization tool to help me with this.)

_Finally, the above is my understanding. Maybe my answer is similar to what you read on the internet, and please be more tolerant._
### **Thank you for seeing this.**
If possible use email contact me at [limebow@sina.com](mailto:limebow@sina.com) (I'm lazy and busy.)

**Comment by zhiyiYo** [comment]
PyQt and PySide have similar speeds as they are both based on the C++ Qt framework. The reason Groove uses PyQt is because PyQt is considered more stable.

**Comment by ImmiProgramer** [comment]
> PyQt and PySide have similar speeds as they are both based on the C++ Qt framework. The reason Groove uses PyQt is because PyQt is considered more stable.
> 
> Both PySide6-Fluent-Widgets and PyQt-Fluent-Widgets have GPLv3 licenses for non-commercial use, so you can choose either one.

Thanks

**Comment by ImmiProgramer** [comment]
> PyQt and PySide have similar speeds as they are both based on the C++ Qt framework. The reason Groove uses PyQt is because PyQt is considered more stable.
> 
> Both PySide6-Fluent-Widgets and PyQt-Fluent-Widgets have GPLv3 licenses for non-commercial use, so you can choose either one.

I don't understand
"The reason Groove uses PyQt is because PyQt is considered more stable."

**Comment by zhiyiYo** [comment]
> I don't understand
> "The reason Groove uses PyQt is because PyQt is considered more stable."

At least in my experience with PyQt, I haven't encountered any strange bugs, while with PySide, the frameless windows often pose problems.
