### ISSUE TITLE
关于Acrylic实现

### ISSUE THREAD

**Issue by AbrasiveBoar902** [zhiyiYo/PyQt-Fluent-Widgets#44]
基本都使用Qml，对PyQt很不了解，所以求教
1. Acrylic控件如何获取自己的下方像素以进行高斯模糊？在Qml中由于渲染方式的原因，着色器源截取应该是在 `source-over` 混合之前，我在尝试实现时用了繁琐的层和同步才能部分解决问题，依然实现不了任意混合和多层混合
2. 一般的Acrylic模拟中使用四层，底层高斯模糊背景，一层颜色以 `Color` 混合模式和背景混合预处理，一层以 `Luminosity` 预处理，一层噪声图像，最终以 `source-over` 叠加，AcrylicLabel中可以在哪里找到一些示例实现？同上原因，我不得不把高斯模糊和两种混合预处理的着色器写在同一个片段着色器中，增加了耦合而且使得维护有一些障碍。
3. 如何知道颜色定义？通过测出来的还是说源码读出来的

图片是我尝试搓的Acrylic (纯Qml)
![image](https://user-images.githubusercontent.com/76773705/227999093-28589253-ee11-42f9-a3f0-d837c0a23e88.png)

**Comment by zhiyiYo** [comment]
> 2. AcrylicLabel中可以在哪里找到一些示例实现？同上原因，我不得不把高斯模糊和两种混合预处理的着色器写在同一个片段着色器中，增加了耦合而且使得维护有一些障碍。
> 3. 如何知道颜色定义？通过测出来的还是说源码读出来的

没看懂这两个问题什么意思，可以描述的清楚一些吗

**Comment by AbrasiveBoar902** [comment]
> > 3. 如何知道颜色定义？通过测出来的还是说源码读出来的
> 
> 没看懂这个问题什么意思，可以描述的清楚一些吗

就是使用的各种颜色的详细色值和透明度 渐变等等

**Comment by zhiyiYo** [comment]
我记得他是自己模糊的吧，不是用的系统api来模糊的图片，难道是改代码了

**Comment by zhiyiYo** [comment]
> 就是使用的各种颜色的详细色值和透明度 渐变等等

这个也没有官方文档，我就瞎调的透明度，至于使用的颜色，我之前是用 ColorThief 写了一个主题色提取类 DominentColor，不过没把他内置在亚克力标签中
