### ISSUE TITLE
DropDownPushButton设置下拉菜单后，当按钮在窗口最底部时点击后弹出的菜单未自适应位置显示

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#440]
大佬您好，更新了最新版本后发现DropDownPushButton如果设置了下拉菜单，点击按钮后，如果弹出的菜单位置超出屏幕的话之前是可以自适应位置往上弹出显示的，但是现在发现不会自适应，一直下拉弹出，导致无法自适应显示
我尝试重写RoundMenu将aniType改成MenuAnimationType.PULL_UP，但是点击按钮后弹出的菜单会将按钮遮住
<img width="259" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/580ee026-53e4-457d-be36-e5c61144fccc">

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/a10a1234-28a8-42d3-b2ac-fdddeac6c88b)
相关代码：
```python
self.menu = RoundMenu(self)
self.menu.addActions([
                QAction('测试'),
                QAction('测试'),
                QAction('测试'),
                QAction('测试'),
                QAction('测试')
            ])
self.batch_Btn.setMenu(self.menu)
```

**Comment by zhiyiYo** [comment]
我记得只有 ComboBox 写了自动上拉的功能

**Comment by zhiyiYo** [comment]
目前已修复此问题
