### ISSUE TITLE
PopUpAniStackedWidget在切换子页面时候子页面偏移

### ISSUE THREAD

**Issue by LxHTT** [zhiyiYo/PyQt-Fluent-Widgets#443]
**描述Bug**
PopUpAniStackedWidget在切换页面时候疑似由于动画的计算导致位置偏差，并且，改变窗口大小后能恢复正常。
QStackWidget不存在此问题。

**环境信息**
- OS: Windows 11
- DPI scaling: 100%
- Python: 3.8.0 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 1.1.4

**复现**
[视频](https://lxhtt-my.sharepoint.com/:v:/g/personal/lxhtt_lxhtt_onmicrosoft_com/EQgtQa7iiXlMjNSVrSsFWcQBIWU5WXYUOisRFYDqoxjKjQ?e=ytYmAy)

**理应的行为**
切换页面的时候坐标不会偏差

**截图**
1.切换页面后的PopUpAniStackedWidget
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/98154001/ee4ed193-dedd-4cc4-9a8d-927df96d4878)
2.切换页面后的QStackedWidget
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/98154001/17e2c051-43c1-4df7-8a47-e099a215fbbd)

**Comment by zhiyiYo** [comment]
换成 FluentWindow 用的 StackedWidget

**Comment by LxHTT** [comment]
成功解决。
