### ISSUE TITLE
右键菜单显示时无法自适应位置显示

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#447]
#440 这个问题最新的1.1.6版本DropdownPushButton正常了，但是运行examples中的menu的demo程序右键菜单仍然无法自适应位置
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/32fbf1fc-a6c4-4e26-b577-03f24560f41a)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/a3812479-be0d-49da-88a7-c474935be880)

**Comment by zhiyiYo** [comment]
现在还有这个问题吗
