### ISSUE TITLE
garllery/demo 运行报错

### ISSUE THREAD

**Issue by ILJEUN** [zhiyiYo/PyQt-Fluent-Widgets#448]
**Describe the bug**
最新的V1.1.7 master分支上的garllery/demo 运行后报错
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/112267717/28e25355-bc25-47f4-8a07-b229ecd2a73e)

**Environment**
环境信息
- OS: [e.g. Windows11]
- Python: [e.g. 3.6.5 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 1.1.7]

**Comment by zhiyiYo** [comment]
感觉是你环境乱了

**Comment by ILJEUN** [comment]
我再重新创建了一下虚拟环境，没检查出环境有什么异常。
分别尝试运行了example里面一部分demo，目前有一部分可以正常运行，一部分不可以，不可以的运行的demo报错都来源于qfluentwidgets\common\overload.py。python和pyqt5的版本有影响吗？

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/112267717/e5491864-5d98-4f85-b007-44b5d0eaa468
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/112267717/287c8e8b-c27e-4673-a0b9-ebe6b8a67d69
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/112267717/1a71ac9f-fc26-42bc-94cf-a69ab8a2ec29

**Comment by zhiyiYo** [comment]
试下3.8

**Comment by ILJEUN** [comment]
> 试下3.8

3.8的py可以正常运行了
