### ISSUE TITLE
文档改进建议

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#449]
打算换个文档网站，欢迎大家在此处留下文档的改进建议，比如文档中写得不够清楚、需要补充的地方( •̀ ω •́ )✧

**Comment by ImmiProgramer** [comment]
> 打算换个文档网站，欢迎大家在此处留下文档的改进建议，比如文档中写得不够清楚、需要补充的地方( •̀ ω •́ )✧

Good decision

**Comment by Moxiner** [comment]
文档中建议把所有icon图标列举出来（我记得之前，不知道现在为啥没了

**Comment by zhiyiYo** [comment]
> 文档中建议把所有icon图标列举出来（我记得之前，不知道现在为啥没了

可以在 Gallery 的图标界面查看所有图标

**Comment by Moxiner** [comment]
> > 文档中建议把所有icon图标列举出来（我记得之前，不知道现在为啥没了
> 
> 可以在 Gallery 的图标界面查看所有图标

奇怪，之前运行 ```Gallery``` 没有显示全....
没事了，谢谢大佬！
( 建议在文档里加一句，全部图标可以在 ```Gallery``` 查看

**Comment by zhiyiYo** [comment]
> 奇怪，之前运行 `Gallery` 没有显示全.... 没事了，谢谢大佬！ ( 建议在文档里加一句，全部图标可以在 `Gallery` 查看

收到

**Comment by zhiyiYo** [comment]
[文档网站](https://qfluentwidgets.github.io/)已上线，文档相关的 issue 请移步 https://github.com/qfluentwidgets/qfluentwidgets.github.io
