### ISSUE TITLE
add Table & Tree & List widgets

### ISSUE THREAD

**Issue by guixiaocai** [zhiyiYo/PyQt-Fluent-Widgets#45]
一人血书，求加Table 、Tree、List widgets，这三个东西对于广大的数据工程师是必不可少的组件。

**Comment by Ephemeralwanning** [comment]
顺便加上textedit、spinbox

**Comment by qianye216** [comment]
我也再求个， @zhiyiYo  大佬能不能再加个loading加载动画的组件

**Comment by zhiyiYo** [comment]
还有 `InfoBar` 没有实现呢🥲 平时还要给老板干活，只能周末慢慢写了

**Comment by qianye216** [comment]
> 还有 `InfoBar` 没有实现呢🥲 平时还要给老板干活，只能周末慢慢写了

不急，慢慢来，大佬读研了啊

**Comment by qianye216** [comment]
> > > 还有 `InfoBar` 没有实现呢🥲 平时还要给老板干活，只能周末慢慢写了
> > 
> > 
> > 不急，慢慢来，大佬读研了啊
> 
> 是的呀，所以希望大家不要催的太急

恩恩，按自己的计划来就行，有时间就弄，也要保证自己的学习和日常生活，劳逸结合哈

**Comment by Cheukfung** [comment]
一人血书，还有日历组件

**Comment by zhiyiYo** [comment]
@Ephemeralwanning 
目前已添加 `SpinBox`

**Comment by zhiyiYo** [comment]
@qianye216 
已修复此问题

**Comment by zhiyiYo** [comment]
@Ephemeralwanning 
都加了，可以看下我新上传的演示视频

**Comment by zhiyiYo** [comment]
> @zhiyiYo 我看已经添加了TextEdit，能否顺便加下纯文本编辑框PlainTextEdit

已添加

**Comment by wuhanhui** [comment]
是的，table 和 tree太有必要了。大佬加油

**Comment by zhiyiYo** [comment]
> will there be a pyqt-framework of mac style in future?

？这是 fluent design 风格的库啊🥲

**Comment by bihailantian655** [comment]
will there be a pyqt-framework of mac style in future?，这个人是个老外。

**Comment by bihailantian655** [comment]
要是能出个像designer 一样的软件，就更方便了

**Comment by zhiyiYo** [comment]
> will there be a pyqt-framework of mac style in future?，这个人是个老外。

看他的博客用的是中文

**Comment by zhiyiYo** [comment]
没有 mac 电脑，要是有富哥vivo一台mac电脑也许可以安排一下

**Comment by zhiyiYo** [comment]
pyqt5 分支加了树状组件，如果大家测试 ok 的话我就打包上传到 pypi 了

**Comment by zhiyiYo** [comment]
windows没有这个问题，是不是应该在qss里面把背景搞成透明的

**Comment by zhiyiYo** [comment]
选中状态可能也得改下

**Comment by zhiyiYo** [comment]
这个得用户自己改下界面背景，我把背景弄成透明的

**Comment by zhiyiYo** [comment]
改成透明样式好使不

**Comment by zhiyiYo** [comment]
gallery界面的树状视图会这样吗

**Comment by zhiyiYo** [comment]
试下这个：
https://stackoverflow.com/questions/28366805/remove-blue-selection-from-qtreeview-in-fusion-style

**Comment by zhiyiYo** [comment]
不会吧，现在样式表长啥样

**Comment by zhiyiYo** [comment]
他这个不是还有一个蓝色方块吗

**Comment by zhiyiYo** [comment]
setAllColumnsShowFocus(False) 有加上吗

**Comment by zhiyiYo** [comment]
@qianye216 
改成下面这样应该就没问题了吧
```python
QTreeView {
    background-color: transparent;
    border: none;
    border-radius: 5px;
    outline: 0;
    padding-right: 5px;
    font: 13px 'Segoe UI', 'Microsoft YaHei';
    selection-background-color: transparent;
}
```

**Comment by zhiyiYo** [comment]
不可能吧，你有重新编译 qrc 吗

**Comment by zhiyiYo** [comment]
把 `qfluentwidgets/_rc/resource.py` 替换成压缩包里面的 `resource.py` 试试
[resource.zip](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/files/11188405/resource.zip)

**Comment by zhiyiYo** [comment]
试下：
```python
QTreeView::item:selected {
    background-color: transparent;
}
```

**Comment by zhiyiYo** [comment]
[resource.zip](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/files/11188899/resource.zip)

**Comment by zhiyiYo** [comment]
在 `TreeView` 里面加上 `self.setAllColumnsShowFocus(False)` 呢？

**Comment by zhiyiYo** [comment]
@qianye216 
可以帮我试下 https://github.com/zhiyiYo/PyQt-Frameless-Window/tree/PySide6 在 mac 下能否成功运行 `examples/demo.py` 吗

**Comment by zhiyiYo** [comment]
@Erica-Iris 
感觉你用的是之前下载的包跑的代码，可以试下把 demo.py 放到和 `qframlesswindow` 同一级目录下再运行吗，这样用的是仓库的最新代码而非 pypi 上下载的包的代码

**Comment by Cheukfung** [comment]
gallery的treeview选了父节点，子节点不会全选

**Comment by Cheukfung** [comment]
好吧，我以为是自带的功能

**Comment by zhiyiYo** [comment]
@qianye216 @Cheukfung 
日期和时间选择器组件在 master 分支上发布了，可以帮忙测试一下吗，没问题的话我就要发布到 pypi 上了🙃

**Comment by Cheukfung** [comment]
@zhiyiYo pyqt5测试没问题

**Comment by zhiyiYo** [comment]
> @zhiyiYo pyqt5测试没问题

感谢，macOS 上也没问题吗

**Comment by Cheukfung** [comment]
没问题，datepicker的月份能不能留个接口设置成紧凑的，月份太宽了，不好布局

**Comment by zhiyiYo** [comment]
之后可以接着完善日期时间组件

**Comment by zhiyiYo** [comment]
windows看是居中的吧

**Comment by Cheukfung** [comment]
> windows看是居中的吧

Windows是居中的

**Comment by zhiyiYo** [comment]
> > windows看是居中的吧
> 
> demo那个文件运行就有问题，gallery运行正常

难道又是 mac 的坑

**Comment by zhiyiYo** [comment]
可以参考 Apple Music 的样式写表格控件
![image](https://user-images.githubusercontent.com/65096819/234752488-1bb1328d-22ee-4432-9ad0-3ddfc0881391.png)

**Comment by AuroraZiling** [comment]
抱歉打扰，ListWidget有吗（）
gallery没翻到

**Comment by zhiyiYo** [comment]
暂时没打算写这个组件，因为 QListWidget 一般都要设置自定义的 itemWidget 或者重写委托来绘制

**Comment by AuroraZiling** [comment]
好吧，那只能先凑合用QListWidget（）

**Comment by zhiyiYo** [comment]
下个版本也许可以加上，这个也很简单

**Comment by zhiyiYo** [comment]
@AuroraZiling 
v0.8.6 加了列表组件

**Comment by AuroraZiling** [comment]
![image](https://user-images.githubusercontent.com/69903523/236668187-47f3b616-d2a8-4903-9d74-5af59edea841.png)
刚更新，悲

**Comment by zhiyiYo** [comment]
跑得起来吗

**Comment by AuroraZiling** [comment]
![image](https://user-images.githubusercontent.com/69903523/236668353-b9d0e202-4f9e-4eb3-a0c1-fe3ad39ea52b.png)

**Comment by AuroraZiling** [comment]
哦哦哦，环境冲突了，抱歉

**Comment by zhiyiYo** [comment]
看下版本有没有问题
