### ISSUE TITLE
FluentWindow如何获取侧边栏当前已选中的item的objectname

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#452]
大佬您好，目前遇到一个问题，就是在使用FluentWindow的时候，有时我想根据当前选中的item判断是否要执行某个操作，
目前我是通过执行`self.stackedWidget.widget(self.stackedWidget.currentIndex()).objectName()`来获取的，如果有类似`getCurrentItem`（获取当前已选中侧边栏item的routkey）、`getCurrentItemText`（获取当前已选中侧边栏的item的文本）方法就好了

**Comment by zhiyiYo** [comment]
给 StackedWidget` 加了一个 `currentWidget()` 方法
