### ISSUE TITLE
ScrollArea疑问

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#456]
我在使用qtdesginer操作ScrollArea的时候，发现当控件超出窗口范围时，我无法获取超出范围的控件（当然可以从对象查看器获取，但是不利于我排版），我之前用这个控件不是很多，还望博主赐教，万分感谢！
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/f1ca60ad-0041-4d31-98bf-9c1804e46de6)

**Comment by zhiyiYo** [comment]
qtdesigner我也不太会用

**Comment by youjunxiaji** [comment]
> qtdesigner我也不太会用

好的感谢  主要是控件太多了  手撕有点太累了

**Comment by zhiyiYo** [comment]
或者拖拽一下窗口大小

**Comment by youjunxiaji** [comment]
> 或者拖拽一下窗口大小

这个打开就好了，感谢
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/2dc1c51d-a9c8-46c8-a994-ac58ecf56594)
