### ISSUE TITLE
关于qt-designer中使用组件的问题

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#46]
>  @Ephemeralwanning  
> 可以在qtdesigner用的，比如lineEdit，你在qtdesigner正常添加LineEdit控件，然后右键，把它提升为 LineEdit （作者写的组建名），头文件就写 qfluentwidgets .这样你的ui文件生成py文件的时候，会自动import这个组件

尝试以上方法结果报错
报错信息：
```python
Traceback (most recent call last):
  File "d:/apkTS/code/github/test/demo.py", line 435, in <module>
    w = Window()
  File "d:/apkTS/code/github/test/demo.py", line 312, in __init__
    self.thumbInterface = MainWindow()
  File "d:/apkTS/code/github/test/demo.py", line 69, in __init__
    self.setupUi(self)
  File "d:\apkTS\code\github\test\Mai_UI\thumbs.py", line 153, in setupUi
    self.lineEdit_3 = LineEdit(self.groupBox_2)
  File "d:\apkTS\code\github\test\qfluentwidgets\components\widgets\line_edit.py", line 14, in __init__
    super().__init__(contents, parent)
TypeError: arguments did not match any overloaded call:
  QLineEdit(parent: QWidget = None): too many arguments
  QLineEdit(str, parent: QWidget = None): argument 1 has unexpected type 'QGroupBox'         
```

**Comment by zhiyiYo** [comment]
构造函数没匹配，`LineEdit` 的第一个参数是 `str`

**Comment by Ephemeralwanning** [comment]
> 构造函数没匹配，`LineEdit` 的第一个参数是 `str`

这是ui文件自动生成的py代码，所以并没有传入第一个参数

**Comment by zhiyiYo** [comment]
不能指定参数吗，应该是可以的吧

**Comment by Ephemeralwanning** [comment]
> 不能指定参数吗

应该可以，不过我也不太懂，我研究一下

**Comment by Cheukfung** [comment]
qtdesigner生成的py文件，构造函数是默认的，你可以自定义一个子类，比如：

custom.py
```Python
from qfluentwidgets import LineEdit

class MyLineEdit(LineEdit):
    def __init__(self, parent=None):
        super().__init__('', parent)
```
你在qtdesigner正常添加LineEdit控件，然后右键，把它提升为 MyLineEdit，头文件就写 custom，这样就可以了。

**Comment by Ephemeralwanning** [comment]
> 不能指定参数吗

话说作者大大，为什么我使用`pip install "PyQt-Fluent-Widgets[full]"`命令无法更新呢，目前仍然是0.3.3版本，移除重装也没用，是因为我使用的是豆瓣镜像源还没同步的原因吗

**Comment by Ephemeralwanning** [comment]
> 不能指定参数吗

如果将源码中
`class LineEdit(QLineEdit):
    """ Line edit """

    def __init__(self, contents='', parent=None):
        super().__init__(contents, parent)`

传入的参数改为`*args,**kwargs`，也可以正常运行

`class LineEdit(QLineEdit):
    """ Line edit """

    def __init__(self, *args,**kwargs):
        super().__init__(*args,**kwargs)`

**Comment by UnknownWonder** [comment]
使用qtdesigner，提升QPushButton类为PushButton，代码出现报错：
``` python
TypeError: unable to convert a Python 'QWidget' object to a C++ 'QString' instance
```
源代码：
``` python
class PushButton(QPushButton):
    """ push button """

    def __init__(self, text: str, parent=None, icon: Union[QIcon, str, FluentIconBase] = None):
        super().__init__(text=text, parent=parent)
```
其中`super().__init__`报错，查看了一下text被传入为`QWidget`类型

我直接把`text`参数删掉了，能正确运行，但是感觉不是很好，这个问题有更优雅的修正方法吗？

**Comment by zhiyiYo** [comment]
目前我在考虑重写new方来设置样式表，这样应该就不会破坏构造函数的重载了

**Comment by zhiyiYo** [comment]
在网上看到一篇文章详细介绍了如何在 QtDesigner 中使用这个组件库：https://www.blog.zeeland.cn/archives/eoifh3szz，大家可以参考一下

**Comment by zhiyiYo** [comment]
PyQt5 分支的代码添加了构造函数重载，现在应该不需要自己再继承一次了

**Comment by zhiyiYo** [comment]
录了一个搭配 QtDesigner 的使用教程
https://www.bilibili.com/video/BV1na4y1V7jH

**Comment by CheshireCC** [comment]
请问使用 `qfluentwidgets` 控件还支持 `uic` 动态加载 UI 吗？

**Comment by CheshireCC** [comment]
@zhiyiYo @Ephemeralwanning 
感谢大佬
