### ISSUE TITLE
窗口标题控件溢出

### ISSUE THREAD

**Issue by rainzee** [zhiyiYo/PyQt-Fluent-Widgets#461]
请问为什么 PySide6 版本大于 6.4.2 版本后，窗口标题栏的控件（最小化，最大化，关闭）就会稍微溢出屏幕一点，这是 PySide6 的 BUG 还是预期行为？修复该问题的思路是什么？该问题是否可以被修复？

**Comment by ImmiProgramer** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/454

**Comment by rainzee** [comment]
> #454

我提到了 6.4.2 之后导致溢出，在这里的上下文是这是否是预期的行为？这是 PySide6 的 BUG还是？解决的思路等。

**Comment by zhiyiYo** [comment]
把窗口标志设置为 `FramelessWindowHint` 就会出现此问题，总感觉是 Qt6 的 Bug

**Comment by rainzee** [comment]
> 把窗口标志设置为 `FramelessWindowHint` 就会出现此问题，总感觉是 Qt6 的 Bug

我仔细读了源码，没有发现有什么问题。看起来可能真的是 Qt6 的问题，但是不知道这是不是预期行为。

**Comment by zhiyiYo** [comment]
不太清楚
