### ISSUE TITLE
导航栏新增 interface 丢失

### ISSUE THREAD

**Issue by wHangsHuGe** [zhiyiYo/PyQt-Fluent-Widgets#464]
**Describe the bug**
问题的简要描述。
使用 example 中的 navigation 实例代码，新增由自定义 widget 创建的 interface，在导航栏中没有显示，修改原有 interface 可能导致丢失的问题 

**Environment**
环境信息
- OS: [e.g. Windows10]
-Windows11
- DPI scaling: [e.g. 125%]
- 150%
- Python: [e.g. 3.8.6 64-bit]
- 3.11.4
- PyQt: [e.g. 5.15.2]
- PyQt5
- PyQt-Fluent-Widgets: [e.g 0.2.1]
- 1.1.7

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
class TableWidget(QTableWidget):
    def __init__(self, rows, columns, parent = None):
        super().__init__(rows, columns)
        print("table widget")
        print("row: %d" % rows)

    def keyPressEvent(self, event) -> None:
        if event.key() == Qt.Key_V and (event.modifiers() & Qt.KeyboardModifier.ControlModifier):
            
            clickboard = QApplication.clipboard()

            rows = clickboard.text().split('\n')

            for index_row, row in enumerate(rows):
                values = row.split('\t')
                for index_col, value in enumerate(values):
                    item = QTableWidgetItem(value)
                    self.setItem(index_row, index_col, item)
            super().keyPressEvent(event)

# 修改原有 video interface
self.videoInterface = TableWidget(20, 2)
```

**Expected behavior**

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/71683806/c9425daa-16e7-40fa-8486-15d77f3ef3f8)

丢失原有 demo 中的 music interface

**Comment by zhiyiYo** [comment]
检查一下 ObjectName 设置了吗
