### ISSUE TITLE
PopUpAniStackedWidget、SegmentedWidget组合使用存在空距

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#466]
我在使用PopUpAniStackedWidget、SegmentedWidget控件过程中，我发现在切换过程中会有空距
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/7a004c43-58ab-4e1a-bcb7-c19175346d27)

**Comment by zhiyiYo** [comment]
参见 #443

**Comment by zhiyiYo** [comment]
可能得找个时间来分析一下问题所在，目前只要用了布局就会出现这个问题

**Comment by youjunxiaji** [comment]
> 可能得找个时间来分析一下问题所在，目前只要用了布局就会出现这个问题

不好意思 我才看见  我现在这么写
class MyPopUpAniStackedWidget(fluent_window.StackedWidget):
    pass
然后现在方向是从上往下走，而不是原来的自下而上，这个是正常的吗

**Comment by zhiyiYo** [comment]
把 `popOut` 改成 `False` 试试：
```python
def setCurrentWidget(self, widget, popOut=True):
        if isinstance(widget, QAbstractScrollArea):
            widget.verticalScrollBar().setValue(0)

        if not popOut:
            self.view.setCurrentWidget(widget, duration=300)
        else:
            self.view.setCurrentWidget(
                widget, True, False, 200, QEasingCurve.InQuad)

    def setCurrentIndex(self, index, popOut=True):
        self.setCurrentWidget(self.view.widget(index), popOut)
  ```

**Comment by youjunxiaji** [comment]
> 把 `popOut` 改成 `False` 试试：
> 
> ```python
> def setCurrentWidget(self, widget, popOut=True):
>         if isinstance(widget, QAbstractScrollArea):
>             widget.verticalScrollBar().setValue(0)
> 
>         if not popOut:
>             self.view.setCurrentWidget(widget, duration=300)
>         else:
>             self.view.setCurrentWidget(
>                 widget, True, False, 200, QEasingCurve.InQuad)
> 
>     def setCurrentIndex(self, index, popOut=True):
>         self.setCurrentWidget(self.view.widget(index), popOut)
> ```

解决了 感谢！
