### ISSUE TITLE
tabwidget右键错误

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#467]
当我在tabwidgetitem使用右键，会出现这个bug，我记得以前是没有出现过的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/49d4835e-67a4-46fa-a4dd-bd7d4eba5cc1)
我本身重写了tabwidget控件，部分代码如下：
```python
class MyTableWidget(TableWidget):

    paste_signal = Signal()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # TAG 设置tabwidget属性
        self.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.setContextMenuPolicy(Qt.CustomContextMenu)
        # 创建QMenu信号事件
        self.customContextMenuRequested.connect(self.showMenu)
        self.contextMenu = RoundMenu(self)
        # 分离
        self.CP = QAction('复制')
        self.contextMenu.addAction(self.CP)
        self.JQ = QAction('剪切')
        self.contextMenu.addAction(self.JQ)
        self.NT = QAction('粘贴')
        self.contextMenu.addAction(self.NT)
        # TAG QAction 槽函数连接
        self.CP.triggered.connect(self.copy)
        self.JQ.triggered.connect(self.cut)
        self.NT.triggered.connect(self.paste)
```
但是我不认为是这部分代码出了问题。我觉得可能是qtablewidgetitem的右键重写出了问题（自己猜测）。
**但是这部分功能在qtdesginer中是好的**
<img width="908" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/ed809345-ae28-4e1f-ac2e-da8cecad9845">

**Comment by youjunxiaji** [comment]
PySide6-Fluent-Widgets     1.0.4
PySideSix-Frameless-Window 0.0.5

**Comment by youjunxiaji** [comment]
我尝试更新了一下版本，现在问题已经解决了。顺带请教一下，这部分的功能你写在什么地方了呢？
<img width="190" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/aa5e6c80-25f6-4d0d-93cc-8d811768aa9a">

**Comment by zhiyiYo** [comment]
弹出菜单的功能吗，就是line-edit.py里面

**Comment by youjunxiaji** [comment]
> 弹出菜单的功能吗，就是line-edit.py里面

就是我想修改下tabwidget自带的这个功能，应该修改什么函数呢

**Comment by zhiyiYo** [comment]
createEditor 函数

**Comment by youjunxiaji** [comment]
> 

好的 谢谢  可能是我没看懂，我还是没找到tablewidget中Paste功能所在的位置 ![052BF8C4](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/43a65610-6ccd-414b-bfa9-7338984b70d3)

**Comment by zhiyiYo** [comment]
粘贴功能是 LineEdit 自带的
