### ISSUE TITLE
PySide6-Fluent-Widgets   ComboBoxBase bug 导致ComboBox及其子类无法使用

### ISSUE THREAD

**Issue by lidanqing123** [zhiyiYo/PyQt-Fluent-Widgets#468]
测试时ComboBox无法选定除第一个值之外的其他值，排查发现是qfluentwidgets\components\widgets\combo_box.py 285行的lambda函数问题，x值会被triggered信号值顶替，self._onItemClicked收到的是bool值
。
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/21281783/bbb98036-dda1-4730-8f84-72bafc434f1d)

![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/21281783/e5b8d0bc-4d8a-4547-9a35-cb7aa1387cec)

修改方法可参考下图

![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/21281783/98cb471b-62ac-4441-acb3-ca7b5709f4c4)

**Comment by zhiyiYo** [comment]
我的 pyside6.4.2 和 python3.8 可以收到 index

**Comment by lidanqing123** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by lidanqing123** [comment]
> 我的 pyside6.4.2 和 python3.8 可以收到 index

我用的python3.10，还没试python其他版本

**Comment by lidanqing123** [comment]
> 我的 pyside6.4.2 和 python3.8 可以收到 index

我看pyqt5分支这个地方跟我改后是一样的

**Comment by zhiyiYo** [comment]
因为python3.8收不到checked参数，所以被我移除了

**Comment by zhiyiYo** [comment]
python3.11 也很正常

**Comment by lidanqing123** [comment]
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/21281783/169a95cd-8fa6-45fb-8533-2a7c0461590e)
https://doc.qt.io/qtforpython-6/PySide6/QtGui/QAction.html#PySide6.QtGui.PySide6.QtGui.QAction.toggled
PySide6 中 QAction.toggled 信号是会传checked参数的，还是建议在lambda函数中加上一个额外的位置参数。
我现在需要自己修改源码才可以正常使用

**Comment by lidanqing123** [comment]
不好意思啊，截图截错位置了
https://doc.qt.io/qtforpython-6/PySide6/QtGui/QAction.html#PySide6.QtGui.PySide6.QtGui.QAction.triggered
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/21281783/64ec5bdb-9005-49be-9e24-37d0ec7c7b73)
triggered 的 checked参数 还是会收到

```
import sys
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("My App")

        label = QLabel("Hello!")
        label.setAlignment(Qt.AlignCenter)

        self.setCentralWidget(label)

        toolbar = QToolBar("My main toolbar")
        toolbar.setIconSize(QSize(16, 16))
        self.addToolBar(toolbar)

        button_action = QAction(QIcon("bug.png"), "&Your button", self)
        button_action.setStatusTip("This is your button")
        button_action.triggered.connect(self.onMyToolBarButtonClick)
        button_action.setCheckable(True)
        toolbar.addAction(button_action)

        toolbar.addSeparator()

        button_action2 = QAction(QIcon("bug.png"), "Your &button2", self)
        button_action2.setStatusTip("This is your button2")
        button_action2.triggered.connect(self.onMyToolBarButtonClick)
        button_action2.setCheckable(True)
        toolbar.addAction(button_action2)

        toolbar.addWidget(QLabel("Hello"))
        toolbar.addWidget(QCheckBox())

        self.setStatusBar(QStatusBar(self))

        menu = self.menuBar()

        file_menu = menu.addMenu("&File")
        file_menu.addAction(button_action)
        file_menu.addSeparator()
        file_menu.addAction(button_action2)

    def onMyToolBarButtonClick(self, s):
        print("click", s)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = MainWindow()
    w.show()
    app.exec()

```

**Comment by zhiyiYo** [comment]
单独运行这个示例确实能收到 checked 信号，但是运行 demo 很正常
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/6388a2b6-a56e-4d60-bfb9-218b9fe5469c)
加上 checked 参数会报错：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/fe80643c-b4c2-46cd-926b-250d8caa66e9)

**Comment by zhiyiYo** [comment]
是不是你的pyside版本太高

**Comment by lidanqing123** [comment]
我发现是我的pyside6版本高了，降回到pyside6 6.4.3的话不加c参数可以正常运行

**Comment by lidanqing123** [comment]
会有升级pyside6版本的计划吗

**Comment by zhiyiYo** [comment]
暂时没有

**Comment by Ruchild** [comment]
我今天遇到了同样的问题，研究了3个小时，源码也改来改去，依然没解决，刚才搜了下这个问题，然后我把PySide6 从6.5.3降回到6.4.2，问题解决了！
我真的。。再也不乱升版本了

**Comment by lidanqing123** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by zhiyiYo** [comment]
还是得根据版本号处理一下这个问题
