### ISSUE TITLE
有关FlowLayout布局内容增减的样式错乱，或报错的问题

### ISSUE THREAD

**Issue by OceanYoungY** [zhiyiYo/PyQt-Fluent-Widgets#470]
版本：1.1.8

使用场景：FlowLayout 内设置可增减的 widget，导入不同的数据时，会清除原本的Widget，增加新数据对应的widget

1. FlowLayout 使用 takeAt 方法 删除其内的 widget 时，页面上的元素并没有被清除，还需要配和 deleteLater() 方法使用，但使用此方法清除FlowLayout 中所有的 widget 后，再一次性添加多个widget的时候，所有 widget 会重叠显示，再点击新增按钮，或者修改窗口大小，则所有的 widget 才能正常显示。

2. 使用如下方法时候，一次性添加多个 widget 的时候，所有widget能够正常显示
        for i in range(self.card_layout.count()):
            if not i == 0:
                item = self.card_layout.itemAt(i)
                item.widget().deleteLater()

但是会报一个异常：
TypeError: invalid result from FlowLayout.takeAt(), QWidget cannot be converted to PyQt5.QtWidgets.QLayoutItem in this context

3.删除掉其中一个 widget 的时候，被删 widget 的位置被空着，后面的 widget 并未补上来，再新增或调整整个窗口大小的时候，其他的 widget 才会补上原有的位置。

**Comment by zhiyiYo** [comment]
请按照模板提供复现代码
