### ISSUE TITLE
MessageBox 内容显示错误

### ISSUE THREAD

**Issue by Franknah** [zhiyiYo/PyQt-Fluent-Widgets#476]
如图，Message的排版处理出现问题，主窗口宽度越小换行越多，甚至超出主窗口
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110982569/f9be9dea-2559-436e-8153-646b9b51772d)
呃，能不能加个ScrollArea，这样就不用排版了（

**Comment by AlphaLiu** [comment]
我想这种你需要自己写一个Dialog吧，MessageBox本来就只适合传递简单信息

**Comment by Franknah** [comment]
> 我想这种你需要自己写一个Dialog吧，MessageBox本来就只适合传递简单信息

确实，但是内容一长就这样是不是有点诡异？我只是想用来展示的，想随便调用个Dialog，没必要再自己写一个吧😶
