### ISSUE TITLE
Action().setCheckabled(True)后，如何区分checked状态？

### ISSUE THREAD

**Issue by gamesun** [zhiyiYo/PyQt-Fluent-Widgets#478]
**Describe the bug**
setCheckabled(True)的Action菜单项，有没有√图标 or 其他的标识 or 我的环境问题？

Environment
环境信息

OS: Windows10
DPI scaling: 100%
Python: 3.10.10 64-bit
PySide2: 5.15.2.1
PySide2-Fluent-Widgets: 1.1.7

**Code**
最小复现代码
例程：PyQt-Fluent-Widgets\examples\menu\demo.py

**Screenshots**
![1](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/3817128/fa963859-74a8-4a93-8376-ff88b8c3aa49)

**Comment by zhiyiYo** [comment]
得用 CheckableRoundMenu

**Comment by gamesun** [comment]
OK
