### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by YinBuLiao** [zhiyiYo/PyQt-Fluent-Widgets#48]
**Describe the bug**
Traceback (most recent call last):
  File "D:\Source\PyQt-Fluent-Widgets-master\examples\gallery\demo.py", line 9, in <module>
    from app.view.main_window import MainWindow
  File "D:\Source\PyQt-Fluent-Widgets-master\examples\gallery\app\view\main_window.py", line 13, in <module>
    from .gallery_interface import GalleryInterface
  File "D:\Source\PyQt-Fluent-Widgets-master\examples\gallery\app\view\gallery_interface.py", line 6, in <module>
    from qfluentwidgets import (ScrollArea, PushButton, ToolButton, FluentIcon,
ImportError: cannot import name 'PushButton' from 'qfluentwidgets' (C:\Users\YinBuLiao\AppData\Roaming\Python\Python311\site-packages\qfluentwidgets\__init__.py)

**Environment**
- OS:win11
- DPI scaling: 100%
- Python: 3.11
- PyQt: 5
- PyQt-Fluent-Widgets: 0.45

**To Reproduce**
cd examples/gallery
python demo.py

**Comment by Ephemeralwanning** [comment]
**Run Example**
After installing PyQt-Fluent-Widgets package using pip, you can run any demo in the examples directory, for example:

```
cd examples/gallery
python demo.py
```

**Comment by YinBuLiao** [comment]
I installed from whl normally

**Comment by Sakurapole** [comment]
I meet the same problem，but when I install it from .whl file, I can't make it work normally

**Comment by zhiyiYo** [comment]
@Sakurapole 
可以  `pip show PyQt-Fluent-Widgets` 看下当前包版本是多少吗

**Comment by Sakurapole** [comment]
@zhiyiYo 0.3.3
python是3.9.6，pyqt5是5.12.3

**Comment by zhiyiYo** [comment]
包版本太低了，安装 0.4.7 试试

**Comment by Sakurapole** [comment]
@zhiyiYo OK，明天试试，感谢( •͈ᴗ⁃͈)ᓂ- - -♡﻿

**Comment by YinBuLiao** [comment]
> @zhiyiYo OK，明天试试，感谢( •͈ᴗ⁃͈)ᓂ- - -♡

直接从release下载whl安装就好了

**Comment by Ephemeralwanning** [comment]
> I meet the same problem，but when I install it from .whl file, I can't make it work normally

下载master的zip 将qfluentwidghets文件夹放在项目目录下也行

**Comment by zhiyiYo** [comment]
> > @zhiyiYo OK，明天试试，感谢( •͈ᴗ⁃͈)ᓂ- - -♡
> 
> 直接从release下载whl安装就好了

有的时候 release 页面的 wheel 文件版本可能比 pypi 上的低，因为最近更新太频繁了，还是推荐大家使用 pypi 官网上的 wheel 文件
