### ISSUE TITLE
使用FlowLayout布局时，使用takeAllWidgets的方法清除掉布局中所有的 Widget 之后，再批量增加时，新增加的 Widget 会重叠显示

### ISSUE THREAD

**Issue by OceanYoungY** [zhiyiYo/PyQt-Fluent-Widgets#483]
**Environment**
环境信息
- OS: [e.g. Windows11]
- Python: [3.11.4]
- PyQt: [5.15.9]
- PyQt-Fluent-Widgets: [1.1.8]

使用场景：
FlowLayout 内的 Widget 与进程绑定，新增和删除一个 Widget  都代表一个进程的启动和终止。

问题描述：
使用FlowLayout布局时，使用takeAllWidgets的方法清除掉布局中所有的 Widget 之后，再批量增加时，新增加的 Widget 会重叠显示，

`
       # 删除后再批量增加的代码：
       self.card_layout.takeAllWidgets()
       initWorkers = self._workspace.jm.workers
       for item in initWorkers:
            self._addCard(item)
`
`
    def _addCard(self, item:ProcessWorker):
        """
        在界面上添加一个表示Worker的卡片
        :param: item: 一个Worker的进程
        """
        card = WorkerCard(item,self.card_layout.count() + 1)
        self.card_layout.addWidget(card)
        card._workerStateChangedSignal.connect(self._stateChanged)
`
widget堆叠的效果：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/1a6d5330-d702-4555-8802-9fecaeec34e6)
在widget堆叠的时候，如果鼠标拖动改变窗口大小，则能够恢复实际该有的效果。
 实际该有的效果：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/fb709d85-337a-40ee-8cb6-ee0c2275e052)

**Comment by zhiyiYo** [comment]
加一行 `self.flowLayout.setGeometry(self.flowLayout.geometry())` 试试

**Comment by OceanYoungY** [comment]
想额外问一个问题，怎么使在界面中插入的图片或者 gif 图，在窗口变化的时候，能够等比例的放大缩小？

**Comment by OceanYoungY** [comment]
@zhiyiYo 想额外问一个问题，怎么使在界面中插入的图片或者 gif 图，在窗口变化的时候，能够等比例的放大缩小？

**Comment by zhiyiYo** [comment]
用 ImageLabel 的 scaleWidthTo
