### ISSUE TITLE
是否可以提供组件的快速转换

### ISSUE THREAD

**Issue by Undertone0809** [zhiyiYo/PyQt-Fluent-Widgets#49]
假设一个场景，我现在想要把一个老项目中的button全部转换成 `qfluentwidgets`中的 `PushButton`，请问我需要怎么做？其他类型控件也同理。看了一下代码实现，好像暂时没有提供组件快速转换的功能，能否提供一个快速转换的方式，让开发者可以用最小的成本进行UI主题的转换呢？

**Comment by zhiyiYo** [comment]
qpushbutton和pushbutton应该可以无缝衔接的，vscode搜索替换一下

**Comment by zhiyiYo** [comment]
大部分组件只是把前缀 Q 给去除了

**Comment by Undertone0809** [comment]
如果用qt designer生成ui转py的文件不太好改动，因为如果后期修改了ui文件重新转换成py文件，原来替换的代码就会被覆盖掉。

**Comment by zhiyiYo** [comment]
那只能改改 ui 文件了，可以看看这个：https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/46

**Comment by Undertone0809** [comment]
感谢大佬，想咨询一下大佬平常开发GUI的时候，是用代码开发还是先用QtDesigner生成ui再生成代码呢。
