### ISSUE TITLE
Designer插件中的HeaderCardWidget无法进行布局

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#491]
在Designer中拖入HeaderCardWidget，拖入其他控件后，选择HeaderCardWidget后无法右键进行布局，其他cardWidget正常
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/32c5f477-62cc-43a9-a98c-4e7659b2d6ea)

**Comment by zhiyiYo** [comment]
HeaderCardWidget 已经内置布局了

**Comment by zhiyiYo** [comment]
好像不行，只能像 examples 里面那样手写布局了
