### ISSUE TITLE
Mac下模态对话框中的tablewidget设置右键菜单后无法点击

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#492]
大佬您好，现在遇到一个问题不知道是我使用的问题还是bug，情况如下：
我在主窗口点击按钮，弹出一个模态对话框，模态对话框中有一个Tablewidet，其设置了右键菜单
现在是点击列表右键可以显示菜单，但是点击菜单没反应
如果去掉对话框的模态属性就正常了
但是对比自带的QMenu，不管是否是模态对话框都正常
部分代码如下：
```python
self.menu = RoundMenu(self)
self.delete_item = Action(FIF.DELETE,'删除')
self.delete_item.triggered.connect(self.deleteEngine)
self.menu.addAction(self.delete_item)
self.menu.exec(QCursor.pos())

def deleteEngine(self):
        
        try:
            print('deleteEngine')

        except Exception as e:
            print(e)
```

**Comment by zhiyiYo** [comment]
试下 `app.setAttribute(Qt.AA_DontCreateNativeWidgetSiblings)`

**Comment by zhiyiYo** [comment]
换成 MessageBox 可以吗

**Comment by zhiyiYo** [comment]
不太确定是不是焦点导致的

**Comment by zhiyiYo** [comment]
有没有能跑的起来的代码，周末测试一下

**Comment by zhiyiYo** [comment]
测试了 PyQt6 是可以的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/297b4841-a6e7-4a87-9ff0-0dd5fee46997)

**Comment by zhiyiYo** [comment]
好像只有 PyQt5 有这个问题

**Comment by zhiyiYo** [comment]
怀疑是 Qt 自身的 bug，Qt6 和 Qt5 表格和菜单组件代码相同
