### ISSUE TITLE
ListWidget和StackedWidget如何搭配使用啊？

### ISSUE THREAD

**Issue by winds1983** [zhiyiYo/PyQt-Fluent-Widgets#494]
原版的ListWidget和StackedWidget搭配会用，但使用PyQt-Fluent-Widgets一直没调试好，可以提供个例子吗？
需求是使用ListWidget列出数据列表，点击List后显示详细的数据的form，并进行编辑和保存。

**Comment by zhiyiYo** [comment]
把 QListWidget 替换成 ListWidget 不就好了？

**Comment by winds1983** [comment]
> 

好的，我试下！
