### ISSUE TITLE
【建议】无障碍适配，适配 Windows 中的讲述人应用

### ISSUE THREAD

**Issue by Moxiner** [zhiyiYo/PyQt-Fluent-Widgets#495]
**Describe the bug**
问题的简要描述。

Accessible adaptation for the narrator application in Windows
It is recommended to give a convenient SDK to add attributes for various controls that can be adapted by the narrator
无障碍适配，适配 Windows 中的讲述人应用
建议给出方便的SDK以为各种控件添加讲述人可以适配的属性

**Environment**
环境信息
- OS: Windows 11
- DPI scaling: 150%
- Python: 3.8.6 64-bit
- PyQt:  5.15.9
- PyQt-Fluent-Widgets: 1.1.7

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。

This Issue is a recommendation and does not require a repeat step
此 Issue 为建议，无需复现步骤  

**Code**
最小复现代码
```python
# No code
# 无代码


```

**Expected behavior**

Applications developed using this framework smoothly in Windows Narrator
在 Windows 讲述人 中 流畅使用此框架开发的应用

**Screenshots**

No screenshots
无截图

**Comment by zhiyiYo** [comment]
测试了一下应该没有问题
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/bc517bd0-8859-49e6-bbb4-724d9dfb0bd1)

**Comment by Moxiner** [comment]
并不是，其实是有很多控件不适用无障碍
1. 无障碍无法选择 ```Label``` 控件
2. 采用 ```Navigation``` 布局时，无障碍无法通过键盘切换每个 ```Navigation``` 子页面
3. 仅通过键盘，无法退出 ```TableWidget``` 控件
4. 其他问题我倒是没遇到过 (

**Comment by zhiyiYo** [comment]
可能得设置 QLabel 的可交互属性才能用讲述人？

**Comment by Moxiner** [comment]
我不是很清楚如何给 Label 添加讲述人属性，可以麻烦大佬说明一下嘛……

**Comment by Moxiner** [comment]
而且 `Navigation` 的切换与 `TableWidget` 的退出貌似都有Bug（也可能是微软的锅

**Comment by AlexZhu2001** [comment]
> 我不是很清楚如何给 Label 添加讲述人属性，可以麻烦大佬说明一下嘛……

设置textInteractionFlags属性就行，见[Qt doc](https://doc.qt.io/qt-6/qlabel.html#textInteractionFlags-prop)
如果要实现键盘和鼠标都可以选定，设置为Qt::LinksAccessibleByKeyboard | Qt::LinksAccessibleByMouse就行了
Qt内置的所有控件应该都实现了Accessibility的，自定义控件实现起来好像是非常麻烦，可以考虑以插件形式做。详见[Qt doc](https://doc.qt.io/qt-6/accessible-qwidget.html)
