### ISSUE TITLE
python3.6碰到的问题

### ISSUE THREAD

**Issue by sys98** [zhiyiYo/PyQt-Fluent-Widgets#496]
**Environment**
环境信息
- OS: Windows10
- Python: 3.6.5
- PyQt: [e.g. 5.15.4]
- PyQt-Fluent-Widgets: 1.0.2

python3.6会出现下面的异常，不知道是不是不支持py36
望回复
![图片](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/fb2381af-dffb-4fbc-a8d2-0a88f8e838e8)

**Comment by zhiyiYo** [comment]
换成 3.8 吧
