### ISSUE TITLE
ComboBox信号bug

### ISSUE THREAD

**Issue by sys98** [zhiyiYo/PyQt-Fluent-Widgets#499]
**Describe the bug**
ComboBox在setCurrentIndex无法触发currentTextChanged信号，currentIndexChanged也一样。
如下图，在初始化的时候尽管我有setCurrentIndex(0)的操作，依然无法触发槽函数

**Environment**
环境信息
- OS: Windows10

- Python: 3.7.3
- PyQt: 5.15.4
- PyQt-Fluent-Widgets: 1.0.2

**Screenshots**
![impicture_20230906_202133](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/70613171/3291fa67-783e-4113-bad4-dd80c761aa85)

**Comment by sys98** [comment]
我的组件版本写错了，组件版本是1.1.4

**Comment by keymou** [comment]
> 我的组件版本写错了，组件版本是1.1.4

用新版本试下？， 版本 `1.1.9` 可以正常触发槽函数。
```python
    def __init__(self):
        super().__init__()
        self.comboBox = ComboBox(self)

        items = ['shoko 🥰', '西宫硝子', 'aiko', '柳井爱子']
        self.comboBox.currentTextChanged.connect(lambda: print(self.comboBox.currentText()))
        self.comboBox.addItems(items)
        self.comboBox.setCurrentIndex(0)
```
