### ISSUE TITLE
在重构后，运行，出现找不到依赖的报错

### ISSUE THREAD

**Issue by xianyongjian080402** [zhiyiYo/PyQt-Fluent-Widgets#5]
在此之前我以`pip install -r requirements.txt`安装了依赖库，在试图运行tool_tip时出现问题

不论我是cd到tool_tip目录下还是项目根目录都没用

```
Traceback (most recent call last):
  File "/home/xian/文档/PyQt-Fluent-Widgets/examples/tool_tip/demo.py", line 6, in <module>
    from qfluentwidgets import ToolTip
ModuleNotFoundError: No module named 'qfluentwidgets'
```

**Comment by zhiyiYo** [comment]
要想运行 example 目录下的示例，有两种方法：
1. 克隆这个仓库，然后 `pip install -r requirements.txt`，接着把要运行的示例文件夹里面的文件都拖到 `qfluentwidgets` 的同级目录下，再运行才不会报错；
2. 直接 `pip install qfluentwidgets`，然后直接运行 demo.py 就行（目前我还没把包传到 pypi 上，估计一个小时后会传，吃个饭先🙂）

**Comment by xianyongjian080402** [comment]
okk好的

**Comment by zhiyiYo** [comment]
已经把包上传到 pypi 了，可以试下能否运行
