### ISSUE TITLE
切换主题有bug

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#50]
从某个版本开始，切换 浅色到自动主题的时候会出错

**Comment by zhiyiYo** [comment]
还有这种事，我测试一下

**Comment by zhiyiYo** [comment]
> 表现为，从浅色切换到自动主题，选项会跳到黑色主题，但是一部分组件还是浅色

可能你的系统主题是深色的，所以跳到了深色主题

**Comment by Cheukfung** [comment]
不是，我录个视频给你看，之前版本不是这样的

https://user-images.githubusercontent.com/14865236/228295356-3050412d-f038-4f76-b2d1-1a575649593c.mp4

**Comment by Cheukfung** [comment]
另外lineEdit切换主题后，关闭按钮颜色也不跟随改变

**Comment by zhiyiYo** [comment]
把 `SettingInterface.__setQss`  第 270 行改为 `theme = 'dark' if isDarkTheme() else 'light'` 试试？

**Comment by zhiyiYo** [comment]
我改了一下 `setTheme` 函数，现在单选按钮应该不会出问题了：
```python
def setTheme(theme: Theme, save=False):
    """ set the theme of application

    Parameters
    ----------
    theme: Theme
        theme mode

    save: bool
        whether to save the change to config file
    """
    qconfig.set(qconfig.themeMode, theme, save)
    updateStyleSheet()
```

**Comment by Cheukfung** [comment]
好的，感谢
