### ISSUE TITLE
lineEdit的关闭按钮切换主题无效

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#51]
lineEdit如果设置了关闭按钮，切换主题时，关闭按钮的颜色不跟随。
![image](https://user-images.githubusercontent.com/14865236/228396880-4d4fe0e2-5e0d-41db-847c-9442226eefaa.png)
![image](https://user-images.githubusercontent.com/14865236/228396985-0b103a46-602b-47be-a899-eda6134498a3.png)

**Comment by CryFeiFei** [comment]
来信收到，我会尽快回复您

**Comment by zhiyiYo** [comment]
当初 `clearButton` 直接用的 `QToolButton`，看来得改改了

**Comment by Cheukfung** [comment]
感谢，最近这star蹭蹭往上涨哦

**Comment by zhiyiYo** [comment]
之前在B站上发了个演示的视频，好像大家挺喜欢的🙂
