### ISSUE TITLE
designer改进，希望可以直接打开 UI 文件

### ISSUE THREAD

**Issue by kylinxjd** [zhiyiYo/PyQt-Fluent-Widgets#510]
**Describe the bug**
release 下载的 designer 添加启动参数打开已有的 ui 文件，需要打开designer窗口后再选择 ui 文件。在Pycharm中不方便使用。

**Environment**
- OS: [Windows10]
- DPI scaling: [125%]
- Python: [ 3.10 64-bit]
- PyQt: [ 6 ]
- PyQt-Fluent-Widgets: [ 1.1.9 ]

**To Reproduce**
在命令行打开designer
`D:\FluentDesigner_v1.1.9\designer\designer.exe D:\demo\demo.ui`

**Code**
最小复现代码
```shell
# Minimum code to reproduce the error
D:\FluentDesigner_v1.1.9\designer\designer.exe D:\demo\demo.ui
```

**Expected behavior**
designer.exe 可以附带参数指定 UI 文件直接打开并设计，在Pycharm中就可以直接使用designer打开ui文件。
原生designer中可以`pyqt6-tools designer D:\demo\demo.ui`

**Screenshots**

**Comment by zhiyiYo** [comment]
之后可以加上

**Comment by LxHTT** [comment]
我提pr了  
[使Fluent Designer支持直接打开UI文件而不仅拖放打开 #515](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/pull/515)

**Comment by zhiyiYo** [comment]
已添加该功能
