### ISSUE TITLE
主窗口关闭然后再次显示时进行切换主题操作程序崩溃

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#513]
主窗口点击退出登录操作，调用以下代码：
```python
 
            self.trayIcon.hide()
            self.close()
            self.deleteLater()
            signalBus.logout_Signal.emit()
```
然后回到登录页面，再次登录，再调用主窗口进行显示：
```python
main_window = MainWindow()
 main_window.show()
```
然后到设置页面切换主题，程序崩溃（其他功能都正常，包括更改主题色）：
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/label.py", line 58, in <lambda>
    lambda: self.setTextColor(self.lightColor, self.darkColor))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/qfluentwidgets/components/widgets/label.py", line 75, in setTextColor
    palette = self.palette()
RuntimeError: wrapped C/C++ object of type BodyLabel has been deleted
```

**Comment by zhiyiYo** [comment]
是不是有什么临时组件被析构了，比如 Flyout

**Comment by zhiyiYo** [comment]
deleteLater() 会把子部件也给析构掉

**Comment by zhiyiYo** [comment]
label很奇怪，切换主题的时候重新设置palette不起作用，我能想到的方法就是重新设置样式表

**Comment by zhiyiYo** [comment]
按下面这样改可以吗 @qianye216 
```python
class FluentLabelBase(QLabel):
    """ Fluent label base class """

    @singledispatchmethod
    def __init__(self, parent: QWidget = None):
        super().__init__(parent)
        self._init()

    @__init__.register
    def _(self, text: str, parent: QWidget = None):
        self.__init__(parent)
        self.setText(text)

    def _init(self):
        self.setFont(self.getFont())
        self.setTextColor()
        connect = qconfig.themeChanged.connect(
            lambda: self.setTextColor(self.lightColor, self.darkColor))
        self.destroyed.connect(lambda: self.disconnect(connect))
        return self
```

**Comment by liuyichen** [comment]
@liuyichen @qianye216 又做了下调整，因为程序退出时，偶尔会出现qconfig已经销毁的情况下，无法disconnect报错。 主题切换的问题是可以解决的。
import sip

class FluentLabelBase(QLabel):
    """ Fluent label base class """

    @singledispatchmethod
    def __init__(self, parent: QWidget = None):
        super().__init__(parent)
        self._init()

    @__init__.register
    def _(self, text: str, parent: QWidget = None):
        self.__init__(parent)
        self.setText(text)

    def _init(self):
        self.setFont(self.getFont())
        self.setTextColor()
        set_text_color = lambda: self.setTextColor(self.lightColor, self.darkColor)
        qconfig.themeChanged.connect(set_text_color)
        self.destroyed.connect(lambda: qconfig.themeChanged.disconnect(set_text_color) if not sip.isdeleted(qconfig) else None)
        return self
