### ISSUE TITLE
窗口尺寸强制被改变

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#519]
我摸不清楚其中的规律，其问题如视频所示，其界面最小值尺寸会被强制改变

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/94896689/f9ed8aa9-5ca0-4d40-982a-19c8b4cd729a

**Comment by youjunxiaji** [comment]
这种情况在我单独调用这个widget的时候看起来更加明显，我使用的`position=InfoBarPosition.TOP_RIGHT,`但是现在不在这个位置，是因为自动变大了

**Comment by zhiyiYo** [comment]
没看懂，有没有复现代码

**Comment by youjunxiaji** [comment]
稍等 &nbsp;我知道为什么会出现这个情况了 &nbsp;我把这个问题怎么出现的发给你看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 之一 ***@***.***&gt;
发送时间: 2023年9月30日 19:32
收件人: zhiyiYo/PyQt-Fluent-Widgets ***@***.***&gt;
抄送: 鼬君夏纪 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zhiyiYo/PyQt-Fluent-Widgets] 窗口尺寸强制被改变 (Issue #519)





 
没看懂，有没有复现代码

**Comment by youjunxiaji** [comment]
不好意思 我发晚了  我没有研究底层代码为什么会这样 但是我大概解释一下出现这样情况的原因：
 我第一个widget尺寸过小导致整体的window窗口变小，然后我在尝试resize尺寸后问题得到解决。
