### ISSUE TITLE
Run Example 报错

### ISSUE THREAD

**Issue by LiangZhang0103** [zhiyiYo/PyQt-Fluent-Widgets#52]
Run Example 报错
![image](https://user-images.githubusercontent.com/24890020/228489412-4a0789a7-fb56-4ec5-a765-cdfd09e4bc6c.png)

**Comment by zhiyiYo** [comment]
应该是安装的包版本过低，你现在版本号是多少呀

**Comment by zhiyiYo** [comment]
国内的镜像网站同步速度比较慢，你可以去pypi官网上下载whl文件来安装

**Comment by Cheukfung** [comment]
大概率国内镜像不同步导致安装的低版本，换成阿里云镜像比较新

**Comment by LiangZhang0103** [comment]
pypi官网上下载whl重新安装解决了 @zhiyiYo ，安装版本过低了

**Comment by zhiyiYo** [comment]
> pypi官网上下载whl重新安装解决了 @zhiyiYo ，安装版本过低了

ok
