### ISSUE TITLE
Menu使用addSeparator之后，部分方法调用不合预期

### ISSUE THREAD

**Issue by sannmizu** [zhiyiYo/PyQt-Fluent-Widgets#520]
**Describe the bug**
RoundMenu使用addSeparator之后，部分方法调用不合预期。比如：
1、调用setDefaultAction高亮无法选到正确的Action，选择到Separator上了；
2、调用removeAction remove Separator后面的action时会崩溃；

**Environment**
环境信息
- OS: WIN11
- DPI scaling: 150%
- Python: 3.10.2
- PySide6: 6.5.2
- PyQt-Fluent-Widgets: 1.2

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
见代码
![GIF 2023-9-23 0-22-29](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/53028899/0a04f769-a7c7-4f19-a232-153092a75ee7)

![GIF 2023-9-23 0-23-49](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/53028899/d498793e-2281-4482-8100-dbd304f8f50d)

**Code**
最小复现代码
```python
# coding:utf-8
import sys
from PySide6.QtCore import Qt
from PySide6.QtGui import QAction
from PySide6.QtWidgets import QApplication, QWidget, QHBoxLayout, QLabel
from qfluentwidgets import RoundMenu, setTheme, Theme, Action, MenuAnimationType, MenuItemDelegate, CheckableMenu, MenuIndicatorType
from qfluentwidgets import FluentIcon as FIF


class Demo(QWidget):

    def __init__(self):
        super().__init__()
        self.setLayout(QHBoxLayout())

    def contextMenuEvent(self, e):
        menu = RoundMenu(parent=self)

        # add action
        menu.addAction(Action(FIF.COPY, 'Copy'))

        # add separator
        menu.addSeparator()

        # add action
        act = Action(FIF.CUT, 'Cut')
        menu.addAction(act)

        # BUG1: setDefaultAction
        menu.setDefaultAction(act)
        # BUG2: removeAction
        # menu.removeAction(act)

        # show menu
        menu.exec(e.globalPos(), aniType=MenuAnimationType.DROP_DOWN)


if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = Demo()
    w.show()
    app.exec()
```

**原因定位**
RoundMenu中addSeparator方式是通过加入一个QListWidgetItem来实现分隔符的，调用了父类的addItem
```python
item = QListWidgetItem(self.view)
item.setFlags(Qt.NoItemFlags)
item.setSizeHint(QSize(w, 9))
self.view.addItem(item)
```
但是在setDefaultAction中，是通过查找action在self._actions中的索引位置来设置当前行的：
```python
index = self._actions.index(action)
self.view.setCurrentRow(index)
```
这样如果中间插入了分隔符，就会导致索引位置产生偏差了。

同理removeAction方法也是通过索引来查找的Item：
```python
index = self._actions.index(action)
item = self.view.takeItem(index)
super().removeAction(action)
```
这样就会取错item，从而出现异常。

应该所有使用索引来查找action对应item的地方都会因为分隔符导致出现异常，我只用了这两函数，所以就提出来了。可以修改一下，计算下有多少个分隔符，要给索引增加几个偏移量。

**Comment by zhiyiYo** [comment]
感谢反馈，应该使用 action 的 item 动态属性来获取 item，这样就不会有下标偏移问题了
