### ISSUE TITLE
QCompleter 检索导致页面卡顿

### ISSUE THREAD

**Issue by witech-king** [zhiyiYo/PyQt-Fluent-Widgets#523]
**Describe the bug**
QCompleter过多导致检索卡顿

**Environment**
环境信息
- OS: [e.g. Windows10]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.6.9 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 1.0.2]

**To Reproduce**
items长度为3866出现卡顿要8s
耗时代码\qfluentwidgets\components\widgets\line_edit
setCompletion
```python
 for i in items:
     self.addAction(QAction(i, triggered=lambda c, x=i: self.lineEdit.setText(x)))
```

**Code**
最小复现代码
```python
# Minimum code to reproduce the error
class CSearchLineedit(SearchLineEdit):

    def __init__(self, parent=None):
        super(CSearchLineedit, self).__init__(parent)
        self.setClearButtonEnabled(True)

    def set_completer(self, search_info_list):
        search_completer = QCompleter(search_info_list, self)
        search_completer.setCaseSensitivity(Qt.CaseInsensitive)
        search_completer.setFilterMode(Qt.MatchContains)
        self.setCompleter(search_completer)
```

**Expected behavior**

**Screenshots**

**Comment by witech-king** [comment]
复现视频

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/137036346/2ca6707b-c7b1-4733-bb1b-6714c6440acf

**Comment by zhiyiYo** [comment]
目前已修复此问题，延迟为 0
