### ISSUE TITLE
gallery demo，暗黑模式（Dark Mode）下主题亮度条（brightSlider）颜色选择无法生效；白天模式下的却可以

### ISSUE THREAD

**Issue by Justin62628** [zhiyiYo/PyQt-Fluent-Widgets#524]
**Describe the bug**
gallery demo，暗黑模式（Dark Mode）下主题亮度条（brightSlider）颜色选择无法生效；白天模式下的却可以

**Environment**
环境信息
- OS: Windows10
- DPI scaling: 200%
- Python: 3.7.9 64-bit
- PyQt: 5.15.2
- PyQt-Fluent-Widgets: latest

**To Reproduce**
使用官方demo即可复现

**Expected behavior**

**Screenshots**
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/37169106/85f7dc50-3647-44a0-8db6-85c513c7a6ee)

**Comment by zhiyiYo** [comment]
这里选择的是浅色模式下的主题色，深色模式下会把选中的颜色的饱和度调到最高
