### ISSUE TITLE
pyqt6 branch 中 由于CalendarPicker组件导致designer无法加载

### ISSUE THREAD

**Issue by qiauil** [zhiyiYo/PyQt-Fluent-Widgets#525]
**Describe the bug**
**qt6 branch** 中 直接调用tools/designer.py 无法打开designer。
经排查后发现问题出现在plugins/date_time_plugin.py中的`CalendarPickerPlugin`类。
只要屏蔽该类就可以正常打开designer并成功注册其它组件。
进一步排查发现问题出现在CalendarPicker组件中的`dateFormat = pyqtProperty(Qt.DateFormat, getDateFormat, setDateFormat)`这一行代码中，只要屏蔽该行代码即可正常加载该组件到designer中。
进一步分析后猜测问题应该在`setDateFormat`方法上。该方法将接收的`format`参数赋值给CalendarPicker的`_dateFormat`变量。`_dateFormat`在定义时给的初值为`str`类型，而`dateFormat = pyqtProperty(Qt.DateFormat, getDateFormat, setDateFormat)`这行代码将注册一个`Qt.DateFormat`类型的变量作为`setDateFormat`的参数。这导致designer在导入的时候传入`Qt.DateFormat`类型参数给`setDateFormat`方法引发赋值类型错误（`Qt.DateFormat`赋值给`str`）。

**Environment**
环境信息
- OS: Windows11
- DPI scaling: 150%
- Python: 3.11.5
- PyQt6                  6.4.2
- PyQt6-Fluent-Widgets   1.2.0

**To Reproduce**
tools目录下输入`python .\designer.py` 后designer无法打开。
屏蔽plugins/date_time_plugin.py中的`CalendarPickerPlugin`类后一切正常。
或屏蔽`\site-packages\qfluentwidgets\components\date_time`中的`dateFormat = pyqtProperty(Qt.DateFormat, getDateFormat, setDateFormat)`后一切正常。

**Comment by qiauil** [comment]
好吧，其实是getDateFormat的问题，这个函数在designer加载的时候默认返回初始str类型的_date_tim, 但是`dateFormat = pyqtProperty(Qt.DateFormat, getDateFormat, setDateFormat)`要求返回`Qt.DateFormat`类型。将`dateFormat = pyqtProperty(Qt.DateFormat, getDateFormat, setDateFormat)`改为dateFormat = pyqtProperty(str, getDateFormat, setDateFormat)也能正常工作。

**Comment by zhiyiYo** [comment]
感谢，已修复此问题
