### ISSUE TITLE
Menu Bug in Dark Mode

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#528]
show bottom border in dark mode when move curser bottom to top

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/cdeb8965-e32a-4685-972f-9085840f00d2

**Comment by zhiyiYo** [comment]
I think this is a problem for QT itself

**Comment by immiProgrammer** [comment]
> I think this is a problem for QT itself

did u face that issue?

**Comment by immiProgrammer** [comment]
> I think this is a problem for QT itself

I am 70% sure this is a Qt stylesheet problem (not QFluentWidgets) I will test it later and if the issue persists I'll consider closing it
