### ISSUE TITLE
navigation menu treewidget on bottom

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#530]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/ce25e98b-c400-49d4-ab19-f0a377b1f54a

**Comment by zhiyiYo** [comment]
You should add item to `NavigationItemPosition.SCROLL`

**Comment by immiProgrammer** [comment]
> You should add item to `NavigationItemPosition.SCROLL` 

But I need on bottom
