### ISSUE TITLE
Pyside6 FluentWindow navigation creates memory leaks.

### ISSUE THREAD

**Issue by apooreapo** [zhiyiYo/PyQt-Fluent-Widgets#531]
**Describe the bug**
When switching on different tabs in a FluentWindow, some serious memory leaks are created.

**Environment**
- OS: [Windows10]
- DPI scaling: [125%]
- Python: [3.9.13 64-bit]
- PySide: [6.4.2]
- PyQt-Fluent-Widgets: [1.2.2]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
1. Run /examples/gallery/demo.py
2. Open task manager, so that you can see memory usage
3. Switch between tabs and see how the memory usage is temporary rising

**Expected behavior**
Memory should be only rising when opening the tabs for the first time. After that, it should not rise any further.

**Screenshots**

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/35412051/11222e85-d9e0-484c-8b48-325e034fda4e

**Comment by riferg206** [comment]
I've noticed the same when scrolling on a sufficiently large ScrollArea or populating/interacting with a TreeWidget, both inside a FluentWindow. I've been using PySide6-Fluent-Widgets 1.2.2 on Python 3.11.5.

**Comment by zhiyiYo** [comment]
This is a bug of PySide6 itself
