### ISSUE TITLE
dead link in docs

### ISSUE THREAD

**Issue by hannesdelbeke** [zhiyiYo/PyQt-Fluent-Widgets#533]
this docs page https://qmaterialwidgets.vercel.app/pages/navigation
contains the following dead link: https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/master/examples/navigation2

**Comment by zhiyiYo** [comment]
The usage of qmaterialwidgets is almost the same as that of qfluentwidgets, so I did not rewrite its document, but instead reused the document of qfluentwidgets.
