### ISSUE TITLE
custom messageBox

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#535]
when showing message and setFocus on lineEdit
i face that problem only 1 time

#show in terminal:
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::translate: Painter not active
QPainter::worldTransform: Painter not active
QWidgetEffectSourcePrivate::pixmap: Painter not active
QPainter::worldTransform: Painter not active
QPainter::setWorldTransform: Painter not active
QPainter::setWorldTransform: Painter not active

**Comment by Atumyugi** [comment]
How did you solve this problem?

**Comment by keymou** [comment]
How did you solve a similar problem that you encountered? Help

**Comment by immiProgrammer** [comment]
@Atumyugi, are you facing this issue?
I don't know how to fix this problem based on past occurrences.
Please provide me with the minimum code required to reproduce the issue, and I will try to fix it again.
