### ISSUE TITLE
Tooltips and teaching tips don't work on multiple-screen setups

### ISSUE THREAD

**Issue by apooreapo** [zhiyiYo/PyQt-Fluent-Widgets#536]
**Describe the bug**
When having a setup with more than one screen, the teaching tips and tooltips don't work as expected. The tooltips are only shown on the primary screen. For example, if I have configured my second screen to be positioned above the primary screen, and I run the demo on my second screen, the tooltip will be shown on the top of the primary screen.

**Environment**
环境信息
- Windows 10
- Have tried with multiple dpis
- Python: 3.9.13 64-bit
- PyQt: both PyQt6 and PySide6
- PyQt-Fluent-Widgets: 1.2.2

**To Reproduce**
1. Use a multiple screen setup (have 2 or more connected screens that do not mirror each other)
2. Position the main application window on the secondary screen
3. Run a teaching tooltip
4. Observe that the tooltip is not in the correct position
**Code**

```

**Expected behavior**
The tooltip should be shown in the correct position, independently of the screen configuration.

**Comment by zhiyiYo** [comment]
Thank  you for reporting this problem. PyQt5 branch has fixed this issue.

**Comment by apooreapo** [comment]
The problem continues to exist on the vertical dimension. If I position my secondary screen above the primary, the tooltip stil appears on the primary screen.
