### ISSUE TITLE
启用showMenuButton时，navigationInterface 的MenuButton错位。

### ISSUE THREAD

**Issue by kingmo888** [zhiyiYo/PyQt-Fluent-Widgets#548]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/17401091/ed98183a-6d14-4bc3-895c-b26ff1fd2a98)

```
self.navigationInterface = NavigationInterface(
            self, showMenuButton=True, showReturnButton=False)
```
当启用showMenuButton时，三等号按钮激活位置只在红框（下沿为分界线）下方了。红框下沿的上方，鼠标划过、点击无反应。

**Comment by zhiyiYo** [comment]
最小复现代码贴下

**Comment by zhiyiYo** [comment]
你没给主界面的 hBoxLayout 设置顶部 margin，导致标题栏和导航栏按钮重叠了

**Comment by zhiyiYo** [comment]
或者你就重写主界面 resizeEvent，把标题栏往左移动 60px
