### ISSUE TITLE
Best way to adapt theme for non PyQt-Fluent-Widgets

### ISSUE THREAD

**Issue by maziggy** [zhiyiYo/PyQt-Fluent-Widgets#549]
I'm wondering what's the best way to adapt the theme for widgets which are not part of the PyQt-Fluent-Widgets. For example I'm using a lot of QGroupBoxes in my current project (please see attached screenshots) and need to adapt the theme.

![Screenshot 2023-10-08 at 08 13 38](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/17797632/ebb25603-75f5-4b28-9c65-f3cfb24cfffb)
![Screenshot 2023-10-08 at 08 13 27](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/17797632/1a412f39-b0d8-4168-8f8f-073d8f69a1dd)

**Comment by zhiyiYo** [comment]
Check the document please. https://qfluentwidgets.com/pages/theme
