### ISSUE TITLE
Add spinbox without buttons

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#550]
[Site](https://learn.microsoft.com/en-us/windows/apps/design/controls/number-box#formatting-input)
![Image](https://learn.microsoft.com/en-us/windows/apps/design/controls/images/numberbox-formatted.png)

**Comment by immiProgrammer** [comment]
How can use 
.setButtonSymbols(QSpinBox.NoButtons)

**Comment by immiProgrammer** [comment]
[this line of code in qss will effect](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/08237d9498fd327a5dc3b7639b7e6f4f8b6d69f0/qfluentwidgets/_rc/qss/dark/spin_box.qss#L16) when use `setFixedWidth`
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/07f57dc7-9344-40b4-8f3c-6d4c78aa8582)

**Comment by zhiyiYo** [comment]
You can use setCustomStyleSheet to adjust the padding-right
