### ISSUE TITLE
[HELP] How to add menubar? Also, is there any way to use this with PyQt6?

### ISSUE THREAD

**Issue by rohankishore** [zhiyiYo/PyQt-Fluent-Widgets#551]
How can I add a menu bar to the app?

Using: PySide6
Python: 3.11

**Comment by zhiyiYo** [comment]
You should use FramelessMainWindow. Check this example: https://github.com/zhiyiYo/PyQt-Frameless-Window/blob/PySide6/examples/main_window.py
