### ISSUE TITLE
对`TransparentToolButton`组件`setFixedSize` 函数设置Icon时无法生效，是否考虑增加自定义`ToolButton` size功能？

### ISSUE THREAD

**Issue by keymou** [zhiyiYo/PyQt-Fluent-Widgets#558]
**Describe the bug**
对`TransparentToolButton`组件`setFixedSize` 函数设置Icon时无法生效，是否考虑增加自定义按钮size功能？

**Environment**
环境信息

OS: [e.g. Windows 7]
DPI scaling: [100%]
Python: [3.8.6 64-bit]
PyQt: [5.15.2]
PyQt-Fluent-Widgets: [1.0.2]

暂时我是通过`ToolButton`初始化中`self.setIconSize(QSize(16, 16))`来设置特定size

**Comment by zhiyiYo** [comment]
不是可以 `button.setIconSize()` 吗？

**Comment by keymou** [comment]
可以了，忘了可以通过`setIconSize()`设置图标大小
