### ISSUE TITLE
menu item icon bug

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#559]
when change item size

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/f00f48d5-1b71-443f-a438-3e159dddeeeb)

to fix it
```
        menu.setItemHeight(n)
        menu.view.setIconSize(QSize(h:=(menu.itemHeight//2), h))
```
best results for 'n' item height

**Comment by zhiyiYo** [comment]
This should be done by user.

**Comment by immiProgrammer** [comment]
> This should be done by user.

Plz don't mind I am highlight that issue u can fix it in qfluentwidgets or help for other users
