### ISSUE TITLE
Navigation侧边栏添加的菜单如果设置的是Scroll属性，焦点定位后按左右方向键会左右发生位移

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#560]
触摸板左右滑动也会，能否屏蔽左右方向上的滚动只保留垂直方向的滚动
![2023-10-12 11 56 15](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/788c4fad-e7c3-4353-8c87-a07ba0824c13)

**Comment by zhiyiYo** [comment]
应该换成 SingleDirectionScrollArea

**Comment by zhiyiYo** [comment]
已修复此问题
