### ISSUE TITLE
ExpandSettingCard控件出现错位

### ISSUE THREAD

**Issue by gcc2001** [zhiyiYo/PyQt-Fluent-Widgets#561]
**Describe the bug**
所有继承ExpandSettingCard的控件，在对窗口大小进行调整时，会导致这些控件出现错位的问题

**Environment**
环境信息
- OS: [e.g. Windows10] Windows 11
- DPI scaling: [e.g. 125%] 125%
- Python: [e.g. 3.8.6 64-bit] python 3.10.11
- PyQt: [e.g. 5.15.2] 5.15.2
- PyQt-Fluent-Widgets: [e.g 0.2.1] 1.2.7

**To Reproduce**
![问题界面](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/95568606-22ef-440a-913b-23cf3e0ee18b)

**Code**
由于是针对![gallery](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/releases/download/v1.2.7/PyQt-Fluent-Widgets-Gallery_v1.2.7_windows_x64.7z)测试，所以没有代码

**Expected behavior**
所有集成ExpandSettingCard的控件不会出现错位
![预期界面](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/d53039c1-2288-40f1-ad59-7c48dc7b39be)

目前测试只需要在截图中标注的位置增加一句代码即可解决该问题
![需要增加的代码](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/798728af-851e-4cf4-b2b2-fc7e998425a4)

**Comment by zhiyiYo** [comment]
已修复此问题
