### ISSUE TITLE
[HELP] How can I add QDockWidget to MSFluentWindow? 

### ISSUE THREAD

**Issue by rohankishore** [zhiyiYo/PyQt-Fluent-Widgets#565]
How can I add QDockWidget to MSFluentWindow? I can't use the "addDockWidget" method. Help please. And also, it HAS to be MSFluentWindow. Thanks in advance

**Comment by zhiyiYo** [comment]
You can't use `addDockWidget`, bacause the super class of MSFluentWindow is QWidget

**Comment by rohankishore** [comment]
Oh ok. Thanks for letting me know.
