### ISSUE TITLE
关于FluentWindow的QEvent事件问题

### ISSUE THREAD

**Issue by gcc2001** [zhiyiYo/PyQt-Fluent-Widgets#566]
经过测试发现FramelessWindow有closeEvent()方法，但是FluentWindow却没有closeEvent()方法，有没有什么方法可以自己写一个closeEvent()方法，尝试看源码没有弄清楚该如何重写，谢谢！

**Comment by zhiyiYo** [comment]
继承 FluentWindow 之后重写 closeEvent
