### ISSUE TITLE
ProgressBar布局问题

### ISSUE THREAD

**Issue by gcc2001** [zhiyiYo/PyQt-Fluent-Widgets#568]
**Describe the bug**
当对ProgressBar添加setOrientation(Qt.Vertical)后，没有按照预期垂直排列，IndeterminateProgressBar也是同样的问题

**Environment**
环境信息
- OS: [e.g. Windows10] Windows 11
- DPI scaling: [e.g. 125%] 125%
- Python: [e.g. 3.8.6 64-bit] 3.10.11
- PyQt: [e.g. 5.15.2] 5.15.2
- PyQt-Fluent-Widgets: [e.g 0.2.1] 1.3.1

**To Reproduce**

![错误 垂直排列](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/43594ea8-cd31-4e5a-9379-fdb4fbc5bea1)
![正确 水平排列](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/fb82d4f3-1a49-446e-baab-d4ddc32f1228)

**Code**
截图中已展示，基于![demo.py](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/master/examples/status_info/info_bar/demo.py)进行修改

**Expected behavior**
如果设置垂直排列，显示的效果如下
![预期的垂直排列](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/144214115/22d82ced-2d14-437a-a98e-13aef0812a76)

**Comment by zhiyiYo** [comment]
因为没写垂直布局的进度条
