### ISSUE TITLE
SettingCard Drop-down resize

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#569]
Expand SettingCard Drop-down then resize window Drop-down width in not changed to change it close drop-down and expand again to fix it

I provided u video later
U can try it

**Comment by immiProgrammer** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/86b858f7-14c6-4ef2-9046-6be1abac231a

**Comment by zhiyiYo** [comment]
try 1.3.1
