### ISSUE TITLE
comboBox下拉选项间距为0

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#57]
选项之间应该有个margin，另外下拉菜单最好能像Windows一样，位置覆盖在comboBox上面
![image](https://user-images.githubusercontent.com/14865236/229001418-43e88790-5d9a-4d03-a516-00b9a05a7a4f.png)
![image](https://user-images.githubusercontent.com/14865236/229001481-d988740e-c1a5-4ac2-bbbb-f968f6347f09.png)

**Comment by zhiyiYo** [comment]
下拉框有好几种，照片里面就是显示在下方
![image](https://user-images.githubusercontent.com/65096819/229001887-7aec9f6d-d282-453f-8a73-4fa49add155b.png)

**Comment by Cheukfung** [comment]
> 

这是在哪个界面的，我好像在系统没见过上面这种

![image](https://user-images.githubusercontent.com/14865236/229002128-2e362714-4458-43cc-ad2b-6774b4ab9abf.png)

**Comment by zhiyiYo** [comment]
照片软件

**Comment by Cheukfung** [comment]
那目前就是两个问题：1.选项之间没有距离，2.comboBox打开的情况下，再次点击的逻辑应该是关闭，现在是重新打开一次。

**Comment by zhiyiYo** [comment]
下次改改，目前在写 `InfoBar`

**Comment by zhiyiYo** [comment]
目前重复弹出菜单的问题已解决，但是 item 之间的间距不太好搞，直接 `MenuActionListWidget.setSpacing` 会同时改变水平和竖直方向的间距

**Comment by Cheukfung** [comment]
不能通过添加margin实现吗

**Comment by zhiyiYo** [comment]
加上 margin 的话会影响到第一个或者最后一个 item 的间距

**Comment by Cheukfung** [comment]
可以用伪状态 :first :last试试

**Comment by zhiyiYo** [comment]
qt 好像不支持 :first 和 :last 伪选择器

**Comment by Cheukfung** [comment]
支持的

**Comment by Cheukfung** [comment]
好像是QTabBar才支持。。

**Comment by Cheukfung** [comment]
那不能把ContentsMargins的上边距减小吗，比如上边距减少4px，item的margin-top就加回来了

**Comment by zhiyiYo** [comment]
不知道有没有更优雅一点的方法，实在不行的话只能这么干了

**Comment by Cheukfung** [comment]
![image](https://user-images.githubusercontent.com/14865236/229290294-6d58d975-d42f-40f4-b6b8-7d17e872d93c.png)
