### ISSUE TITLE
ColorDialog view error

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#570]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/ba9261b4-989d-44b8-8876-f18fde8138e7

the demo example of colordialog is fine

**Comment by LxHTT** [comment]
Looks like a QPainter conflict. Trying to cut out some animation or effects?

**Comment by zhiyiYo** [comment]
偶尔会出现这个问题，但是概率极低

**Comment by immiProgrammer** [comment]
How can fix it
