### ISSUE TITLE
在teaching_tip的demo中，CustomFlyoutView(FlyoutViewBase)重写paintEvent每次回触发两次

### ISSUE THREAD

**Issue by liuqiang1111** [zhiyiYo/PyQt-Fluent-Widgets#571]
**Environment**
环境信息
- OS: [e.g. Windows10]
- Python: [e.g. 3.9 64-bit]
- PyQt: [e.g. 5.15.2]
- PyQt-Fluent-Widgets: [e.g 0.3.2]

**To Reproduce**
复现问题的步骤，推荐使用 gif 进行演示。
Steps to reproduce the behavior(you can use gif to demonstrate the problem:)
最小复现代码
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52993562/caf1fe6e-d45a-4380-bd40-191293042325)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/52993562/566cacbc-8032-4aba-939d-bd67afae975c)

```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by zhiyiYo** [comment]
正常，调整大小等事件触发的时候都会导致重绘
