### ISSUE TITLE
按照视频里做的，但到了脚本打开ｑｔｄｅｓｉｇｎｅｒ时，显示没有ｄｅｓｉｇｎｅｒ．ｐｙ,请问这是怎么回事

### ISSUE THREAD

**Issue by thechosenonehaiou** [zhiyiYo/PyQt-Fluent-Widgets#578]
### What do you want?

![2023-10-21_000053](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/48875640/9dd34437-c13c-40c9-90a9-6923ea7a201e)

**Comment by zhiyiYo** [comment]
需要下载仓库代码
