### ISSUE TITLE
Qss 样式异常

### ISSUE THREAD

**Issue by Wings-Looo** [zhiyiYo/PyQt-Fluent-Widgets#579]
Windows11 22H2 22621.2428
Python 3.10
Gallery 基于 release V1.3.2 最新代码
运行 Gallery 的 demo 时发现当窗体未被聚焦时样式正常，为 Qss 中设置的样式；当窗体被聚焦时样式背景显示异常

聚焦时：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/16877298/d43c149a-b216-4ad6-a96d-ce1e22cf0d6f)
未聚焦时：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/16877298/1d59a7e0-bf23-4c5c-84bb-b375b5af76d9)
请问有遇到此种问题么？

**Comment by Wings-Looo** [comment]
在 win11 个性化 - 颜色 - 开启透明效果 后会出现此问题

**Comment by zhiyiYo** [comment]
设置界面关了云母效果就行
