### ISSUE TITLE
添加QVideoWidget播放组件后需要变化页面才能加载

### ISSUE THREAD

**Issue by s772970282** [zhiyiYo/PyQt-Fluent-Widgets#58]
具体表现为添加播放器组建后，打开页面无法立即渲染，需要变化页面大小后（通过放大缩小或者左侧菜单变化后）才可以出现

**Comment by zhiyiYo** [comment]
可以提供一下最小复现代码和环境信息吗

**Comment by s772970282** [comment]
估计是FlowLayout布局导致的问题，我嵌套一个QWidget()追加后无问题了
