### ISSUE TITLE
[Feature]: 可以增加一个下拉多选的组件么

### ISSUE THREAD

**Issue by niuzijia** [zhiyiYo/PyQt-Fluent-Widgets#580]
### What do you want?

可以增加一个下拉多选的组件么，类似如下图片的这种
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68538774/da041e06-e1ea-4005-abab-790352389844)

**Comment by zhiyiYo** [comment]
商业版加了
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/82ea70b9-d923-4191-b3e1-9c64227dd6de)
