### ISSUE TITLE
Demo 中有木马

### ISSUE THREAD

**Issue by FrankSFLYS** [zhiyiYo/PyQt-Fluent-Widgets#582]
### What happened?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/10843159/d9187b18-af68-44f3-9023-738ae8b4be7d)

### Operation System

Windows 11 23H2

### Python Version

Python

### PyQt/PySide Version

PyQt

### PyQt/PySide-Fluent-Widgets Version

1.3.2

### How to Reproduce?

QFluentWidgets_v1.3.2.zip 和 PyQt-Fluent-Widgets-Gallery_v1.3.;2_windows_x64.7z 中解压出来的 exe 均报告有特洛伊木马。

**Comment by zhiyiYo** [comment]
cpp demo文件被我加固过了，defender会误报

**Comment by zhiyiYo** [comment]
不甘心的话就用沙盒跑一下吧

**Comment by zhiyiYo** [comment]
不放心的话就用沙盒跑一下吧
