### ISSUE TITLE
No module named 'qmaterialwidgets'

### ISSUE THREAD

**Issue by anselzhou** [zhiyiYo/PyQt-Fluent-Widgets#583]
大佬，我安装的是PyQt-Fluent-Widgets[full]。做出来的UI文件运行之后为什么会提示ModuleNotFoundError: No module named 'qmaterialwidgets'。

**Comment by zhiyiYo** [comment]
你是不是用错库了

**Comment by zhiyiYo** [comment]
qmaterilwidgets 是我林外一个组件库

**Comment by anselzhou** [comment]
我UI文件搞出来转py文件下面就多一行：
self.BodyLabel_3.setText(_translate("MainWindow", "德玛西亚"))
from qmaterialwidgets import BodyLabel, ListWidget, ProgressRing, TitleLabel
import resource_rc

**Comment by zhiyiYo** [comment]
你用错 designer 了，自己检查下

**Comment by anselzhou** [comment]
我是代码也直接下载下来的QMaterialWidgets-master这个。请问要下载哪个？

**Comment by zhiyiYo** [comment]
下载 PyQt-Fluent-Widgets 的

**Comment by anselzhou** [comment]
下载太。。。慢。。。。。。了。。。。。。
等下载下来我再试一下。

**Comment by anselzhou** [comment]
我自己不知道在哪下载的版本，现在git作者的就搞好了。
