### ISSUE TITLE
Config enhancement

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#585]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/64049c895f04977a8519fea24012b7fab222ce4f/qfluentwidgets/common/config.py#L313C9-L313C46

70 times faster
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/d11c2256-e314-4ebe-a56a-ca4dc6051bca)

**Comment by zhiyiYo** [comment]
Thanks, next version will add this patch

**Comment by immiProgrammer** [comment]
Directly use `        styleSheetManager.deregister(widget)`
And remove appending and again iterate the remove list

**Comment by immiProgrammer** [comment]
[Directly use `        styleSheetManager.deregister(widget)`
And remove appending and again iterate the remove list](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/master/qfluentwidgets/common/style_sheet.py#L354)
