### ISSUE TITLE
调整表格和树状组件表头样式

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#586]

**Comment by immiProgrammer** [comment]
TabelView header border color
If you think it would be good to do so u can do this

**Comment by zhiyiYo** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/9f35156f-b666-48ed-8795-1e396296f1e6)
