### ISSUE TITLE
使用贝塞尔曲线优化动画

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#587]
https://www.figma.com/file/Nz1B4Xrt5cH9FQ0d2zvOc5/Windows-UI-3-(Community)?node-id=2265%3A5171&mode=dev

**Comment by zhiyiYo** [comment]
下面是一个 point to point 的例子：
```python
curve = QEasingCurve(QEasingCurve.Type.BezierSpline)
curve.addCubicBezierSegment(QPointF(0.55, 0.55), QPointF(0, 1), QPointF(1, 1))
slideAni.setEasingCurve(curve)
slideAni.setDuration(187)
```

**Comment by zhiyiYo** [comment]
计划添加 FluentAnimation 类

**Comment by immiProgrammer** [comment]
> 计划添加 FluentAnimation 类
Good plan

**Comment by immiProgrammer** [comment]
> 计划添加 FluentAnimation 类

Thanks

**Comment by zhiyiYo** [comment]
计划优化下述组件的动画：
* PopUpStackedWidget
* Pivot
* SwitchButton

**Comment by zhiyiYo** [comment]
SwitchButton 动画有点奇怪，还是换回去
