### ISSUE TITLE
[Install Error] cannot import name 'InfoBar' from 'qfluentwidgets' 

### ISSUE THREAD

**Issue by chunleili** [zhiyiYo/PyQt-Fluent-Widgets#59]
**Describe the bug**

**Environment**
- OS: [Windows10]
- Python: [e.g. 3.10.9 64-bit]

  File "D:\Dev\PyQt-Fluent-Widgets\examples\gallery\demo.py", line 9, in <module>
    from app.view.main_window import MainWindow
  File "D:\Dev\PyQt-Fluent-Widgets\examples\gallery\app\view\main_window.py", line 21, in <module>
    from .status_info_interface import StatusInfoInterface
  File "D:\Dev\PyQt-Fluent-Widgets\examples\gallery\app\view\status_info_interface.py", line 5, in <module>
    from qfluentwidgets import (StateToolTip, ToolTipFilter, PushButton, PixmapLabel,
ImportError: cannot import name 'InfoBar' from 'qfluentwidgets' (C:\Users\GRBJ200045\.conda\envs\ti-build\lib\site-packages\qfluentwidgets\__init__.py)

**Comment by zhiyiYo** [comment]
InfoBar is a new component and I haven't publish it to pypi. You can move  subfiles and subfolders of gallery folder to project root folder, then run demo.py should work well.

**Comment by zhiyiYo** [comment]
@chunleili 
I have released the new version package to pypi. You can now run `demo.py` directly.
