### ISSUE TITLE
使用mobaxterm，x-server打开frameless相关窗口，页面无法使用鼠标拖动，最大化最小化失效

### ISSUE THREAD

**Issue by witech0103** [zhiyiYo/PyQt-Fluent-Widgets#590]
### What happened?

在win10上使用mobaxterm进入Ubuntu18.04.6 Xserver打开的窗口无法移动，最大化最小化

### Operation System

Windows10

### Python Version

3.6.9

### PyQt/PySide Version

5.15.4

### PyQt/PySide-Fluent-Widgets Version

1.3.1

### How to Reproduce?

​​​​​​
![test](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/58321577/7da1a2dd-c9b4-48cb-9586-ab9a80051a96)

### Minimum code

```python3
null
```

**Comment by zhiyiYo** [comment]
Dulpliacted with https://github.com/zhiyiYo/PyQt-Frameless-Window/issues/129
