### ISSUE TITLE
能否添加一个设定ScrollArea鼠标默认滚动XY轴的功能？

### ISSUE THREAD

**Issue by wsyong111** [zhiyiYo/PyQt-Fluent-Widgets#591]
能不能添加一个函数来设定ScrollArea在鼠标滚动时默认滚动X轴还是Y轴？

**Comment by wsyong111** [comment]
直接继承ScrollArea来重写wheelEvent不会有反应

**Comment by zhiyiYo** [comment]
换成 SingleDirectionScrollArea 试试，把参数换成 Qt.Horizontal

**Comment by wsyong111** [comment]
谢谢，能用了
