### ISSUE TITLE
使用`setWindowIcon`设置主窗口图标，同时将这个图标设置为屏闪，运行时屏闪图标显示正常，但主窗口图标设置不生效，可能原因是什么？

### ISSUE THREAD

**Issue by keymou** [zhiyiYo/PyQt-Fluent-Widgets#592]
**Describe**
使用`setWindowIcon`设置主窗口图标，同时将这个图标设置为屏闪，运行时屏闪图标显示正常，但主窗口图标设置不生效，可能原因是什么？

**Environment**

OS: [e.g. Windows 7]
DPI scaling: [100%]
Python: [3.8.6 64-bit]
PyQt: [5.15.2]
PyQt-Fluent-Widgets: [1.3.0]

```python
    def initWindow(self):

        self.resize(960, 780)
        self.setMinimumWidth(1469)
        self.setWindowIcon(QIcon(':/app/images/logo.png'))
        self.setWindowTitle(self.tr('Test platform'))
        self.titleBar.setAttribute(Qt.WA_StyledBackground)
        # 启动屏闪
        self.splash = SplashScreen(self.windowIcon(), self)
        self.splash.setIconSize(QSize(106, 106))
        self.splash.raise_()
        # 窗口置桌面中央位置
        desktop = QApplication.desktop().availableGeometry()
        w, h = desktop.width(), desktop.height()
        self.move(w//2 - self.width()//2, h//2 - self.height()//2)
        self.show()
        QApplication.processEvents()
```

**Comment by zhiyiYo** [comment]
给个能跑起来的完整例子

**Comment by keymou** [comment]
> 给个能跑起来的完整例子

还没能找到最小复现代码，从项目中抽取出来代码可以正常显示窗口图标 :confused: 
我再试试 :sob:

**Comment by immiProgrammer** [comment]
> > 给个能跑起来的完整例子
> 
> 还没能找到最小复现代码，从项目中抽取出来代码可以正常显示窗口图标 :confused: 
> 我再试试 :sob:
> 

Maybe parent issue 
Dont forget to set parent when creating a widget (like QWidget(parent=self))

**Comment by keymou** [comment]
> > > 给个能跑起来的完整例子
> > 
> > 
> > 还没能找到最小复现代码，从项目中抽取出来代码可以正常显示窗口图标 😕
> > 我再试试 😭
> 
> Maybe parent issue Dont forget to set parent when creating a widget (like QWidget(parent=self))

Thank you for your reply, but the window with the problem is the main window, has no parent window.
