### ISSUE TITLE
help required

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#593]
plz tell me which tool u can use to py to exe

**Comment by immiProgrammer** [comment]
plz tell me

**Comment by zhiyiYo** [comment]
I use pyinstaller at most of the time

**Comment by immiProgrammer** [comment]
> I use pyinstaller at most of the time
Thanks for replying
But in my case
When executing .exe files created with PyInstaller, antivirus (like windows defender) often blocks them.
