### ISSUE TITLE
TableWidget 表格 动画卡顿

### ISSUE THREAD

**Issue by znahovo** [zhiyiYo/PyQt-Fluent-Widgets#596]
TableWidget 表格 
如果我加载了100行,有20个列, 那么我最大化的时候表格 下滚会卡顿
窗口缩小到800*600不会明显卡顿
请问下现在tablewidget可以显示比较多的数据 最大化时不卡顿嘛?

**Comment by zhiyiYo** [comment]
按模板重新开个 issue 进行提问
