### ISSUE TITLE
[Bug]: 更新至1.3.5后，下拉框获得焦点后文字周围会出现黑色框线

### ISSUE THREAD

**Issue by pth2000** [zhiyiYo/PyQt-Fluent-Widgets#598]
### What happened?

更新至1.3.5后，下拉框获得焦点后文字周围会出现黑色框线。
不清楚是否为特性。

### Operation System

win11

### Python Version

3.9.9

### PyQt/PySide Version

pyside6

### PyQt/PySide-Fluent-Widgets Version

1.3.5

### How to Reproduce?

见内容。

### Minimum code

```python3
略。
```

**Comment by immiProgrammer** [comment]
U can use 
setFocusPolicy(Qt.NoFocus)
