### ISSUE TITLE
PyQt6 Support

### ISSUE THREAD

**Issue by sumeshir26** [zhiyiYo/PyQt-Fluent-Widgets#6]

**Comment by zhiyiYo** [comment]
Some components of PyQt-Fluent-Widgets depend on PyQt-Frameless-Window, but the PyQt6 branch of PyQt-Frameless-Window does not support Linux system at present.

**Comment by sumeshir26** [comment]
Okay, thanks

**Comment by zhiyiYo** [comment]
@sumeshir26 
I have added support for PyQt6, you can download the code in [PyQt6 branch](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/PyQt6).

**Comment by sumeshir26** [comment]
> @sumeshir26 I have added support for PyQt6, you can download the code in [PyQt6 branch](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/tree/PyQt6).

Thank you so much. Really appreciate your work!
