### ISSUE TITLE
fluent window maximized bug

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#600]
window is resizeable on maximized

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/970a3149-3a05-4d79-b865-b9bf12f933f3

in demo example qframelesswindow this bug is not shown

**Comment by immiProgrammer** [comment]
Ignore green overlay when cursor touch display boundaries

**Comment by rainzee** [comment]
Please provide the minimum reproduction code

**Comment by immiProgrammer** [comment]
Fluent window example

**Comment by immiProgrammer** [comment]
> Please provide the minimum reproduction code

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/master/examples/window/fluent_window/demo.py

**Comment by rainzee** [comment]
？

**Comment by immiProgrammer** [comment]
When window is maximized window is resize able by pushing with mouse cursor
On the other hand other windows is to resize able 
In qframelesswindow examples

**Comment by zhiyiYo** [comment]
AcrylicWindow 会有这个问题，修复不了， FramelessWindow 不会有此问题

**Comment by immiProgrammer** [comment]
> When window is maximized window is resize able by pushing with mouse cursor
> On the other hand other windows is not resize able 
> In qframelesswindow examples

**Comment by immiProgrammer** [comment]
> AcrylicWindow 会有这个问题，修复不了， FramelessWindow 不会有此问题

Sry for FramelessWindow it is my typing mistake
