### ISSUE TITLE
请问如何隐藏或者禁用窗口按钮

### ISSUE THREAD

**Issue by dingtom** [zhiyiYo/PyQt-Fluent-Widgets#601]
试了网上找到的答案都不行，谢谢！

**Comment by dingtom** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/35419759/37a5283d-ddc8-4fa6-a567-83b4b33fa6a2)
这些

**Comment by zhiyiYo** [comment]
`self.titleBar.xxBtn.hide()`

**Comment by dingtom** [comment]
十分感谢😁
