### ISSUE TITLE
Dialog里隐藏控件后窗口大小不会重新调整

### ISSUE THREAD

**Issue by AIchar** [zhiyiYo/PyQt-Fluent-Widgets#604]
### What happened?

如下图，用一个SwitchButton控制lineEdit显示和隐藏，显示的时候窗口会自适应调整大小，但隐藏的时候不会调整大小，而且控件都是靠下对齐的，我的用法有问题吗？
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/24260957/8f7efd0d-be21-49cb-adfe-5f7fa7701e50)

### Operation System

Windows 11 22h2

### Python Version

3.11 64bit

### PyQt/PySide Version

PYQT 5.15

### PyQt/PySide-Fluent-Widgets Version

1.3.5

### How to Reproduce?

 直接运行下面的代码

### Minimum code

```python3
import sys
from qfluentwidgets import BodyLabel, Dialog, CardWidget, SwitchButton, LineEdit
from PyQt5.QtCore import Qt, QPoint, pyqtSignal
from PyQt5.QtWidgets import QVBoxLayout, QHBoxLayout, QGroupBox, QWidget, QGridLayout, QSizePolicy, QFileDialog, \
    QApplication

class FlashOptionEditDialog(Dialog):


    class SettingCard(CardWidget):

        switchClickSignal = pyqtSignal(str)
        def __init__(self, title, parent=None):
            super().__init__(parent)

            self.setFixedWidth(300)
            self.vBoxLayout = QVBoxLayout(self)
            self.hBoxLayout = QHBoxLayout()

            label = BodyLabel(title)
            self.btnRegxStart = SwitchButton()
            self.btnRegxStart.label.hide()
            self.editRegx = LineEdit()
            self.editRegx.hide()
            self.hBoxLayout.addWidget(label, alignment=Qt.AlignLeft)
            self.hBoxLayout.addWidget(self.btnRegxStart, alignment=Qt.AlignRight)

            self.btnRegxStart.checkedChanged.connect(self.onBtnClick)
            self.vBoxLayout.addLayout(self.hBoxLayout)
            self.vBoxLayout.addWidget(self.editRegx)

        def onBtnClick(self, isCheck):

            if isCheck:
                self.switchClickSignal.emit('1')
                self.editRegx.show()
            else:
                self.switchClickSignal.emit('2')
                self.editRegx.hide()

    def __init__(self, config=None, name=None, parent=None):
        super().__init__('下载框编辑', '', parent=parent)
        self.config = config
        self.setFixedWidth(300)
        self.name = ''

        self.settingWidget = QWidget()
        vBoxLayout = QVBoxLayout()
        self.settingWidget.setLayout(vBoxLayout)

        cardStartRegx = self.SettingCard("使用开始正则")
        cardProcessRegx = self.SettingCard("使用处理正则")
        cardEndtRegx = self.SettingCard("使用结束正则")

        cardStartRegx.switchClickSignal.connect(self.test)
        cardProcessRegx.switchClickSignal.connect(self.test)
        cardEndtRegx.switchClickSignal.connect(self.test)


        vBoxLayout.addWidget(cardStartRegx)
        vBoxLayout.addWidget(cardProcessRegx)
        vBoxLayout.addWidget(cardEndtRegx)
        vBoxLayout.setContentsMargins(1, 1, 1, 1)

        self.vBoxLayout1 = vBoxLayout

        self.textLayout.addWidget(self.settingWidget)


        print(f'size:{self.size()}  {self.settingWidget.size()}')

    def test(self, hh):
        print(f'size:{self.size()}  {self.settingWidget.size()}')
        if hh == '1':
            print('1')
        else:
            print('2')
        # self.resize(self.width(), self.height())
        print(f'size1:{self.size()}  {self.settingWidget.size()}')


app = QApplication(sys.argv)
w = FlashOptionEditDialog()
w.show()
ret = app.exec_()
```

**Comment by keymou** [comment]
> ### What happened?
> 如下图，用一个SwitchButton控制lineEdit显示和隐藏，显示的时候窗口会自适应调整大小，但隐藏的时候不会调整大小，而且控件都是靠下对齐的，我的用法有问题吗？ ![image](https://user-images.githubusercontent.com/24260957/280579724-8f7efd0d-be21-49cb-adfe-5f7fa7701e50.png)
> 
> ### Operation System
> Windows 11 22h2
> 
> ### Python Version
> 3.11 64bit
> 
> ### PyQt/PySide Version
> PYQT 5.15
> 
> ### PyQt/PySide-Fluent-Widgets Version
> 1.3.5
> 
> ### How to Reproduce?
> 直接运行下面的代码
> 
> ### Minimum code
> ```python
> import sys
> from qfluentwidgets import BodyLabel, Dialog, CardWidget, SwitchButton, LineEdit
> from PyQt5.QtCore import Qt, QPoint, pyqtSignal
> from PyQt5.QtWidgets import QVBoxLayout, QHBoxLayout, QGroupBox, QWidget, QGridLayout, QSizePolicy, QFileDialog, \
>     QApplication
> 
> class FlashOptionEditDialog(Dialog):
> 
> 
>     class SettingCard(CardWidget):
> 
>         switchClickSignal = pyqtSignal(str)
>         def __init__(self, title, parent=None):
>             super().__init__(parent)
> 
>             self.setFixedWidth(300)
>             self.vBoxLayout = QVBoxLayout(self)
>             self.hBoxLayout = QHBoxLayout()
> 
>             label = BodyLabel(title)
>             self.btnRegxStart = SwitchButton()
>             self.btnRegxStart.label.hide()
>             self.editRegx = LineEdit()
>             self.editRegx.hide()
>             self.hBoxLayout.addWidget(label, alignment=Qt.AlignLeft)
>             self.hBoxLayout.addWidget(self.btnRegxStart, alignment=Qt.AlignRight)
> 
>             self.btnRegxStart.checkedChanged.connect(self.onBtnClick)
>             self.vBoxLayout.addLayout(self.hBoxLayout)
>             self.vBoxLayout.addWidget(self.editRegx)
> 
>         def onBtnClick(self, isCheck):
> 
>             if isCheck:
>                 self.switchClickSignal.emit('1')
>                 self.editRegx.show()
>             else:
>                 self.switchClickSignal.emit('2')
>                 self.editRegx.hide()
> 
>     def __init__(self, config=None, name=None, parent=None):
>         super().__init__('下载框编辑', '', parent=parent)
>         self.config = config
>         self.setFixedWidth(300)
>         self.name = ''
> 
>         self.settingWidget = QWidget()
>         vBoxLayout = QVBoxLayout()
>         self.settingWidget.setLayout(vBoxLayout)
> 
>         cardStartRegx = self.SettingCard("使用开始正则")
>         cardProcessRegx = self.SettingCard("使用处理正则")
>         cardEndtRegx = self.SettingCard("使用结束正则")
> 
>         cardStartRegx.switchClickSignal.connect(self.test)
>         cardProcessRegx.switchClickSignal.connect(self.test)
>         cardEndtRegx.switchClickSignal.connect(self.test)
> 
> 
>         vBoxLayout.addWidget(cardStartRegx)
>         vBoxLayout.addWidget(cardProcessRegx)
>         vBoxLayout.addWidget(cardEndtRegx)
>         vBoxLayout.setContentsMargins(1, 1, 1, 1)
> 
>         self.vBoxLayout1 = vBoxLayout
> 
>         self.textLayout.addWidget(self.settingWidget)
> 
> 
>         print(f'size:{self.size()}  {self.settingWidget.size()}')
> 
>     def test(self, hh):
>         print(f'size:{self.size()}  {self.settingWidget.size()}')
>         if hh == '1':
>             print('1')
>         else:
>             print('2')
>         # self.resize(self.width(), self.height())
>         print(f'size1:{self.size()}  {self.settingWidget.size()}')
> 
> 
> app = QApplication(sys.argv)
> w = FlashOptionEditDialog()
> w.show()
> ret = app.exec_()
> ```

继承 `Dialog` 直接在文本布局`textLayout`中插入自定义控件类`SettingCard`

```python
class FlashOptionEditDialog(Dialog):

    def __init__(self, title: str = '下载框设置', content: str = '', config=None, name=None, parent=None):
        super().__init__(title=title, content=content, parent=parent)
        self.config = config
        self.setFixedWidth(300)
        self.name = name

        self.cardStartRegx = SettingCard("使用开始正则")
        self.cardProcessRegx = SettingCard("使用处理正则")
        self.cardEndtRegx = SettingCard("使用结束正则")

        self.cardStartRegx.switchClickSignal.connect(self.test)
        self.cardProcessRegx.switchClickSignal.connect(self.test)
        self.cardEndtRegx.switchClickSignal.connect(self.test)

        self.textLayout.insertWidget(1, self.cardStartRegx, 0, Qt.AlignTop)
        self.textLayout.insertWidget(2, self.cardProcessRegx, 0, Qt.AlignTop)
        self.textLayout.insertWidget(3, self.cardEndtRegx, 0, Qt.AlignTop)

    def test(self, hh):
        if hh == '1':
            print('1')
        else:
            print('2')
        # self.resize(self.width(), self.height())
        self.adjustSize()
```

**Comment by zhiyiYo** [comment]
你没有设置布局的 Alignment，或者就干脆在下面加一个 stretch，这些都和对话框没什么关系
