### ISSUE TITLE
Switching to a sub-interface 

### ISSUE THREAD

**Issue by deeffest** [zhiyiYo/PyQt-Fluent-Widgets#606]
Is there an option to move from one Sub Interface to another? For example, in 1 interface I have a button, when I press it I want to go to the 2nd interface. Is it possible to do it by myself or can we hope that this functionality will be implemented in future updates?

**Comment by rainzee** [comment]
请参考 exampls/gallery/app/component/SampleCard
希望你能多阅读源码，进行一些思考，这样也能使你快速上手框架，不是吗？

```
def switchToSample(self, routeKey, index):
        """ switch to sample """
        interfaces = self.findChildren(GalleryInterface)
        for w in interfaces:
            if w.objectName() == routeKey:
                self.stackedWidget.setCurrentWidget(w, False)
                w.scrollToCard(index)
```

**Comment by zhiyiYo** [comment]
`FluentWindow.switchTo(interface: QWidget)`
