### ISSUE TITLE
[Bug]: TypeError: arguments did not match any overloaded call:   QPushButton(parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'   QPushButton(text: Optional[str], parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'   QPushButton(icon: QIcon, text: Optional[str], parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'

### ISSUE THREAD

**Issue by dazui20** [zhiyiYo/PyQt-Fluent-Widgets#608]
### What happened?

ModuleNotFoundError: No module named 'qfluentwidgets'

### Operation System

window

### Python Version

3.9

### PyQt/PySide Version

pyside

### PyQt/PySide-Fluent-Widgets Version

1.3.1

### How to Reproduce?

/

### Minimum code

```python3
/
```

**Comment by dazui20** [comment]
TypeError: arguments did not match any overloaded call:
  QPushButton(parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'
  QPushButton(text: Optional[str], parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'
  QPushButton(icon: QIcon, text: Optional[str], parent: Optional[QWidget] = None): argument 1 has unexpected type 'PySide2.QtWidgets.QWidget'

**Comment by zhiyiYo** [comment]
组件库不是最新的，而且连复现代码都没有
