### ISSUE TITLE
FolderListSettingCard 组件，布局调整宽度后，下拉子项没有对应调整

### ISSUE THREAD

**Issue by niuzijia** [zhiyiYo/PyQt-Fluent-Widgets#609]
FolderListSettingCard 组件，布局调整宽度后，下拉子项没有对应调整
![)NT)FL86KD28R9FAG_)D47C](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68538774/d73c3df3-744c-4d32-9478-1bddbda00e3a)
如图，组件不会根据缩小同步进行缩小，右边的X号，缩小一点就会看不到了

**Comment by zhiyiYo** [comment]
已修复此问题
