### ISSUE TITLE
更新对PySide6的支持

### ISSUE THREAD

**Issue by XiangQinxi** [zhiyiYo/PyQt-Fluent-Widgets#61]
我需要使用PySide6进行开发，但是本项目的只提供PyQt5的最新版

**Comment by XiangQinxi** [comment]
PyPi上的版本也只更新到1.x.x版本

**Comment by zhiyiYo** [comment]
去pypi官网下载whl文件

**Comment by XiangQinxi** [comment]
不是，我要是能在PyPI官网找到，我就不会来这了，最新版本还在0.2.8

**Comment by zhiyiYo** [comment]
0.2.8就是最新版本呀

**Comment by XiangQinxi** [comment]
那为什么我安装后报错有些方法没有，而在github上下载的却能正常使用

**Comment by zhiyiYo** [comment]
奇怪，我等下看看

**Comment by zhiyiYo** [comment]
0.2.8应该就是最新的，pypi上打包的源代码里面就有 `InfoBar`，`pip show PySide6-Fluent-Widgets` 看下自己下载的包版本号是不是 0.2.8

**Comment by Cheukfung** [comment]
要不统一一下pyqt pyside的版本号？

**Comment by zhiyiYo** [comment]
已经统一了
