### ISSUE TITLE
[Bug]: FramelessWebEngineView 搭配 FluentWindow 会导致窗口绘制异常

### ISSUE THREAD

**Issue by Hpero4** [zhiyiYo/PyQt-Fluent-Widgets#610]
### What happened?

我查阅了 PyQt-Fluent-Widgets 和 PyQt-Frameless-Window 中关于 QWebEngineView 的 Issues, 并在项目中使用了 qframelesswindow.webengine.FramelessWebEngineView 来替代 QWebEngineView , 但它似乎带来了新的问题.

我在项目中添加了一个 FramelessWebEngineView 控件, 无论它是否有显示在当前的页面中, 都会导致页面绘制异常.

在鼠标移入或有动画产生时尤为明显, 看上去就像是界面会一直叠加. 

并且, 这个问题仅出现于 Mica Enabled 时.

它似乎是某一个控件导致的, 我曾尝试在 PyQt-Frameless-Window 的 web_engine.py 中, 将 FramelessWindow 改为 FluentWindow 尝试复现它但并未能成功.

它可以在 PyQt-Fluent-Widgets 的演示demo中快速复现, Patch 请参考 Minimum code.

也有可能是我的用法有误, 还请dalao指点一下 _(:з」∠)_

### Operation System

Windows11 22H2

### Python Version

Python 3.8.17

### PyQt/PySide Version

PyQt5 5.15.9

### PyQt/PySide-Fluent-Widgets Version

PyQt-Fluent-Widgets 1.2.0

### How to Reproduce?

此处仅演示现象, 复现代码请参考 Minimum code .

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/40506420/dbc4307e-e7c6-416c-8cdc-c6111c5db9bc

### Minimum code

```python3
Subject: [PATCH] bug reproduce
---
Index: examples/gallery/app/view/main_window.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/examples/gallery/app/view/main_window.py b/examples/gallery/app/view/main_window.py
--- a/examples/gallery/app/view/main_window.py	(revision cd65a7718abc427f83a76fd65ff1903c5a1fc3a3)
+++ b/examples/gallery/app/view/main_window.py	(date 1699445608843)
@@ -1,10 +1,11 @@
 # coding: utf-8
 from PyQt5.QtCore import QUrl, QSize
 from PyQt5.QtGui import QIcon, QDesktopServices
-from PyQt5.QtWidgets import QApplication
+from PyQt5.QtWidgets import QApplication, QHBoxLayout
+from qframelesswindow.webengine import FramelessWebEngineView
 
 from qfluentwidgets import (NavigationAvatarWidget, NavigationItemPosition, MessageBox, FluentWindow,
-                            SplashScreen)
+                            SplashScreen, SmoothScrollArea)
 from qfluentwidgets import FluentIcon as FIF
 
 from .gallery_interface import GalleryInterface
@@ -51,6 +52,13 @@
         self.textInterface = TextInterface(self)
         self.viewInterface = ViewInterface(self)
 
+        self.testInterface = SmoothScrollArea(self)
+        self.testInterface.hBoxLayout = QHBoxLayout(self)
+        self.testInterface.browser = FramelessWebEngineView(self)
+        self.testInterface.browser.load(QUrl("https://qfluentwidgets.com/"))
+        self.testInterface.hBoxLayout.addWidget(self.testInterface.browser)
+        self.testInterface.setObjectName('testInterface')
+
         # enable acrylic effect
         self.navigationInterface.setAcrylicEnabled(True)
```

**Comment by Hpero4** [comment]
FYI 

web_engine.py 中尝试复现时所使用的代码, 它看起来一切正常

```python
# coding:utf-8
import sys

import qfluentwidgets
from PyQt5.QtCore import QUrl, Qt
from PyQt5.QtWidgets import QApplication, QHBoxLayout
from qfluentwidgets import FluentWindow, SmoothScrollArea

from qframelesswindow import StandardTitleBar
from qframelesswindow.webengine import FramelessWebEngineView


class Window(FluentWindow):

    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setMicaEffectEnabled(True)

        self.interface = SmoothScrollArea(self)
        self.interface.setObjectName("testInterface")

        self.addSubInterface(self.interface, qfluentwidgets.FluentIcon.TAG, "test")

        # change the default title bar if you like
        self.setTitleBar(StandardTitleBar(self))
        self.hBoxLayout = QHBoxLayout(self.interface)

        # must replace QWebEngineView with FramelessWebEngineView
        self.webEngine = FramelessWebEngineView(self)

        self.hBoxLayout.setContentsMargins(0, self.titleBar.height(), 0, 0)
        self.hBoxLayout.addWidget(self.webEngine)

        # load web page
        self.webEngine.load(QUrl("https://qfluentwidgets.com/"))
        self.resize(1200, 800)

        self.titleBar.raise_()


if __name__ == "__main__":
    # enable dpi scale
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
    
    app = QApplication(sys.argv)
    demo = Window()
    demo.show()
    app.exec()
```

**Comment by zhiyiYo** [comment]
亚克力窗口的透明样式表可能会导致这个问题

**Comment by zhiyiYo** [comment]
一种解决办法是把无边框窗口下载下来，放在项目里面，这样导入的不会是 site-packages 里面的 qframelesswindow，而是你下载的这个

**Comment by zhiyiYo** [comment]
然后把 `qframelesswindow/windows/__init__.py` 的 `AcrylicWindow` 构造函数的`self.setStyleSheet("AcrylicWindow{background:transparent}")` 注释掉

**Comment by zhiyiYo** [comment]
感觉还是有必要给 FramelessWindow 添加一个 useWebEngine 参数来控制设置透明属性

**Comment by Hpero4** [comment]
感谢回复~

我按照您提到的进行了修改, 动画的拖影问题解决了, 但窗口会被蒙上一层白色的遮罩, 有一部分控件能显示在它之上
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/40506420/80a854d7-3b3f-43be-812d-e4d44269c871)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/40506420/31b54a2c-53fb-4394-8d10-b537a638aab1)

**Comment by zhiyiYo** [comment]
这个没碰到过，你有调用 `addSubInterface` 来添加 testInterface 吗

**Comment by Hpero4** [comment]
> 这个没碰到过，你有调用 `addSubInterface` 来添加 testInterface 吗

我没有在上述示例中调用addSubinterface, testInterface并未在界面中;
我对两种情况都进行了测试, 它是否在界面中似乎不影响这层白色遮罩的出现.

---
并且, 在存在白色遮罩时, 进行以下操作会有特殊的表现:
1. 在设置界面中将Mica关闭再启用, 届时背景会显示为完全透明, 切换窗口（Alt\Win+Tab）、切换明暗主题、再次切换Mica会使界面恢复正常(没有白色遮罩)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/40506420/0d4903fc-c03b-4faf-8fac-337f46b4051e)

2. 在设置界面中, 切换一次明暗主题, 白色遮罩会消失, 界面恢复正常
3. 在代码中, 显式调用一次 `setTheme(cfg.get(cfg.themeMode))`, 遮罩也会消失, 界面恢复正常

**Comment by dariofervenza** [comment]
Hello!

I am having issues with FluentWindow, in one of my subinterfaces when i add a QWebEngineView or a FramelessWebEngineView, the fluent interface changes and it goes totally black. 
![Screenshot 2024-01-14 145111](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54205459/aba23bad-5fc8-4bef-95de-bb15cce745ec)
I have tryed to uninstall the packages but i am gettign the same output, Python 3.11.4

**Comment by zhiyiYo** [comment]
PyQt5 banch has a web engine example. You can check it.

**Comment by mengdeer589** [comment]
或许你可以试试，设置FluentWindow，self.setMicaEffectEnabled(False)，我在win11平台上成功避免了这个异常
