### ISSUE TITLE
[Issue]: 关于组件风格

### ISSUE THREAD

**Issue by TcDhlPro** [zhiyiYo/PyQt-Fluent-Widgets#613]
### What happened?

老哥能不能整个mac风格的, windows上mac风格的, 这不卖的飞起

### Operation System

Windwos

### Python Version

3.10.6

### PyQt/PySide Version

PySide6/PyQt5

### PyQt/PySide-Fluent-Widgets Version

1.3.1

### How to Reproduce?

...

### Minimum code

```python3
...
```

**Comment by zhiyiYo** [comment]
mac 也没多好看吧😂
