### ISSUE TITLE
希望可以添加一个支持多选的OptionsSettingCard

### ISSUE THREAD

**Issue by AirJerryWhite** [zhiyiYo/PyQt-Fluent-Widgets#615]

**Comment by zhiyiYo** [comment]
Pro 版本有

**Comment by immiProgrammer** [comment]
How can buy or use pro version

**Comment by zhiyiYo** [comment]
@immiProgrammer You can buy it from [here](https://qfluentwidgets.com/price). It only supports PySide6/2. You are not allowed to use it in open source community. Please read the [User Agreement](https://afdian.net/item/b9c1f79e027911eeb4295254001e7c00) carefully before purchasing it.
