### ISSUE TITLE
m3u8的支持

### ISSUE THREAD

**Issue by xiaoqiangclub** [zhiyiYo/PyQt-Fluent-Widgets#616]
- 我有一个需求，就是希望能在pyside6中实现m3u8流视频的播放，试了一下模块里面的VideoWidget，mp4的网络视频可以正常的播放，但是m3u8却无法播放，请教一下我要如何写才能实现对m3u8的支持，或者希望能增加对m3u8视频的支持，谢谢！

**Comment by zhiyiYo** [comment]
自己用 ffmpeg 写一个吧
