### ISSUE TITLE
InfoBar长消息显示问题

### ISSUE THREAD

**Issue by marrylin2019** [zhiyiYo/PyQt-Fluent-Widgets#62]
![image](https://user-images.githubusercontent.com/55835892/229263804-e1050ab2-241c-4a43-a22c-b6cd5aadf8b0.png)
是我的使用方式不对吗，我看代码中是有调节尺寸的部分的。
这是一个使用了navigation的UI。这个InfoBar出现在一个属于navigation的页面（继承自ScrollArea），这页面类中创建了一个ScrollArea控件和ExpandLayout(综合参考你给出的setting和gallary两个demo)，创建的InfoBar传递的parent为self(继承自ScrollArea的页面)

**Comment by zhiyiYo** [comment]
能贴一下最小复现代码吗

**Comment by marrylin2019** [comment]
[Test.txt](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/files/11128439/Test.txt)


在您的navigation demo中添加TestInterface这个页面即可复现。如果不行，我可以把mainwindow_interface.py文件内容粘贴。

**Comment by marrylin2019** [comment]
> > 可以贴一下最小复现代码吗
> > ![image](https://user-images.githubusercontent.com/8281775/229265391-990a8293-57ff-41a7-a2a8-5be31f582760.png)
> 
> 昨晚我也发现了，忘记提了，我是改成垂直布局显示才正常，当是水平布局如果content内容比较长时，title和content之间的间距就非常大，如果能解决间距的问题应该就可以了
> 
> ## 复现代码的话直接用大佬那个infoBar的demo中的第一个信息提示，改成水平的就能复现
> ![image](https://user-images.githubusercontent.com/8281775/229265469-fd141525-1058-47e7-a7ca-4c71bd18c911.png)
> 另外提一个建议，目前title为空字符串的话，infoBar的图标和content的间距好像也也偏大了点，不知道能否优化下，另外这个title是否能够默认缺省，有时候不想显示title，只显示content ![image](https://user-images.githubusercontent.com/8281775/229265569-808c2012-4dca-4cf0-8b5e-92c8de4b5d63.png) ![image](https://user-images.githubusercontent.com/8281775/229265588-3581c328-e9cc-4516-98b2-6c6028aed8f6.png)

我的也是，改成垂直就ok了，感谢~
猜一下，可能是垂直和水平处理反了。

**Comment by zhiyiYo** [comment]
v0.5.0修复了此问题，同时可以把 title 参数置为空字符串以达到隐藏标题的目的

**Comment by zhiyiYo** [comment]
消息条还是别放太长的消息吧

**Comment by zhiyiYo** [comment]
建议换成消息框

**Comment by zhiyiYo** [comment]
@qianye216 
话说你那边的 checkbox 在 dpi 缩放大于 1 的时候会模糊吗

**Comment by zhiyiYo** [comment]
我这边直接运行 check_box 的 demo 也不会模糊，但是切换到 gallery 的 demo，里面的 check_box 就会糊掉

**Comment by zhiyiYo** [comment]
好吧，可能是 Windows 的问题
