### ISSUE TITLE
flip_view错误地拉伸了图片

### ISSUE THREAD

**Issue by phlinsia** [zhiyiYo/PyQt-Fluent-Widgets#620]
我在使用up为pyside6开发的qfluentwidgets中的flipview时出现了一个需求问题。我想要用flipview展示的图片长宽并不一致，因此在添加到flipview后都出现了相对于第一张图的拉伸。请问有什么好的解决办法吗。
![1699844421354.png](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/61466017/6d33653f-399b-4c69-b7df-8e5728851815)

![1699844429105.png](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/61466017/a7b4a7b7-6b8e-4979-8799-67992d0dbab3)

**Comment by zhiyiYo** [comment]
这周末再修修看吧

**Comment by zhiyiYo** [comment]
pyqt5 分支已修复此问题

**Comment by zhiyiYo** [comment]
`FlipView.setAspectRatioMode(Qt.AspectRatioMode.KeepAspectRatio)`
