### ISSUE TITLE
MessageBox组件内容只能显示，不能选择复制其中的文本

### ISSUE THREAD

**Issue by niuzijia** [zhiyiYo/PyQt-Fluent-Widgets#625]
![FD% Z673_507IB{H4OU7{{D](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68538774/8eaab484-54f5-4d32-8c3e-a08d4939b254)
这个组件内容可以设置为可以复制的么
显示的文本不能复制

**Comment by rainzee** [comment]
你可以用 `MessageBox` 的基类自己实现任何你需要的 Dialog

**Comment by zhiyiYo** [comment]
`setContentCopyable(True)` 来启动选中文本功能
