### ISSUE TITLE
InfoBar组件会出现长文本显示问题

### ISSUE THREAD

**Issue by niuzijia** [zhiyiYo/PyQt-Fluent-Widgets#626]
```
def createSuccessInfoBar(self):
        # convenient class mothod
        InfoBar.success(
            title='Lesson 4',
            content="svn: warning: W160013: '/svn/SysTest/!svn/rvr/9155/TBOX/TestProject/CanoeProject/TBOX_EEA2.5_CICT_TestProject/trunk/TBOX_EEA2.5_CICT_CAN_VT2.cfg/tags' path not found\nsvn: E200009: Could not list all targets because some targets don't exist",
            orient=Qt.Horizontal,
            isClosable=True,
            position=InfoBarPosition.TOP,
            # position='Custom',   # NOTE: use custom info bar manager
            duration=2000,
            parent=self
        )
```
上面代码会显示
![6C2U9M~ ` B%RSXNUUG`X0J](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68538774/da11d9f9-afab-407d-b0fa-a380022519dd)

**Comment by rainzee** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/3e6ba896-2445-4bf4-a6d2-b755a8bf149f)

我这里测试长文本没有问题，是不是你的符号被转义了？给个最小复现代码？

**Comment by rainzee** [comment]
定位到为题了，可能是换行算法导致的，尝试修复一下

**Comment by rainzee** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/e393ce95-d88f-46d4-93cf-063165757a69)

修复后效果如图，是否符合你的预期？

**Comment by niuzijia** [comment]
> ![image](https://user-images.githubusercontent.com/4585440/283364603-e393ce95-d88f-46d4-93cf-063165757a69.png)
> 
> 修复后效果如图，是否符合你的预期？

很强，可以了，符合预期
