### ISSUE TITLE
[Bug]: 整个框架存在内存泄漏问题

### ISSUE THREAD

**Issue by Daiobs** [zhiyiYo/PyQt-Fluent-Widgets#631]
### What happened?

10.3号apooreapo老哥提出了内存泄漏问题，不知道作者是否有注意到。在Fluent UI框架中，几乎所有的操作都会造成内存泄漏，不知道作者本地开发环境是否存在这个问题。

### Operation System

win10

### Python Version

3.10 64位

### PyQt/PySide Version

Pyside 6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.3.8

### How to Reproduce?

运行demo.py，查看任务管理器的内存消耗情况

### Minimum code

```python3
无
```

**Comment by Daiobs** [comment]
已经查明原因在class LinuxFramelessWindow中注释以下两行代码即可恢复正常
    def eventFilter(self, obj, event):
        return LinuxFramelessWindowBase.eventFilter(self, obj, event)

**Comment by zhiyiYo** [comment]
pyside6 6.4.2 的 bug，换成 pyqt5、pyside2、pyside6.6.1 即可解决
