### ISSUE TITLE
[Bug]: TableView使用setItemDelegate后程序闪退

### ISSUE THREAD

**Issue by parawang** [zhiyiYo/PyQt-Fluent-Widgets#634]
### What happened?

# projects是一个TableView ，前面设置好model（包含外键，使用的QSqlRelationalTableModel）
self.pmodel = ProjectsModel()
self.projects.setModel(self.pmodel.model)
# 设置tableview的item代理，页面可以正常打开，只要鼠标一动，程序就自动退出了。
# 如果把下面这行去掉，即去掉编辑功能，页面可以正常显示。
self.projects.setItemDelegate(QSqlRelationalDelegate(self.projects))

具体退出代码为：
进程已结束,退出代码-1073740791 (0xC0000409)

### Operation System

Win11

### Python Version

3.8

### PyQt/PySide Version

PyQt5.12

### PyQt/PySide-Fluent-Widgets Version

PyQt

### How to Reproduce?

# projects是一个TableView ，前面设置好model（包含外键，使用的QSqlRelationalTableModel）
self.pmodel = ProjectsModel()
self.projects.setModel(self.pmodel.model)
# 设置tableview的item代理，页面可以正常打开，只要鼠标一动，程序就自动退出了。
# 如果把下面这行去掉，即去掉编辑功能，页面可以正常显示。
self.projects.setItemDelegate(QSqlRelationalDelegate(self.projects))

具体退出代码为：
进程已结束,退出代码-1073740791 (0xC0000409)
将TableView 更换为QTableView后，页面能正常显示，可以选择下拉列表，编辑保存均正常。

### Minimum code

```python3
# projects是一个TableView ，前面设置好model（包含外键，使用的QSqlRelationalTableModel）
self.pmodel = ProjectsModel()
self.projects.setModel(self.pmodel.model)
# 设置tableview的item代理，页面可以正常打开，只要鼠标一动，程序就自动退出了。
# 如果把下面这行去掉，即去掉编辑功能，页面可以正常显示。
self.projects.setItemDelegate(QSqlRelationalDelegate(self.projects))

具体退出代码为：
进程已结束,退出代码-1073740791 (0xC0000409)
```

**Comment by zhiyiYo** [comment]
代理应该继承自 `TableItemDelegate`
