### ISSUE TITLE
[Bug]: FluentIcon 返回的 QIcon 无法自动切换主题

### ISSUE THREAD

**Issue by OceanYoungY** [zhiyiYo/PyQt-Fluent-Widgets#639]
### What happened?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/1aa55cd9-3eaa-4adc-877c-d962a3efe617)
使用 QListWidgetItem 类 并含有logo 的条目，切换明暗主题后，logo的颜色没有自动变化。

### Operation System

Windows11

### Python Version

3.11.4

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

PyQt-Fluent-Widgets  1.2.7

### How to Reproduce?

使用 QListWidgetItem 类 并含有logo 的条目，切换明暗主题，查看logo的颜色

### Minimum code

```python3
class JobManagerInterface(ScrollArea):
    """JobManagerInterface 目录列表"""

    def __init__(self, parent=None):
        super().__init__(parent=parent)

        self.listWidget = ListWidget(self)

        jobItem = QListWidgetItem("Job List")
        jobItem.setIcon(FluentIcon.DOCUMENT.icon())
        self.listWidget.addItem(jobItem)

        workerItem = QListWidgetItem("Worker Manager")
        workerItem.setIcon(FluentIcon.DEVELOPER_TOOLS.icon())
        self.listWidget.addItem(workerItem)

        self.hBoxLayout = QHBoxLayout(self)
        self.hBoxLayout.addWidget(self.listWidget)
```

**Comment by zhiyiYo** [comment]
ListWidget 的 icon 不支持自动更换颜色

**Comment by OceanYoungY** [comment]
是否有替代方案，能解决自动更换颜色的问题呢？

**Comment by zhiyiYo** [comment]
下述代码应该可以 work
```python
from qfluentwidgets.common.icon import FluentIconEngine, Icon

icon = QIcon(FluentIconEngine(Icon(FluentIcon.DOCUMENTS)))
item = QListWidgetItem(icon, "item")
```

**Comment by zhiyiYo** [comment]
v1.4.0 中将提供 `FluentIconBase.qicon()` 方法，用于返回一个可以随着系统主题自动切换颜色的 QIcon
