### ISSUE TITLE
[Bug]: FluentWindow的titlebar的titleLabel字体建议增加默认的中文字体

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#641]
### What happened?

当使用FluentWindow调用setWindowTitle设置标题时，如果包含中文的话在win11系统下中文显示成宋体了，经查看FluentWindow的qss，里面只有设置了英文的默认字体，建议加上mac下的苹方字体和windows下的微软雅黑字体

### Operation System

Mac

### Python Version

3.9.6

### PyQt/PySide Version

PyQt5.15.10

### PyQt/PySide-Fluent-Widgets Version

1.3.8

### How to Reproduce?

qss更新添加默认中文字体
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/28e23512-00c7-49c4-bc46-7ecb12d78e3b)

### Minimum code

```python3
FluentTitleBar>QLabel#titleLabel,
SplitTitleBar>QLabel#titleLabel {
    color: black;
    background: transparent;
    font: 13px 'Segoe UI';
    padding: 0 4px
}
```
```

**Comment by zhiyiYo** [comment]
已修复此问题
