### ISSUE TITLE
[Bug]: VideoWidget 播放视频失真，自动播放失败

### ISSUE THREAD

**Issue by OceanYoungY** [zhiyiYo/PyQt-Fluent-Widgets#644]
### What happened?

需求：我想要放一个十几秒的视频，在一个页面上循环播放。使用 VideoWidget 的时候，视频无法自动播放，手动播放后视频色彩失真，且报错：DirectShowPlayerService::doRender: Unknown error 0x80040266.

使用 VideoWidget 的颜色
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/3d20f3ca-cfe1-4e45-b1de-0ab196b1f2f6)

视频正常的颜色：（这个是使用 QMediaPlayer 和 QVideoWidget 实现的，视频循环播放和色彩没有问题，但是初始化的时候，整个窗口的样式都乱了。）
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/f5e0aa2e-305e-4dcf-bb69-65e37d7bf033)
错乱的样式：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/6f522669-a531-4904-9e4d-bd011c484989)

### Operation System

Windows11

### Python Version

3.11.4

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

PyQt-Fluent-Widgets  1.2.7

### How to Reproduce?

在一个基于QFrame 的页面中，使用 VideoWidget 播放一个视频

### Minimum code

```python3
class BasePage(QFrame):
    """默认页面"""

    currentPageSignal = pyqtSignal()

    def __init__(self, routeKey: str, title: str, icon, parent=None):
        super().__init__(parent=parent)
        self._tabRouteKey = routeKey
        self._tabTitle = title
        self._tabIcon = icon
        self.setObjectName(routeKey)

    def getRouteKey(self):
        """获取页面对应的 Key"""
        return self._tabRouteKey

    def getTitle(self):
        """获取页面的标题"""
        return self._tabTitle

    def getIcon(self):
        """获取页面的 icon"""
        return self._tabIcon

class myVideoWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.hlayout = QtWidgets.QHBoxLayout(self)
        self.videowidget = VideoWidget(self)
        self.videowidget.setVideo(
            QUrl.fromLocalFile(f"{get_local_config_path()}/video.avi")
        )
        # self.videowidget.playBar.hide()
        self.hlayout.addWidget(self.videowidget)
        self.videowidget.play()


class WelcomePage(BasePage):
    def __init__(self, routeKey: str, title: str, icon, parent=None):
        super().__init__(routeKey, title, icon, parent)
        self.setObjectName(routeKey)
        self.vBoxLayout = QtWidgets.QVBoxLayout(self)
        self.setContentsMargins(0, 0, 0, 0)

        # 视频播放模块
        self.videopart = myVideoWidget()
        self.vBoxLayout.addWidget(self.videopart)
```

**Comment by zhiyiYo** [comment]
有个类似的历史issue

**Comment by OceanYoungY** [comment]
按照 #507 的方法改了 似乎也没有效果

**Comment by OceanYoungY** [comment]
这是 使用 QMediaPlayer 和 QVideoWidget 组合方式 的代码

`class myVideoWidget(QtWidgets.QWidget):
    """最近打开模块的面板类"""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.hlayout = QtWidgets.QHBoxLayout(self)

        self.videoplayer = QMediaPlayer(None, QMediaPlayer.Flag.VideoSurface)
        self.videoplayer.setMuted(True)
        self.videowidget = QVideoWidget()
        # self.videowidget.show()
        self.mplayList = QMediaPlaylist()
        self.mplayList.addMedia(
            QMediaContent(QUrl.fromLocalFile(f"{get_local_config_path()}/video.avi"))
        )
        self.mplayList.setPlaybackMode(QMediaPlaylist.PlaybackMode.CurrentItemInLoop)
        self.videoplayer.setPlaylist(self.mplayList)
        self.videoplayer.setVideoOutput(self.videowidget)
        self.videoplayer.play()
        self.hlayout.addWidget(self.videowidget)`

**Comment by zhiyiYo** [comment]
不确定是不是视频格式导致的，换成 mp4 试试呢？

**Comment by kj2v** [comment]
目前有发现程序会和yolo冲突，产生和你一模一样的问题，动态import冲突库或许可以解决问题。
