### ISSUE TITLE
[Bug]: 应该升级Pillow版本以适配PY3.12

### ISSUE THREAD

**Issue by ColdWindScholar** [zhiyiYo/PyQt-Fluent-Widgets#645]
### What happened?

应该升级Pillow版本以适配PY3.12

### Operation System

Windows 11 23H2

### Python Version

3.12

### PyQt/PySide Version

PyQt 5.15.10

### PyQt/PySide-Fluent-Widgets Version

v1.3.1

### How to Reproduce?

可以使用Pillow==9.5.0替代

### Minimum code

```python3
# no code
```

**Comment by zhiyiYo** [comment]
低版本的 pyqt 会和高版本的 pillow 发生冲突
