### ISSUE TITLE
[Bug]: 进度条无法设置垂直

### ISSUE THREAD

**Issue by Lin-Yuhao** [zhiyiYo/PyQt-Fluent-Widgets#646]
### What happened?

![截图_20231125122904](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/92281663/5b02463d-6734-4038-a766-9e5601907c5f)

### Operation System

win11

### Python Version

python3.10

### PyQt/PySide Version

pyqt6

### PyQt/PySide-Fluent-Widgets Version

1.38

### How to Reproduce?

不管是代码还是designer都无法将进度条垂直

### Minimum code

```python3
self.ProgressBar.setOrientation(Qt.Orientation.Vertical)
```

**Comment by Lin-Yuhao** [comment]
需求
![截图_20231125123446](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/92281663/c1f9ac9a-f32d-49c0-acc1-42052460bbb9)
代码无法查看

**Comment by zhiyiYo** [comment]
我只给pro版本组件库写了垂直进度条

**Comment by Lin-Yuhao** [comment]
我需要购买pyqt6的pro版本解锁垂直进度条和图表功能，发行页面没有找到pyqt6的版本

**Comment by zhiyiYo** [comment]
> 我需要购买pyqt6的pro版本解锁垂直进度条和图表功能，发行页面没有找到pyqt6的版本

pyqt不能商用，所以只搞了pyside

**Comment by Lin-Yuhao** [comment]
好的，感谢

**Comment by zhiyiYo** [comment]
pyqt 和 pyside 写法没区别，VSCode 全局搜索替换 PyQt6 为 PySide6 即可
