### ISSUE TITLE
gallery demo 的展示优化方案

### ISSUE THREAD

**Issue by kongbair** [zhiyiYo/PyQt-Fluent-Widgets#648]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93134550/907a563b-2dc8-46c2-9c8e-46fb373028d7)

正如上面所示，我知道了该组件所显示的效果，但是并不能确认它所对应的英文组件名是什么，因为在designer中，是像下面那样的
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93134550/2c3f9fcf-5330-4db0-859e-590446ab4fe6)

我最终只能被迫去官网找对应的英文组件名，或者在designer中，根据英文去猜测我所想要的组件
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/93134550/f9efdf92-6599-41da-93f0-1334aad7d772)

但对于PyQt-Fluent-Widgets老手来说，可能并不再话下，但是对于新手，或者英文不好的来说，可能有点吃力

针对以上问题，我想可以在gallery中，进行组件名标注，示例如下：

望采纳

**Comment by zhiyiYo** [comment]
界面语言切换为英文
