### ISSUE TITLE
【建议】拆分按钮SplitPushbutton等建议增加给最右侧的拆分按钮设置图标的方法

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#649]
大佬你好，目前拆分按钮右侧的拆分按钮图标默认是下拉图标
有些场景不需要下拉，就是希望用一个单独的主按钮和右侧的拆分按钮，这个时候如果需要给右侧的拆分按钮设置自定义的图标就稍微麻烦点
建议增加单独的可设置拆分按钮图标的方法，这样通用性更强，例如以下示例，如果有直接设置图标的方法，就可以直接给右侧按钮设置关闭按钮图标就可以了：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/8ed4c49d-d37b-4cd3-9a21-c6e43ffc721e)

**Comment by zhiyiYo** [comment]
已添加 `setDropIcon` 和 `setDropIconSize`
