### ISSUE TITLE
flow_layout显示异常

### ISSUE THREAD

**Issue by Liruochen1207** [zhiyiYo/PyQt-Fluent-Widgets#66]
**在窗口边框反复拉动时出现了卡顿在空中的情况**

![test 00_00_00-00_00_30](https://user-images.githubusercontent.com/74223784/229331435-e4dc263a-a230-40b5-a709-0121e98c1282.gif)

**Comment by zhiyiYo** [comment]
好像只有 gallery 界面会出现这种情况，单独运行 `examples/flow_layout/demo.py` 就不会有这个问题

**Comment by Liruochen1207** [comment]
是的，我在examples/flow_layout/demo.py中也是正常的，或许是gallery 界面与其他部件一同加载尺寸，计算量大所以容易卡？

**Comment by zhiyiYo** [comment]
不太清楚，不过正常情况下应该不会有人这么玩吧😆

**Comment by Liruochen1207** [comment]
qwq

**Comment by zhiyiYo** [comment]
目前应该是解决了这个问题 #85
