### ISSUE TITLE
how can create a subMenu of RoundedMenu with multiple parent Menus

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#662]
a menu has multiple self.parentMenu and self.menuItem in
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/6b37964b70e0f7d1d16fa455b01ff233fcc728e6/qfluentwidgets/components/widgets/menu.py#L328C9-L328C9

**Comment by zhiyiYo** [comment]
Is there an example? I didn't understand what it meant

**Comment by immiProgrammer** [comment]
1 subMeun is used in 2 parent menus
Menu1.addMenu(submenu)
Menu2.addMenu(submenu)
when exec Menu1 it has item of 'submenu' but doesn't work when hover it
and Menu2 also has 'submenu' item and working fine
both parent menus (Menu1 and Menu2) has 'submenu' in self._subMenus list

**Comment by zhiyiYo** [comment]
Submenu stores a parent pointer. So you should create one more submenu instead of sharing the same one.

**Comment by immiProgrammer** [comment]
Done
