### ISSUE TITLE
[Bug]: Windows下menu组件的availableViewSize方法偶发报错

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#664]
### What happened?

Windows下启动应用时，突然有360杀毒软件弹出是否运行的弹窗，然后程序崩溃，怀疑是其他应用抢了焦点导致menu组件中的QApplication.screenAt(QCursor.pos())返回了None，导致程序崩溃，大佬看看是否在相关方法增加是否是None的判断？
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/73eea450-6aeb-4e14-8fd4-b2bc8fed87fd)
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/ba49964c-48e6-4d46-9076-afaaacc04462)

### Operation System

Windows11

### Python Version

3.9.6

### PyQt/PySide Version

PyQt5.15.10

### PyQt/PySide-Fluent-Widgets Version

1.4.1

### How to Reproduce?

报错显示：availableViewSizeAttributeError: 'NoneType' object has no attribute "availableGeometry'

### Minimum code

```python3
availableViewSizeAttributeError: 'NoneType' object has no attribute "availableGeometry'
```

**Comment by zhiyiYo** [comment]
除了这种方法不知道怎么准确地获取鼠标所在窗口

**Comment by zhiyiYo** [comment]
试一下下面这一段代码：
```cpp
// 获取当前鼠标的位置
    QPoint cursorPos = QCursor::pos();

    // 获取所有可用的屏幕
    QList<QScreen*> screens = QGuiApplication::screens();

    // 查找包含鼠标位置的屏幕
    QScreen *screen = nullptr;
    for (QScreen* s : screens) {
        if (s->geometry().contains(cursorPos)) {
            screen = s;
            break;
        }
    }
```

**Comment by zhiyiYo** [comment]
@qianye216
