### ISSUE TITLE
TableView Selection (updateSelectedRows)

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#667]
the better way to updateSelectedRows in TableView using this signal
table.selectionModel().selectionChanged.connect(updateSelectedRows)

in [this File](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/dd0bd684e9fc1e4eac0a7d8f455783bab191995c/qfluentwidgets/components/widgets/table_view.py#L276)

when u use this method doesn't matter user call
keyPressEvent, mouseReleaseEvent, selectAll, selectRow, clearSelection, setCurrentIndex, and directly call updateSelectedRows

in current situations i am using QSortFilterProxyModel in Table when i sort table doesn't update selected row

**Comment by immiProgrammer** [comment]
this method are both supposed QTableView and QTableWidget

**Comment by zhiyiYo** [comment]
This will cause an indicator to appear on the data row as soon as the mouse is pressed

**Comment by immiProgrammer** [comment]
> This will cause an indicator to appear on the data row as soon as the mouse is pressed

I don't understand

**Comment by zhiyiYo** [comment]
In the current implementation, the indicator only switches position when the mouse is released

**Comment by immiProgrammer** [comment]
> In the current implementation, the indicator only switches position when the mouse is released

Which is the benefit of current implement

**Comment by immiProgrammer** [comment]
> the better way to updateSelectedRows in TableView using this signal
> table.selectionModel().selectionChanged.connect(updateSelectedRows)
> 
> in [this File](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/dd0bd684e9fc1e4eac0a7d8f455783bab191995c/qfluentwidgets/components/widgets/table_view.py#L276)
> 
> when u use this method doesn't matter user call
> keyPressEvent, mouseReleaseEvent, selectAll, selectRow, clearSelection, setCurrentIndex, and directly call updateSelectedRows
> 
> in current situations i am using QSortFilterProxyModel in Table when i sort table doesn't update selected row

This method is triggered whenever selection is changed

**Comment by zhiyiYo** [comment]
The current interaction behavior is based on Apple music, and you can connect the `selectionChanged` signal to the `updateSelectedRows` if you don't like this behavior.
