### ISSUE TITLE
[Bug]: TableWidget 导致菜单动画帧率变低

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#668]
### What happened?

TableWidget 导致菜单动画帧率变低

### Operation System

Windows11 23H2

### Python Version

3.11.5

### PyQt/PySide Version

PySide6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.4.3

### How to Reproduce?

全屏之后右击表格

### Minimum code

```python3
tets
```

**Comment by zhiyiYo** [comment]
右击菜单的动画会不停地触发代理的 `paint` 方法，导致卡顿

**Comment by 3101057414** [comment]
> 右键菜单的动画会不停地触发代理的`paint`方法，导致卡顿

我在tableview中加载了50行数据，动画就出现明显掉帧，请问这种情况正常吗？或许可以修改动画速率等情况优化？

**Comment by zhiyiYo** [comment]
> > 右键菜单的动画会不停地触发代理的`paint`方法，导致卡顿
> 
> 我在tableview中加载了50行数据，动画就出现明显掉帧，请问这种情况正常吗？或许可以修改动画速率等情况优化？

修改动画速率和掉帧应该没啥区别？
