### ISSUE TITLE
examples的scroll_area示例qss样式未设置水平滚动条的，导致运行时显示不出来

### ISSUE THREAD

**Issue by theSmokingSea** [zhiyiYo/PyQt-Fluent-Widgets#67]
以下是我调整后的qss，增加了点水平和垂直的处理：
QScrollBar {
    background: transparent;
    padding-right: 2px;
}

QScrollBar:vertical{
    width: 5px;
}

QScrollBar:horizontal{
    height: 5px;
}
/*隐藏上箭头*/
QScrollBar::sub-line {
    background: transparent;
}

/*隐藏下箭头*/
QScrollBar::add-line {
    background: transparent;
}

QScrollBar::handle {
    background: rgb(122, 122, 122);
    border: 2px solid rgb(128, 128, 128);
    border-radius: 1px;
}

QScrollBar::handle:vertical {
    min-height: 40px;
}
QScrollBar::handle:horizontal {
    min-width: 40px;
}

QScrollBar::add-page,
QScrollBar::sub-page {
    background: none;
}

**Comment by zhiyiYo** [comment]
感谢指正，等下就加进去
