### ISSUE TITLE
MaterialDesigner中设置ComboBox的选项？运行时发现似乎无法选择ComboBox菜单中的其他项

### ISSUE THREAD

**Issue by kingki663** [zhiyiYo/PyQt-Fluent-Widgets#672]
请问应该如何在MaterialDesigner中设置ComboBox？
我的解决方案是在生成的py文件中addItems，不过运行时发现似乎无法选择下拉菜单中的其他项，请问该如何解决？

**Comment by zhiyiYo** [comment]
designer 设置不了
