### ISSUE TITLE
Fluent Window 在拖动大小时会显示原生标题栏

### ISSUE THREAD

**Issue by x405x** [zhiyiYo/PyQt-Fluent-Widgets#682]
### What happened?

Windows 7 环境下，使用 MSFluentWindow 创建的Fluent Window 在拖动大小时会短暂显示 Windows 原生标题栏，而且会随着拖动不断闪烁。请问有办法解决吗？

### Operation System

Windows 11 23H1 & Windows 7 SP1

### Python Version

3.8.10 64-bit

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

V1.4.1

### How to Reproduce?

/

### Minimum code

```python3
# Just create the window
```
```

**Comment by rainzee** [comment]
感觉这是 Qt 那边的问题

**Comment by x405x** [comment]
> 感觉这是 Qt 那边的问题

谢谢，我再想想别的解决方法吧

**Comment by Tamakostory** [comment]
> > 感觉这是 Qt 那边的问题
> 
> 谢谢，我再想想别的解决方法吧
请问是否已经找到解决办法？
