### ISSUE TITLE
[Bug]: 使用Nuitka打包之後出現問題

### ISSUE THREAD

**Issue by abyss-zues** [zhiyiYo/PyQt-Fluent-Widgets#684]
### What happened?

在使用Nuitka打包之後，報錯：
Traceback (most recent call last):
  File "D:\Projects\WORKSP~1\MAIN~1.DIS\qfluentwidgets\components\widgets\stacked_widget.py", line 193, in __onAniFinished
TypeError: patched_disconnect() missing 1 required positional argument: 'receiver'
定位代碼如下位置：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110171545/c8634320-2ada-461b-8ea1-f186d5d004ba)
EditableComboBox也會有同樣問題。
使用開發環境調試時不報錯，用Nuitka打包之後就會報錯

### Operation System

Windows 10 21H1

### Python Version

Python 3.11.6 x64

### PyQt/PySide Version

Pyside6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.4.3

### How to Reproduce?

Nuitka版本：1.9.5
打包命令：`nuitka --standalone --enable-plugin=pyside6 --nofollow-import-to=tkinter --mingw --follow-imports   mini_code.py`

### Minimum code

```python3
# 此處使用EditableComboBox來復現
import sys

from PySide6.QtWidgets import QApplication
from qfluentwidgets import EditableComboBox
app = QApplication(sys.argv)

EditableComboBox().show()
sys.exit(app.exec())
```

**Comment by zhiyiYo** [comment]
换成1.8.6

**Comment by shenjackyuanjie** [comment]
@abyss-zues 请使用 nuitka 1.8.6
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54507071/28c2f2a8-df41-41d8-a3b5-190439d15f49)

这个问题 Nuitka 的 develop 分支修复了，但是还没有发布新的hotfix, 估计得等 1.9.8/2.0
或者你自己去用develop版（

**Comment by shenjackyuanjie** [comment]
@abyss-zues  Nuitka 2.0 发布了，可以更新一下去

**Comment by abyss-zues** [comment]
謝謝
