### ISSUE TITLE
combo_box.py

### ISSUE THREAD

**Issue by CheshireCC** [zhiyiYo/PyQt-Fluent-Widgets#686]
### What happened?

Nuitka 编译之后代码报错
定位代码为 combo_box.py 第 431 行代码
```
self.clearButton.clicked.disconnect()
```

这行代码是必须的吗？好像没有写完？这里是否缺失了参数？
如果它不是必须的，能否修复或者我自行删掉这行代码？

### Operation System

Windows11 22H2

### Python Version

3.10.6 64bit

### PyQt/PySide Version

PySide6.4.0

### PyQt/PySide-Fluent-Widgets Version

1.4.5

### How to Reproduce?

-

### Minimum code

```python3
-
```

**Comment by zhiyiYo** [comment]
这个好像是你以前提的 issue？

**Comment by zhiyiYo** [comment]
nuitka 换成 1.8.6 应该就可以编译了

**Comment by CheshireCC** [comment]
Nuitka 升级速度太快了，我已经升级到 1.9.5 了，恐怕回不去了😂

**Comment by CheshireCC** [comment]
检索了相关 issue 确实有人提过，我重新尝试安装 1.8.6 版本吧，哎~

**Comment by zhiyiYo** [comment]
Nuitka 2.0 应该会修复这个问题
https://github.com/Nuitka/Nuitka/issues/2636

**Comment by zhiyiYo** [comment]
Nuitka2.0 已经发布了
