### ISSUE TITLE
Add central Window

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#688]
first create a window like this before creating FluentWindowBase
for using card example and other stuff

```
class MicaWindow(BackgroundAnimationWidget, FramelessWindow):

    def __init__(self, parent=None):
        self._isMicaEnabled = False
        super().__init__(parent)

        self.setTitleBar(FluentTitleBar(self))

        # enable mica effect on win11
        self.setMicaEffectEnabled(True)
        qconfig.themeChangedFinished.connect(self._onThemeChangedFinished)


    def _normalBackgroundColor(self): # immi watch this later
        if not self.isMicaEffectEnabled():
            return QColor(32, 32, 32) if isDarkTheme() else QColor(243, 243, 243)

        return QColor(0, 0, 0, 0) if isDarkTheme() else QColor(255, 255, 255, 50)

    def _onThemeChangedFinished(self):
        if self.isMicaEffectEnabled():
            self.windowEffect.setMicaEffect(self.winId(), isDarkTheme())

    def paintEvent(self, e):
        super().paintEvent(e)
        if self.isMicaEffectEnabled():return
        painter = QPainter(self)
        painter.setPen(Qt.NoPen)
        painter.setBrush(self.backgroundColor)
        painter.drawRect(self.rect())

    def setMicaEffectEnabled(self, isEnabled: bool):
        """ set whether the mica effect is enabled, only available on Win11 """
        if sys.platform != 'win32' or sys.getwindowsversion().build < 22000:
            return

        self._isMicaEnabled = isEnabled

        if isEnabled:
            self.windowEffect.setMicaEffect(self.winId(), isDarkTheme())
        else:
            self.windowEffect.removeBackgroundEffect(self.winId())

        self.setBackgroundColor(self._normalBackgroundColor())

    def isMicaEffectEnabled(self):
        return self._isMicaEnabled
```

**Comment by immiProgrammer** [comment]
# or
class MicaWindow(BackgroundAnimationWidget, FramelessWindow):

    def __init__(self, parent=None):
        self._isMicaEnabled = False
        super().__init__(parent)
        ...

    _normalBackgroundColor = FluentWindowBase._normalBackgroundColor
    _onThemeChangedFinished = FluentWindowBase._onThemeChangedFinished
    setMicaEffectEnabled = FluentWindowBase.setMicaEffectEnabled
    isMicaEffectEnabled = FluentWindowBase.isMicaEffectEnabled

    def paintEvent(self, e):
        super().paintEvent(e)
        if self.isMicaEffectEnabled():return
        painter = QPainter(self)
        painter.setPen(Qt.NoPen)
        painter.setBrush(self.backgroundColor)
        painter.drawRect(self.rect())

**Comment by TonsenWei** [comment]
Hi，Pro:
   I want to use FramelessMainWindow, while I replace
```
class FluentWindowBase(BackgroundAnimationWidget, FramelessWindow):
```
to 
```
class FluentWindowBase(BackgroundAnimationWidget, FramelessMainWindow):
```
the function paintEvent rewrite will make the program crash like:
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/19351075/4ce10419-9f77-4708-8371-b13b9c7260e0)

Do you know how to use FramelessMainWindow correctly?
Thank you very much. It would be best if you could provide a demo.
