### ISSUE TITLE
设置卡改进

### ISSUE THREAD

**Issue by abcdesteve** [zhiyiYo/PyQt-Fluent-Widgets#689]
现在的`ComboBoxSettingCard`用下拉框不太方便，改设置起码要点2次
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72078508/65bbe039-198d-4ea3-a486-f83e0bc847d3)
不如新增一个`RadioBoxSettingCard`，做成单选样式平铺开，这样用户体验更好
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/72078508/416ae937-2f1f-432a-9117-5863f8dfe162)
如果选项比较多的话再退回`OptionsSettingCard`这样的折叠样式

最好加上新组件`SegmentedWidget` `SegmentedToolWidget` `SegmentedToggleToolWidget`的设置卡，进一步提升空间利用率

**Comment by abcdesteve** [comment]
哦对了，设置卡的选项是否可以设置别名呢？给用户看到`AUTO`这样的选项不太好，直接把选项改成对应的语言又不方便国际化

**Comment by Tinhone** [comment]
不过 WinUI 3 Gallery 用的就是下拉框来着 🤔

**Comment by Tinhone** [comment]
不过 WinUI 3 Gallery 的设置页用的是下拉框来着 🤔

**Comment by rainzee** [comment]
不符合 Fluent Design 不会计划改进

**Comment by abcdesteve** [comment]
> 不符合 Fluent Design 不会计划改进

那别名会不会考虑呢🤔
