### ISSUE TITLE
无法运行 Gallery

### ISSUE THREAD

**Issue by kingc2022** [zhiyiYo/PyQt-Fluent-Widgets#69]
**Describe the bug**
The demo program (PyQt-Fluent-Widgets/examples/gallery/demo.py) can't run normally

**Environment**
- OS: Windows 10 21H2
- Python: 3.11.1 64-bit
- PyQt: 5.15.9
- PyQt-Fluent-Widgets: 0.3.3

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. Go to 'PyQt-Fluent-Widgets/examples/gallery/app/view/gallery_interface.py'
2. Scroll down to Line 6 and 7
3. See error

**Code**
```python
from qfluentwidgets import (ScrollArea, PushButton, ToolButton, FluentIcon,
                            isDarkTheme, IconWidget, Theme, ToolTipFilter)
```

**Expected behavior**
Run normally

**Screenshots**
![1](https://great.wzznft.com/i/2023/04/02/u2itj2.png)
![2](https://great.wzznft.com/i/2023/04/02/u2it66.png)

**Comment by zhiyiYo** [comment]
版本太低了，可以去 pypi 官网下载最新whl文件
