### ISSUE TITLE
Use PyQt6/PySide6, just like in the examples

### ISSUE THREAD

**Issue by Advik-B** [zhiyiYo/PyQt-Fluent-Widgets#690]

**Comment by Advik-B** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/86160411/6f4a2f95-511d-415e-badf-f431744853c3)

**Comment by Advik-B** [comment]
How did you use pyside6 when the library only uses pyqt5

**Comment by rainzee** [comment]
Can you give me more details?

**Comment by zhiyiYo** [comment]
switch to PySide6/PyQt6 branch
