### ISSUE TITLE
[Bug]: 存在水平滚动条时，TableWidget中添加的自定义cellWidget某些情况下错位

### ISSUE THREAD

**Issue by socrazyaaa** [zhiyiYo/PyQt-Fluent-Widgets#692]
### What happened?

根据我个人的检查，是 table_view.py 中的 TableItemDelegate().updateEditorGeometry() 中的 x, w = max(8, rect.x()), rect.width() 导致的。存在水平滚动条时，将 TableWidget 中添加的自定义 cellWidget 滚动至 x 坐标为小于8时，控件的坐标会被强制设置为8，导致错位。不知道作者添加最小为8的限制是怎么考虑的，我把限制去掉了，然后 if index.column() == 0 时 x+=8 ，不知道这样改会不会出现其他问题?

### Operation System

Win10 1902

### Python Version

3.11.5

### PyQt/PySide Version

PySide6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.4.5

### How to Reproduce?

在TableWidget中添加自定义控件，并将控件滑动至TableWidget最左侧直到隐藏，通过调整单元格大小等方式重绘TableWidget，自定义控件会调整位置到TableWidget已显示部分的最左侧。

### Minimum code

```python3
-
```

**Comment by zhiyiYo** [comment]
最左侧的单元格存在一定的偏移
