### ISSUE TITLE
[Bug]: 图标错位

### ISSUE THREAD

**Issue by Aprebus** [zhiyiYo/PyQt-Fluent-Widgets#695]
### What happened?

在FluentDesigner预览没问题，但代码运行图标会错位。左边是原生的pushButton显示无问题，图标均来自阿里巴巴矢量图标库，我尝试了svg、png均有错位现象，历史Issue没有找到解决办法
![预览](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/71392091/8afba743-dc54-4248-affe-3171895bc658)
![代码运行](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/71392091/5b82dc45-27b9-487b-b335-d521195cf87c)

### Operation System

win11

### Python Version

3.11.4

### PyQt/PySide Version

pyside6 == 6.4.2

### PyQt/PySide-Fluent-Widgets Version

PySide6-Fluent-Widgets == 1.4.5

### How to Reproduce?

使用FluentDesigner为透明按钮添加图标（其他按钮也有此问题）

### Minimum code

```python3
self.TransparentPushButton = TransparentPushButton(Dialog)
        self.TransparentPushButton.setObjectName(u"TransparentPushButton")
        self.TransparentPushButton.setGeometry(QRect(190, 110, 41, 41))
        icon2 = QIcon()
        icon2.addFile(u":/icons/\u6587\u4ef6\u9009\u62e9.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.TransparentPushButton.setIcon(icon2)
        self.TransparentPushButton.setIconSize(QSize(30, 30))
```

**Comment by Aprebus** [comment]
问题在button的paintEvent里
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/71392091/558ff910-ad31-4948-bf82-9af2584988ae)
修改为如下代码后显示正常了
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/71392091/84f34ddd-3300-4f0a-8681-a664be400f88)

**Comment by zhiyiYo** [comment]
最好给图标留点白

**Comment by Aprebus** [comment]
我刚开始学pyside6，我是很不理解为什么minimumSizeHint的值比按钮的width还要大，以至于偏移是负数。

**Comment by zhiyiYo** [comment]
不太清楚，我没遇到过
