### ISSUE TITLE
【建议】对话框MessageBox或者Dialog设置内容为可复制后，复制内容右键菜单建议优化为Fluent样式的右键菜单

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#696]
目前对话框通过调用`setContentCopyable(True)`后，内容可以复制了，但是右键菜单还是原生的样式，不太协调，建议优化成RoundMenu的样式
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/608e9ad3-46b7-44c0-bbc7-efc6d7f73fdb)

**Comment by zhiyiYo** [comment]
这个不太好搞，不知道要怎么获取选中区域

**Comment by zhiyiYo** [comment]
v1.5.0 已重写右键菜单
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/2cd5511c-f631-4fb0-af92-386140f2b754)

**Comment by zhiyiYo** [comment]
FluentLabel 现在自带的右击菜单又会被替换成 RoundMenu
