### ISSUE TITLE
[Bug]: Win系统托盘图标进行右键菜单时位置不正确

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#698]
### What happened?

当程序设置了系统托盘图标和系统托盘菜单时，如果系统托盘图标放置在最底部的话，进行右键菜单，菜单位置不对
![6c421cee7564bf5d42c4de4ec0004abb](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/30360404-9286-40c0-87f7-41e0eb864248)

### Operation System

Win11

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.5

### How to Reproduce?

怀疑是adjustPosition函数的问题

### Minimum code

```python3
def adjustPosition(self):
        m = self.layout().contentsMargins()
        rect = getCurrentScreenGeometry()
        w, h = self.layout().sizeHint().width() + 5, self.layout().sizeHint().height()

        x = min(self.x() - m.left(), rect.right() - w)
        y = self.y()
        if y > rect.bottom() - h:
            y = self.y() - h + m.bottom()

        self.move(x, y)
```

**Comment by zhiyiYo** [comment]
已修复此问题
