### ISSUE TITLE
关于 PyQt-Fluent-Widgets 安装失败

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#7]
大佬你好，我直接安装你在github发布的PyQt-Fluent-Widgets会报错，请问是什么原因呢？

pip install PyQt-Fluent-Widgets

![QQ截图20230130101928](https://user-images.githubusercontent.com/104692238/215377026-8d9fe0f4-e031-4908-bd3c-037c368f09c0.png)

**Comment by Ephemeralwanning** [comment]
我本来是想提交的 但是看大佬在其他issue的回复说不是项目的问题就发邮件.....

**Comment by zhiyiYo** [comment]
感觉是安装 scipy 的问题

**Comment by Ephemeralwanning** [comment]
> 感觉是安装 scipy 的问题

我试着pip install scipy
确实是它的问题 我去搜索一下解决方法

**Comment by zhiyiYo** [comment]
如果不使用 `AcrylicLabel` 的话，其实不用安装 `scipy`、`pillow` 和 `colorthief`，我打算把这几个依赖包放在可选项里面

**Comment by Ephemeralwanning** [comment]
> 如果不使用 `AcrylicLabel` 的话，其实不用安装 `scipy`、`pillow` 和 `colorthief`，我打算把这几个依赖包放在可选项里面

已经解决 感谢大佬
前往https://www.lfd.uci.edu/~gohlke/pythonlibs/下载对应版本的whl文件对应安装即可

**Comment by Ephemeralwanning** [comment]
> 如果不使用 `AcrylicLabel` 的话，其实不用安装 `scipy`、`pillow` 和 `colorthief`，我打算把这几个依赖包放在可选项里面

另外问个问题 大佬用的vscode代码补全是自带的还是安装了另外的插件呢？我感觉自带的好难用

**Comment by zhiyiYo** [comment]
安装了 python 插件和 pylance 插件

**Comment by Ephemeralwanning** [comment]
> 安装了 python 插件和 pylance 插件

好的 非常感谢解惑

**Comment by zhiyiYo** [comment]
我在 pypi 发布了新版本，你可以试下 `pip install PyQt-Frameless-Window`(轻量版，`AcrylicLabel` 不可用，不需要安装 scipy、pillow 和 colorthief) 或者 `pip install 'PyQt-Frameless-Window[full]'`（全特性版，`AcrylicLabel` 可用）

**Comment by Ephemeralwanning** [comment]
> 我在 pypi 发布了新版本，你可以试下 `pip install PyQt-Fluent-Widgets`(轻量版，`AcrylicLabel` 不可用，不需要安装 scipy、pillow 和 colorthief) 或者 `pip install 'PyQt-Fluent-Widgets[full]'`（全特性版，`AcrylicLabel` 可用）

好的 我去试试
