### ISSUE TITLE
spinbox dateEdit的布局间距

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#70]
![image](https://user-images.githubusercontent.com/14865236/229394880-4e4f5600-caf3-47aa-8869-2431b80eb4f9.png)

箭头会不会太宽了，导致整个widget的宽度很大，不方便程序的布局

![image](https://user-images.githubusercontent.com/14865236/229395853-a9898e4e-8f35-4174-a444-7a9c5f6c967a.png)
这是和winui3的设计文档对比的，感觉还是宽了

**Comment by zhiyiYo** [comment]
我是按照 WinUI3 Gallery 中 SpinBox 的宽度写的，缩放 125% 的情况下都是 39px
![image](https://user-images.githubusercontent.com/65096819/229396708-125a9577-495a-4e68-aea5-20430a584979.png)
