### ISSUE TITLE
Pivot 超出宽度时 如何可以滚动

### ISSUE THREAD

**Issue by shiyueGG** [zhiyiYo/PyQt-Fluent-Widgets#701]
如图这种需求 应该怎么
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/58288932/745353b5-b6ea-4f0e-be67-ae484af159c6)

**Comment by zhiyiYo** [comment]
把 pivot 丢到 scrollarea 就行了

**Comment by shiyueGG** [comment]
> 把pivot丢到scrollarea就行了

是的 我就是这么想的，但是丢进去 好像也无法同步位置状态。请问有这类实例吗！

**Comment by zhiyiYo** [comment]
无法同步状态是什么意思？你有设置 widget resizable 吗

**Comment by shiyueGG** [comment]
> widget resizable

是的 设置了

`# 创建 Pivot 和 QScrollArea
        self.pivot = Pivot(self)
        self.scrollArea = QScrollArea(self)  # 创建滚动区域
        self.scrollArea.setWidget(self.pivot)  # 将 Pivot 控件设置为滚动区域的子控件
        self.scrollArea.setWidgetResizable(True)  # 允许滚动区域中的控件调整大小
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)  # 总是显示水平滚动条`

**Comment by zhiyiYo** [comment]
看不出有什么问题
