### ISSUE TITLE
请问右上角如何隐藏放大按钮图标，如何新增右上角自定义图标和按钮事件。

### ISSUE THREAD

**Issue by shiyueGG** [zhiyiYo/PyQt-Fluent-Widgets#703]
文档位置未找到、issues已搜索没有类似的情况。感谢作者。

**Comment by zhiyiYo** [comment]
方法按钮图标是什么意思？

**Comment by shiyueGG** [comment]
> 方法按钮图标是什么意思？

不好意思，没有看好标题就发了。我说的放大按钮 最大化按钮 想隐藏掉。。

**Comment by zhiyiYo** [comment]
直接调用 self.titleBar.maxBtn.hide(), 其他这种基础的问题可以加下官方交流群（群号在 B 站关注我之后可以拿到）来问，github 看的不多了

**Comment by shiyueGG** [comment]
> 直接调用 self.titleBar.maxBtn.hide(), 其他这种基础的问题可以加下官方交流群（群号在 B 站关注我之后可以拿到）来问，github 看的不多了

好的
