### ISSUE TITLE
[Bug]: 浅色模式开启云母效果，再切换到黑色全屏状态下界面显示异常

### ISSUE THREAD

**Issue by KandyYe** [zhiyiYo/PyQt-Fluent-Widgets#704]
### What happened?

1. 浅色模式，开启云母效果；
2. 切换到深色模式；
![Snipaste_2024-01-07_09-19-18](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/66efaa5b-b2ba-4843-88ea-2d55b0453fe7)
3. 放大窗口，显示异常。
![Snipaste_2024-01-07_09-18-52](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/c14dac96-12a9-4dca-b40e-ab74f19ed32a)

### Operation System

Windows 11  23H2

### Python Version

64-bit

### PyQt/PySide Version

Pyside6

### PyQt/PySide-Fluent-Widgets Version

v1.4.5

### How to Reproduce?

1. 浅色模式，开启云母效果；
2. 切换到深色模式；
![Snipaste_2024-01-07_09-19-18](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/66efaa5b-b2ba-4843-88ea-2d55b0453fe7)
3. 放大窗口，显示异常。
![Snipaste_2024-01-07_09-18-52](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/c14dac96-12a9-4dca-b40e-ab74f19ed32a)

### Minimum code

```python3
无
```

**Comment by zhiyiYo** [comment]
无法复现此问题

**Comment by zhiyiYo** [comment]
可以录个屏吗

**Comment by KandyYe** [comment]
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/2ca1b763-5034-49a5-824f-8e659db18f11

**Comment by zhiyiYo** [comment]
有动过我的 gallery 代码吗？子界面的位置看起来不太对，往右边偏移了很多

**Comment by KandyYe** [comment]
没有动过，刚刚重新抓取最新的代码，编译完成还是存在这个问题。
![Snipaste_2024-01-09_20-54-21](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/62ada188-aa65-4e2f-b7c6-1983807448ea)
![Snipaste_2024-01-09_20-56-38](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/336bb367-f16e-42a2-a373-53fc0107fc61)
![Snipaste_2024-01-09_21-03-29](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/5a34e03d-ad56-4ccb-841e-faba60492e3d)
![Snipaste_2024-01-09_21-04-07](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/33487591/fbc0098b-9319-4e0b-b615-7b7aebf817b3)

**Comment by Kewei-cpu** [comment]
遇到相同问题

**Comment by zhiyiYo** [comment]
已经开始怀疑是系统问题了

**Comment by zhiyiYo** [comment]
把云母特效关了试试

**Comment by zhiyiYo** [comment]
顺便把无边框窗口更新到 0.3.6

**Comment by Kewei-cpu** [comment]
需要启动时是浅色模式，开启云母，切换到深色再全屏，才能触发

**Comment by Kewei-cpu** [comment]
启动时是深色模式，切换到浅色再全屏，也会有一个神奇的灰色效果
<img width="1280" alt="image" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/84075255/e87a7c71-ef6f-41cb-80ae-f106c4343091">

**Comment by Kewei-cpu** [comment]
> 把云母特效关了试试

关掉就一切正常

**Comment by zhiyiYo** [comment]
复现不出来，估计是操作系统的原因了
