### ISSUE TITLE
Add information about python version needed

### ISSUE THREAD

**Issue by Usercyk** [zhiyiYo/PyQt-Fluent-Widgets#705]
额，是这样，我今天想下载pyside6的包，用了python 3.12，发现下载不了，看起来来自于版本兼容问题。
当然pyside6本身是有3.12的，那就应该是这个包没有
但我在所有文档里都没看到版本的标识……一个一个试貌似不太方便……
所以希望能在文档里加一下说明

（话说wiki的样式怎么和tailwindcss一样，还以为我点错了

**Comment by rainzee** [comment]
为什么你会自信地觉得 PYSIDE 支持312呢？目前由于 PYSIDE 的一个计算几何 BUG，我们使用 6.4.2 做为上游版本，6.4.2 的 pypi 中 Requires: Python <3.12, >=3.7，所以没有什么不方便的。建议仔细看看。

**Comment by zhiyiYo** [comment]
有历史 issue

**Comment by Usercyk** [comment]
> 为什么你会自信地觉得 PYSIDE 支持312呢？目前由于 PYSIDE 的一个计算几何 BUG，我们使用 6.4.2 做为上游版本，6.4.2 的 pypi 中 Requires: Python <3.12, >=3.7，所以没有什么不方便的。建议仔细看看。

???
添加一个版本号又不麻烦……这确实不是啥大问题，但每一个新使用的用户都会遇到确认版本这件事，何乐而不为呢？而且我认为3.12的类型标注以及其他功能确实方便了，bug迟早会修，先写代码。

而且我又不是让你们赶紧更新3.12，我只是想添加一行版本标识……markdown里加一行应该很快（
而且问题来了，我就是因为没有找到任何版本信息，包括依赖的pyside6的版本，才来提这个issue的啊（
就是因为仔细看过了，没找到，才希望能加一个标识（
这年头，写个版本号还能有错了是吧，戾气咋这么大（

**Comment by Usercyk** [comment]
> 有历史 issue

请问一下这个历史在哪里啊，能不能给个链接，谢谢

**Comment by zhiyiYo** [comment]
v1.4.6 已支持 py312

**Comment by Usercyk** [comment]
好吧，不加算了

不过还是谢谢

**Comment by zhiyiYo** [comment]
1.5.2 已取消 PySide6 版本限制
