### ISSUE TITLE
TextEdit控件光标定位到编辑框后底部的那个边框宽度应该是2px

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#71]
目前TexEdit光标聚焦后底部边框还是1px高亮
根据设计文档，应该是2px
![image](https://user-images.githubusercontent.com/8281775/229400265-8dbfac41-3b41-4a39-a56a-0b246c1eb351.png)
![image](https://user-images.githubusercontent.com/8281775/229400328-4aec4150-54b6-4999-8cc6-a704ec9589c1.png)

**Comment by zhiyiYo** [comment]
目前只能在 `viewport` 上面绘制边框，如果加了 `padding-left: 10px`，会导致视口向右缩小 10px，就画不出那种效果了
