### ISSUE TITLE
[现象] ComboBox无法正确向上弹出

### ISSUE THREAD

**Issue by chenzhanpeng2018** [zhiyiYo/PyQt-Fluent-Widgets#710]
不同分辨率不同缩放比例的两块屏幕上下分布，使得ComboBox控件处于上面屏幕的最下方，ComboBox无法正确向上弹出(调试代码发现逻辑计算出来的结果是向下弹出（hd，hu都为1）)（上面屏幕最下方的点全局坐标计算显示大概为(1906,-10)）

**Comment by zhiyiYo** [comment]
屏幕分辨率、缩放比以及排列方式是怎么样的？

**Comment by chenzhanpeng2018** [comment]
一个笔记本，一个显示器，屏幕上下排列，分辨率都是1920*1080，下方笔记本缩放比例 150% ，上方显示器缩放比例100%。设置为扩展显示器。

**Comment by chenzhanpeng2018** [comment]
<img width="293" alt="微信图片_20240116142251" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/45413535/3d92af36-d63f-4e80-bc53-2fbfa3b04314">

**Comment by chenzhanpeng2018** [comment]
Combobox放置在上方屏幕的最下方，就会出现不能正确选择向上弹出，还是向下弹出，导致item无法显示。

**Comment by chenzhanpeng2018** [comment]
@zhiyiYo
