### ISSUE TITLE
[Bug]: CalendarView年視圖顯示錯誤

### ISSUE THREAD

**Issue by abyss-zues** [zhiyiYo/PyQt-Fluent-Widgets#712]
### What happened?

CalendarView年視圖和標題上的範圍顯示不同
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/110171545/7ee980ea-395e-4c0f-a1f8-8bb8a1e2cb1a)

### Operation System

Windows 10 21H1

### Python Version

Python 3.11.6 x64

### PyQt/PySide Version

Pyside6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.4.5

### How to Reproduce?

無

### Minimum code

```python3
無
```

**Comment by zhiyiYo** [comment]
这个不太算 bug
