### ISSUE TITLE
[Bug]: scrollarea and its contents do not change color

### ISSUE THREAD

**Issue by brandonzorn** [zhiyiYo/PyQt-Fluent-Widgets#713]
### What happened?

scrollarea and its contents do not change color
![изображение](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68778953/3d180b7f-6811-4b04-829c-46fa0693035d)

### Operation System

Windows11 23H2

### Python Version

3.11.7 64-bit

### PyQt/PySide Version

6.4.2

### PyQt/PySide-Fluent-Widgets Version

1.4.5

### How to Reproduce?

![изображение](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68778953/b7a8a72f-6b68-4afb-a137-dbf8b0faab9c)

### Minimum code

```python3
import sys

from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication
from qfluentwidgets import setTheme, Theme, FluentWindow, ScrollArea, CardWidget, TitleLabel


class AppWindow(FluentWindow):
    def __init__(self):
        super().__init__()

        self.area = ScrollArea()
        self.card = CardWidget()
        self.card.setFixedSize(120, 120)
        self.lbl = TitleLabel("label", self.card)
        self.area.setWidget(self.card)
        self.stackedWidget.addWidget(self.area)


if __name__ == "__main__":
    QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.RoundPreferFloor)
    setTheme(Theme.DARK)
    app = QApplication(sys.argv)
    window = AppWindow()
    window.show()
    sys.exit(app.exec())
```

**Comment by zhiyiYo** [comment]
You should set the style sheet of ScrollArea by yourself.
