### ISSUE TITLE
[Bug]: Installation problem: Pillow version not compatible with Python version

### ISSUE THREAD

**Issue by 3rdPix** [zhiyiYo/PyQt-Fluent-Widgets#715]
### What happened?

When trying to install with `pip install "PyQt6-Fluent-Widgets[full]" -i https://pypi.org/simple/`. It finds an error at the very end with the Pillow library. In requirements it is expressed that **pillow version should be <=9.4.0**... why do you keep that? Is there a backwards compatibility problem with newer versions? In the pillow site its expressed that newer python versions only work with Pillow >= 10.1. See:

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/86542704/8448b2d8-ee3b-4ddc-8d4b-5a2e75cbcf5b)

On this matter, is there a reason you keep pillow in older versions? Could we just use the newer version?

### Operation System

Windows 23H2

### Python Version

Python 3.12.1

### PyQt/PySide Version

PyQt6

### PyQt/PySide-Fluent-Widgets Version

1.4.5

### How to Reproduce?

During installation

### Minimum code

```python3
Does not apply.
```

**Comment by 3rdPix** [comment]
**AUTO-UPDATE**

I manually installed the latest versions of all the dependencies. Including *Pillow* and *Frameless-Window*. **There is no need to add version restriction**, newer versions will work just fine. This needs to be updated in the `setup` and `requirements` files so that it does not cause wheel errors whilst installing fluent widgets.

Here you can see the version list with `pip` and the fluent window (the only one currently updated to PyQt6) working normally:

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/86542704/4cd6efb4-d309-4377-ba7c-acfeae1db27e)

The main issue was the **Pillow** package, but again, there is no need to restrict the requirement to older versions. I suggest to change it, and let it install the latest version.

**Comment by zhiyiYo** [comment]
See https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/376

**Comment by zhiyiYo** [comment]
`Image.fromqpixmap(QPixmap(image))` will raise an exception if the version of pillow >= 9.4.0, maybe I should use another way to convert `QPixmap` to `Image`

**Comment by 3rdPix** [comment]
You're right! But in this case I was only referring to PyQt6 branch (where obviously PyQt > 5.15.10)... maybe apply the change only on that deployment?

**Comment by zhiyiYo** [comment]
Sorry, `Image.fromqpixmap(QPixmap(image))` will raise an exception if the version of pillow >= 9.4.0 and PyQt > 5.15.2. PyQt6 has not been tested.

**Comment by zhiyiYo** [comment]
I checked the source code of PIL, and found that high version PIL only supports PyQt6/PySide6.
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/42eae6a4-addd-4ca7-8027-c02c618b1068)

**Comment by zhiyiYo** [comment]
But Pillow 9.4.0 supports all Qt bindings. This is weird.
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/107b2cfb-5a54-49b9-844c-f1c510e53a03)

**Comment by zhiyiYo** [comment]
This is the conversion method, I will add it to my repo:
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/782db335-964d-493c-a4cb-42140a7bb8db)

**Comment by 3rdPix** [comment]
I was just checking the same! Here you can see the exact commit where they stopped supporting PyQt5:

https://github.com/python-pillow/Pillow/commit/59c9d87f8a4d8443a482ca7abb5f1f8d5d970cbd
https://github.com/python-pillow/Pillow/commits/main/src/PIL/ImageQt.py

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/86542704/cb095141-4900-4d7c-aa8c-522e4bdb40db)

I think the solution should be to make a clear differentiation between the PyQt5 and the PyQt6 branch. Modifying the `setup.py` so that it takes into account that newer versions of Pillow support PyQt6 only instead of PyQt5.

**Comment by zhiyiYo** [comment]
V1.4.6 has removed restrictions on the PIL version

**Comment by 3rdPix** [comment]
Just saw the commit. Installation for PyQt6 now working perfectly with latest version of Pillow:

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/86542704/1e344eac-c057-46be-a096-6d20289e0bdc)

Thanks!
