### ISSUE TITLE
[Bug]: Small adjusment in flag for PyQt6 in example widget

### ISSUE THREAD

**Issue by 3rdPix** [zhiyiYo/PyQt-Fluent-Widgets#716]
### What happened?

Alignment flags are consistent with new PyQt6 `Qt.AlignmentFlag` except for one single case. I thought is not worth a pull request.

On branch: PyQt6, example widget **ComboBox** in `demo.py` change line 30 from

`self.hBoxLayout.addWidget(self.comboBox, 0, Qt.AlignCenter)`

to

`self.hBoxLayout.addWidget(self.comboBox, 0, Qt.AlignmentFlag.AlignCenter)`

Every other example is changed to this new way of setting alignment flags except for this case.

### Operation System

Windows 23H2

### Python Version

Python 3.12.1

### PyQt/PySide Version

PyQt6

### PyQt/PySide-Fluent-Widgets Version

1.4.6

### How to Reproduce?

try demo.py for combobox

### Minimum code

```python3
does not apply
```

**Comment by zhiyiYo** [comment]
Thank you, I will fix this bug later
