### ISSUE TITLE
[Bug]: Pro组件的MultiSelectionComboBox在QtPy版本中多选后按钮重叠，在Pyside6版本多选后未水平对齐

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#721]
### What happened?

QtPy版本：多选选项后，选项按钮之间重叠显示了
PySide6版本：多选选项后，选项按钮未水平对齐
备注：另外如果多选选项后无法完整显示时好像不支持水平滚动查看？不知道能否大佬能否加上

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/0853f4ce-7a04-4dea-b449-87865c497916)

### Minimum code

```python3
MultiSelectionComboBox的demo文件
```

**Comment by zhiyiYo** [comment]
布局还是 `setAttribute(Qt.WidgetAttribute.WA_LayoutUsesWidgetRect)` 的问题
