### ISSUE TITLE
[Bug]: Pro组件的快捷键选择器对话框的重置按钮未和确定和取消按钮水平对齐显示

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#725]
### What happened?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/fd08e94f-872d-418f-b87c-eb82826d90c3)

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PySide6 6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

三个按钮对齐显示

### Minimum code

```python3
demo
```

**Comment by zhiyiYo** [comment]
感觉少设置了标志位
