### ISSUE TITLE
[Bug]: SegmentedWidget.setCurrentItem不起作用

### ISSUE THREAD

**Issue by fyplclfkr** [zhiyiYo/PyQt-Fluent-Widgets#729]
### What happened?

不管代码里选择哪个，运行后都是第一个，演示里的我改了代码也是这个情况，但是实际的选择是对的，只是UI上选择的不对
![g111](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74193811/4202f5ff-5fa2-4964-960d-e2a1e7051331)
![g222](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/74193811/5c35d16f-6459-41d3-90ee-6b6a17594448)

### Operation System

windows10 22H2

### Python Version

3.9.18

### PyQt/PySide Version

5.15.9

### PyQt/PySide-Fluent-Widgets Version

1.3.5

### How to Reproduce?

随便写一个都是这种情况

### Minimum code

```python3
import sys

from PyQt5.QtWidgets import QApplication, QWidget

from qfluentwidgets import SegmentedWidget


class demo(QWidget):

    def __init__(self):
        super().__init__()
        self.sss = SegmentedWidget(self)
        self.sss.addItem("111", "111")
        self.sss.addItem("222", "222")
        self.sss.setCurrentItem("222")
        print("当前选择项：",self.sss.currentItem().text())
        
if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = demo()
    w.show()
    app.exec()
```

**Comment by zhiyiYo** [comment]
你可能得在 showEvent() 里面设置，不然 Pivot 宽度计算有问题，导致指示器位置错误
