### ISSUE TITLE
cannot import name 'FramelessDialog' from 'qframelesswindow'

### ISSUE THREAD

**Issue by eggegg2001** [zhiyiYo/PyQt-Fluent-Widgets#73]
如题，很抱歉我是新手，所以不知道发生什么。
这个问题存在在任何一个demo运行的时候。
更为神奇的是，并没有所谓的FramelessDialog和qframelesswindow
![Uploading image.png…]()

**Comment by eggegg2001** [comment]
![image](https://user-images.githubusercontent.com/28710721/229460142-6808b245-ebbd-4be9-a905-cf07863b2d95.png)

**Comment by zhiyiYo** [comment]
请补充一下环境信息，包括 PyQt5-Frameless-Window 和 PyQt-Fluent-Widgtes 的包版本

**Comment by eggegg2001** [comment]
环境为win10 python310
PyQt-Fluent-Widgets       0.5.6
PyQt5                     5.15.7
PyQt5-Frameless-Window    0.1.1
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.11.0

**Comment by eggegg2001** [comment]
更新PyQt5-Frameless-Window 后问题得到解决，感谢作者，秒回太爱了
