### ISSUE TITLE
smooth scroll in ListWidget

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#730]
how can smooth scroll in listwidget using list_widget.scrollToItem(list_item)
like this

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/9ae334f0-7143-4a9c-a45f-a4b04d379709

**Comment by zhiyiYo** [comment]
You can check the source code of SmoothScrollDelegate

**Comment by zhiyiYo** [comment]
You can check the source code of SmoothScrollDelegate

**Comment by zhiyiYo** [comment]
set the `useAni` property to `True`, and run `listWidget.scrollDelegate.vScrollBar.scrollTo(the position of item)`
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/946a8c4b-724d-4116-9466-ac5ce342603e)

**Comment by immiProgrammer** [comment]
It works this way. If you have a better solution, please share it with me; otherwise, consider the issue solved.
```
    def onClicked(self):
        item = self.list_widget.item(10)
        if not item:return

        rect = self.list_widget.visualItemRect(item)
        vsBar = self.list_widget.scrollDelegate.vScrollBar
        v = rect.y() # top
        # v = -int((self.list_widget.viewport().height()/2)-rect.height()/2)+rect.y() # center
        # v = -(self.list_widget.viewport().height()-rect.height())+rect.y() # bottom
        vsBar.scrollTo(vsBar.value()+v)
```

**Comment by immiProgrammer** [comment]
override `scrollToItem` method of QListWidget in qfluentwidget `ListWidget`
