### ISSUE TITLE
how can i change the resolution of the images showing in the FlipView?

### ISSUE THREAD

**Issue by AliMostafaRadwan** [zhiyiYo/PyQt-Fluent-Widgets#731]
how can i change the resolution of the images in the FlipView without changing the resolution of the original images?

**Comment by zhiyiYo** [comment]
Sorry, I don't get your point. Can you express yourself more clearly, such as giving an example in a picture

**Comment by immiProgrammer** [comment]
Using pixmap or icon widget

**Comment by AliMostafaRadwan** [comment]
having a high resolution images can make the FlipView SOO LAGY

**Comment by AliMostafaRadwan** [comment]
> Using pixmap or icon widget

can you show me the code ?

**Comment by zhiyiYo** [comment]
> having a high resolution images can make the FlipView SOO LAGY

Yes, you should scale the image before adding it to flipview.
