### ISSUE TITLE
[Bug]: Pro组件中的颜色选择器在深色模式下的色值前面的“#”未显示成白色样式

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#733]
### What happened?

颜色选择器当使用深色模式时，查看色值，色值前面的“#”仍显示成黑色了，应该显示成白色
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/33be413b-ec59-4377-9c98-f1d6f744c759)

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

浅色模式下正常

### Minimum code

```python3
demo文件
```

**Comment by zhiyiYo** [comment]
已修复此问题
