### ISSUE TITLE
Resizing the Action icon in RoundMenu 

### ISSUE THREAD

**Issue by deeffest** [zhiyiYo/PyQt-Fluent-Widgets#734]
The thing is that I didn't find the right icons in FIF and so I decided to use svg icons from google. In the case of FIF icons, their size is quite balanced and large, unlike icons set via setIcon(QIcon()). - they are too small and changing their size via setIconSize is impossible, I have also tried changing QProxyStyle which works with the standard QMenu making the icons in QAction bigger/smaller, but what can be done with the icons in RoundMenu?

Take a look at the icons provided by google:
![изображение](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/117280555/c4832ce6-9fc5-485c-a8ec-5d37535bf596)

And here's FIF:
![изображение](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/117280555/38a863f1-353a-4171-8740-95884787dca0)

**Comment by immiProgrammer** [comment]
Svg viewbox and height issue plz provide me svg code

**Comment by deeffest** [comment]
<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z"/></svg> 
@immiProgrammer

**Comment by deeffest** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z"/></svg>`
@immiProgrammer

**Comment by immiProgrammer** [comment]
> `<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z"/></svg>`
> @immiProgrammer 

It's look fine i try it later

**Comment by zhiyiYo** [comment]
You can set the transform property of path. Set the scale factor to a bigger one.

**Comment by immiProgrammer** [comment]
<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0V0z" fill="red" /><path transform="translate(-5 -5) scale(1.4)" d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z" />
</svg>

**Comment by deeffest** [comment]
If anyone needs it, I found a tool that removes all free space from svg, thus making the icons in RoundMenu adequately sized. - [https://svgcrop.com](https://svgcrop.com)

**Comment by JackYuan12138** [comment]
> If anyone needs it, I found a tool that removes all free space from svg, thus making the icons in RoundMenu adequately sized. - https://svgcrop.com

Your comment has done me a great favor!!!!
