### ISSUE TITLE
[Feature Require] `OptionsSettingCard` 添加禁用样式

### ISSUE THREAD

**Issue by rainzee** [zhiyiYo/PyQt-Fluent-Widgets#738]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/c305794c-5917-48ce-b1cc-312dd5bb93db)

为 `OptionsSettingCard` 添加禁用样式，当禁用时提示用户，如果可行的话，可以添加是否展开的方法，特别地可以区分，禁止展开，和禁用，当禁用的时候，也许禁用内部所有的 RadioButton 更合适，毕竟是禁用选项，而不是禁止展开，让用户知道可选项，和禁用样式，更加符合用户心智，WinUI如此

**Comment by zhiyiYo** [comment]
目前的x效果
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65096819/d4123d1c-fc2a-4c5f-9414-08ea631792e0)
