### ISSUE TITLE
[Bug]:  PyQt-Fluent-Widgets in QtDesigner failed yo work properly (QyQt6 environment)

### ISSUE THREAD

**Issue by JohnHa0** [zhiyiYo/PyQt-Fluent-Widgets#739]
### What happened?

The environment has been set successfully based on the instructions in PyQt branch. I can successfully launch the designer from the terminal (python ./tools/designer.py). However, the sidebar did not contain the  PyQt-Fluent-Widgets elements. Would you please check this issue ?

### Operation System

Mac 14.2.1  

### Python Version

python 3.11.7

### PyQt/PySide Version

PyQt6

### PyQt/PySide-Fluent-Widgets Version

v1.4.7

### How to Reproduce?

python ./tools/designer.py from the source code file for the pyqt6 branch. The designer will launch but it will not integrate the  PyQt-Fluent-Widgets 

### Minimum code

```python3
python ./tools/designer.py
```

**Comment by zhiyiYo** [comment]
试下 PySide6：https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/196#issuecomment-1776499395

**Comment by JohnHa0** [comment]
Pyslide6 still failed to work properly with the plug
