### ISSUE TITLE
颜色选择对话框可以增加一个获取Alpha不透明度的功能吗

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#74]
![QQ截图20230403164723](https://user-images.githubusercontent.com/104692238/229461274-33a69747-bce4-4c60-9282-a1d6c13f6f2c.png)

类似这种

![QQ截图20230403165837](https://user-images.githubusercontent.com/104692238/229462113-561d90eb-fbd9-4246-8b9b-b7cc09fb03d0.png)

**Comment by zhiyiYo** [comment]
下个版本可以加上

**Comment by zhiyiYo** [comment]
用的 typora，错位了页问题不大，只要 github 主页不错位就行

**Comment by zhiyiYo** [comment]
v0.7.4 已添加该功能
