### ISSUE TITLE
优化切换主题的效率

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#741]
目前切换主题的速度有点慢，有必要优化一下

**Comment by immiProgrammer** [comment]
> 目前切换主题的速度有点慢，有必要优化一下

nice

**Comment by zhiyiYo** [comment]
以下三个函数都添加了 `lazy` 参数，设置为 `True` 可提升更换主题的速度：
* `toggleTheme(save=False, lazy=False)`
* `setTheme(theme, save=False, lazy=False)`
* `setThemeColor(color, save=False, lazy=False)`
