### ISSUE TITLE
[Bug]: Pro组件中的拖放单文件夹和拖放多文件夹组件在QtPy版本无法点击按钮打开选择文件对话框，在PySide6版本中拖放多文件夹点击按钮后无法多选文件夹

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#745]
### What happened?

问题1：在QtPy版本中，拖放单文件夹和拖放多文件夹组件点击浏览按钮没反应，无法打开选择文件对话框
问题2：在PySide6版本中，拖放多文件夹组件点击浏览按钮打开选择文件对话框后，无法多选文件夹，只能单选
备注：以上版本拖放文件夹组件拖曳本地文件夹到组件框正常
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/a4f98b2e-0033-422b-9eef-9e49bd84b116)

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.4.6

### How to Reproduce?

QtPy版本及PySide6版本均有问题，但是拖放单文件组件在QtPy版本可以打开选择文件对话框

### Minimum code

```python3
Demo文件
```

**Comment by zhiyiYo** [comment]
qt 好像没有提供多选文件夹的功能

**Comment by zhiyiYo** [comment]
除非不使用本地文件夹选择器，换成 qt 自带的那个很丑的文件夹选择器
