### ISSUE TITLE
新手请教几个基础使用问题

### ISSUE THREAD

**Issue by npzs** [zhiyiYo/PyQt-Fluent-Widgets#746]
大佬好，文档读了但是有些表述不是很明确，麻烦抽空回一下，谢谢。

1. 我下载了 Fluent Designer 设计界面，是不是主界面不能在设计器里完成，只能用代码写？我的意思是主界面用 FluentWindow 这样的类的话，没找到设计器里能把窗口设置成这种类的方法。（或者说我看文档描述说 FluentWindow 等几个窗口类只是封装了侧边导航，我不清楚是否还有更多区别，假设我不使用侧边导航、或者我手动添加侧边导航的话，那是不是在设计器里随便一个默认的窗口类做程序入口的主界面都是可以的？）
2. 如果使用了 FluentWindow，它自带的侧边导航栏始终是在左侧，这是由布局控制的么，我意思是如果我想给它设置到窗口右侧该怎么操作？
3. 还有控件CommandBar，是不是也只能用代码写，我在设计器里拖入这个控件，找不到添加动作的方法，并不像QToolBar那样支持把QAction拖进去，还有这个CommandBar能代替QToolBar不，是不是不支持QToolBar那样设置ToolBarArea的方式，我只能手动依靠布局来定位是不是？
4. 这个库是不是没有替代 QMdiArea 的控件，如果我想开发个MDI的程序，是不是直接用 QMdiArea 然后再把这个库的窗口及空间插入就行？

谢谢！

**Comment by zhiyiYo** [comment]
1. 子界面可以用设计师，主界面你只能用代码
2. 可以加到右侧，但是菜单展开有问题
3. 只能用代码加 action
4. 没有 MDI

**Comment by npzs** [comment]
> 1. 子界面可以用设计师，主界面你只能用代码
> 2. 可以加到右侧，但是菜单展开有问题
> 3. 只能用代码加 action
> 4. 没有 MDI

了解了，谢谢老板
