### ISSUE TITLE
Plz add toast widget using InfoBar

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#748]
like this
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101139501/3e4e7a5f-d53e-466e-83d5-0349ab71c9d8)

**Comment by zhiyiYo** [comment]
Maybe you are lookding for this: https://github.com/GitHub30/win11toast

**Comment by immiProgrammer** [comment]
> Maybe you are lookding for this: https://github.com/GitHub30/win11toast

I'm already aware of this, but the problem arises when other toasts are in the list. For instance, when receiving notifications from WhatsApp or other applications, it becomes delayed.

**Comment by immiProgrammer** [comment]
> Maybe you are lookding for this: https://github.com/GitHub30/win11toast

by the way this toast message is showing with `QSystemTrayIcon.showMessage()`

**Comment by immiProgrammer** [comment]
not completed
