### ISSUE TITLE
Very laggy when scrolling on macOS

### ISSUE THREAD

**Issue by xicrosoft** [zhiyiYo/PyQt-Fluent-Widgets#75]
**Describe the bug**
Very laggy when scrolling through pages, both on the trackpad (Apple Magic Trackpad) and on the mouse (Apple Magic Mouse)

**Environment**
- OS: macOS Ventura 13.4 beta (22F5027f) [latest]
- DPI scaling: 100% [Default]
- Python: 3.11.1:a7a450f84a [?latest]
- PySide: 6.4.2 [latest]
- PySide6-Fluent-Widgets: 0.3.4 [latest]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. Run `python demo.py` or `python3 demo.py`
2. See the error

**Code**
[examples/gallery/demo.py](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/a6765d89f1df5ba2c2202d6c7752b34452f70b5f/examples/gallery/demo.py)

**Expected behavior**
Pages should scroll smoothly

**Screenshots**
I think you should understand

> I am not a native English speaker, so please ignore my wording errors!

**Comment by AuroraZiling** [comment]
我这边mac也出现了滚动延迟的情况，正打算提个issue😂

**Comment by zhiyiYo** [comment]
Windows 没有此问题，你们测试过 PyQt 吗

**Comment by xicrosoft** [comment]
我试一下

**Comment by xicrosoft** [comment]
我这边 pip 装 pyqt5 报错了，@AuroraZiling 你试试吧

**Comment by zhiyiYo** [comment]
可能得用 conda 安装

**Comment by xicrosoft** [comment]
我用的是venv，之前装过一次，现在忘了咋装了

**Comment by xicrosoft** [comment]
**Re.[@AuroraZiling 75#1494484969](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/75#issuecomment-1494484969)**

用这个 demo 试试
[examples/gallery/demo.py](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/a6765d89f1df5ba2c2202d6c7752b34452f70b5f/examples/gallery/demo.py)

**Comment by AuroraZiling** [comment]
报错，怪
```python
Traceback (most recent call last):
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/demo.py", line 37, in <module>
    w = MainWindow()
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/app/view/main_window.py", line 64, in __init__
    self.setTitleBar(CustomTitleBar(self))
  File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/app/view/title_bar.py", line 14, in __init__
    self.iconLabel = QLabel(self)
TypeError: arguments did not match any overloaded call:
  QLabel(parent: typing.Optional[QWidget] = None, flags: Qt.WindowType = Qt.WindowFlags()): argument 1 has unexpected type 'CustomTitleBar'
  QLabel(text: str, parent: typing.Optional[QWidget] = None, flags: Qt.WindowType = Qt.WindowFlags()): argument 1 has unexpected type 'CustomTitleBar'

```

**Comment by xicrosoft** [comment]
**Re. [@AuroraZiling ｜ 75#1494525475](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/75#issuecomment-1494525475)**

看看这个，应该也是用的镜像，版本太低了
[#48 运行demo报错](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/48)

**Comment by xicrosoft** [comment]
用官方源试试

**Comment by AuroraZiling** [comment]
更新后还是一样报错（悲

**Comment by xicrosoft** [comment]
又可以开新 issue 了（

**Comment by zhiyiYo** [comment]
看起来代码也没问题，`QLabel` 的父级设置为 `CustomTitleBar`

**Comment by zhiyiYo** [comment]
难道是pyside6的坑，也许可以换成 SmoothScrollArea

**Comment by Cheukfung** [comment]
> 不知道是不是这样实现，测试发现无滑动延迟
> 
> ```python
> from PyQt6.QtWidgets import (QWidget, QLabel, QScrollArea, QVBoxLayout, QMainWindow)
> from PyQt6.QtCore import Qt
> from PyQt6 import QtWidgets
> import sys
> 
> 
> class MainWindow(QMainWindow):
> 
>     def __init__(self):
>         super().__init__()
>         self.scroll = QScrollArea()
>         self.widget = QWidget()
>         self.vbox = QVBoxLayout()
> 
>         for i in range(1, 100):
>             object = QLabel(f"Label: {i}")
>             self.vbox.addWidget(object)
> 
>         self.widget.setLayout(self.vbox)
> 
>         self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
>         self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
>         self.scroll.setWidgetResizable(True)
>         self.scroll.setWidget(self.widget)
> 
>         self.setCentralWidget(self.scroll)
> 
>         self.setGeometry(600, 100, 1000, 900)
>         self.setWindowTitle('Test')
>         self.show()
> 
>         return
> 
> 
> def main():
>     app = QtWidgets.QApplication(sys.argv)
>     main = MainWindow()
>     sys.exit(app.exec())
> 
> 
> if __name__ == '__main__':
>     main()
> ```

@zhiyiYo 用这个pyqt6的例子测试也没问题。python版本3.10.8。
另外运行examples/gallery/demo.py的python版本是3.9.12，都没复现问题

**Comment by AuroraZiling** [comment]
暂时不太好录屏，大概效果就是：
在划动触摸版后1-2s，页面滑动

用的m1芯片

**Comment by Cheukfung** [comment]
> 报错，怪
> 
> ```python
> Traceback (most recent call last):
>   File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/demo.py", line 37, in <module>
>     w = MainWindow()
>   File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/app/view/main_window.py", line 64, in __init__
>     self.setTitleBar(CustomTitleBar(self))
>   File "/Users/mccreelee/CodeSpace/PyQt-Fluent-Widgets/examples/gallery/app/view/title_bar.py", line 14, in __init__
>     self.iconLabel = QLabel(self)
> TypeError: arguments did not match any overloaded call:
>   QLabel(parent: typing.Optional[QWidget] = None, flags: Qt.WindowType = Qt.WindowFlags()): argument 1 has unexpected type 'CustomTitleBar'
>   QLabel(text: str, parent: typing.Optional[QWidget] = None, flags: Qt.WindowType = Qt.WindowFlags()): argument 1 has unexpected type 'CustomTitleBar'
> ```

@zhiyiYo 这可能是mac上有的bug，我在mac也遇到了，Windows没问题。QLabel的构造函数里面,parent参数类型如果不是QWidget，就会出错，很奇怪。

**Comment by xicrosoft** [comment]
**Re. @Cheukfung ｜ [75#1494612124](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/75#issuecomment-1494612124)**

不太可能吧，m1的，有点太次性能了吧

**Re. @zhiyiYo ｜ [75#1495148155](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/75#issuecomment-1495148155)**

不仅仅是触摸板，magic mouse也有问题，一开始我也以为是触摸板的问题

**Comment by zhiyiYo** [comment]
@xicrosoft 
触控板是不是会有延迟然后才开始滚动

**Comment by xicrosoft** [comment]
**Re. @zhiyiYo ｜ [75#1495351906](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/75#issuecomment-1495351906)**

差不多，是滑动过后差不多卡1秒，然后一下滚动到应该滚动到的位置

**Comment by zhiyiYo** [comment]
Windows上也会这样，现在不知道要怎么判断 QWheelEvent 是由触控板引起的还是滚轮引起的

**Comment by StoneMoe** [comment]
> Windows上也会这样，现在不知道要怎么判断 QWheelEvent 是由触控板引起的还是滚轮引起的

不知道能不能用得上：
[qt::MouseEventSource-enum](https://doc.qt.io/qt-5/qt.html#MouseEventSource-enum)

> [pixelDelta](https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta)() returns the deltas in screen pixels, and is available on platforms that have high-resolution trackpads, such as macOS. If that is the case, [source](https://doc.qt.io/qt-5/qwheelevent.html#source)() will return [Qt::MouseEventSynthesizedBySystem](https://doc.qt.io/qt-5/qt.html#MouseEventSource-enum).

**Comment by zhiyiYo** [comment]
我之前测了一下好像还是区分不了滚轮和触控板。

出现这个延迟的原因是触控板引发的 `QWheelEvent.angleDelta().y()` 太小，对他进行插值的话会有一些小于 1 的值，然后再进行四舍五入就变成 0 了，这时候插值出来的 `QWheelEvent` 不起作用

**Comment by zhiyiYo** [comment]
v0.6.8 已修复该问题
