### ISSUE TITLE
[Bug]: Card的setBackground，无法改变hover状态的颜色

### ISSUE THREAD

**Issue by Lin-Yuhao** [zhiyiYo/PyQt-Fluent-Widgets#754]
### What happened?

![e3e4a833d4923b93535818636f231a4a](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/92281663/05b289e6-f2fb-43cf-9675-2d80bcecedd9)

### Operation System

Win11

### Python Version

python310

### PyQt/PySide Version

Pyside6

### PyQt/PySide-Fluent-Widgets Version

pro

### How to Reproduce?

![e3e4a833d4923b93535818636f231a4a](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/92281663/1d427339-1948-46b0-9eb9-62ad7f45d881)
只能改变初始normal的颜色，当触发hover状态时就会变回默认颜色

### Minimum code

```python3
card = CardWidget(run)
card.setBackgroundColor(QColor("#212121"))
```

**Comment by zhiyiYo** [comment]
换成子类并重写那几个方法，用 lambda 看起来有点奇怪

**Comment by Lin-Yuhao** [comment]
因为只用一次，继承子类代码量就多了

**Comment by zhiyiYo** [comment]
没看出代码有什么问题

**Comment by Lin-Yuhao** [comment]
card修改颜色后，初始颜色正常显示，但是鼠标放上去，颜色就会变成默认的黑白色。
修改颜色方法正常来说应该始终改变颜色，不管有没有触发hover鼠标悬停事件。

**Comment by zhiyiYo** [comment]
最小能运行的代码发一份？

**Comment by Lin-Yuhao** [comment]
`card = CardWidget(run)
card.setBackgroundColor(QColor("＃DC143C"))`

运行这个代码就能测试，鼠标放在card上，颜色就会变成默认颜色

**Comment by zhiyiYo** [comment]
感觉这个逻辑没什么问题？因为 card widget 监听了 hover 和 press，一旦 hover 之后就会变成 `_hoverBackgroundColor()` 返回的颜色
