### ISSUE TITLE
incorrect spelling in stylesheet

### ISSUE THREAD

**Issue by immiProgrammer** [zhiyiYo/PyQt-Fluent-Widgets#755]
[in these lines](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/blob/c76da1dd8968b87803daa5575e6f889394595ad6/qfluentwidgets/_rc/qss/dark/button.qss#L276C1-L276C21)

**Comment by immiProgrammer** [comment]
> Thank you, I will fix this bug in next version, or you can contribute a PR

Help me to contribute PR
rebuild resource.py?
change on master branch? (Or other)

**Comment by zhiyiYo** [comment]
You should fork this repo first. Then modify the qss on your master branch. After pushing your commit to github, you can open your repo and create a PR. 

**Don't need to rebuild resource.py. I will do it later.**

**Comment by immiProgrammer** [comment]
i fix it https://github.com/zhiyiYo/PyQt-Fluent-Widgets/pull/760
