### ISSUE TITLE
使用pyinstaller将代码打包成.exe 文件时，会存在很多模块导入失败的情况[Bug]: 

### ISSUE THREAD

**Issue by OceanYoungY** [zhiyiYo/PyQt-Fluent-Widgets#767]
### What happened?

使用pyinstaller将代码打包成.exe 文件时，会存在很多模块导入失败的情况
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/42138417/32b75c87-8da8-43a2-87e6-33ff8a46170f)

### Operation System

Windows11

### Python Version

3.11.4

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

PyQt-Fluent-Widgets  1.2.7

### How to Reproduce?

使用pyinstaller将代码打包成.exe 文件。并执行其  .exe 文件

### Minimum code

```python3
无
```

**Comment by rainzee** [comment]
打包流程是什么

**Comment by OceanYoungY** [comment]
直接对启动文件进行的打包，打包后执行 .exe 文件，报错显示 fluent的很多控件导入失败

**Comment by AlexZhu2001** [comment]
在相同版本上无法复现，请给出你的打包指令或者spec文件
