### ISSUE TITLE
[feature request] 希望作者大大能够添加一个多apikey输入框

### ISSUE THREAD

**Issue by NEKOparapa** [zhiyiYo/PyQt-Fluent-Widgets#776]
之前在自己的程序中，都是用富文本框来输入多key，但还是希望能够有个组件能够方便美观的输入和管理多key，比如点击添加按钮，就可以生成一行空文本输入框挂在组件下边，输入框右边自带删除按钮。然后点击组件还可以向上缩进到组件里

**Comment by NEKOparapa** [comment]
像现在的日历选择器这样差不多

**Comment by NEKOparapa** [comment]
如果能够开发，我会考虑付费使用prp版本

**Comment by zhiyiYo** [comment]
参考 FolderListSettingCard 就行了
