### ISSUE TITLE
[Bug]: 当屏幕分辨率发生改变时，窗口有时不能按照设定的大小启动

### ISSUE THREAD

**Issue by Kiramei** [zhiyiYo/PyQt-Fluent-Widgets#783]
### What happened?

这是窗口的正常大小：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54705837/e8053a70-d92d-4345-8322-a5c3b077e6be)

### Operation System

Windows 23H2

### Python Version

3.9.18 64-bit

### PyQt/PySide Version

5.15.7

### PyQt/PySide-Fluent-Widgets Version

1.2.0

### How to Reproduce?

然而在切换屏幕后大小却变为：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54705837/a960d7f8-1e0d-42cd-a4fd-118a1f47c23b)
再切换屏幕的时候大小变为：
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/54705837/f5cb2049-de99-425b-86b9-ab6480ca714c)
有时在启动的时候，也无法完成正常大小启动。

### Minimum code

```python3
class Window(MSFluentWindow):

    def __init__(self):
        super().__init__()
        self.initWindow()
        # ...

    def initWindow(self):
        self.resize(900, 700)
        desktop = QApplication.desktop().availableGeometry()
        _w, _h = desktop.width(), desktop.height()
        self.move(_w // 2 - self.width() // 2, _h // 2 - self.height() // 2)

    # ...

if __name__ == '__main__':
    QApplication.setHighDpiScaleFactorRoundingPolicy(Qt.HighDpiScaleFactorRoundingPolicy.PassThrough)
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)

    app = QApplication(sys.argv)
    w = Window()
    # 聚焦窗口
    w.setFocus(True)
    w.show()
    app.exec_()
```

**Comment by AlexZhu2001** [comment]
请问两块屏幕是同样的分辨率吗，如果不是，感觉这个行为应该就是正常的行为吧，毕竟Windows的原生窗口貌似也是这个逻辑

**Comment by zhiyiYo** [comment]
估计你屏幕缩放比不一样
