### ISSUE TITLE
请问如何改变按钮按下的颜色

### ISSUE THREAD

**Issue by LoveUSimone** [zhiyiYo/PyQt-Fluent-Widgets#785]
` self.pushButton1 = PushButton('Standard push button')
        self.pushButton1.setStyleSheet(
                             "QPushButton::clicked"
                             "{"
                             "background-color : red;"
                             "}"
                             )`
这样写不奏效
我想要在PushButton点击或按下时显示一个比较明显的颜色

**Comment by keymou** [comment]
> ` self.pushButton1 = PushButton('Standard push button') self.pushButton1.setStyleSheet( "QPushButton::clicked" "{" "background-color : red;" "}" )` 这样写不奏效 我想要在PushButton点击或按下时显示一个比较明显的颜色


已经提供使用`setCustomStyleSheet` 函数来自定义按钮样式表
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/35944974/c156d7e6-b360-4aed-b711-3a8feb2ae7df)

```python
def setCustomStyleSheet(widget: QWidget, lightQss: str, darkQss: str):
    """ set custom style sheet

    Parameters
    ----------
    widget: QWidget
        the widget to add style sheet

    lightQss: str
        style sheet used in light theme mode

    darkQss: str
        style sheet used in light theme mode
    """
    CustomStyleSheet(widget).setCustomStyleSheet(lightQss, darkQss)
```

```qss
PushButton:pressed, ToolButton:pressed, ToggleButton:pressed, ToggleToolButton:pressed {
    color: rgba(0, 0, 0, 0.63);
    background: rgba(249, 249, 249, 0.3);
    border-bottom: 1px solid rgba(0, 0, 0, 0.073);
}
```


</body>
</html>

更多样式表可参考：https://doc.qt.io/qt-5/stylesheet-reference.html#border-width-prop

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/35944974/365992eb-31a9-4de8-8fb6-7414ea70923e)
