### ISSUE TITLE
[Bug]: Pro组件中的CodeEdit组件在Mac下代码行号未显示完整，且光标定位后，选中行位置不对

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#789]
### What happened?

CodeEdit组件加载代码显示后，在Mac下代码行数未显示完整
且光标定位后，选中行样式未显示在光标所在行，位置不对，另外选中行和代码未水平居中对齐显示

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.5.2

### How to Reproduce?

安装了consoals字体后，代码行数基本显示正确，当仍有光标定位后选中行不对的问题
![6273e26854d89466e5058b0204eaf33b](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/b2fd752f-ae88-46b7-875a-daac0ef83d54)
![2bf40307a6e62552820c5b9dc4af8226](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/f858f4fd-32da-43c4-986b-880e7c2325fc)

### Minimum code

```python3
demo文件
```

**Comment by zhiyiYo** [comment]
可能还得搞个宋体
