### ISSUE TITLE
[Bug]: There is already a class named "PushButton" when using Qt Designer

### ISSUE THREAD

**Issue by leakedby** [zhiyiYo/PyQt-Fluent-Widgets#793]
### What happened?

When trying to convert pyqt .ui file to QFluentWidgets with Fluent Designer, I got this error message.
Can anyone else known how to fix this?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4213260/3aff08d3-4fd3-421f-802f-82799ab6d4f3)

### Operation System

Windows 10

### Python Version

3.11

### PyQt/PySide Version

5.15.10

### PyQt/PySide-Fluent-Widgets Version

1.5.2

### How to Reproduce?

...

### Minimum code

```python3
...
```

**Comment by AlexZhu2001** [comment]
You can just using QtDesigner without FluentWidget plugin to do that. Just use pyqt5-tools designer to launch it.
