### ISSUE TITLE
[Bug]: scroll区域暗黑模式背景显示异常

### ISSUE THREAD

**Issue by infinitebook** [zhiyiYo/PyQt-Fluent-Widgets#796]
### What happened?

我纯萌新，刚刚接触这个，把gallery里的setting页面粘到ms fluent Windows的一个sub interface里面，发现换主题的功能好用，但是scroll的区域背景是白色的，显示不正常，不知道该怎么改才能让他正常，light主题显示都正常

### Operation System

windows 11 23h2

### Python Version

3.11

### PyQt/PySide Version

pyside 6.4.2

### PyQt/PySide-Fluent-Widgets Version

v1.5.0

### How to Reproduce?

light主题下显示正常
<img width="759" alt="{ECB95BCF-1FA3-4868-9294-D0F0E870AA41}" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/20833671/84d426fb-b4a1-417d-94ef-fa94efeeb2fe">
dark主题下scroll区域不正常
<img width="745" alt="{0C148574-BE29-4948-9600-79D989158B43}" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/20833671/8d05ce8e-8ecd-44c1-9391-b719304accba">
其他区域正常
<img width="760" alt="{B71B9496-F10C-4109-BCF5-DE9D5786060D}" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/20833671/9da5a0e7-7923-4167-a936-6b929ffdfdcf">

### Minimum code

```python3
就替换了个这个，然后把import改了一下，别的没动
self.setting = SettingInterface(self)
```

**Comment by zhiyiYo** [comment]
看文档
