### ISSUE TITLE
[Bug]: Pro组件中的DropMultiFilesWidget组件拖放本地文件时无法拖曳设置的后缀名是大写的文件

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#798]
### What happened?
问题1：
self.dropMultiFileWidget.setSuffixes(["jpg", "png", "gif"])
当设置指定格式的文件时
如果拖曳本地文件后缀名为大写的，例如“1.PNG”格式的文件，无法拖曳，即使设置的self.dropMultiFileWidget.setSuffixes(["jpg", "PNG", "gif"])，拖放PNG格式后缀的文件也无法拖曳
`DropSingleFileWidget`正常

问题2：
若DropMultiFilesWidget不设置格式限制，允许选择所有文件或文件夹的话，无法从本地拖曳任何格式的文件
### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.5.2

### How to Reproduce?

QtPy以及Pyside6版本都有该问题

### Minimum code

```python3
demo文件
```

**Comment by zhiyiYo** [comment]
已修复此问题
