### ISSUE TITLE
demo运行失败

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#8]
win11 python3.8.5 32位

为什么我安装后全部demo都无法运行呢，基本都是下图错误

![QQ截图20230130205810](https://user-images.githubusercontent.com/104692238/215486299-b9ef4118-fc6c-48ce-800f-9952343443ef.png)

**Comment by zhiyiYo** [comment]
这个还是scipy的导入问题，安装的是full版本吗？不然 lite 版本应该不会用到scipy的

**Comment by zhiyiYo** [comment]
建议搭个虚拟环境测试一下，应该不会有问题的

**Comment by Ephemeralwanning** [comment]
> 这个还是scipy的导入问题，安装的是full版本吗？不然 lite 版本应该不会用到scipy的

这样吗 我以为我scipy安装成功后就能直接用full版本了呢

我刚刚重新用了lite版部分demo就能运行成功了 

但是好像所有带resource文件夹的demo都无法运行

**Comment by zhiyiYo** [comment]
可能是你的运行路径有问题，你有切换到 demo.py 所在目录运行吗？

**Comment by Ephemeralwanning** [comment]
> 可能是你的运行路径有问题，你有切换到 demo.py 所在目录运行吗？

我是vscode打开目录 点击d emo 直接运行

**Comment by zhiyiYo** [comment]
如果你是用的 python 插件提供的运行按钮，他不会切换到 demo.py 所在目录的，建议安装一个 code runner 插件，然后按住 ctrl+alt+n 运行 demo.py

**Comment by Ephemeralwanning** [comment]
> 如果你是用的 python 插件提供的运行按钮，他不会切换到 demo.py 所在目录的，建议安装一个 code runner 插件，然后按住 ctrl+alt+n 运行 demo.py

试了一下 好像resource里带qss的都无法运行

![QQ截图20230130215141](https://user-images.githubusercontent.com/104692238/215495712-b036710e-2c57-4fde-94d6-7d044cb69a00.png)

**Comment by Ephemeralwanning** [comment]
> 请在 `.vscode/settings.json` 中填入下述配置：
> 
> ```json
> {
>     "code-runner.executorMap": {
>         "python": "cd $dir && python $fileName",
>     }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/65096819/215496331-267b97b9-db11-476b-bf90-1732a1947430.png) 我图片里面用的是虚拟环境 PyQt-Fluent-Widgets 的 python.exe 路径，你可以换成你自己的 python.exe 路径

哇 可以运行了非常感谢您的解答

**Comment by zhiyiYo** [comment]
有其他问题欢迎提新 issue 🙂
