### ISSUE TITLE
[Bug]: DoubleSpinBox设置setReadOnly后按钮仍能操作

### ISSUE THREAD

**Issue by ShionCox** [zhiyiYo/PyQt-Fluent-Widgets#802]
### What happened?

修复

### Operation System

WINDOWS11

### Python Version

3.12 64位

### PyQt/PySide Version

PySide6

### PyQt/PySide-Fluent-Widgets Version

1.5.3

### How to Reproduce?

 DoubleSpinBox设置setReadOnly后虽然不能输入了，但是按钮还是能操作

### Minimum code

```python3
DoubleSpinBox.setReadOnly(True)
```

**Comment by zhiyiYo** [comment]
已修复此问题
