### ISSUE TITLE
[Bug]: 在FlowLayout放置ElevatedCardWidget错误

### ISSUE THREAD

**Issue by pkanyone** [zhiyiYo/PyQt-Fluent-Widgets#815]
### What happened?

在FlowLayout中启用needAni参数，布局ElevatedCardWidget，在初次进入窗体，未完成最终布局时，鼠标划过ElevatedCardWidget，会导致动画停止，ElevatedCardWidget停留在鼠标位置，无法完成最终布局。
正常情况下：
![1](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/163859577/1fb9bb54-bfee-4539-8b65-3af7e7e1a6a9)
错误情况下：
![2](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/163859577/b9e2a415-ab16-4c7c-a99a-946a0be8886c)

### Operation System

Windows11

### Python Version

3.12.2

### PyQt/PySide Version

pyside6.6.2

### PyQt/PySide-Fluent-Widgets Version

1.5.3

### How to Reproduce?

在FlowLayout中启用needAni参数，布局ElevatedCardWidget，在初次进入窗体，未完成最终布局时，鼠标划过ElevatedCardWidget，会导致动画停止，ElevatedCardWidget停留在鼠标位置，无法完成最终布局

### Minimum code

```python3
class Custom_ElevatedCard(ElevatedCardWidget):
    def __init__(self,parent=None):
        super().__init__(parent)
        self.setFixedSize(400,400)
class MyWidget(QWidget):
    def __init__(self,parent=None):
        super().__init__(parent)
        self.setObjectName('MyWidget')
        fly=FlowLayout(needAni=True)
        for i in range(6):
            fly.addWidget(Custom_ElevatedCard())
        self.setLayout(fly)
class Test(FluentWindow):
    def __init__(self,parent=None):
        super().__init__(parent)
        setTheme(Theme.DARK)
        self.setWindowState(Qt.WindowState.WindowFullScreen)
        self.setMicaEffectEnabled(False)
        wid=QWidget()
        wid.setObjectName('t')
        self.addSubInterface(wid,FluentIcon.SHARE,'TEST')
        self.addSubInterface(MyWidget(),FluentIcon.DELETE,'Test1')
if __name__=='__main__':
    app=QApplication([])
    w=Test()
    w.show()
    app.exec()
```

**Comment by zhiyiYo** [comment]
ElevatedCardWidget 开了位置动画，不能和带动画的 FlowLayout 一起用，否则会起冲突
