### ISSUE TITLE
StackedWidget popup animation issue

### ISSUE THREAD

**Issue by XenomVenom** [zhiyiYo/PyQt-Fluent-Widgets#824]
### What happened?

This issue started after the "lazy" stylesheet update. If you switch themes during runtime, the popup animation for StackedWidget becomes very laggy and ugly to look at.

### Operation System

Windows 10

### Python Version

3.9

### PyQt/PySide Version

5.15.2

### PyQt/PySide-Fluent-Widgets Version

v1.3.1

### How to Reproduce?

Switch themes during runtime causes popup animation to become very laggy. If theme is not switched during runtime, popup animation plays smoothly and without issue.

https://i.imgur.com/0KcpQjY.mp4

### Minimum code

```python3
Default code / no changes
```

**Comment by rainzee** [comment]
Works fine on my environment
