### ISSUE TITLE
请问如何自定义侧边导航栏的字体颜色呢？

### ISSUE THREAD

**Issue by xielinzhen** [zhiyiYo/PyQt-Fluent-Widgets#826]
请问如何自定义侧边导航栏的字体颜色呢？

**Comment by AlexZhu2001** [comment]
暂时无法做到这一点，侧边栏的文字是QPainter绘制上去的，没有提供可以修改的变量。

**Comment by xielinzhen** [comment]
> 暂时无法做到这一点，侧边栏的文字是QPainter绘制上去的，没有提供可以修改的变量。

谢谢
