### ISSUE TITLE
Calendar widget is very slow to show and hide, can you improve it

### ISSUE THREAD

**Issue by Khanhlinhdang** [zhiyiYo/PyQt-Fluent-Widgets#840]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78089189/25b68eaa-79e2-48b9-969a-4e04b31ae174)

**Comment by Khanhlinhdang** [comment]
Thank you bro!

**Comment by Khanhlinhdang** [comment]
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/78089189/556e8265-696c-492e-8517-70a7ee46d0cc)
i use this stylesheet for darktheme, it is very fast
you can setup it like a custom components, 

QWidget {
    background-color: #2b2b2b;
	color:#eaeaea;
	border: solid;
	border-width: 0.5px;
	border-color: transparent;
    border-radius: 5px;

}

QCalendarWidget QToolButton
{
	height:40px;
	width:50px;
	color:white;
	font:18px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	icon-size:25px 25px;
	background-color:#2b2b2b;
}
QCalendarWidget QToolButton:hover
{
	background-color:#202020;
}

QCalendarWidget QWidget#qt_calendar_navigationbar
{
	height:40px;
	background-color:#2b2b2b;

}

#qt_calendar_monthbutton
{
	width:100px;
	font:18px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	color:white;
	background-color:#2b2b2b;
	margin: 0px 2px;
	padding: 0px 2px

}

#qt_calendar_yearbutton
{
	font:18px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	color:white;
	background-color:#2b2b2b;
	margin: 0px 2px;
	padding: 0px 2px

}

#qt_calendar_monthbutton:hover,
#qt_calendar_yearbutton:hover
{
	background-color:#202020;
}

/* MenuBar Code */

QCalendarWidget QMenu
{
	width:150px;
	color:white;
	font:14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	background-color:#2b2b2b;
}

/* SpinBox Code */



/* Calendar View Code */
QCalendarWidget QWidget
{
	alternate-background-color:#2b2b2b;
}


QCalendarWidget QAbstractItemView:enabled
{
	font:14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	color:white;
	background-color:#2b2b2b;
	selection-background-color:#202020;
	selection-color:white;
}
QCalendarWidget QAbstractItemView:disabled
{
	color:rgb(100,100,100);
}

QCalendarWidget QSpinBox
{
	width:60px;
	height:25px;
	font:14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	color:white;
	background-color:#2b2b2b;
}

#qt_calendar_calendarview
{
	font:14px 'Segoe UI', 'Microsoft YaHei', 'PingFang SC';
	color:white;
	background-color:#202020;
	border: solid;
	border-width: 0.5px;
	border-color: #2b2b2b;
    border-radius:5px;
}


#qt_calendar_calendarview::item
{
	width:25px;
	height:25px;
	background-color:#2b2b2b;
	border: solid;
	border-width: 1px;
	border-color: #2b2b2b;
    border-radius:15px;
	padding: 2px 2px 2px 2px
}


#qt_calendar_calendarview::item:hover
{
	width:25px;
	height:25px;
	background-color:black;
	border: solid;
	border-width: 1px;
	border-color: black;
    border-radius:15px;
	padding: 2px 2px 2px 2px
}

#qt_calendar_calendarview::item:selected
{
	width:25px;
	height:25px;
	background-color:black;
	border: solid;
	border-width: 1px;
	border-color: black;
    border-radius:15px;
	padding: 2px 2px 2px 2px
}

**Comment by zhiyiYo** [comment]
#983
