### ISSUE TITLE
[Bug]: TransparentDropDownPushButton二级菜单显示位置错误

### ISSUE THREAD

**Issue by onobug** [zhiyiYo/PyQt-Fluent-Widgets#844]
### What happened?

二级菜单显示每次增加20px位置偏差

### Operation System

windows

### Python Version

py3.11

### PyQt/PySide Version

pyside

### PyQt/PySide-Fluent-Widgets Version

1.5.1

### How to Reproduce?

多次点击按钮，调用二级菜单

### Minimum code

```python3
def createDropDownButton(self):
        button = TransparentDropDownPushButton('Menu', self, FluentIcon.MENU)
        button.setFixedHeight(34)
        setFont(button, 12)
        menu1 = RoundMenu(parent=self)
        menu1.addActions([
            Action(FluentIcon.COPY, 'Cosdfdfdpy'),
            Action(FluentIcon.CUT, 'Cutsdfsdfsfdfd'),
            Action(FluentIcon.PASTE, 'Paste'),
            Action(FluentIcon.CANCEL, 'Cancel'),
            Action('Select all'),
        ])
        menu = RoundMenu(parent=self)
        menu.addActions([
            Action(FluentIcon.COPY, 'Cosdfdfdpy'),
            Action(FluentIcon.CUT, 'Cutsdfsdfsfdfd'),
            Action(FluentIcon.PASTE, 'Paste'),
            Action(FluentIcon.CANCEL, 'Cancel'),
            Action('Select all'),
        ])
        menu.addMenu(menu1)

        button.setMenu(menu)
        return button
```

**Comment by onobug** [comment]
![微信图片_20240416215635](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/37992331/16161393-1796-48e4-99db-d2a7c889ad2b)

**Comment by AlexZhu2001** [comment]
同 #792

**Comment by AlexZhu2001** [comment]
已修复，可以关闭问题了

**Comment by zhiyiYo** [comment]
`self.viewport().adjustSize()` 好像没什么用，注释掉也不会影响目前代码的运行效果

![image](https://github.com/user-attachments/assets/c9cd589c-75b1-4f5d-ab40-f3f46f661f4a)

**Comment by zhiyiYo** [comment]
最新的 [commit](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/commit/91d2e0a9fd801b3a17344f6f39df6e7c1134069f) 已修复此问题，在菜单例子和 gallery 测试都没啥问题
