### ISSUE TITLE
[Bug]: Incorrect theme change

### ISSUE THREAD

**Issue by brandonzorn** [zhiyiYo/PyQt-Fluent-Widgets#847]
### What happened?

incorrect theme change

https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/68778953/bdc8728d-46ab-4029-af07-198954acb9a5

### Operation System

Windows11 23H2

### Python Version

3.12.3 x64

### PyQt/PySide Version

PySide6 6.6.3.1

### PyQt/PySide-Fluent-Widgets Version

1.5.5

### How to Reproduce?

Run the code below and change the theme in Windows settings from dark to light

### Minimum code

```python3
import sys
from PySide6.QtWidgets import QApplication
from qfluentwidgets import FluentWindow, setTheme, Theme

setTheme(Theme.DARK)
app = QApplication(sys.argv)
window = FluentWindow()
window.show()
sys.exit(app.exec())
```

**Comment by AmirMahdaviAM** [comment]
Suggest you to use gallery app as template and build your app on it, otherwise you must set custome stylesheet to prevent from this inconsistency
