### ISSUE TITLE
pyside6更新到6.7.0后，阴影效果出现问题

### ISSUE THREAD

**Issue by Cheukfung** [zhiyiYo/PyQt-Fluent-Widgets#848]
如果用pyside6 6.7.0版本，下拉菜单的阴影会变得很奇怪，不清楚是什么原因，降级到6.6.3就正常了。

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/14865236/ea8aaa51-feeb-48f7-878b-41647229b2d5)

**Comment by rainzee** [comment]
6.7.1 应该修复了这个问题，在我的测试环境中看起来一切正常了。

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/4585440/f651f762-1fbe-4371-bef1-35e62c19496d)

**Comment by zhiyiYo** [comment]
Windows 11 下仍然有问题
![image](https://github.com/user-attachments/assets/230423cf-76c6-4443-8f86-b3901425163d)

**Comment by zhiyiYo** [comment]
目前最简单的解决方案就是在 win11 下修改 app 的默认样式方案：
```python
app = QApplication(sys.argv)
app.setStyle("fusion")
```

**Comment by zhiyiYo** [comment]
v1.6.2 已修复此问题
