### ISSUE TITLE
动画冲突问题

### ISSUE THREAD

**Issue by TaoChenyue** [zhiyiYo/PyQt-Fluent-Widgets#85]
**Describe the bug**

**Environment**
- OS: [e.g. Windows11]
- DPI scaling: [e.g. 125%]
- Python: [e.g. 3.8.16 64-bit]
- PySide6: [e.g. 6.4.2]
- PyQt-Fluent-Widgets: [e.g 0.6.2]

**To Reproduce**
Steps to reproduce the behavior(you can use gif to demonstrate the problem):
1. demo
2. 在有动画的地方，前一个动画未结束(State.Running)，后一个动画就开始了(其实start失败了)。

**Expected behavior**
增加动画判断逻辑，如果上一个动画还在继续，停掉，然后启动下一个。

**Screenshots**
![flow layout](https://user-images.githubusercontent.com/40346985/230084614-64ee744a-5eb8-4b26-8ebc-c35fbdb4c76b.png)
![navigation](https://user-images.githubusercontent.com/40346985/230084397-ca97635e-49e3-4965-b295-ae0ae8b02031.png)

**Comment by zhiyiYo** [comment]
奇怪，代码里面不是有停止动画吗：
```python
self._anis[i].stop()
```

**Comment by TaoChenyue** [comment]
滑动快了或者点快了都有这个问题，我改的是
```python
if self.needAni:
            self._aniGroup.start()
```

**Comment by TaoChenyue** [comment]
```python
if move:
    if not self.needAni:
        item.setGeometry(QRect(QPoint(x, y), item.sizeHint()))
    else:
        self._anis[i].stop()
        self._anis[i].setEndValue(QRect(QPoint(x, y), item.sizeHint()))
```
这个move条件好像是手动给的，会不会出问题。

**Comment by zhiyiYo** [comment]
不会吧，这能出啥问题🤔

**Comment by TaoChenyue** [comment]
我没理解move的作用。这句话是修改某个时刻的内部控件位置或动画终点位置。既然有needAni作为动画的判断条件了，为什么又加了move条件。

**Comment by zhiyiYo** [comment]
`heightForWidth()` 函数也要用这个函数来计算高度

**Comment by TaoChenyue** [comment]
也许计算应该分开，把计算结果用一个位置列表存起来？

**Comment by TaoChenyue** [comment]
HeightForWidth 应该是一个确切的值，但是有动画的话，这么写就是发动时停技能，取当前时刻的高度了。动画在不同时刻返回的结果也不一样🤔。

**Comment by TaoChenyue** [comment]
第二张图里面，导航栏上快速点两个标签，第二个标签对应的页面也没显示，应该是被动画卡住了。跟这个流式布局的bug机理应该一样。

**Comment by zhiyiYo** [comment]
这个不会出问题的把，因为传给 `_doLayout` 的宽度决定了动画的终值

**Comment by TaoChenyue** [comment]
> 这个不会出问题的把，因为传给 `_doLayout` 的宽度决定了动画的终值

程序跑得比动画快，所以动画没结束值就已经返回了，动画是另一个线程(也许进程)的事情。

**Comment by zhiyiYo** [comment]
> 第二张图里面，导航栏上快速点两个标签，第二个标签对应的页面也没显示，应该是被动画卡住了。跟这个流式布局的bug机理应该一样。

原因是切换标签页的时候会判断动画是否在运行：
```python
if self._ani and self._ani.state() == QAbstractAnimation.Running:
      return
```

**Comment by TaoChenyue** [comment]
如果在运行，应该关掉启动新的吧，这直接return了。

**Comment by TaoChenyue** [comment]
大佬有没有QQ群之类的，github交流不便，邮箱提醒也有延迟😓。

**Comment by zhiyiYo** [comment]
没有qq群，qq群太吵了
