### ISSUE TITLE
希望作者大佬在QConfig中支持普通字符串

### ISSUE THREAD

**Issue by mstouk57g** [zhiyiYo/PyQt-Fluent-Widgets#861]
希望作者大佬在QConfig中支持普通字符串
当前使用的1.5.5版本中，似乎没有任何配置项支持普通的字符串
在ConfigItem中使用普通字符串会报错（当然我知道它要求是布尔值，只是举个例子）
![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/65524880/72a58a14-8748-4bc6-8636-f669786b3c23)
在设置中可能会遇到要设置普通字符串的情况（比如名字等等）
十分感谢大佬

**Comment by zhiyiYo** [comment]
你需要自定义一个设置卡片
