### ISSUE TITLE
ComboBox的setPlaceholderText失效

### ISSUE THREAD

**Issue by youjunxiaji** [zhiyiYo/PyQt-Fluent-Widgets#87]
作者你好，我想问一下你的`ComboBox`好像没有`setPlaceholderText`方法，我尝试使用这种方式重写，但是不起作用，界面直接不出来了，但是也没有报错
```python
class MyComboBox(ComboBox, QComboBox):

    def setPlaceholderText(self, placeholderText):
        QComboBox.setPlaceholderText(self,placeholderText)
        pass
```
然后我去看源码，发现你的`ComboBox`继承的是`QpushButton`
![image](https://user-images.githubusercontent.com/94896689/230109422-140371b8-827e-48ef-b764-e0b966579eb5.png)

**Comment by zhiyiYo** [comment]
`ComboxBox` 继承是 `QPushButton` 的子类，所以少了很多 `QComboBox`

**Comment by youjunxiaji** [comment]
是的，所以这个方法注定是会消失吗，我把界面继承了你做的大部分自定义部件，但是对qside6 qlabel控件本身的外观实在是没法形容的另类

**Comment by youjunxiaji** [comment]
> `ComboxBox` 继承是 `QPushButton` 的子类，所以少了很多 `QComboBox`

我只是想给ComboBox加一个标题，博主你还有其他的建议方式吗

**Comment by zhiyiYo** [comment]
我下次加上这个函数吧

**Comment by youjunxiaji** [comment]
> 我下次加上这个函数吧

博主最近考虑做这样风格的 qlabel和tableView控件吗

**Comment by zhiyiYo** [comment]
QLabel 没有什么风格吧🤔

**Comment by zhiyiYo** [comment]
不过这里倒是有一个表显示了各种标签
![image](https://user-images.githubusercontent.com/65096819/230113331-350cc1d1-24f6-45d3-ba6d-18c2ff4f706d.png)

**Comment by zhiyiYo** [comment]
打开 PS，对着 WinUI 3 组件就是一段测量，然后开始敲代码

**Comment by youjunxiaji** [comment]
> 打开 PS，对着 WinUI 3 组件就是一顿测量，然后开始敲代码
感谢  听起来还要从ps开始学起。那意思是首先自己要开始制作qss吗

**Comment by youjunxiaji** [comment]
> WinUI3 好像有设计稿，具体可以问问另一个维护者 @Cheukfung

感谢，我先用你们制作好的现成的吧   很好看

**Comment by Cheukfung** [comment]
@youjunxiaji winUI3官方设计稿 https://www.figma.com/community/file/1159947337437047524

**Comment by youjunxiaji** [comment]
> @youjunxiaji winUI3官方设计稿 https://www.figma.com/community/file/1159947337437047524

好的感谢  不好意思 昨天早早的就下线了

**Comment by youjunxiaji** [comment]
> 我下次加上这个函数吧

麻烦博主做好了踢我一下^_^

**Comment by zhiyiYo** [comment]
已添加该方法
