### ISSUE TITLE
[Bug]: Pro组件中的GuideWindow在Mac下显示了Mac自带的最小化最大化和关闭按钮，且下一步和启动按钮的文案未翻译

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#877]
### What happened?

Pro组件中的GuideWindow在Mac下显示了Mac自带的最小化最大化和关闭按钮，且下一步和启动按钮的文案未翻译
<img width="648" alt="115截图20240513081639" src="https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/8281775/613c1763-f092-433d-99c8-00806390ba20">

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt 5.15.9

### PyQt/PySide-Fluent-Widgets Version

v1.5.6

### How to Reproduce?

Mac下隐藏自带的最小化最大化和关闭按钮，下一步、上一步、启动按钮文案在中文下显示正确的翻译文案

### Minimum code

```python3
demo文件
```

**Comment by zhiyiYo** [comment]
已修复此问题
