### ISSUE TITLE
 安装事件过滤器后无法获取鼠标滚轮事件

### ISSUE THREAD

**Issue by Lyn0222** [zhiyiYo/PyQt-Fluent-Widgets#889]
我的主界面为一个SingleDirectionScrollArea，我在其中插入了一系列Qwidget控件，控件中含有TextEdit。我希望在滚动鼠标滚轮时，触发主界面的滚动。但是当我在TextEdit范围内添加事件过滤器，试图获取滚轮事件并传递给父控件时，无法触发主界面的滚动。当我直接继承QTextEdit的时候，该事件过滤器没有问题。同时，在Qwidget（ExpandingTextEdit范围外）滚动的时候，主界面的滚动也没有问题
我的界面：
![1716866219715](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/138124774/973d4bdb-ee3c-4459-bc44-a6267ecb5703)
在TextEdit类型（包括其他的很多控件）中，有内部定义的self.scrollDelegate = SmoothScrollDelegate(self)，可能是这个滚动设置阻碍了信号的传递，导致信号无法被事件过滤器获取。是否可以添加一个选项，让控件内部的滚动变成可选择的，而不是强制的？这样或许可以解决问题

**Comment by zhiyiYo** [comment]
下个版本可以加上

**Comment by Lyn0222** [comment]
好的，期待住了，感谢大佬！
