### ISSUE TITLE
[Bug]: 主窗口没有阴影

### ISSUE THREAD

**Issue by shiyueGG** [zhiyiYo/PyQt-Fluent-Widgets#897]
### What happened?

在官方的demo是有阴影的，我创建之后没有。是需要自己加吗？

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/58288932/ead208a4-2061-4878-b827-c242f38ce383)

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/58288932/9dc14984-336e-457e-920f-6a32e0d4aee7)

### Operation System

Win11

### Python Version

3.10.8

### PyQt/PySide Version

pyside6 6.7.1

### PyQt/PySide-Fluent-Widgets Version

pyside6 6.7.1

### How to Reproduce?

无

### Minimum code

```python3
无
```

**Comment by shiyueGG** [comment]
原因是初始化了下面这段代码 这是什么原因
`class webWidget(QFrame):
    def __init__(self, parent=None):
        super().__init__(parent=parent)

        # 1. 将 QWebEngineView 替换成 FramelessWebEngineView
        self.webView = FramelessWebEngineView(self)
        self.webView.load(QUrl("https://www.baidu.com/"))

        self.vBoxLayout = QVBoxLayout(self)
        self.vBoxLayout.setContentsMargins(20, 20, 20, 20)
        self.vBoxLayout.addWidget(self.webView)
        self.setObjectName("homeInterface--web")`

**Comment by zhiyiYo** [comment]
官网文档写了
