### ISSUE TITLE
使用state_tool_tip 部分错位

### ISSUE THREAD

**Issue by Ephemeralwanning** [zhiyiYo/PyQt-Fluent-Widgets#9]
win11 python3.8.5 32位

demo截图
![QQ截图20230207193605](https://user-images.githubusercontent.com/104692238/217234972-c68ecb2c-4742-4b1a-9d27-8af20f34d897.png)

我使用时的截图
![QQ截图20230207193521](https://user-images.githubusercontent.com/104692238/217234983-6a23aa31-f8e7-4e94-91ad-21118d5f23d5.png)

感觉明显‘x’和demo的不同，变得非常难看

**Comment by zhiyiYo** [comment]
可以贴一下pyqt-fluent-widgets包版本和复现你的问题的最小代码吗

**Comment by Ephemeralwanning** [comment]
> 可以贴一下pyqt-fluent-widgets包版本和复现你的问题的最小代码吗

我尝试写了一段简单的代码，发现并不能复现上述问题

我觉得应该是我使用了别人的皮肤主题，取消主题代码后发现state_tool_tip可以正常显示

问题已解决，感谢大大的回复

![QQ截图20230207202801](https://user-images.githubusercontent.com/104692238/217244841-75066c04-f21a-4653-8276-c708bc6deefc.png)
