### ISSUE TITLE
[Bug]: missing font family "Segoe UI" on macos

### ISSUE THREAD

**Issue by JunjieZhaoFelix** [zhiyiYo/PyQt-Fluent-Widgets#900]
### What happened?

windows下没问题，但是在macos下，运行软件，一直会报字体错误，qt.qpa.fonts: Populating font family aliases took 366 ms. Replace uses of missing font family "Segoe UI" with one that exists to avoid this cost. 
查了一下，这些字体在windows下是没问题的，但是macos没有这些字体，就会导致加载这些字体失败，build出来的app，点击app就打不开，只能打开binary的app

### Operation System

macOS Ventura 13.6.4 

### Python Version

3.11

### PyQt/PySide Version

Pyqt5 5.15.10

### PyQt/PySide-Fluent-Widgets Version

1.5.7

### How to Reproduce?

pycharm运行这些demo都会报这个警告

### Minimum code

```python3
参考demo
```

**Comment by kaka1909** [comment]
是的，我这边也能复现。我看了之前的issue，虽然在qss里都在 font_family 加了 Pingfang 啥的，但还是报错，挺奇怪。
