### ISSUE TITLE
[Bug]: tips 显示位置，左右颠倒

### ISSUE THREAD

**Issue by Reinering** [zhiyiYo/PyQt-Fluent-Widgets#901]
### What happened?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/29029467/6869804f-f797-424f-bf3e-86545186c060)

### Operation System

win10

### Python Version

3.10

### PyQt/PySide Version

pyside6

### PyQt/PySide-Fluent-Widgets Version

6.4.3

### How to Reproduce?

![image](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/29029467/4921f44d-ec80-4945-90ba-912064493748)

### Minimum code

```python3
示例
```

**Comment by Reinering** [comment]
上下也颠倒

**Comment by zhiyiYo** [comment]
tailPosition 是尾巴位置的意思
