### ISSUE TITLE
新功能请求：Defalt themeColor自动获取当前系统主题色

### ISSUE THREAD

**Issue by mstouk57g** [zhiyiYo/PyQt-Fluent-Widgets#902]
新功能请求 -> 如题所述：
当前好像是直接使用一个默认的固定的颜色
有点想法：
在Windows环境下选择默认颜色的时候用ctypes调用dwmapi来获取当前主题色
在Linux/MacOS环境下使用固定的颜色的值

**Comment by zhiyiYo** [comment]
有一些第三方库可以获取系统颜色，只要在启动应用之前调用 setThemeColor 设置一下即可
