### ISSUE TITLE
[Bug]: 关于demo.py运行出现问题

### ISSUE THREAD

**Issue by Verdant-Grassland** [zhiyiYo/PyQt-Fluent-Widgets#909]
### What happened?

![e0e5025695fda1f032c92f142857dbc6](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/107308136/26c5fb37-51f7-4e6f-8600-e147571fff3a)
这个报错了，我不知道怎么回事呢？

### Operation System

Windows 11 23H2

### Python Version

3.12 64-bit

### PyQt/PySide Version

PySide6 6.6.2

### PyQt/PySide-Fluent-Widgets Version

PySide-Fluent-Widgets 1.5.8

### How to Reproduce?

![e0e5025695fda1f032c92f142857dbc6](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/107308136/26c5fb37-51f7-4e6f-8600-e147571fff3a)
这个报错了，我不知道怎么回事呢？

### Minimum code

```python3
![e0e5025695fda1f032c92f142857dbc6](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/107308136/26c5fb37-51f7-4e6f-8600-e147571fff3a)
这个报错了，我不知道怎么回事呢？

我不知道如何解决问题？这些以上早东西安装了
```

**Comment by zhiyiYo** [comment]
环境乱了
