### ISSUE TITLE
[Bug]: TableWidget doesn't word-wrap with verticalHeader set to 'Resize to Contents'

### ISSUE THREAD

**Issue by PyFlat-JR** [zhiyiYo/PyQt-Fluent-Widgets#910]
### What happened?

![grafik](https://github.com/zhiyiYo/PyQt-Fluent-Widgets/assets/101415786/63517dbc-94aa-4e02-a4a7-2928d0361849)

I have a ```QTableWidget``` with the ```horizontalHeader``` on stretch. If there is a text in one of the cells that is longer than the width of the header, the text is cut off. With QTableWidget the problem can be solved by changing the ```SectionResizeMode``` of the ```verticalHeader``` to ```QHeaderView.ResizeToContents```. WordWrap then simply increases the height of the cell. With ```TableWidget```, however, the text remains truncated and the height of the cell does not change.

### Operation System

Windows 10 22H2

### Python Version

3.11.2 64-bit

### PyQt/PySide Version

PySide 6.6.3.1

### PyQt/PySide-Fluent-Widgets Version

v1.5.8

### How to Reproduce?

Create a ```TableWidget``` set ```verticalHeader.SectionResizeMode``` to ```QHeaderView.ResizeToContents``` and add a text to the widget longer than the width of the header section so it should do ```WordWrap```.

### Minimum code

```python3
import sys

from PySide6.QtWidgets import (
    QApplication,
    QHBoxLayout,
    QHeaderView,
    QMainWindow,
    QTableWidget,
    QTableWidgetItem,
    QWidget,
)
from qfluentwidgets import TableWidget


class MyWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Two TableWidgets Example")

        central_widget = QWidget(self)
        self.setCentralWidget(central_widget)

        layout = QHBoxLayout(central_widget)

        table1 = QTableWidget()
        table1.setColumnCount(1)
        table1.setRowCount(1)
        table1.verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)

        table2 = TableWidget()
        table2.setColumnCount(1)
        table2.setRowCount(1)
        table2.verticalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)

        data1 = "test test test test test"

        item1 = QTableWidgetItem(data1)
        item2 = QTableWidgetItem(data1)
        table1.setItem(0, 0, item1)
        table2.setItem(0, 0, item2)

        layout.addWidget(table1)
        layout.addWidget(table2)

        central_widget.setLayout(layout)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MyWindow()
    window.show()
    sys.exit(app.exec())
```

**Comment by zhiyiYo** [comment]
You need to set the wrap mode of Tablewidget

**Comment by PyFlat-JR** [comment]
But wordWrap() is True by default so setting it to True doesnt change anything. Or is there a different setting to set the wrap behaviour?

**Comment by PyFlat-JR** [comment]
???
