### ISSUE TITLE
[Bug]: Menu 显示不全，上半部分无法显示

### ISSUE THREAD

**Issue by motocoder-cn** [zhiyiYo/PyQt-Fluent-Widgets#922]
### What happened?

Menu 显示不全，上半部分无法显示

### Operation System

ubuntu16.04

### Python Version

3.8

### PyQt/PySide Version

PyQt5.15

### PyQt/PySide-Fluent-Widgets Version

1.5.8

### How to Reproduce?

example gallery menu
![menu](https://github.com/user-attachments/assets/52b8326a-6a60-429a-9d0a-ec2fdfbc179d)

### Minimum code

```python3
.
```

**Comment by motocoder-cn** [comment]
@zhiyiYo 可以帮看下是否是问题么，谢谢

**Comment by zhiyiYo** [comment]
之前测试的时候不会这样

**Comment by motocoder-cn** [comment]
> 之前测试的时候不会这样
@zhiyiYo 用普通的QMenu是可以正常的不会有显示不全的情况
