### ISSUE TITLE
[Bug]: LineTableWidget表头排序箭头的颜色和风格没有统一，表现为黑色

### ISSUE THREAD

**Issue by songqian1130** [zhiyiYo/PyQt-Fluent-Widgets#925]
### What happened?

LineTableWidget表头排序箭头的颜色和风格没有统一，表现为黑色

### Operation System

Win11

### Python Version

3.8

### PyQt/PySide Version

pyside 6.1.3

### PyQt/PySide-Fluent-Widgets Version

1.5.8

### How to Reproduce?

启用linetablewidget的表头排序即可

### Minimum code

```python3
无
```

**Comment by zhiyiYo** [comment]
已修复此问题
