### ISSUE TITLE
调整流畅窗口默认背景颜色

### ISSUE THREAD

**Issue by zhiyiYo** [zhiyiYo/PyQt-Fluent-Widgets#928]

**Comment by rainzee** [comment]
暗色模式下也调整吗？

**Comment by zhiyiYo** [comment]
> 暗色模式下也调整吗？

深色模式暂时不修改

**Comment by rainzee** [comment]
这算一个比较大的改动，我建议在 Docs 里加一个提醒类似 Since 1.6.0 窗口默认颜色修改，如果需要改回XXX。你觉得呢

**Comment by zhiyiYo** [comment]
之后改下文档，目前流畅窗口文档没说明如何修改背景颜色

**Comment by rainzee** [comment]
因为修改了默认行为，所有使用 FluentWindow 都会有变化，所以可以开个 warning 或者 info 的提醒
