### ISSUE TITLE
[Bug]: Qt Designer中如何将组件提升为SimpleCardWidget

### ISSUE THREAD

**Issue by springleeo** [zhiyiYo/PyQt-Fluent-Widgets#937]
### What happened?

你好，想请教一下，Qt Designer中如何将组件直接提升为SimpleCardWidget？我理解的提升过程是Qframe ->CardWidget->SimpleCardWidget不知道对不对。有参考https://github.com/Eanya-Tonic/MihiroToolbox 中的ui文件，如图所示，但是不知道如何实现，帮忙指导一下，谢谢
![图片](https://github.com/user-attachments/assets/fa8809ea-c9f8-4ed1-9ade-7d06d9e7b841)

### Operation System

win11

### Python Version

3.8

### PyQt/PySide Version

PyQt5.15.2

### PyQt/PySide-Fluent-Widgets Version

1.6.0

### How to Reproduce?

无

### Minimum code

```python3
无
```

**Comment by zhiyiYo** [comment]
不能直接把 QWidget 提升成 SimpleCardWidget 吗

**Comment by springleeo** [comment]
> 不能直接把 QWidget 提升成 SimpleCardWidget 吗

找到问题了，他的ui文件里面确实提升了两次，只是不知道第二次提升的时候，基类名称如何能设置为CardWidget的，因为我这里基类名称都是qtdesigner自带的组件名称。试了一下，可以将QWidget直接提升为SimpleCardWidget，感谢。
![图片](https://github.com/user-attachments/assets/989402ee-3ed2-417b-99c3-a191244f0220)
