### ISSUE TITLE
如何取消 每次执行前出现的 📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

### ISSUE THREAD

**Issue by caofei996** [zhiyiYo/PyQt-Fluent-Widgets#939]
和 QtScheduler  模块使用的时候，每次执行定时任务，会弹出大量的 📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.  如何取消呢 
![Uploading screenshot-20240805-221143.png…]()

**Comment by rainzee** [comment]
目前没有相关接口取消

**Comment by xiaoshu312** [comment]
我有一计🤓👆可以先`sys.stdout = None`再import
