### ISSUE TITLE
[Bug]: example tab_view 删除标签页异常

### ISSUE THREAD

**Issue by XeonWangYue** [zhiyiYo/PyQt-Fluent-Widgets#942]
## 第一种场景

初始 ↓
![316c0cabdc51e6f7c483cbbfab404a85](https://github.com/user-attachments/assets/ca73b6db-52d9-4bbd-af8a-595cd0cc8521)

添加 ↓
![image](https://github.com/user-attachments/assets/2e46796e-ead9-4208-be42-05d5d49bcc18)

删除 No.1 ↓
![image](https://github.com/user-attachments/assets/497a615a-322d-455d-bba4-794fc02ac199)

删除全部 ↓
![image](https://github.com/user-attachments/assets/5f318079-88f9-40c5-b9ef-dc6a6c711d3d)

预期：页面为空
实际：页面保留为最后显示的widget

## 第二种场景

添加两个页面 ↓
![image](https://github.com/user-attachments/assets/27dc6599-57c0-4990-bb5d-bf22471c8549)

切换到第二个页面  ↓
![image](https://github.com/user-attachments/assets/65557fb6-a488-4fbd-a872-b05db6859002)

删除第一个标签页 ↓
![image](https://github.com/user-attachments/assets/79eeda38-7871-4d72-9234-87248df8bf40)

点+ 加标签页，控制台报错 ↓
![image](https://github.com/user-attachments/assets/dddda113-7d30-465f-98a6-afab14acbccd)

### Operation System

Windows 11 23H2 Build 22631.3880

### Python Version

3.9

### PyQt/PySide Version

PySide2 5.15.2

### PyQt/PySide-Fluent-Widgets Version

Branch PySide2 Lastest

### How to Reproduce?

运行实例代码即可复现

### Minimum code

```python3
运行实例即可复现
```

**Comment by zhiyiYo** [comment]
问题不大，只是个演示示例
