### ISSUE TITLE
[Bug]: setThemeColor函数对color参数处理错误

### ISSUE THREAD

**Issue by not-exist** [zhiyiYo/PyQt-Fluent-Widgets#944]
### What happened?

根据源代码中的说明，`setThemeColor`函数中`color`参数允许使用类型为`QColor`作为传参参数，但试图以此为传参方式时，发生错误。

### Operation System

Windows11 21H2

### Python Version

3.11.1 64 bit

### PyQt/PySide Version

PySide 6.7.2

### PyQt/PySide-Fluent-Widgets Version

1.6.0

### How to Reproduce?

在`setThemeColor`函数中，通过`color=QColor(color)`来实现对`str`类型传参的支持，但当传参为`QColor`类型时，如此做会导致运行错误。

### Minimum code

```python3
from qfluentwidgets import setTheme, Theme, setThemeColor
from PySide6.QtGui import QColor
from PySide6.QtCore import Qt, QSharedMemory
from PySide6.QtWidgets import QApplication

if __name__ == "__main__":
    setThemeColor(QColor(255,255,255))
```

**Comment by zhiyiYo** [comment]
我用 pyside6.6.2 不会报错

**Comment by zhiyiYo** [comment]
换成 6.7.2 也无法复现
