### ISSUE TITLE
[Bug]: Pyside6中，OptionsSettingCard类错误接管wheelEvent

### ISSUE THREAD

**Issue by Chr0nixz** [zhiyiYo/PyQt-Fluent-Widgets#945]
### What happened?

设置选项卡中，只要是有下拉菜单的，鼠标在上面然后滚轮是不起作用的

### Operation System

Windows 10 22H2

### Python Version

3.12.5

### PyQt/PySide Version

PySide 6.6.2

### PyQt/PySide-Fluent-Widgets Version

1.6.0

### How to Reproduce?

gallery pro中也有类似问题

### Minimum code

```python3
有一个很粗暴的solution:
self.themeCard.wheelEvent = self.scrollWidget.wheelEvent
不考虑接管，直接干函数
```

**Comment by zhiyiYo** [comment]
已修复此问题
