### ISSUE TITLE
TableWidget 内嵌 QWidget 组件的方式

### ISSUE THREAD

**Issue by Cooooldwind** [zhiyiYo/PyQt-Fluent-Widgets#953]
局部的代码。
```python
def update_result_table(self, result):
  new = Ui_musicWidget()
  widget = QWidget()
  new.setupUi(widget)
  # ......
  self.ui.resultTableWidget.setCellWidget(int(result["index"]), 0, widget)
  self.update()
```
这是我看到的它的显示（局部）。它不应该是空白。
我的QWidget里面定义了三个Label，但是一个都显示不出来。
是不支持QWidget吗？还是我的方式不对？求教QwQ
![屏幕截图](https://github.com/user-attachments/assets/79022618-6d0e-4f8b-b8da-8c32cbc80321)

**Comment by Cooooldwind** [comment]
因为明天开学所以坐在电脑前面刷新了1小时等人帮的我qwq

**Comment by zhiyiYo** [comment]
换成 QTableWidget 试试

**Comment by Cooooldwind** [comment]
> 换成 QTableWidget 试试
还是没有......😓
![image](https://github.com/user-attachments/assets/4bc1f9a6-58f2-43f4-b36b-74c91d20bc4e)

**Comment by Cooooldwind** [comment]
这里面装的是一个QWidget，QWidget里面嵌套了BodyLabel，ImageLabel，TitleLabel

**Comment by Cooooldwind** [comment]
![image](https://github.com/user-attachments/assets/d20cdaf6-d592-41bf-838a-aadfed783250)

**Comment by zhiyiYo** [comment]
问问chatgpt吧，这个不算组件库的问题，可能你需要设置sizeHint

**Comment by Cooooldwind** [comment]
重写了下 莫名其妙就好了 感谢dalao
