### ISSUE TITLE
Typo in info_badge.py file: "INFOAMTION" instead of "INFORMATION"

### ISSUE THREAD

**Issue by odest** [zhiyiYo/PyQt-Fluent-Widgets#955]
Hi there,

I noticed a small typo in the repository. In the info_badge.py, the word **"INFOAMTION"** is used instead of the correct spelling **"INFORMATION"**.

Here’s the exact location of the typo:

File: *qfluentwidgets/components/widgets/info_badge.py*
Lines: *17, 49, 122, 136,149, 209, 221, 316, 329*
Current: **INFOAMTION** Suggested: **INFORMATION**

Would you mind correcting this typo? Thanks!

## And...

I’m currently working with the InfoBadge and I have added a badge to a navigation item using the following code:

```python
# add badge to navigation item
item = self.navigationInterface.widget(self.videoInterface.objectName())
InfoBadge.attension(
    text=9,
    parent=item.parent(),
    target=item,
    position=InfoBadgePosition.NAVIGATION_ITEM
)
```

I would like to know how I can remove or hide this InfoBadge when it's no longer needed. Is there a method or a recommended approach to achieve this?

Thanks in advance for your help!

Best regards, odest

**Comment by LiXiangpan** [comment]
I think you can let `self.badge = InfoBadge.attension(......)`,
and when you want to hide the badge, you can try `self.badge.hide()` or `self.badge.close()`.
Please let me know if this method is feasible.

**Comment by odest** [comment]
## Thank you for your suggestion.

I tried using the .hide() method, and it seems that when the navigation menu is closed, the badge does not appear. However, when the menu is opened again, the badge reappears.

I’m sharing a video related to this issue.

https://github.com/user-attachments/assets/2b6c9d1e-f265-426b-8697-a0ea0d3f9b18



## If I’m not mistaken,
this might be due to the code in the qfluentwidgets/components/navigation/navigation_widget.py file.

```python
@InfoBadgeManager.register(InfoBadgePosition.NAVIGATION_ITEM)
class NavigationItemInfoBadgeManager(InfoBadgeManager):
    """ Navigation item info badge manager """

    def eventFilter(self, obj, e: QEvent):
        if obj is self.target:
            if e.type() == QEvent.Show:
                self.badge.show() #this

        return super().eventFilter(obj, e)

    def position(self):
        target = self.target
        self.badge.setVisible(target.isVisible()) # and this

        if target.isCompacted:
            return target.geometry().topRight() - QPoint(self.badge.width() + 2, -2)

        if isinstance(target, NavigationTreeWidget):
            dx = 10 if target.isLeaf() else 35
            x = target.geometry().right() - self.badge.width() - dx
            y = target.y() + 18 - self.badge.height() // 2
        else:
            x = target.geometry().right() - self.badge.width() - 10
            y = target.geometry().center().y() - self.badge.height() // 2

        return QPoint(x, y)
```

**Comment by LiXiangpan** [comment]
Maybe you can destroy the badge object to let it completely disappear.
I tried this code and it works. 
Hope it's useful for you.
```
if self.badge: 
  self.badge.manager = None
  self.badge.deleteLater()
  self.badge = None
```

**Comment by odest** [comment]
Thank you for your suggestion! Yes, this approach works well.

Do you think this method is applicable to the projects?

**Comment by LiXiangpan** [comment]
I think this is the temporary way to achieve the effect, it can be used in project. 
But this method is not beautiful enough.
I'm not a professional developer, so there may be some good method I haven't discovered.

**Comment by odest** [comment]
You're right, I can use this until I find a better method. thanks

**Comment by zhiyiYo** [comment]
I think users should write a custom manager to meet their special needs. I can't handle all cases in my code.
