### ISSUE TITLE
[Bug]: 日期选择控件 ZhDatePicker 在超过3个窗口出现并点击过时,会导致怎么程序闪退

### ISSUE THREAD

**Issue by wz-wong** [zhiyiYo/PyQt-Fluent-Widgets#956]
### What happened?

![image](https://github.com/user-attachments/assets/a5f9bd69-e4b1-4fbe-9735-7bd0cad30960)
![image](https://github.com/user-attachments/assets/c349fffb-406d-4440-bf55-d394280c8511)

每个卡片点开,都会弹出一个详情窗口(里面包含2个日期选择控件)
当点开卡片超过3个,并且每个详情窗口都点击过 日期控件(窗口点击完也关闭了)

必定会导致整个程序闪退
下面是控制台信息:
`E:\xxxxxxxxxx\main.py `
`进程已结束，退出代码为 -1073740791 (0xC0000409)`

没有其他有效报错信息,目前只发现这个选日期的控件存在这个问题

### Operation System

win10 21H2

### Python Version

python3.10

### PyQt/PySide Version

PyQt5                     5.15.9

### PyQt/PySide-Fluent-Widgets Version

PyQt-Fluent-Widgets       1.6.3

### How to Reproduce?

下方图片,是具体的调用代码
![image](https://github.com/user-attachments/assets/634e8234-9670-4ce5-91e4-9673a01af05b)

### Minimum code

```python3
1, 创建多个卡片控件
2, 增加 点击卡片,显示详情窗口的信号槽代码
3, 详情窗口放入 2个日期控件
4, 当程序启动,点击卡片->进入详情页->点击日期控件
5, 重复第4步 3次以上, 程序就会闪退  

注: 详情窗口不会复用,每次都是 新的
ui_detail = WidgetDetail(参数)
ui_detail.show()
```

**Comment by rainzee** [comment]
给个完整复现代码

**Comment by mengdeer589** [comment]
看起来像是访问了没有的属性，试试
import cgitb
cgitb.enable()

**Comment by wz-wong** [comment]
![image](https://github.com/user-attachments/assets/96bb6c2f-b804-494e-8839-64ec2b934614)

**Comment by wz-wong** [comment]
不知道哪里出了问题, 将敏感数据拆除后, 详情页打开就闪退, 详情页已经最小了, 就2个日期控件,附件是拆出来最小的代码
[tmp.zip](https://github.com/user-attachments/files/16939009/tmp.zip)
卡片动画也有问题, 打开多次,就会出现错位情况, 手动拖动边框大小再次触发动画才会恢复正常
@[rainzee](https://github.com/rainzee)

**Comment by wz-wong** [comment]
> 看起来像是访问了没有的属性，试试 导入cgitb cgitb.enable()

这个我现在把详情页改成单例模式了, 单例模式不会有这样情况, 后面又加了不少改动,旧代码回不去了

**Comment by rainzee** [comment]
让你给个完整可复现的最小代码

**Comment by wz-wong** [comment]
> 让你给个完整可复现的最小代码
上面那个 zip文件, 就是拆了敏感数据之后的最小代码, 但是拆了了之后, 详情窗口闪退, 我自己都没法复现, 只能给个逻辑你参考下, 能修则修,或者等别人报这个问题提供,  目前我的解决方案是,  详情窗口用单例,不同卡片点击都指向这同一个窗口, 测试是正常的
