### ISSUE TITLE
【建议】建议给MessageBoxBase基类增加是否点击遮罩后关闭对话框的方法

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#957]
看到群里有用户反馈，个人感觉这个功能也比较实用，如果添加对应方法的话，用户可以自由选择是否点击遮罩区域关闭对话框，
可以默认关闭，想要开启的话可以调用例如`self.setMaskCloseable(True)`
基本示例代码如下：
```python
def mousePressEvent(self, event):
        #使用 mapFromGlobal() 方法，将全局屏幕坐标转换为相对于当前窗口的局部坐标。
        pos = self.mapFromGlobal(event.globalPos())
        if not QRect(self.widget.geometry()).contains(pos):
            self.reject()
```

**Comment by zhiyiYo** [comment]
下个版本可以加上

**Comment by WorkSync** [comment]
`    def mousePressEvent(self, event: QMouseEvent):
        if event.button() == Qt.LeftButton:
            if event.pos().x() < self.widget.x() or \
               event.pos().x() > self.widget.x() + self.widget.width() or \
               event.pos().y() < self.widget.y() or \
               event.pos().y() > self.widget.y() + self.widget.height():
                self.reject()
        super().mousePressEvent(event)`
        
这个也行，就是笨笨的哈哈。
请问群是高级版的交流群吗
