### ISSUE TITLE
[Bug]: Pyside6 增加原始组件QWebEngineView引起的异常

### ISSUE THREAD

**Issue by abclaboratory** [zhiyiYo/PyQt-Fluent-Widgets#960]
### What happened?

![PixPin_2024-09-12_22-48-05](https://github.com/user-attachments/assets/0ed8c8b3-6f3e-4659-94ce-29a2ab95d57d)

### Operation System

Windows11

### Python Version

3.7.8

### PyQt/PySide Version

pyside6.5.3

### PyQt/PySide-Fluent-Widgets Version

1.6.3

### How to Reproduce?

引入原始组件QWebEngineView后页面主题样式异常，打包后的项目无法运行，也无报错

### Minimum code

```python3
无
```

**Comment by zhiyiYo** [comment]
https://qfluentwidgets.com/zh/pages/components/fluentwindow#%E8%83%8C%E6%99%AF%E5%A4%B1%E6%95%88%E8%A7%A3%E5%86%B3%E5%8A%9E%E6%B3%95
