### ISSUE TITLE
【建议】qfluentwidgets建议支持直接导入MaskDialogBase

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#962]
大佬你好，目前虽然MessageBoxBase能满足大部分情况，但是有时候还是需要单纯的遮罩基类进行搭建自定义组件，例如图片查看器等
但是目前导入MaskDialogBase比较麻烦：
`from qfluentwidgets.components.dialog_box.mask_dialog_base import MaskDialogBase`
建议支持直接导入：
`from qfluentwidgets import MaskDialogBase`
这样能满足各种需求
在dialog_box文件夹下的__init__.py加上这行应该就行了
`from .mask_dialog_base import MaskDialogBase`

**Comment by zhiyiYo** [comment]
已导出
