### ISSUE TITLE
[Bug]: MaskDialogBase的setMaskColor方法设置颜色的时候，设置颜色样式中的rgba顺序不对

### ISSUE THREAD

**Issue by qianye216** [zhiyiYo/PyQt-Fluent-Widgets#964]
### What happened?

应该是：
![image](https://github.com/user-attachments/assets/dec02494-dca6-4b18-8898-6b2cadae5bb1)
```python
self.windowMask.setStyleSheet(f"""
            background: rgba({color.red()}, {color.green()},{color.blue()}, {color.alpha()})
        """)
```

### Operation System

Mac

### Python Version

3.11.7

### PyQt/PySide Version

PyQt5 

### PyQt/PySide-Fluent-Widgets Version

1.6.3

### How to Reproduce?

设置正确的颜色样式

### Minimum code

```python3
self.windowMask.setStyleSheet(f"""
            background: rgba({color.red()}, {color.green()},{color.blue()}, {color.alpha()})
        """)
```

**Comment by zhiyiYo** [comment]
已修复此问题
