### ISSUE TITLE
[Bug]: 下拉框，每选择一次，内存会增加一些的bug

### ISSUE THREAD

**Issue by dengsanpi** [zhiyiYo/PyQt-Fluent-Widgets#966]
### What happened?

![3a78bbc515ad323f7d2440fc70bf7306](https://github.com/user-attachments/assets/f148a9a1-3b76-41cd-8a28-e29cebd652ed)
每点选一次，内存会增加1M左右

### Operation System

bo

### Python Version

python3.10

### PyQt/PySide Version

6.6.2

### PyQt/PySide-Fluent-Widgets Version

1.6.2

### How to Reproduce?

1

### Minimum code

```python3
1
```

**Comment by zhiyiYo** [comment]
更新到1.6.5即可
