### ISSUE TITLE
关于下拉菜单按钮add_widget添加搜索输入框后无法切换输入法

### ISSUE THREAD

**Issue by mengdeer589** [zhiyiYo/PyQt-Fluent-Widgets#970]
您好，我在使用DropDownPushButton时遇到了问题，尝试在该组件的下拉菜单中，使用RoundMenu的addWidget方法添加一个SearchLineEdit组件到菜单中，发现正常弹出菜单后，无法切换输入法来输入中文，您能帮帮我吗？万分感谢。
版本：
window11 
python 3.11
pyqt-fluent-widgets 1.6.5
以下是复现代码：
import sys

from PyQt5.QtWidgets import QApplication
from qfluentwidgets import DropDownPushButton,SearchLineEdit,RoundMenu
class MyDropDownPushButton(DropDownPushButton):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.search_btn=SearchLineEdit(self)
        self.setMenu(RoundMenu())
        self.menu().addWidget(self.search_btn)
        self.setFixedSize(300,200)
if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = MyDropDownPushButton()
    window.show()
    sys.exit(app.exec_())

**Comment by zhiyiYo** [comment]
参考这个 issue：
https://github.com/zhiyiYo/PyQt-Fluent-Widgets/issues/780#issuecomment-1986721014
