### ISSUE TITLE
[Bug]: PyQt6国际化设置

### ISSUE THREAD

**Issue by chuanzhangbuhuishui** [zhiyiYo/PyQt-Fluent-Widgets#982]
### What happened?

# 官网示例
### 简体中文
FluentTranslator(QLocale(QLocale.Chinese, QLocale.China))
### 香港繁体
FluentTranslator(QLocale(QLocale.Chinese, QLocale.HongKong))

### Operation System

Windows

### Python Version

3.11

### PyQt/PySide Version

PyQt6.7

### PyQt/PySide-Fluent-Widgets Version

1.6.6

### How to Reproduce?

# 更改后运行示例
translator = FluentTranslator(QLocale(QLocale.Language.Chinese, QLocale.Country.China))
    app.installTranslator(translator)

### Minimum code

```python3
translator = FluentTranslator(QLocale(QLocale.Language.Chinese, QLocale.Country.China))
app.installTranslator(translator)
```

**Comment by zhiyiYo** [comment]
pyqt6枚举类的问题，pyqt5 pyside2 和 pyside6正常运行，个人建议将项目迁移到 pyside6

**Comment by chuanzhangbuhuishui** [comment]
谢谢回复。还有Label标签也有问题，在PyQt6的项目中不管哪一类Label都是一个样式，必须要再写qss。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月09日 09:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zhiyiYo/PyQt-Fluent-Widgets] [Bug]: PyQt6国际化设置 (Issue #982) |

Closed #982 as completed.
