### ISSUE TITLE
[question] 如果支持PySide，为何不命名为Fluent-Widgets？

### ISSUE THREAD

**Issue by moonshineBoy** [zhiyiYo/PyQt-Fluent-Widgets#984]
您好，请问：
1、[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets) 是支撑PySide6的
2、既然支持PySide，为何不命名为Fluent-Widgets？

**Comment by zhiyiYo** [comment]
改了名字之后别的网页上的链接会失效
