### ISSUE TITLE
如何把这个程序在windows下面做成exe

### ISSUE THREAD

**Issue by henrywoo** [zhiyiYo/PyQt-Fluent-Widgets#985]
有一个小白问题,但是搜了下没有找到官方答案,也不知道是我没有找到呢,还是本来就没有?就是如何把这些可运行的程序在windows下面或者macos下面转换成可以直接启动的可执行文件.不知道官方能否提供或者推荐一个方便的解决方案?谢谢.

**Comment by henrywoo** [comment]
具体怎么打包呢?可以提供些简单的指令吗?各有什么优缺点呢?谢谢

**Comment by zhiyiYo** [comment]
这种问题适合问chatgpt
