### ISSUE TITLE
[Bug]: ListWidget使用NoSelection不生效

### ISSUE THREAD

**Issue by wanniwa** [zhiyiYo/PyQt-Fluent-Widgets#992]
### What happened?

设置ListWidget没有选中效果，但是还是有选中的颜色变更的效果

### Operation System

mac

### Python Version

11

### PyQt/PySide Version

6.7.3

### PyQt/PySide-Fluent-Widgets Version

1.7.0

### How to Reproduce?

设置ListWidget没有选中效果，ListWidget换成QListWidget是能生效的

### Minimum code

```python3
self.task_list_widget = ListWidget()
self.task_list_widget.setSelectionMode(ListWidget.SelectionMode.NoSelection)
```

**Comment by zhiyiYo** [comment]
已修复此问题
