### ISSUE TITLE
[Bug]: ExpandSettingCard样式受到父级样式表影响

### ISSUE THREAD

**Issue by Pujx315** [zhiyiYo/PyQt-Fluent-Widgets#993]
### What happened?

放在外部加粗的字体，放到ExpandSettingCard中后，加粗消失了

### Operation System

Windows11

### Python Version

Python 3.11.10

### PyQt/PySide Version

PySide6 6.4.2

### PyQt/PySide-Fluent-Widgets Version

v0.7.1

### How to Reproduce?

放在外部加粗的字体，放到ExpandSettingCard中后，加粗消失了
使用setFont进行设定也没有用处

### Minimum code

```python3
setFont(self.nameLabel, 14, QFont.Weight.DemiBold)
```

**Comment by zhiyiYo** [comment]
已修复此问题
