### ISSUE TITLE
[Bug]: MessageBox 在显示和关闭时画面会有一次明显的闪烁

### ISSUE THREAD

**Issue by neavo** [zhiyiYo/PyQt-Fluent-Widgets#996]
### What happened?

MessageBox 在显示和关闭时画面会有一次明显的闪烁

### Operation System

Windows 11 24H2

### Python Version

3.12.7

### PyQt/PySide Version

PyQT5 5.15.11

### PyQt/PySide-Fluent-Widgets Version

1.7.0

### How to Reproduce?

MessageBox 在显示和关闭时画面会有一次明显的闪烁

### Minimum code

```python3
message_box = MessageBox("警告", "停止的翻译任务可以随时继续翻译，是否确定停止任务 ... ？", window)
message_box.yesButton.setText("确认")
message_box.cancelButton.setText("取消")

# 确认则触发停止翻译事件
if message_box.exec():
    pass
```

**Comment by neavo** [comment]
上个版本应该是没有的，我没记错的话 。。。

**Comment by AlexZhu2001** [comment]
Windows10同环境无法复现，可能win11的bug？

**Comment by neavo** [comment]
> Windows10同环境无法复现，可能win11的bug？

降级到 1.6.6 试了一下，确实还是会闪，但是我记得前段时间应该是不闪的

控制变量法排除的话，那大概确实是系统的兼容性问题了
